### ISSUE TITLE
How can one create a new Document from an instance of GenericValue?

### ISSUE THREAD

**Issue by SylvainCorlay** [Tencent/rapidjson#1005]
It does not seem that I can set a new document from a node read in another document.

**Comment by pah** [comment]
You need to make sure to use the same allocator for both `Document`s, if you want to move `Value`s between the instances.  The allocator of course has to be taken from the `Document` with the longest lifetime.

You can create a Document with a custom allocator with [this constructor](http://rapidjson.org/classrapidjson_1_1_generic_document.html#a82b27e7b228eb46a23f99720063ab4fb):
```cpp
  rapidjson::Document d1; // own allocator
  rapidjson::Document d2( &d1.GetAllocator() ); // share allocator with d1
```

**Comment by SylvainCorlay** [comment]
Thanks for the answer. My question was about copying a ` value`   that is not a document into a document.

i.e.
```
source = {
"data": { somecontent} 
};

data_document = souce["data"];
```

**Comment by pah** [comment]
If you want to **copy** a value instead of **moving** it (where the latter is the default), you can use the explicit [`CopyFrom`](http://rapidjson.org/classrapidjson_1_1_generic_value.html#ad9399a2a69444c44a9db2f63c3aa3eae) function:
```cpp
  data_document.CopyFrom( source["data"], data_document.GetAllocator() );
```
