### ISSUE TITLE
How to new line for addMember

### ISSUE THREAD

**Issue by ThomasD9** [Tencent/rapidjson#1022]
My output file as below:

{"OrderInfo":{"Order":"abc123","Customer":"Cust1","Type":"BType"....

Where I want to have something like below, any idea how to make it?
{"OrderInfo":
                {"Order":"abc123","
                   Customer":"Cust1",
                    "Type":"BType"....

Thank You

**Comment by pah** [comment]
You can use the `PrettyWriter` instead of the plain `Writer` to get formatted output.
