### ISSUE TITLE
crash when parsing (with call stack)  Expand<char> (long unsigned int) (stack.h:186)

### ISSUE THREAD

**Issue by raomuming** [Tencent/rapidjson#1023]
we write code like below to parse a json, and it crashed when parse the json tring.
`rapidjson::Document object;`
 `object.Parse(value.c_str());`

and crash stack is as below. It is very hard to reproduce, Do you have any idea about what could cause this? thank you~

0	libsystem_kernel.dylib 0x0000000187a9d014 __pthread_kill + 4
1	libsystem_c.dylib 0x0000000187a119c4 abort + 136
2	libsystem_malloc.dylib 0x0000000187ae29e8 nanozone_error + 328
3	libsystem_malloc.dylib 0x0000000187ae3c54 _nano_malloc_check_clear + 408
4	libsystem_malloc.dylib 0x0000000187ae2c38 nano_malloc + 40
5	libsystem_malloc.dylib 0x0000000187ad1664 malloc_zone_malloc + 168
6	libsystem_malloc.dylib 0x0000000187ad456c malloc + 28
7	libc++abi.dylib 0x00000001874f36b0 operator new() + 44
8	GlipCore 0x0000000101902b5c Expand<char> (long unsigned int) (stack.h:186)
9	GlipCore 0x0000000101901a00 ParseString<0, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator> > (GenericStringStream<rapidjson::UTF8<char> >, GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator>, bool) (stack.h:118)
10	GlipCore 0x0000000101901cc8 ParseObject<0, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator> > (GenericStringStream<rapidjson::UTF8<char> >, GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator>) (reader.h:609)
11	GlipCore 0x0000000101901610 Parse<0, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator> > (GenericStringStream<rapidjson::UTF8<char> >, GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator>) (reader.h:501)
12	GlipCore 0x0000000101901528 ParseStream<0, rapidjson::UTF8<char>, rapidjson::GenericStringStream<rapidjson::UTF8<char> > > (GenericStringStream<rapidjson::UTF8<char> >) (document.h:2159)

**Comment by oubenal** [comment]
You should use **_Parse_** like this : 
```cpp
object.Parse<0>(value.c_str());
```

**Comment by miloyip** [comment]
@oubenal No. The newer version provides an overload of `Parse()` without template parameter.
@raomuming From the call stack it seems the memory allocation by `new` is failed. It is hard to tell why `new` is failed. And in my experience I think there may be memory corruption outside rapidjson, which causes the runtime library fail to allocate memory. You may try to use valgrind or similar tools to test your application.
