### ISSUE TITLE
min max problems on windows

### ISSUE THREAD

**Issue by kylejan** [Tencent/rapidjson#1033]
now we can define NOMINMAX on windows platform to prevent use predefined max in msvc.

I think you can change the syntax from
std::numeric_limits<std::int32_t>::max()
into
(std::numeric_limits<std::int32_t>::max)()
which can prevent numeric_limits's max confused with predefined max in msvc.

It will be more cross-platform without define NOMINMAX.

**Comment by miloyip** [comment]
Thanks. You may prepare a PR.

**Comment by kylejan** [comment]
no problems. i will contribute to that

**Comment by jhugard** [comment]
Looks like this was fixed in 6e38649e.  Should probably close this issue.
