### ISSUE TITLE
key为乱码

### ISSUE THREAD

**Issue by namelij** [Tencent/rapidjson#1036]
如下
"@2�\u0001\u0000\u0000\u0000\u0000�\u0002&\u0016":{"session_id":"1391499839269176928"}

用法
root.AddMember("req_from_aaa", value, allocator);

**Comment by miloyip** [comment]
估计有内存问题。请提供完整测试代码。

**Comment by namelij** [comment]
参考 

Value n(key.c_str(), json_temp.GetAllocator());
json_temp.AddMember(n, v);

就没问题了

两个项目，其中一个项目就是乱码这种使用方式，没问题，但是现在这个项目就有问题。暂时使用如上的方式解决了

**Comment by miloyip** [comment]
对于生成的字符串，上面的才是正确的。

**Comment by miloyip** [comment]
http://rapidjson.org/zh-cn/md_doc_tutorial_8zh-cn.html#CreateString
