### ISSUE TITLE
Storing Document in Value causes corruption of json object on Android, works fine on macOS(iOS emulator). 

### ISSUE THREAD

**Issue by damorton** [Tencent/rapidjson#1039]
Context: Using rapidjson to convert string to json for an Android app written in C++, works fine on macOS(iOS emulator) but when running on Android device causes corruption. 

```
...
rapidjson::Document JsonParser::StringToJson(std::string &jsonObjectString) {
  rapidjson::Document document = CreateEmptyJsonDocument();
  document.Parse(jsonObjectString.c_str());
  return document;
}
...
rapidjson::Value jsonObject = JsonParser::StringToJson(jsonObjectString);
...
```

Printing the contents of jsonObject produces

```
{
  "name": "testname",
  "filename": "\u0000\u0000\u0000\u0000\u0000?~c\u0010\u0000\u0000\u0000ment/environment_grass_type_a.png"
}
```

**Comment by miloyip** [comment]
The `Document` class contains the allocator. The lifetime of `Document` must be considered.
I suggest you may:
~~~cpp
bool JsonParser::StringToJson(const std::string& jsonObjectString, rapidjson::Document& outDocument) {
    // ...
}
~~~
Or returning a (smart) pointer of `Document`.

**Comment by damorton** [comment]
Yes this will work, also storing the returned object in a Document data type resolves the issue, but it's strange that the behaviour differs between macOS (iOS) and Android device.

**Comment by miloyip** [comment]
C++ has many undefined behaviors (UB), such as returning pointer of local variables.
It may be a good practice to use memory sanitizer kind of tools to figure out incorrect usage.
