### ISSUE TITLE
Null String in Document

### ISSUE THREAD

**Issue by RogG1966** [Tencent/rapidjson#1043]
Hi,

When I try and do the following, with a char* which is a null string,  HasParseError crashes. 

char object[] = "";
rapidjson::Document ui;

if (ui.Parse(object).HasParseError()) {

}

Is there a known work around other than checking if the string is null before calling HasParseError.

Thanks

**Comment by miloyip** [comment]
I cannot reproduce the error.

~~~cpp
#include <iostream>
#include "rapidjson/document.h"

int main() {
    rapidjson::Document d;
    std::cout << d.Parse("").HasParseError();
}
~~~

~~~
g++ -I ~/github/rapidjson/include a.cpp && ./a.out
1
~~~

**Comment by RogG1966** [comment]
Hi,

Here is an example that reproduces the segmentation fault issue:

#include <iostream>
#include "rapidjson/document.h"

int main() {
    rapidjson::Document d;
    void *hello = NULL;

    std::cout << d.Parse((char*)hello).HasParseError();
}

I am seeing this when using mosquito brokers to transfer data encoded in JSON format.

By doing:

mosquito_pub – t “Topic –m “”

and then attempting to use RapidJSON to decode the JSON as specified by the “-m” option in mosquito_pub.

I have also noticed a similar issue if the published string is “[]”. In this case HasParseError is OK, but using .HasMember produces a segmentation fault.

Best Regards

**Comment by miloyip** [comment]
1. `doc.Parse(NULL)` is not a valid usage. The application should not call like this. It should check the pointer is valid and point to a JSON (null-terminated string).
2. `[]` is a valid JSON. It is an array. So you should check `doc.IsObject()` first if you assume the JSON is an object `{ ... }` and use `HasMember()`.

**Comment by RogG1966** [comment]
OK.. many Thanks
