### ISSUE TITLE
Repository Transferal Notice ⚠️

### ISSUE THREAD

**Issue by miloyip** [Tencent/rapidjson#1049]
As the current repo owner, I would like to transfer this repository [miloyip/rapidjson](https://github.com/miloyip/rapidjson) to [tencent/rapidjson](https://github.com/tencent/rapidjson).

As far as I know, this should not bring burden to existing users (cloner, forker, submodule, etc). Most existing operations should still work normally according to [this](https://help.github.com/articles/about-repository-transfers/).

If you have any concern about this transferal, please comment on this issue.

If there is no unsolved issue about this transferal within seven days, I will proceed it.

Thank you for your attention.

**Comment by miloyip** [comment]
Transferal completed on 14 Sep 2017.

**Comment by OlafvdSpek** [comment]
What's the reason for this transfer?

**Comment by miloyip** [comment]
The copyright ownership was transferred long time ago (https://github.com/Tencent/rapidjson/commit/d1959ba6e33190550bfd1a0a21e5e51bb6a130c3#diff-98cd14c95bb22f9d397da0603a77d950).
Last year Tencent retrieved its official Github account. And after internal discussion, we decided to transfer back to the official account.

**Comment by OlafvdSpek** [comment]
It's still not entirely clear to me.. why was copyright ownership transferred?
Was the lib sold to Tencent?

**Comment by miloyip** [comment]
@OlafvdSpek I am empolyee of Tencent and I develop RapidJSON in my spare time during the employment. Transferral of the ownership should not affect the users as the license remains unchanged. The positive effect of the transferral is that I, my teammates and other colleagues can develop and maintain RapidJSON in working hours.

**Comment by OlafvdSpek** [comment]
Ah, that makes sense. Thanks a lot!
