### ISSUE TITLE
Parse Value

### ISSUE THREAD

**Issue by oneonce** [Tencent/rapidjson#1050]
{
    "dictVersion": 1,  
    "content":  
    [   
        {"key": "word1", "value": "单词1"} ,
        {"key": "word2", "value": "单词2"} ,
        {"key": "word3", "value": "单词3"} ,
        {"key": "word4", "value": "单词4"} ,
        {"key": "word5", "value": "单词5"} 
    ],
}

when i known "content" is an array, and i get it's value:
Value jArrayValue;
...
if (jArrayValue.IsArray())
{
    // parse jArrayValue, get all object key and value
}

# If i don't know there are 4 objects in it, how can i get all objects's key and value?

**Comment by miloyip** [comment]
Use

~~~cpp
jArrayValue.Size()
~~~

or

~~~cpp
for (Value::ConstValueIterator itr = jArrayValue.Begin(); itr != jArrayValue.End(); ++itr)
~~~

or in C++11

~~~cpp
for (auto& v : a.GetArray())
~~~
