### ISSUE TITLE
Using SAX parser is it possible to get the "raw" byte length of a string?

### ISSUE THREAD

**Issue by dsorber** [Tencent/rapidjson#1054]
I'm using the SAX style parser to locate the position of certain "fields" within JSON objects.  I determine the offsets using the parser and a custom handler, and then hand them off to an additional processing stage that extracts the raw bytes and manipulates the data. I am having a problem determining the correct length for strings that contain escape sequences. 

For example, in the raw string (length 20 bytes):

`"this is \n \n a test"`

the `"\n"` 's are escaped and the Length passed to the String handler function is 18.  Is there a way to get the raw byte length of the string?  If something doesn't currently exist, what approach would you recommend?

NOTE: At the moment I'm only using ASCII data, but this is also a problem for Unicode as well.

**Comment by miloyip** [comment]
May I know how do you obtain the initial offset of the string?

**Comment by dsorber** [comment]
Per a previous conversation I pass in the input stream to my custom handler and then use `inputStream.Tell()` in the String handler function to get the start position.  This seems to work as near as I can tell.

**Comment by miloyip** [comment]
I think this is the only way now, but I cannot promise that this behavior will not be changed in the future.
