### ISSUE TITLE
解析出错获取行号

### ISSUE THREAD

**Issue by fkeujjpdc** [Tencent/rapidjson#1059]
我这几年一直用rapidjson做我应用的配置文件，感觉挺好的，就是每次用户自己修改配置后报错，没办法知道哪行出错了。
我想在调用Parse出错后能获取是哪一行出错了，好像rapidjson只提供了是哪个字节出错了，有没有什么好的办法获取行号

**Comment by miloyip** [comment]
#916 
其实可以做一个 stream 的 wrapper，按读入字符计算 line/column。你有没有兴趣做个 PR？

**Comment by fkeujjpdc** [comment]
嗯嗯，我先试着做做看
