### ISSUE TITLE
Schema validating fails with correct schema and document

### ISSUE THREAD

**Issue by a-tinsmith** [Tencent/rapidjson#1061]
I'm using v1.1.0 of RapidJSON. Documentation says that `format` keyword is ignored and data is treated as a string. However, it seems that when there is `oneOf` combined with `format`, then validation fails with correct schema and document.

Here is the schema:
```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Test schema",
  "type": "object",
  "properties": {
    "a": {
      "type": "string",
      "oneOf": [
        { "format": "ipv4" },
        { "format": "ipv6" }
      ]
    }
  }
}
```

Document:
```json
{
  "a": "127.0.0.1"
}
```

Validation fails with the errors:
```
Invalid schema: #/properties/a
Invalid keyword: oneOf
Invalid document: #/a
```

Validation code:
```C++
if (!d.Accept(validator)) {
    // Input JSON is invalid according to the schema
    // Output diagnostic information
    rj::StringBuffer sb;
    validator.GetInvalidSchemaPointer().StringifyUriFragment(sb);
    std::cout << "Invalid schema: " << sb.GetString() << '\n';
    std::cout << "Invalid keyword: " << validator.GetInvalidSchemaKeyword() << '\n';
    sb.Clear();
    validator.GetInvalidDocumentPointer().StringifyUriFragment(sb);
    std::cout << "Invalid document: " << sb.GetString() << '\n';
}
```

**Comment by miloyip** [comment]
https://github.com/json-schema/json-schema/wiki/anyOf,-allOf,-oneOf,-not
> # oneOf
> An instance is valid against this keyword if and only if it is valid against **exactly one** schema in this keyword's value.

Since `format` is ignored, so both schemas inside `oneOf` are valid, validation fails.

#785

**Comment by a-tinsmith** [comment]
I believe it's a bug. This is not a problem of the schema that `format` is ignored by the validator. Both schema and the document are perfectly valid, therefore validation should succeed. If validator ignores `format` it should accommodate accordingly and not to fail valid documents.

**Comment by miloyip** [comment]
`format` is ignored so the schema `{}` is always valid for any target. So the parent `oneOf` will always fail. I think this is clear.
You may try using `pattern` instead at the mean time.
