### ISSUE TITLE
Schema: GetInvalidSchemaPointer returns empty pointer when a remote schema is violated

### ISSUE THREAD

**Issue by yurikhan** [Tencent/rapidjson#1064]
A schema can include another schema from a different file, via the `$ref` keyword where the URI includes anything other than the fragment identifier.

When that included schema is violated, the schema pointer returned by `GetInvalidSchemaPointer()` is always the empty pointer.

A simplified test case: Validate `null` against the schema

```json
{"$ref": "foo#/integer"}
```

where `foo` refers (via a suitable `RemoteSchemaDocumentProvider`) to

```json
{"integer": {"type": "integer"}}
```

Expected: `GetInvalidSchemaPointer()` returns `Pointer("/integer")`.

Observed: `GetInvalidSchemaPointer()` returns `Pointer()`.

**Comment by miloyip** [comment]
I am not sure how it should be handled.
For example, should it be `Pointer("foo#/integer")`?

**Comment by yurikhan** [comment]
As far as I can tell, `Pointer`s can only express paths within a single JSON document, or, equivalently, the fragment part of an URI.

I am currently working towards a general solution for #619. I envision reporting violations in a JSON document and representing schema locations as string values in URI syntax, like `{"schemaRef": "foo#/integer"}`. I needed accurate in-schema paths for every case so I extracted this part as a separate improvement.

**Comment by miloyip** [comment]
For creating new feature, keep in mind about backward compatibility. That is what RapidJSON always tried to do. Thanks.

**Comment by yurikhan** [comment]
I strive to preserve the existing behavior, yes. However, if I discover surprising behavior that I would consider a bug, I report it as such. It’s then your call whether it’s worth changing.

**Comment by yurikhan** [comment]
So, what’s your take? Should I preserve the existing behavior of `GetInvalidSchemaPointer()` to return an empty pointer when the actual subschema that is violated is in a different schema document?

It turns out to be not a big deal for #619. I can either change `GetInvalidSchemaPointer()` to return the accurate path, or leave it as is and just work around it in the new code.
