### ISSUE TITLE
error: call to constructor of 'rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >' is ambiguous

### ISSUE THREAD

**Issue by cttlee** [Tencent/rapidjson#1066]
build with NDK

cmake ../src/avs/avs-device-sdk-master 
-DCMAKE_SYSTEM_NAME=Android 
-DCMAKE_ANDROID_STL_TYPE=gnustl_static 
-DANDROID_ABI=arm64-v8a 
-DANDROID_NDK=/home/cttlee/projects/avs/android-ndk-r15c 
-DCMAKE_TOOLCHAIN_FILE=/home/cttlee/projects/avs/android-ndk-r15c/build/cmake/android.toolchain.cmake 
-DANDROID_NATIVE_API_LEVEL=22 
-DANDROID_STL=c++_shared

In file included from /home/cttlee/projects/avs/src/avs/avs-device-sdk-master/CapabilityAgents/AudioPlayer/src/AudioPlayer.cpp:20:
In file included from /home/cttlee/projects/avs/src/avs/avs-device-sdk-master/CapabilityAgents/AudioPlayer/include/AudioPlayer/AudioPlayer.h:23:
In file included from /home/cttlee/projects/avs/src/avs/avs-device-sdk-master/AVSCommon/AVS/include/AVSCommon/AVS/CapabilityAgent.h:30:
In file included from /home/cttlee/projects/avs/src/avs/avs-device-sdk-master/AVSCommon/SDKInterfaces/include/AVSCommon/SDKInterfaces/DirectiveHandlerInterface.h:23:
In file included from /home/cttlee/projects/avs/src/avs/avs-device-sdk-master/AVSCommon/AVS/include/AVSCommon/AVS/AVSDirective.h:24:
In file included from /home/cttlee/projects/avs/src/avs/avs-device-sdk-master/AVSCommon/AVS/include/AVSCommon/AVS/Attachment/AttachmentManagerInterface.h:26:
In file included from /home/cttlee/projects/avs/src/avs/avs-device-sdk-master/AVSCommon/AVS/include/AVSCommon/AVS/Attachment/Attachment.h:27:
In file included from /home/cttlee/projects/avs/src/avs/avs-device-sdk-master/AVSCommon/Utils/include/AVSCommon/Utils/SDS/InProcessSDS.h:27:
In file included from /home/cttlee/projects/avs/src/avs/avs-device-sdk-master/AVSCommon/Utils/include/AVSCommon/Utils/SDS/SharedDataStream.h:25:
In file included from /home/cttlee/projects/avs/src/avs/avs-device-sdk-master/AVSCommon/Utils/include/AVSCommon/Utils/Logger/LoggerUtils.h:22:
In file included from /home/cttlee/projects/avs/src/avs/avs-device-sdk-master/AVSCommon/Utils/include/AVSCommon/Utils/Logger/Logger.h:27:
In file included from /home/cttlee/projects/avs/src/avs/avs-device-sdk-master/AVSCommon/Utils/include/AVSCommon/Utils/Configuration/ConfigurationNode.h:28:
/home/cttlee/projects/avs/src/avs/avs-device-sdk-master/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/document.h:1260:22: error:
call to constructor of 'rapidjson::GenericValue<rapidjson::UTF8,
rapidjson::MemoryPoolAllocatorrapidjson::CrtAllocator >' is ambiguous
GenericValue v(value);
^ ~~~~~
/home/cttlee/projects/avs/src/avs/avs-device-sdk-master/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/document.h:1331:16: note:
in instantiation of function template specialization 'rapidjson::GenericValue<rapidjson::UTF8,
rapidjson::MemoryPoolAllocatorrapidjson::CrtAllocator >::AddMember' requested here
return AddMember(n, value, allocator);
^
/home/cttlee/projects/avs/src/avs/avs-device-sdk-master/CapabilityAgents/AudioPlayer/src/AudioPlayer.cpp:484:11: note:
in instantiation of function template specialization 'rapidjson::GenericValue<rapidjson::UTF8,
rapidjson::MemoryPoolAllocatorrapidjson::CrtAllocator >::AddMember' requested here
state.AddMember(
^
/home/cttlee/projects/avs/src/avs/avs-device-sdk-master/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/document.h:634:14: note:
candidate constructor
explicit GenericValue(int i) RAPIDJSON_NOEXCEPT : data_() {
^
/home/cttlee/projects/avs/src/avs/avs-device-sdk-master/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/document.h:640:14: note:
candidate constructor
explicit GenericValue(unsigned u) RAPIDJSON_NOEXCEPT : data_() {
^
/home/cttlee/projects/avs/src/avs/avs-device-sdk-master/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/document.h:646:14: note:
candidate constructor
explicit GenericValue(int64_t i64) RAPIDJSON_NOEXCEPT : data_() {
^
/home/cttlee/projects/avs/src/avs/avs-device-sdk-master/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/document.h:662:14: note:
candidate constructor
explicit GenericValue(uint64_t u64) RAPIDJSON_NOEXCEPT : data_() {
^
/home/cttlee/projects/avs/src/avs/avs-device-sdk-master/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/document.h:674:14: note:
candidate constructor
explicit GenericValue(double d) RAPIDJSON_NOEXCEPT : data_() { data_.n.d = d; data_.f.flags = k...
^
1 error generated.

**Comment by flyshenghui** [comment]
hi,how to solve this problem?

**Comment by ZizhenWang** [comment]
I meet the same problem. Any solution?
