### ISSUE TITLE
parse the string with nul char, will make error kParseErrorStringMissQuotationMark

### ISSUE THREAD

**Issue by lilinj2000** [Tencent/rapidjson#1067]
in readertest.cpp, add test case as below:
```
TEST(Reader, ParseStringWithNullChar) {
  std::string test("{\"Test\": \"\0\"}", 13);
  EXPECT_EQ(10, strlen(test.c_str()));
  EXPECT_EQ(13, test.length());

  rapidjson::Document doc;
  if (doc.Parse(test.c_str(),
                test.length()).HasParseError()) {
    EXPECT_EQ(kParseErrorStringMissQuotationMark, doc.GetParseError());
    EXPECT_EQ(10, doc.GetErrorOffset());
    FAIL();
  }

  SUCCEED();
}
```
the parse is failed.

**Comment by miloyip** [comment]
In C++, you should make the test string as `"{\"Test\": \"\\0\"}", 10, 10);`. Otherwise `\0` is escaped as `(char)0`, which means end of string.

**Comment by lilinj2000** [comment]
@miloyip  see my new case.

**Comment by miloyip** [comment]
Your case is invalid.

**Comment by miloyip** [comment]
Some characters, including null character (U+0000) must be escaped.

https://tools.ietf.org/html/rfc7159#section-7

~~~
      string = quotation-mark *char quotation-mark

      char = unescaped /
          escape (
              %x22 /          ; "    quotation mark  U+0022
              %x5C /          ; \    reverse solidus U+005C
              %x2F /          ; /    solidus         U+002F
              %x62 /          ; b    backspace       U+0008
              %x66 /          ; f    form feed       U+000C
              %x6E /          ; n    line feed       U+000A
              %x72 /          ; r    carriage return U+000D
              %x74 /          ; t    tab             U+0009
              %x75 4HEXDIG )  ; uXXXX                U+XXXX

      escape = %x5C              ; \

      quotation-mark = %x22      ; "

      unescaped = %x20-21 / %x23-5B / %x5D-10FFFF
~~~

**Comment by lilinj2000** [comment]
@miloyip  I got the string with json format from the third library, this string with the nul char, not my case invalid

**Comment by miloyip** [comment]
Then that is a invalid JSON.
RapidJSON successfully detects that it is invalid and shows an appropriate error message.

**Comment by lilinj2000** [comment]
how to say?

> Note that RapidJSON supports null character \0 inside a string. If such situation happens, strlen(str) < length

**Comment by miloyip** [comment]
For example, a JSON `"A\u0000B"` parsed by SAX API will make a C++ call `handler.String("A\0B", 3, true)`. So that `strlen("A\0B") == 1` but length is 3.

**Comment by lilinj2000** [comment]
@miloyip  got, thanks.  have any help function for '\0' transfer to '\u0000'
