### ISSUE TITLE
Parse、ParseStream、std::stringstream 解析的疑问

### ISSUE THREAD

**Issue by hex2tan** [Tencent/rapidjson#1069]
我的环境：

> CentOS release 6.4 X64
> gcc version 4.8.2 20140120 (Red Hat 4.8.2-15) (GCC)
> rapidjson: 1.0.2

接手了个程序，发现有个模块使用rapidjson解析，其流程如下：
std::string ---> std::stringstream---> rapidjson::StringStream---> ParseStream
代码如下：
```
std::string valid_json_str = "{\"hello\":\"world\"}";
std::stringstream ss(valid_json_str.c_str());
rapidjson::StringStream s(ss.str().c_str());
rapidjson::Document msg_body;
msg_body.ParseStream(s);
```

当然实际上valid_json_str不是这么简单，但这个json确实是合法的：
情况如下：

> 1.valid_json_str是用cppjson构造生成的，其json字符串末尾有一个换行符；
> 2.解析失败的时候，记录了valid_json_str的内容，并打印成16进制。从日志文件里重新读取此 valid_json_str,再用同样的步骤进行解析，还是解析失败，其输出的16进制内容同日志的一致。
> 3.如果手动将换行符去掉，大部分又可以解析成功了，但还是有少量失败，而且失败的错误代码都不一致。
> 4.如果直接调用 msg_body.Parse(valid_json_str.c_str())，则都能成功；
> 5.如果不使用std::stringsteam进行中转，也可以解析成功；

针对此，写了以下几行代码进行测试
  ```
   const char p[] = "{\"hello\":\"world\"}";
    rapidjson::Document doc0;
    rapidjson::Document doc0_str;
    rapidjson::Document doc1;
    rapidjson::Document doc2;

    std::stringstream doc0_stream(p);
    std::stringstream doc0_stream_1(p);
    std::string doc1_str(p);
    std::string doc2_str(p);

    rapidjson::StringStream doc0_rj_stream(doc0_stream.str().c_str());
    rapidjson::StringStream doc1_rj_stream(doc1_str.c_str());

    doc0.ParseStream(doc0_rj_stream);
    doc0_str.Parse(doc0_stream_1.str().c_str());
    doc1.ParseStream(doc1_rj_stream);
    doc2.Parse(doc2_str.c_str());

    printf("doc0     ParseStem,  has error: %d, error code: %d, offset: %lu\n", doc0.HasParseError(), doc0.GetParseError(), doc0.GetErrorOffset());
    printf("doc0_str Parse,      has error: %d, error code: %d, offset: %lu\n", doc0_str.HasParseError(), doc0_str.GetParseError(), doc0_str.GetErrorOffset());
    printf("doc1     ParseSteam, has error: %d, error code: %d, offset: %lu\n", doc1.HasParseError(), doc1.GetParseError(), doc1.GetErrorOffset());
    printf("doc2     Parse,      has error: %d, error code: %d, offset: %lu\n", doc2.HasParseError(), doc2.GetParseError(), doc2.GetErrorOffset());
```
其输出如下：

>     doc0     ParseStem,  has error: 1, error code: 11, offset: 3
>     doc0_str Parse,      has error: 0, error code: 0, offset: 0
>     doc1     ParseSteam, has error: 0, error code: 0, offset: 0
>     doc2     Parse,      has error: 0, error code: 0, offset: 0

不知道为何通过std::stringsteam中转过后，使用ParseStream解析就有问题了？
而正常的Parse则可解析成功。
拜读了下源码，Parse底层也是调用了ParseStream进行解析的，也做了一些其他跟踪，没有找到答案，希望大家帮忙看一下，谢谢。

**Comment by miloyip** [comment]
我记得 `ss.str().c_str()` 是不合法的，因为 [`stringstream::str()`](http://en.cppreference.com/w/cpp/io/basic_stringstream/str):

> The copy of the underlying string returned by str is a temporary object that will be destructed at the end of the expression, so directly calling c_str() on the result of str() (for example in auto *ptr = out.str().c_str();) results in a dangling pointer.

这样才可：
~~~
std::stringstream ss(valid_json_str.c_str());
std::string str = ss.str();
rapidjson::StringStream s(str.c_str());
~~~

**Comment by hex2tan** [comment]
今天又自己跟踪了下，发现确实如此。
还说上来自己解答一下呢，发现已经有解答了。
非常感谢。
