### ISSUE TITLE
怎么使用document添加json成员

### ISSUE THREAD

**Issue by zhanMan** [Tencent/rapidjson#1074]
使用下面代码可以添加成员
       	const char json[] = " { \"hello\" : \"world\", \"t\" : true , \"f\" : false, \"n\": null, \"i\":123} ";
        Document document1;
	if (document1.Parse(json).HasParseError())
		return 1;
	document1.AddMember("author1", "123", document1.GetAllocator());
但是没有进行Parse的时候添加不了
         Document document1;
	 document1.AddMember("author1", "123", document1.GetAllocator());
Document 不能直接添加一个新json成员吗

**Comment by miloyip** [comment]
先调用：

~~~cpp
document1.SetObejct();
~~~

一个 JSON 的根可以是任意类型，预设是 JSON 的 null 类型。

**Comment by zhanMan** [comment]
可以了，谢谢！

**Comment by tuzhirun** [comment]
怎么做的呢？
