### ISSUE TITLE
为什么调用方法中使用document会报错，是编码的原因吗？

### ISSUE THREAD

**Issue by zhanMan** [Tencent/rapidjson#1075]
为什么调用方法中使用document会报错，是编码的原因吗？
![image](https://user-images.githubusercontent.com/31401782/30962089-fdc7ecf4-a47a-11e7-89a5-b804e0117398.png)

**Comment by miloyip** [comment]
Pass by reference or pointer instead.

**Comment by zhanMan** [comment]
嗯，O(∩_∩)O谢谢，昨天的时候测试出来了，忘了关闭了，刚刚开始学习C++，基础有点差。
