### ISSUE TITLE
Klocwork Errors for document.h and encodings.h

### ISSUE THREAD

**Issue by cwm262** [Tencent/rapidjson#1077]
Please verify if the following klocwork static analysis errors are valid:

* encodings.h: Operands in a bitwise operation have different size (Line 387)
More info: The CWARN.BITOP.SIZE checker looks for code in which bitwise operations (&=, |=, and ^=) have operands with different sizes. Both operands of a bitwise operation must normally be either 32-bit or 64-bit values, although the checker won't flag a 64-bit mask used on a 32-bit value. When an unsigned 32-bit value is converted to a 64-bit type, the 32 higher bits are set to zero, which probably isn't the original design intent and can cause unexpected results.
* document.h: Memory manipulation routine 'memmove' is applied to a non-POD object (Method: Erase)
* document.h: Memory manipulation routine 'memcpy' is applied to a non-POD object (Method: SetArrayRaw)
* document.h: Memory manipulation routine 'memcpy' is applied to a non-POD object (Method: SetObjectRaw)
* More info for the last three: Low level memory manipulation routines (memset, bzero, memcpy, etc.) should be never used for initializing objects of non-POD (plain old data) types. Such objects should be initialized by means of their constructors. If an object is non-POD, it normally contains information different from plain data. Writing directly to memory occupied by such an object will most likely corrupt its internal memory representation. In particular, the vtable of the object itself or of one of its members may be lost, and an attempt to call a virtual member function may therefore cause a crash. Rewriting reference members directly will also cause a failure when those members are used.

**Comment by miloyip** [comment]
There is no vtable for `GenericValue`.

**Comment by Bu11etmagnet** [comment]
That is not in itself enough to dismiss this issue. A vtable is just one example of what can be corrupted when using `memset`.
Luckily, `GenericValue` contains only two members: an unsigned, and a member of type `Data`. `Data` is a union (of String, ShortString, Number, Object, Array). It so happens that all these types are POD types, so `memset`ting a Data (and by extension, a `GenericValue`) seems to be safe.
*That* would have been a justified reason to close this issue.

**Comment by miloyip** [comment]
It is not luck per se. This was a design decision to make it like a POD but cannot fulfil all requirements of POD.
