### ISSUE TITLE
SetObject/RemoveAllMembers does not reset allocator size

### ISSUE THREAD

**Issue by acidleaf** [Tencent/rapidjson#1078]
```c++
rapidjson::Document doc(rapidjson::kObjectType);
auto& a = doc.GetAllocator();

doc.AddMember("someMember", 12345, a);
printf("%d %d", a.Size(), a.Capacity());		// 512 65536
doc.SetObject();
doc.RemoveAllMembers();
printf("%d %d", a.Size(), a.Capacity());		// 512 65536
````

Shouldn't the second printf give `0 65536` instead?

Compiled with Visual Studio 2015 Professional Version 14.0.25431.01 Update 3
Wndows 10 64-bit

**Comment by miloyip** [comment]
The default allocator does not reduce its size or capacity, by design.
You may manually call `allocator.Clear()`, but you need to ensure that no pointers were still pointing to the allocated memory (which causes dangling pointer).

**Comment by acidleaf** [comment]
Does `allocator.Clear()` free the allocated memory blocks? What I wish to achieve is to reset the used memory and retain the already allocated blocks so that the container can be reused again without reallocating memory until needed.

**Comment by miloyip** [comment]
The current design cannot do so.
I think you may provide a user buffer to do something like that (but not exactly).

**Comment by acidleaf** [comment]
Noted, thank you very much!
