### ISSUE TITLE
-Wclass-memaccess triggered by GCC7

### ISSUE THREAD

**Issue by h-2** [Tencent/rapidjson#1086]
I am using RapidJSON via Cereal and it triggers the above warning, please see USCiLab/cereal#434

Can you fix this warning or locally suppress it?

Thank you very much!

**Comment by miloyip** [comment]
I think suppression is the way to go. I do not have that build environment. Can you make a PR?

**Comment by marehr** [comment]
I think this was fixed and can be closed?

**Comment by marehr** [comment]
Hmm, #1205 indicates that this is not fixed yet.
