### ISSUE TITLE
Is it possible to hold a iterator or reference to a json value?

### ISSUE THREAD

**Issue by h46incon** [Tencent/rapidjson#1088]
I need to store a pointer to a json value (actually a member in a object) in class to access in the further. However, rapidjson use a array as buffer so the pointer may be invalid when calling `RemoveMember()`, `EraseMember()` or `AddMember()` of the json object:
```
rapidjson::Document doc;
//...
rapidjson::Value* jPointer = &doc["key"];
worker.SetJsonPointer(jPointer);
doc.RemoveMember("otherKey");    // This may invalidating jPointer
```
So is it possible to hold a valid reference to a member of object?

**Comment by pah** [comment]
You may want to check out the [JSON Pointer](http://rapidjson.org/md_doc_pointer.html) support instead of using raw C++ pointers.

**Comment by h46incon** [comment]
> You may want to check out the JSON Pointer support instead of using raw C++ pointers.
This will bring additional compute complexity but work as expect, thanks.
