### ISSUE TITLE
Error in regular expression for schmea?

### ISSUE THREAD

**Issue by mj8353** [Tencent/rapidjson#1093]
Hello developers of rapidjson,

I use the regular expression in my schema to check the predefined time forma.

The time format is defined like this example: 2016-09-19T14:39:57-08:00.

But likely the schema validation don't work with my example.

**The schema i used is as followed:**
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id"     : "testSchmea.json",
    "definitions" : {
                       "timeDef"           : { "type"        : "string",
                                               "pattern"     :  `"^[0-9]{4}\\-[0-9]{2}\\-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}[\\+\\-][0-9]{2}:[0-9]{2}$"`,
                                               "maxLength"   : 25,
                                               "minLength"   : 25,
                                               "description" : "Time format used in manifest. The format should be for example 2016-08-19T14:39:50+08:00."
                                             }
                    },
    "additionalProperties" : false,
    "required"             : [ "time" ],
    "properties"           : { "time"    : { "$ref" : "#/definitions/timeDef"}}
} 

**The json file to be checked is here:**
{
    "time" : "2016-0a-19T14:39:57-08:00"
}

**The code i used was from the example in your standard example:**

// Schema Validator example
// The example validates JSON text from stdin with a JSON schema specified in the argument.
#include "rapidjson/error/en.h"
#include "rapidjson/filereadstream.h"
#include "rapidjson/schema.h"
#include "rapidjson/stringbuffer.h"
using namespace rapidjson;
int main(int argc, char *argv[]) {
    if (argc != 2) {
        fprintf(stderr, "Usage: schemavalidator schema.json < input.json\n");
        return EXIT_FAILURE;
    }

    // Read a JSON schema from file into Document
    Document d;
    char buffer[4096];

    {
        FILE *fp = fopen(argv[1], "r");
        if (!fp) {
            printf("Schema file '%s' not found\n", argv[1]);
            return -1;
        }
        FileReadStream fs(fp, buffer, sizeof(buffer));
        d.ParseStream(fs);
        if (d.HasParseError()) {
            fprintf(stderr, "Schema file '%s' is not a valid JSON\n", argv[1]);
            fprintf(stderr, "Error(offset %u): %s\n",
                static_cast<unsigned>(d.GetErrorOffset()),
                GetParseError_En(d.GetParseError()));
            fclose(fp);
            return EXIT_FAILURE;
        }
        fclose(fp);
    }
    
    // Then convert the Document into SchemaDocument
    SchemaDocument sd(d);

    // Use reader to parse the JSON in stdin, and forward SAX events to validator
    SchemaValidator validator(sd);
    Reader reader;
    FileReadStream is(stdin, buffer, sizeof(buffer));
    if (!reader.Parse(is, validator) && reader.GetParseErrorCode() != kParseErrorTermination) {
        // Schema validator error would cause kParseErrorTermination, which will handle it in next step.
        fprintf(stderr, "Input is not a valid JSON\n");
        fprintf(stderr, "Error(offset %u): %s\n",
            static_cast<unsigned>(reader.GetErrorOffset()),
            GetParseError_En(reader.GetParseErrorCode()));
    }

    // Check the validation result
    if (validator.IsValid()) {
        printf("Input JSON is valid.\n");
        return EXIT_SUCCESS;
    }
    else {
        printf("Input JSON is invalid.\n");
        StringBuffer sb;
        validator.GetInvalidSchemaPointer().StringifyUriFragment(sb);
        fprintf(stderr, "Invalid schema: %s\n", sb.GetString());
        fprintf(stderr, "Invalid keyword: %s\n", validator.GetInvalidSchemaKeyword());
        sb.Clear();
        validator.GetInvalidDocumentPointer().StringifyUriFragment(sb);
        fprintf(stderr, "Invalid document: %s\n", sb.GetString());
        return EXIT_FAILURE;
    }
}

**Description:**
Unter my example the schemavalidator should reurn a invalid. But acutally not.
I have already tested this example with follow web schema validator. It bring me a false back. Also it works.
WebSchemaValidator: http://www.jsonschemavalidator.net/

I have already drilled deeper with the follow regular expression in rapidjson.

regex: `"^[0-9]{4}\\-$"`
string to test: "201a-", "1", "20aa-"

The schemavalidator bringe me for all of these strings a "valid" back. If you delete `\\-`, then it works. 

Maybe here is an error in rapidjson? Or i have wrong setting?

**Comment by miloyip** [comment]
As I remember, `"\\-"` is not supported.  Need to use `"-"`.

**Comment by mj8353** [comment]
Thank you miloyip. I replaced `"\\-"` with `"-"` and it works.
