### ISSUE TITLE
Is it possiable to reference a subschema in another file in rapidjson? 

### ISSUE THREAD

**Issue by mj8353** [Tencent/rapidjson#1096]
Hello gurus in forum:

I want to define a schema with two parts. The first one is defined from me and the rest part is defined from thrid party. I want to seperate the both parts in two schema-files.  The main schema can be linked with the sub schema file using "id".  I can use "$ref": "subSchemaFile/definitions/typeDef" to reference the definitions in other sub schema files. But i tried it in rapidjson. Likely it doesn't work. Is the reference to sub schema definitions in other files possiable in rapidjson at all? If it is possiable, how can i use it?

I give here one example to explain my thought:

**mainSchema is like the one as following and locates in file mainSchema.json:**
```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id"     : "mainSchmea",
    "definitions" : {
                       "def1"   : { "type"      : "string",
                                       "pattern"  : "^[a-z]$"
                                      }                
                          },
   "additionalProperties" : false,
   "required"             : [ "def1", "def2" ],                
   "properties"          : { "def1"    : { "$ref" : "#/definitions/def1"},
                                   "def2"    : { "$ref" : "subSchema/definitions/def2"}
                                 }
} 
```
**subSchema is like the one as following and locates in file subSchema.json:**

```
{
    "$schema"     : "http://json-schema.org/draft-04/schema#",
    "id"                : "subSchema",
    "definitions"   : {
                             "def2"   : { "type"    : "string",
                                            "pattern" : "^[0-9]$"
                                      }                
                             }
} 
```

**Both schema files are in the same directory.**

**Comment by miloyip** [comment]
Yes, please check the Remote Schema in [http://rapidjson.org/md_doc_schema.html](documentation).

**Comment by mj8353** [comment]
This is example i tried:

**Main Schema:**
```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id"     : "testSchmea.json",
    "definitions" : {
                       "Def1"           : { "type"    : "string",
                                            "pattern" : "^[a-z]$"
                                          }                       
                    },
    "additionalProperties" : false,
    "required"             : [ "def1", "def2" ],                           
    "properties"           : { "def1" : { "$ref" : "#/definitions/Def1"},
                               "def2" : { "$ref" : "testSubSchema.json#/definitions/Def2"}
                             }
} 

```

**SubSchema:**

```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id"     : "testSubSchmea.json",
    "definitions" : {
                       "Def2"           : { "type"    : "string",
                                            "pattern" : "^[0-9]$"
                                          }                         
                    }
} 
```

**test.json:**
```
{
    "def1" : "z",
    "def2" : "z"
}
```

The schema validator give me a valid for this test.json,because it didn't find the testSubSchmea.json.
The both files are in same directory. 
Should i implement also the IRemoteSchemaDocumentProvider for my usage? I just think, i don't use it remotely. All of my sub files are in the local computer, even in the same directory.

**Comment by Innokentiy-Alaytsev** [comment]
Hello!

Yes, you should implement `IRemoteSchemaDocumentProvider` that provides remote schema files for the validator to use. The remote schema is referenced by URI that identifies it. As a general purpose library, RapidJSON can not know how to dereference the URI.
