### ISSUE TITLE
ParseFlag疑问

### ISSUE THREAD

**Issue by oneonce** [Tencent/rapidjson#1099]
1. ParseFlag和编码有关系吗？如UTF-8，UNICODE等等
2. 我写了个静态类专门用来解析json，静态类有个静态成员document，我想让这个document和vector一样设置一个固定的capacity为4K，每次重新解析前把内容清空，4K空间仍然保留，如何指定4K？

每次解析新的json前做如下操作：
document.SetNull();
document.Erase(document.Begin(), document.End()); //这样会报错

**Comment by miloyip** [comment]
1. 没有
2. http://rapidjson.org/zh-cn/md_doc_dom_8zh-cn.html#UserBuffer 然后 `document.SetNull()`, `valueAllocator.Clear()`, `parseAllocator.Clear()`
