### ISSUE TITLE
Compilation on Solaris around fread() and fwrite()

### ISSUE THREAD

**Issue by clach04** [Tencent/rapidjson#1104]
Different to issue #686.

Error:

    "/...../rapidjson/filereadstream.h", line 71: Error: The function "fread" must have a prototype.
    1 Error(s) detected.

With testcase:

worked with [~dupbr01]. Under Solaris fread() is included from iso/stdio_iso.h which declares fread() in the {{std}} namespace (as one would expect).

Updating rapidjson to use std::fread works (not tried fwrite() yet).

Small test case, test.cpp

{code}
#include "rapidjson.h"
#include "filereadstream.h"
#include "filewritestream.h"
{code}

    CC -I /tmp/cmc/rapidjson/ test.cpp

debug:
    CC -I /tmp/cmc/rapidjson/ test.cpp -E > preprocessed_test.cpp

**Comment by clach04** [comment]
I have a small patch for this.

**Comment by miloyip** [comment]
Please make a PR. Thank you.

**Comment by miloyip** [comment]
Oh. Just saw that.
