### ISSUE TITLE
怎么捕获json解析和获取异常

### ISSUE THREAD

**Issue by zhanMan** [Tencent/rapidjson#1107]
![image](https://user-images.githubusercontent.com/31401782/32219992-03e73072-be6b-11e7-9d06-4db42891ae9d.png)
程序没有进入到catch的异常里面，而是直接报错，这是怎么回事？？

**Comment by miloyip** [comment]
不需要 exception，如有解析错误就 `HasParseError() == true` 。

**Comment by calabashdad** [comment]
这里并不是解析错误，解析对了，但是取值的时候，传了一个错误的值，两码事，这种的怎么捕获下？

**Comment by SamCodeLive** [comment]
我也遇到了. 直接崩溃.

**Comment by FightToDawn** [comment]
> 我也遇到了. 直接崩溃.

`// release模式下 把断言当做异常弹出
#ifndef _DEBUG
#define RAPIDJSON_ASSERT(x)		if (!(x)) throw std::exception("std::exception RAPIDJSON_ASSERT");
#endif // _DEBUG

//包含 rapidjson 库
#include "..\\rapidjson\\document.h"
#include "..\\rapidjson\\writer.h"
#include "..\\rapidjson\\stringbuffer.h"

using namespace rapidjson;`

即可
