### ISSUE TITLE
Create SubDocument of Document which will contain references to values, but not copies

### ISSUE THREAD

**Issue by qywx** [Tencent/rapidjson#1109]
Hi.

Let's imagine there is one json document:
~~~json
{
  "1":11,
  "a":"b",
  "obj":{
    "o":"c",
    "b":true
  }
}
~~~
I want to create subset without copies. For example user could request values by pointers. Let them be `"/a"` and `"/obj/b"`. The sub-document expected to look like:
~~~json
{
  "a":"b",
  "obj":{
    "b":true
  }
}
~~~
In this second document all key and value objects are references to first (master) document.  
`SubDocument` should have all properties of `Document`.

Do you have ideas?

**Comment by miloyip** [comment]
No. Currently a DOM node owns its child nodes. To make such reference possible, you may need to create a DOM with `shared_ptr`-like reference counted ownership, and prevent cyclic reference.
