### ISSUE TITLE
rapidjson不支持长json转换？

### ISSUE THREAD

**Issue by pushingmyway** [Tencent/rapidjson#1111]
有一个长json串 约 244k,在调用d.Parse(feedsProfileJson.c_str()).HasParseError()的时候报错

如下：
rapidjson/include/rapidjson/document.h:1108: rapidjson::GenericValue<Encoding, Allocator>& rapidjson::GenericValue<Encoding, Allocator>::operator[](const rapidjson::GenericValue<Encoding, SourceAllocator>&) [with SourceAllocator = rapidjson::MemoryPoolAllocator<>; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>]: Assertion `false' failed.

**Comment by miloyip** [comment]
这不是 Parse() 时会出现的断言失败。
