### ISSUE TITLE
document.Parse 解析gbk格式的json数据，解析错误

### ISSUE THREAD

**Issue by yangchen8** [Tencent/rapidjson#1112]
下面是我的json数据
[{"data":{"result":[{"actors":[{"name":"鹤广美","roleName":""},{"name":"神谷明","roleName":""},{"name":"广濑正志","roleName":""},{"name":"银河万丈","roleName":""},{"name":"田中秀幸","roleName":""},{"name":"松岛美野里","roleName":""},{"name":"二又一成","roleName":""},{"name":"山本圭子","roleName":""},{"name":"田中和实","roleName":""},{"name":"北川米彦","roleName":""},{"name":"水鸟铁夫","roleName":""},{"name":"户谷公次","roleName":""},{"name":"大冢周夫","roleName":""},{"name":"盐泽兼人","roleName":""},{"name":"乡里大辅","roleName":""},{"name":"堀秀行","roleName":""},{"name":"Sanji Hase","roleName":""},{"name":"神谷明","roleName":""},{"name":"松岛みのり","roleName":""},{"name":"水鸟鉄夫","roleName":""},{"name":"平野正人","roleName":""},{"name":"大冢周夫","roleName":""},{"name":"はせさん治","roleName":""},{"name":"田中秀幸","roleName":""},{"name":"堀秀行","roleName":""},{"name":"塩沢兼人","roleName":""},{"name":"郷里大辅","roleName":""},{"name":"银河万丈","roleName":""},{"name":"佐藤正治","roleName":""},{"name":"広瀬正志","roleName":""}],"company":"","genres":{},"directors":["山吉康夫"],"screenWriters":{},"releaseDate":"1986-12-20","language":"日语","hot":"0","awards":{},"_id":"10925527","areas":["日本"],"picLink":"","episode":{},"name":"筋肉人 正义超人vs战士超人","channel":"电影","season":"","score":"0.0","aliasNames":["Kinnikuman: Seigi Choujin vs. Senshi Choujin","Muscleman: Seigi Choujin vs. Senshi Choujin","金肉人 正义超人vs战士超人","キン肉マン 正义超人vs戦士超人"],"leadactors":[{"name":"鹤广美","roleName":""},{"name":"神谷明","roleName":""},{"name":"广濑正志","roleName":""},{"name":"银河万丈","roleName":""},{"name":"田中秀幸","roleName":""}]},{"actors":[{"name":"大泽茜","roleName":"金丹"}],"company":"","genres":["动漫","儿童"],"directors":{},"screenWriters":{},"releaseDate":"2011-07-02","language":"日语","hot":"0","awards":{},"_id":"10892732","areas":["日本"],"picLink":"","episode":{},"name":"面包超人:面包超人与森林宝藏","channel":"电影","season":"面包超人与森林宝藏","score":"0.0","aliasNames":["それいけ!アンパンマン うたって てあそび! アンパンマンともりのたから"],"leadactors":[{"name":"大泽茜","roleName":"金丹"}]},{"actors":[{"name":"神谷明","roleName":""},{"name":"松岛みのり","roleName":""},{"name":"広瀬正志","roleName":""},{"name":"郷里大辅","roleName":""},{"name":"永井一郎","roleName":""},{"name":"はせさん治","roleName":""},{"name":"鹤ひろみ","roleName":""},{"name":"川岛千代子","roleName":""},{"name":"田中秀幸","roleName":""},{"name":"堀秀行","roleName":""},{"name":"中岛千里","roleName":""},{"name":"蟹江栄司","roleName":""},{"name":"水鸟鉄夫","roleName":""},{"name":"乡里大辅","roleName":"Robin Mask"},{"name":"广濑正志","roleName":"Rikishiman"},{"name":"鹤广美","roleName":"Natsuko Shôno"},{"name":"山本圭子","roleName":"Nachiguron"},{"name":"松岛美野里","roleName":"Alexandria Meat"},{"name":"蟹江荣司","roleName":"Ramenman"},{"name":"水鸟铁夫","roleName":"Brocken Jr"},{"name":"佐藤正治","roleName":"Buffaloman"},{"name":"岸野一彦","roleName":"King Mayumi Kinniku"},{"name":"北川米彦","roleName":"Chairman Harabote Muscle"}],"company":"","genres":["动漫"],"directors":["山吉康夫"],"screenWriters":{},"releaseDate":"1985-03-15","language":"日语","hot":"0","awards":{},"_id":"10925528","areas":["日本"],"picLink":"","episode":{},"name":"筋肉人 正义超人vs古代超人","channel":"电影","season":"","score":"0.0","aliasNames":["キン肉マン 正义超人VS古代超人","Kinnikuman: Seigi Choujin vs. Ancient Choujin","Muscleman: Seigi Choujin vs. Ancient Choujin","金肉人 正义超人vs古代超人","筋肉人 正义超人vs古代超人"],"leadactors":[{"name":"神谷明","roleName":""},{"name":"松岛みのり","roleName":""},{"name":"広瀬正志","roleName":""},{"name":"郷里大辅","roleName":""},{"name":"永井一郎","roleName":""},{"name":"田中秀幸","roleName":"Terryman"},{"name":"乡里大辅","roleName":"Robin Mask"},{"name":"堀秀行","roleName":"Warsman"}]},{"actors":[{"name":"Shakeel Bharati","roleName":""},{"name":"Farogh Jafri","roleName":""},{"name":"Akram Khan","roleName":""},{"name":"Shafique","roleName":""},{"name":"Nazir Shaikh","roleName":""}],"company":"","genres":["纪录片"],"directors":["Faiza Ahmad Khan"],"screenWriters":{},"releaseDate":"2008-07-28","language":"乌尔都语 ,印地语","hot":"216","awards":{},"_id":"10091939","areas":["新加坡","日本","韩国","印度"],"picLink":"","episode":{},"name":"马勒冈的超人","channel":"纪录片","season":"","score":"8.4","aliasNames":["Supermen of Malegaon,业余超人","インド マレガオンのスーパーマン","Supermen of Malegaon"],"leadactors":[{"name":"Shakeel Bharati","roleName":""},{"name":"Farogh Jafri","roleName":""},{"name":"Akram Khan","roleName":""},{"name":"Shafique","roleName":""},{"name":"Nazir Shaikh","roleName":""}]},{"actors":[{"name":"大浦冬华","roleName":""},{"name":"白石凉子","roleName":""},{"name":"定冈小百合","roleName":""}],"company":"","genres":["动漫","短片"],"directors":["石田祐康","石田祐康"],"screenWriters":["田中淳一"],"releaseDate":"2014-10-30","language":"日语","hot":"95","awards":{},"_id":"10060224","areas":["日本"],"picLink":"","episode":{},"name":"拉链超人组","channel":"电影","season":"","score":"6.4","aliasNames":["FASTENING DAYS"],"leadactors":[{"name":"大浦冬华","roleName":""},{"name":"白石凉子","roleName":""},{"name":"定冈小百合","roleName":""}]},{"actors":[{"name":"巴德·科耶尔","roleName":""},{"name":"Joan Alexander","roleName":""},{"name":"Julian Noa","roleName":""},{"name":"Noa","roleName":"Narrator ,Gangster "}],"company":"派拉蒙影业公司","genres":["科幻","动漫","短片","警匪","奇幻","冒险"],"directors":["戴夫·弗莱彻","Dave Fleischer"],"screenWriters":["乔·舒斯特","杰里·西格尔","Seymour Kneitel","Izzy Sparber"],"releaseDate":"1942-01-01","language":"英语","hot":"1","awards":{},"_id":"10183498","areas":["美国"],"picLink":"","episode":{},"name":"超人:亿万金列","channel":"电影","season":"亿万金列","score":"0.0","aliasNames":["超人1941版3,Billion Dollar Limited","Billion Dollar Limited","Superman - Der Millionenraub","Kultakuljetus","El lío del billón de dólares"],"leadactors":[{"name":"巴德·科耶尔","roleName":""},{"name":"Joan Alexander","roleName":""},{"name":"Julian Noa","roleName":""},{"name":"Noa","roleName":"Narrator ,Gangster "}]},{"actors":[{"name":"艾米·亚当斯","roleName":""},{"name":"亨利·卡维尔","roleName":""},{"name":"吉奥夫·约翰斯","roleName":""},{"name":"扎克·施奈德","roleName":""},{"name":"本·阿弗莱克","roleName":""},{"name":"黛博拉·施奈德","roleName":""}],"company":"","genres":["纪录片","短片"],"directors":{},"screenWriters":{},"releaseDate":"2016-07-19","language":"英语","hot":"0","awards":{},"_id":"10091373","areas":["美国"],"picLink":"","episode":{},"name":"超人:复杂与真相","channel":"纪录片","season":"复杂与真相","score":"0.0","aliasNames":["Superman: Complexity & Truth","Gods and Men: A Meeting of Giants"],"leadactors":[{"name":"艾米·亚当斯","roleName":""},{"name":"亨利·卡维尔","roleName":""},{"name":"吉奥夫·约翰斯","roleName":""},{"name":"扎克·施奈德","roleName":""},{"name":"本·阿弗莱克","roleName":""},{"name":"黛博拉·施奈德","roleName":""}]},{"actors":[{"name":"中尾隆圣","roleName":""},{"name":"水野真纪","roleName":""},{"name":"戸田恵子","roleName":""},{"name":"増冈弘","roleName":""},{"name":"佐久间レイ","roleName":""},{"name":"山寺宏一","roleName":""},{"name":"鹤ひろみ","roleName":""},{"name":"岛本须美","roleName":""},{"name":"柳沢三千代","roleName":""},{"name":"かないみか","roleName":""},{"name":"长沢美树","roleName":""},{"name":"肝付兼太","roleName":""},{"name":"滝沢ロコ","roleName":""},{"name":"坂本千夏","roleName":""},{"name":"原えりこ","roleName":""},{"name":"中村ひろみ","roleName":""},{"name":"潘恵子","roleName":""},{"name":"半场友恵","roleName":""},{"name":"豊嶋真千子","roleName":""},{"name":"星野充昭","roleName":""},{"name":"三ツ矢雄二","roleName":""},{"name":"吉田小南美","roleName":""},{"name":"榎本加奈子","roleName":""},{"name":"藤井恒久","roleName":""},{"name":"户田惠子","roleName":"面包超人"}],"company":"Tokyo Theatres K.K","genres":["动漫"],"directors":["矢野博之","日巻裕二"],"screenWriters":["金春智子","菅良幸","柳濑嵩"],"releaseDate":"2007-07-14","language":"日语","hot":"0","awards":{},"_id":"10167532","areas":["日本"],"picLink":"","episode":{},"name":"面包超人:玻露的泡泡球","channel":"电影","season":"玻露的泡泡球","score":"0.0","aliasNames":["それいけ!アンパンマンシャボン玉のプルン,Soreike! Anpanman","Purun of Bubbles","それいけ!アンパンマンシャボン玉のプルン","Anpanman Movie 2007","面包超人:玻露的泡泡球"],"leadactors":[{"name":"中尾隆圣","roleName":""},{"name":"水野真纪","roleName":""},{"name":"戸田恵子","roleName":""},{"name":"増冈弘","roleName":""},{"name":"佐久间レイ","roleName":""},{"name":"山寺宏一","roleName":""},{"name":"户田惠子","roleName":"面包超人"},{"name":"榎本加奈子","roleName":"恐怖妹妹"}]},{"actors":[{"name":"Nancy Schoenberger","roleName":""},{"name":"Jack Law","roleName":""},{"name":"Xan Brookes","roleName":""},{"name":"德克斯特·弗莱彻","roleName":"Narrator"},{"name":"迪恩·凯恩","roleName":"Himself"},{"name":"杰里·西格尔","roleName":"Himself"},{"name":"Gerard Jones","roleName":"Himself"},{"name":"伊尔亚·萨尔金德","roleName":"Himself"},{"name":"玛戈·基德","roleName":"Herself"},{"name":"苏珊娜·约克","roleName":"Herself"},{"name":"乔·舒斯特","roleName":"Himself"}],"company":"","genres":["纪录片"],"directors":["Dexter Fletcher","Andy Baybutt"],"screenWriters":{},"releaseDate":"2006-07-15","language":"英语","hot":"0","awards":{},"_id":"10140667","areas":["英国"],"picLink":"","episode":{},"name":"超人的诅咒","channel":"纪录片","season":"","score":"0.0","aliasNames":["The Curse of Superman"],"leadactors":[{"name":"Nancy Schoenberger","roleName":""},{"name":"Jack Law","roleName":""},{"name":"Xan Brookes","roleName":""},{"name":"德克斯特·弗莱彻","roleName":"Narrator"}]},{"actors":[{"name":"山田恭子","roleName":""},{"name":"花井その子","roleName":""},{"name":"富山敬","roleName":""}],"company":"","genres":["动漫"],"directors":["氷树凡人"],"screenWriters":{},"releaseDate":"1984-03-17","language":"日语","hot":"0","awards":{},"_id":"10120602","areas":["日本"],"picLink":"","episode":{},"name":"宇宙小超人 来自M7.8星的伙伴","channel":"电影","season":"","score":"0.0","aliasNames":["ウルトラマンキッズ M7.8星のゆかいな仲间,Ultraman Kids","M7.8 Sei no Yukai na Nakama","ウルトラマンキッズ M7.8星のゆかいな仲间"],"leadactors":[{"name":"山田恭子","roleName":""},{"name":"花井その子","roleName":""},{"name":"富山敬","roleName":""}]}],"debug":{}}}]
由于项目原因，需要将上面的json字符串转换为gbk，在进行Parse解析。可是在解析的时候，发现解析失败。由于 ”榎“  这个字，gbk编码，第二个字符是一个”\“ 。导致解析失败。请问这种编码问题，有什么好的解决方案吗（直接解析utf-8编码的json字符串是没有问题的）？

**Comment by miloyip** [comment]
RapidJSON 仅支持 JSON 标准所需的 UTF-8、16、32，并不支持其他编码。你可能需要先转码才能使用。

**Comment by yangchen8** [comment]
那有没有好的方案能支持gbk呢？或者说做一些处理，参数设置，让parse解析成功？

**Comment by miloyip** [comment]
不知道你的系统有没有 [libiconv](https://www.gnu.org/software/libiconv/)，或是用类似的库做 GBK -> UTF-8 转换

**Comment by yangchen8** [comment]
代码中有gbk -> utf8 转换的代码，同时用utf8解析没有问题。现在我就想用gbk格式的数据，解析这个json，有没有方法使得parse不出错？

**Comment by miloyip** [comment]
先把 JSON 转换成 UTF-8。

**Comment by beichen2012** [comment]
我的json文件 的编码格式是gbk，在win上没有问题，能正常解析。但是在ubuntu下，就成乱码了。
