### ISSUE TITLE
Document需要释放内存空间吗？

### ISSUE THREAD

**Issue by zhanMan** [Tencent/rapidjson#1113]
Document dest_ds;
	dest_ds.SetObject();
	Document::AllocatorType& allocator = dest_ds.GetAllocator();
	dest_ds.AddMember("a", "a", allocator);
	dest_ds.AddMember("b", b, allocator);
请问需要释放内存空间吗？

**Comment by miloyip** [comment]
Document constructor 不自带 allocator 的话，Document 会建一个内置的 allocator，destructor 会释放该 allocator。所以，简单回答是「不需要」手工释放。
