### ISSUE TITLE
rapidjson 的 SAX 接口是线程安全的吗？

### ISSUE THREAD

**Issue by tantanjing** [Tencent/rapidjson#1116]

**Comment by miloyip** [comment]
线程安全的概念很广，RapidJSON 不会用到如静态变量这类东西，所以各个线程使用不同的 `Reader` 不会有问题，但如果多个线程访问同一个对象就会有问题。

**Comment by tantanjing** [comment]
我的使用场景是多个线程使用不同的 Reader 来对不同的 json 进行并行处理，各个线程间数据是独立的，看来这个场景下使用 rapidjson 是没有问题的。
       感谢 rapidjson 的作者，这个库很好用，性能非常好，在高性能的场景下很赞。
