### ISSUE TITLE
请问如何在 VC++6.0 中使用 rapidjson 呢？

### ISSUE THREAD

**Issue by KruelMeow** [Tencent/rapidjson#1120]
在下是一个 VC++ 初初初初学者，rapidjson 是最喜欢用的 json 解析库，在 VS2017 里用得很舒服。
但是最近有个特别的情况需要在 VC++6.0 里编译，就会报很多很多错误，解决无力。。。
大概是因为 C++11 不能被 VC++6.0 所支持？
请问我这样还有救吗？
第一次提 issue，有什么冒犯或者不详实的地方请指出和包涵，感激不尽！

（附仅 #include "rapidjson/document.h" 了出现的错误）

Compiling...
testjson.cpp
\vc98\include\wchar.h(700) : error C2733: second C linkage of overloaded function 'wmemchr' not allowed
\vc98\include\wchar.h(699) : see declaration of 'wmemchr'	
\vc98\include\wchar.h(702) : error C2733: second C linkage of overloaded function 'wcschr' not allowed
\vc98\include\wchar.h(701) : see declaration of 'wcschr'	
\vc98\include\wchar.h(704) : error C2733: second C linkage of overloaded function 'wcspbrk' not allowed
\vc98\include\wchar.h(703) : see declaration of 'wcspbrk'	
\vc98\include\wchar.h(706) : error C2733: second C linkage of overloaded function 'wcsrchr' not allowed
\vc98\include\wchar.h(705) : see declaration of 'wcsrchr'		
\vc98\include\wchar.h(708) : error C2733: second C linkage of overloaded function 'wcsstr' not allowed
\vc98\include\wchar.h(707) : see declaration of 'wcsstr'
\rapidjson\rapidjson.h(395) : error C2653: 'std' : is not a class or namespace name
\rapidjson\rapidjson.h(395) : error C2868: 'size_t' : illegal syntax for using-declaration; expected qualified-name
\rapidjson\allocators.h(64) : error C2258: illegal pure syntax, must be '= 0'
\rapidjson\allocators.h(64) : error C2252: 'kNeedFree' : pure specifier can only be specified for functions
\rapidjson\allocators.h(104) : error C2252: 'kNeedFree' : pure specifier can only be specified for functions
\rapidjson\allocators.h(267) : see reference to class template instantiation 'rapidjson::MemoryPoolAllocator<BaseAllocator>' being compiled
\rapidjson\allocators.h(251) : error C2258: illegal pure syntax, must be '= 0'
\rapidjson\allocators.h(267) : see reference to class template instantiation 'rapidjson::MemoryPoolAllocator<BaseAllocator>' being compiled
\rapidjson\allocators.h(251) : error C2252: 'kDefaultChunkCapacity' : pure specifier can only be specified for functions
\rapidjson\allocators.h(267) : see reference to class template instantiation 'rapidjson::MemoryPoolAllocator<BaseAllocator>' being compiled
\rapidjson\encodings.h(21) : error C2065: 'warning' : undeclared identifier
\rapidjson\encodings.h(21) : error C2065: 'push' : undeclared identifier
\rapidjson\encodings.h(22) : error C2501: '__pragma' : missing storage-class or type specifiers
\rapidjson\encodings.h(22) : error C2146: syntax error : missing ';' before identifier '__pragma'
\rapidjson\encodings.h(22) : error C2065: 'disable' : undeclared identifier
\rapidjson\encodings.h(22) : error C2143: syntax error : missing ')' before ':'
\rapidjson\encodings.h(22) : error C2143: syntax error : missing ';' before 'constant'
\rapidjson\encodings.h(22) : error C2059: syntax error : ')'
\rapidjson\encodings.h(22) : error C2059: syntax error : ')'
\rapidjson\encodings.h(23) : error C2143: syntax error : missing ';' before 'constant'
\rapidjson\encodings.h(23) : error C2059: syntax error : ')'
\rapidjson\encodings.h(23) : error C2059: syntax error : ')'
\rapidjson\encodings.h(30) : error C2143: syntax error : missing ';' before '{'
\rapidjson\encodings.h(30) : error C2447: missing function header (old-style formal list?)
\rapidjson\encodings.h(713) : error C2065: 'pop' : undeclared identifier
\rapidjson\stream.h(22) : error C2501: '__pragma' : missing storage-class or type specifiers
\rapidjson\stream.h(22) : error C2086: '__pragma' : redefinition
\rapidjson\stream.h(22) : error C2143: syntax error : missing ';' before 'namespace'
\rapidjson\stream.h(131) : error C2989: 'StreamTraits<struct rapidjson::GenericStringStream<Stream> >' : template class has already been defined as a non-template class
\rapidjson\stream.h(131) : error C2988: unrecognizable template declaration/definition
\rapidjson\stream.h(134) : error C2065: 'UTF8' : undeclared identifier
\rapidjson\stream.h(134) : error C2059: syntax error : '>'
\rapidjson\stream.h(143) : error C2899: typename cannot be used outside a template declaration
\rapidjson\stream.h(144) : error C2143: syntax error : missing ';' before '{'
\rapidjson\stream.h(145) : error C2899: typename cannot be used outside a template declaration
\rapidjson\stream.h(145) : error C2653: 'Encoding' : is not a class or namespace name
\rapidjson\stream.h(147) : error C2065: 'dst_' : undeclared identifier
\rapidjson\stream.h(147) : error C2065: 'head_' : undeclared identifier
\rapidjson\stream.h(147) : error C2065: 'src' : undeclared identifier
\rapidjson\stream.h(147) : error C2143: syntax error : missing ',' before '{'
\rapidjson\stream.h(147) : error C2143: syntax error : missing ';' before '{'
\rapidjson\stream.h(150) : error C2143: syntax error : missing ';' before '{'
\rapidjson\stream.h(151) : error C2143: syntax error : missing ';' before '{'
\rapidjson\stream.h(152) : error C2143: syntax error : missing ';' before '{'
\rapidjson\stream.h(155) : error C2143: syntax error : missing ';' before '{'
\rapidjson\stream.h(155) : error C2143: syntax error : missing ',' before ')'
\rapidjson\stream.h(157) : error C2143: syntax error : missing ';' before '{'
\rapidjson\stream.h(158) : error C2143: syntax error : missing ';' before '{'
\rapidjson\stream.h(159) : error C2143: syntax error : missing ';' before '{'
\rapidjson\stream.h(161) : error C2143: syntax error : missing ';' before '{'
\rapidjson\stream.h(162) : error C2143: syntax error : missing ';' before '{'
\rapidjson\stream.h(167) : error C2143: syntax error : missing ';' before '}'
\rapidjson\stream.h(169) : error C2899: typename cannot be used outside a template declaration
\rapidjson\stream.h(170) : error C2065: 'GenericInsituStringStream' : undeclared identifier
\rapidjson\stream.h(170) : error C2065: 'Encoding' : undeclared identifier
\rapidjson\stream.h(170) : error C2974: 'StreamTraits' : invalid template argument for 'Stream', type expected
\rapidjson\stream.h(80) : see declaration of 'StreamTraits'
\rapidjson\stream.h(170) : error C2143: syntax error : missing ';' before '{'
\rapidjson\stream.h(171) : error C2143: syntax error : missing ';' before '{'
\rapidjson\stream.h(172) : error C2143: syntax error : missing ';' before '}'
\rapidjson\stream.h(177) : error C2143: syntax error : missing ';' before '}'
\rapidjson\memorystream.h(26) : error C2143: syntax error : missing ';' before '{'
\rapidjson\memorystream.h(40) : error C2143: syntax error : missing ';' before '{'
\rapidjson\memorystream.h(43) : error C2065: 'begin_' : undeclared identifier
\rapidjson\memorystream.h(43) : error C2065: 'end_' : undeclared identifier
\rapidjson\memorystream.h(43) : error C2065: 'size' : undeclared identifier
\rapidjson\memorystream.h(43) : error C2065: 'size_' : undeclared identifier
\rapidjson\memorystream.h(43) : error C2143: syntax error : missing ',' before '{'
\rapidjson\memorystream.h(43) : error C2143: syntax error : missing ';' before '{'
\rapidjson\memorystream.h(45) : error C2143: syntax error : missing ';' before '{'
\rapidjson\memorystream.h(46) : error C2143: syntax error : missing ';' before '{'
\rapidjson\memorystream.h(47) : error C2143: syntax error : missing ';' before '{'
\rapidjson\memorystream.h(49) : error C2143: syntax error : missing ';' before '{'
\rapidjson\memorystream.h(49) : error C2143: syntax error : missing ',' before ')'
\rapidjson\memorystream.h(50) : error C2143: syntax error : missing ';' before '{'
\rapidjson\memorystream.h(50) : error C2143: syntax error : missing ',' before ')'
\rapidjson\memorystream.h(51) : error C2143: syntax error : missing ';' before '{'
\rapidjson\memorystream.h(51) : error C2143: syntax error : missing ',' before ')'
\rapidjson\memorystream.h(52) : error C2143: syntax error : missing ';' before '{'
\rapidjson\memorystream.h(52) : error C2143: syntax error : missing ',' before ')'
\rapidjson\memorystream.h(55) : error C2143: syntax error : missing ';' before '{'
\rapidjson\memorystream.h(57) : error C2143: syntax error : missing ';' before '}'
\rapidjson\memorystream.h(63) : error C2143: syntax error : missing ';' before '}'
\rapidjson\memorystream.h(65) : error C2143: syntax error : missing ';' before '}'
\rapidjson\encodedstream.h(31) : error C2143: syntax error : missing ';' before '{'
\rapidjson\encodedstream.h(38) : error C2899: typename cannot be used outside a template declaration
\rapidjson\encodedstream.h(38) : error C2899: typename cannot be used outside a template declaration
\rapidjson\encodedstream.h(38) : error C2065: 'InputByteStream' : undeclared identifier
\rapidjson\encodedstream.h(39) : error C2059: syntax error : '<class-head>'
\rapidjson\encodedstream.h(39) : error C2143: syntax error : missing ';' before '{'
\rapidjson\encodedstream.h(40) : error C2899: typename cannot be used outside a template declaration
\rapidjson\encodedstream.h(40) : error C2653: 'InputByteStream' : is not a class or namespace name
\rapidjson\encodedstream.h(40) : error C2065: 'Ch' : undeclared identifier
\rapidjson\encodedstream.h(40) : error C2027: use of undefined type 'STATIC_ASSERTION_FAILURE<0>'
\rapidjson\encodedstream.h(42) : error C2899: typename cannot be used outside a template declaration
\rapidjson\encodedstream.h(42) : error C2653: 'Encoding' : is not a class or namespace name
\rapidjson\encodedstream.h(44) : error C2143: syntax error : missing ';' before '{'
\rapidjson\encodedstream.h(45) : error C2653: 'Encoding' : is not a class or namespace name
\rapidjson\encodedstream.h(46) : error C2143: syntax error : missing ';' before '}'
\rapidjson\encodedstream.h(48) : error C2143: syntax error : missing ';' before '{'
\rapidjson\encodedstream.h(48) : fatal error C1003: error count exceeds 100; stopping compilation
执行 cl.exe 时出错.

**Comment by miloyip** [comment]
没打算支持 Visual C++ 6.0。或许最好使用 C89 语言的库，兼容会好一些。
