### ISSUE TITLE
Typedef for Member in the same style as Value

### ISSUE THREAD

**Issue by SamDeakin** [Tencent/rapidjson#1121]
For simple use cases there should be a convenience class like `rapidjson::Member` for values of `rapidjson::GenericMember<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >` in the same way that there is a convenience class `rapidjson::Value` for the class `rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >`.

This change helps eliminate confusion in cases where two lines of code like:
`for (auto& member : jsonNode.GetObject())`
`for (auto& value : jsonNode.GetArray())`
would have entirely different types for `member` and `value`. It would be much better to be able to write these two lines as:
`for (rapidjson::Member& member : jsonNode.GetObject())`
`for (rapidjson::Value& value : jsonNode.GetArray())`

Instead, currently the first line has to be written as:
`for (rapidjson::GenericMember<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>>& member : jsonNode.GetObject())`
In simple cases this is very bad for readability and hurts the usability of features like this.

**Comment by miloyip** [comment]
How about the existing `rapidjson::Value::Member`?

**Comment by miloyip** [comment]
I think my above reply should have fixed the issue. So I close this now.
