### ISSUE TITLE
Use with sockets

### ISSUE THREAD

**Issue by goodandrewsoft** [Tencent/rapidjson#1123]
How use use rapidjson with sockets if received message (jsonstring) less then recieving buffer?

**Comment by pah** [comment]
I'm not sure, if I understand the question correctly.

You mean the message is _shorter_ than the receiving buffer?  In that case, you can stop parsing parsing after the JSON message is complete by passing the flag `kParseStopWhenDoneFlag`.

**Comment by goodandrewsoft** [comment]
Sorry i mean _longer_.
For example, if i receive message from socket;

> recv(clientSocket, buf, BUF_SIZE, 0);

But buffer have uncompleted `jsonstring` and remaining `jsonstring` will be in next `recv` command.
What algoritme i can use?
Maybe [Custom Stream](http://rapidjson.org/md_doc_stream.html#CustomStream) with [Reader](http://rapidjson.org/md_doc_sax.html#Reader) ?

How properly build custom stream based on sockets (recv command )? 
Can there are examples?

**Comment by pah** [comment]
Yes, a custom stream would then be the right approach.  I don't know, if there are any examples out there for wrapping around `recv`, but for an input stream you just need to provide the three functions (fully untested):
```cpp
struct SocketStream
{
    typedef char Ch; //!< Character type of the stream.

    //! Read the current character from stream without moving the read cursor.
    Ch Peek() const {
        Ch c = 0;
        ssize_t ret = recv(sockfd_, &c, 1, MSG_PEEK);
        if( ret <= 0 ) return '\0'; // error or EOF
        return c;
    }

    //! Read the current character from stream and moving the read cursor to next character.
    Ch Take() {
        Ch c;
        ssize_t ret = recv(sockfd_, &c, 1, 0);
        if( ret <= 0 ) return '\0'; // error or EOF
        ++pos_;
        return c;
    }

    //! Get the current read cursor.
    //! \return Number of characters read from start.
    size_t Tell() { return pos_; }

private:
    int sockfd_;
    size_t pos_;
};
```
Of course, you need to add 
 * a constructor e.g. to open the socket
 * proper error handling
 * and maybe local buffering of pending characters for efficiency.

**Comment by goodandrewsoft** [comment]
I'm very grateful for the help.
