### ISSUE TITLE
像这样斜杠或反斜杠，特殊字符的怎么处理？ Invalid escape character in string

### ISSUE THREAD

**Issue by eGirlAsm** [Tencent/rapidjson#1125]
Invalid escape character in string
{"Time":"1830","KeyTime":"1833","Name":"","Phone":"","Desc":"","Bigo":""},

{"Time":"1830","KeyTime":"1834","Name":"","Phone":"","Desc":"","Bigo":""},

{"Time":"1830","KeyTime":"1835","Name":"테스트/#$","Phone":"","Desc":"신환","Bigo":";/$\gfgfg"},

{"Time":"1830","KeyTime":"1836","Name":"","Phone":"","Desc":"","Bigo":""},

{"Time":"1830","KeyTime":"1837","Name":"","Phone":"","Desc":"","Bigo":""},

{"Time":"1830","KeyTime":"1838","Name":"","Phone":"","Desc":"","Bigo":""},

{"Time":"1830","KeyTime":"1839","Name":"","Phone":"","Desc":"","Bigo":""},

我看了其他 issue,貌似提及了不支持某些特殊符号。
但是遇到了该如何解决?

**Comment by eGirlAsm** [comment]
replace(response.begin(), response.end(), '\\', '-');

resolved

**Comment by miloyip** [comment]
This is actually an invalid JSON. You should try to report to the source of JSON.

**Comment by eGirlAsm** [comment]
你的玩笑一点都不好笑。that's not funny. i am seriously. 
: >
