### ISSUE TITLE
Best way to serialize generic type

### ISSUE THREAD

**Issue by chenziliang** [Tencent/rapidjson#1126]
Hi May i ask what is the best way to serialize a generic type by using RapidJson ?
For example, what is the best way to serialize the following data structure ?

```
template <typename T>
struct Event {
    int64_t timestamp;
    string description;
    T value;
};
```

So far I am thinking of providing a "serialize" template function to do that and enforce some constraints to "T" which shall have "serialize" method if T is not builtin types. Any better idea / way ?

```
template <typename T>
struct Event {
    int64_t timestamp;
    string description;
    T value;

    template <typename Writer>
    Writer& serialize(Writer& writer) const {
        writer.String("timestamp");
        writer.Int64(timestamp);

        writer.String("value");
        ::serialize(value, writer);
    }
};

template<typename T, typename Writer>
Writer& serialize(T value, Writer& writer) {
    value.serialize(writer);
}

// for builtin types
template<typename Writer>
Writer& serialize(int64_t value, Writer& writer) {
    writer.Int64(value)
}

template<typename Writer>
Writer& serialize(const String& value, Writer& writer) {
    writer.String(value)
}
...

```

**Comment by miloyip** [comment]
I think your solution which uses template specialization should be fine. It is something like `std::ostream::operator<<()`.
I just have two comments:

1. It may be better to swap the order of arguments.
2. Using const reference argument, i.e. `Writer& serialize(Writer&, const T&)`, should be better.

**Comment by chenziliang** [comment]
Thanks @miloyip for the good suggestion.
2 additional questions:
1. It appears to me, it is tricky to handle C array like template params like T[]. Say what if client passing an int array or a object array ?
2. Is there an example of doing deserialize ? Using Document can achieve what I would like to do but I would like do inline deserialize to avoid doing a copy from Document to initialize my object.

**Comment by miloyip** [comment]
1. There is no silver bullet for this. For static sized array, such as `T[3]`, it can be detected by template. But for unknown size, you must give the size of array explicitly.
2. Currently I have not written any deserialize example (but I have done in some internal projects using RapidJSON). Deserializing is more difficult than serialization. Using DOM is easier to handle for general structures.

**Comment by chenziliang** [comment]
1. When considering array of array, it appears complex.
2. Looking forward to some example of doing the deserialization recursively for an object inline :)

**Comment by miloyip** [comment]
Please check if #1138 is useful for you. 
Comments are welcome.

**Comment by chenziliang** [comment]
Thanks @miloyip. Helps a lot
