### ISSUE TITLE
Parsing Multiple root element present in JSON

### ISSUE THREAD

**Issue by puagg281** [Tencent/rapidjson#1127]
Hi Everyone, 

Is there any way to parse multiple root elements present in single json file. I am stuck here .

**Comment by miloyip** [comment]
http://rapidjson.org/md_doc_dom.html#Parsing

> `kParseStopWhenDoneFlag`: After parsing a complete JSON root from stream, stop further processing the rest of stream. When this flag is used, parser will not generate kParseErrorDocumentRootNotSingular error. Using this flag for parsing multiple JSONs in the same stream.

**Comment by puagg281** [comment]
Thank you !! It worked
