### ISSUE TITLE
Question: parse "null", HasMember("as") crash

### ISSUE THREAD

**Issue by xiaomingbao008** [Tencent/rapidjson#1128]
Hi,

I met a issue that with following code:

Document d;
ParseResult ok = d.Parse("null");
if (ok) {
   if (d.HasMember("xx"))   <=========== core dump at this line
   {
       /////// xxxxxxx
   }
}

Also happens with "   null"   " null <enter>".

Is this behaviour correct?

-Xiaoming

**Comment by miloyip** [comment]
Yes.
`d.IsObject() == false` so that you should not call `d.HasMember()`.

**Comment by xiaomingbao008** [comment]
Thank you. 

Yes, I used IsObject() to check if it is valid json, which can resolve my biz problem.

The question here is d.Parse("null") results in core dump when calling d.HasMember("xx")
But d.Parse("aaa") doesn't results in core dump when calling d.HasMember("xx").

-Xiaoming

**Comment by pah** [comment]
`null` is valid JSON as well.  `aaa` is not valid JSON, so your `if(ok)` check fails and `HasMember` is not run.

**Comment by xiaomingbao008** [comment]
@pah, @miloyip,

Thank you. That is clear now.

-Xiaoming
