### ISSUE TITLE
string can't multiline

### ISSUE THREAD

**Issue by fkeujjpdc** [Tencent/rapidjson#1132]
{
    "comment":"line1
                 line2",
     "number",1
}
rapidjson can't parse this string,some times my string have mush charater 
i wan't split the string multiline

**Comment by pah** [comment]
Control characters like line feeds or carriage returns must be escaped inside JSON strings, see [RFC 7159](https://tools.ietf.org/html/rfc7159#section-7).  So your example/use case is not valid JSON and therefore rejected by RapidJSON.

Allowing such control characters in the input couid become another "relaxed syntax" flag, see #36.
