### ISSUE TITLE
kParseNumbersAsStringsFlag for single value?

### ISSUE THREAD

**Issue by danielpolski** [Tencent/rapidjson#1133]
Background:
I receive data in the style {"x":123, "d":123.000} where most of the values are integers & strings, but a single value is a double.
I don't receive any more information about the double except the value it contains, and the number of decimals it contains is important to keep.

Question:
Is there some way to parse a single double value as string? What I'm looking for is to get the "d" number in the above description as a string "123.000", but the "x" as the integer 123.

Partial solution:
I've found the kParseNumbersAsStringsFlag which makes it possible to retrieve "d" as the string "123.000", but that flag also makes all the other values returned as strings. (There are many many more values which are processed as integers, so it feels wasteful to receive them all as strings and then convert them back to numbers instead of getting the single double value as a string directly)

**Comment by miloyip** [comment]
I think you may refer to [filterkeydom.cpp](https://github.com/Tencent/rapidjson/blob/master/example/filterkeydom/filterkeydom.cpp), which filters the SAX events via parsing.
So you may use `kParseNumbersAsStringsFlag` but for some keys converts their values to integer.

However, you may just handle these things after parsing as well.
