### ISSUE TITLE
error: #error RAPIDJSON_48BITPOINTER_OPTIMIZATION can  only be set to 1 when RAPIDJSON_64BIT=1".

### ISSUE THREAD

**Issue by puagg281** [Tencent/rapidjson#1134]
Hi Miliyo, 

I am facing the problem while integrating the rapidjson library in my  c++ application. I am getting the " error: #error RAPIDJSON_48BITPOINTER_OPTIMIZATION can  only be set to 1 when RAPIDJSON_64BIT=1".

When i look into the rapidjson.h file and found that this error is thrown when "RAPIDJSON_48BITPOINTER_OPTIMIZATION = 1 and RAPIDJSON_64BIT != 1."

RAPIDJSON_64BIT macro is defined when the  "defined(__LP64__) || (defined(__x86_64__) && defined(__ILP32__)) || defined(_WIN64) || defined(__EMSCRIPTEN__)" condition gets met.

My current application undefines the __LP64__ macro in the make file. I can not make any change at this point of time because it supports backword compatibility and other stuff.

What are the impacts of removing the "RAPIDJSON_48BITPOINTER_OPTIMIZATION = 1 and RAPIDJSON_64BIT != 1 condition or Can you please suggest me the alternate way of doing it.

I am using x86_64 x86_64 x86_64 GNU/Linux, RHEL 7.3, GCC Compiler= gcc (GCC) 4.8.5 20150623

**Comment by Bu11etmagnet** [comment]
Do you also undefine `__x86_64__` ? If not, you should define `__ILP32__` in your makefile, where you undefined `__LP64__`. Then `RAPIDJSON_64BIT` will be defined.

**Comment by Bu11etmagnet** [comment]
Note: It's probably a bad idea to mess with the compiler's predefined macros.

**Comment by miloyip** [comment]
Defining `RAPIDJSON_48BITPOINTER_OPTIMIZATION=0` just turn off a memory size optimization and makes each `Value` occupies 8 extra bytes.

You can make turn off this and run the unit tests to ensure it works on all of your configurations.

And other alternative is to define `RAPIDJSON_64BIT=1`, instead of detecting those predefined macros.

**Comment by puagg281** [comment]
Thank you Bu11etmagnet, miloyip for your quick responses!!  

> Just to confirm that RapidJson works well with  x86_64 GNU/Linux, RHEL 7.3, GCC Compiler= gcc (GCC) 4.8.5 20150623 and C++98. Is it OK to use these stated version or there are any specific version requirement by RapidJson.
