### ISSUE TITLE
Unicode characters in Json

### ISSUE THREAD

**Issue by zoncpp** [Tencent/rapidjson#1143]
Hi,
I Have some Unicode strings in our json strings. And my VC Project setting set to "Use Unicode Character set" .
```
	const char* json = "{\"name\":\"زهره\",\"stars\":10}";
	Document d;
	d.Parse(json);

	Value& sName = d["name"];
	std::wstring ss = sName.GetString();
```
Now, How do I solve my problem. which files of "rapidjson" should be change and how do it?

**Comment by miloyip** [comment]
In C++11, you can use `u8` [string literal](http://en.cppreference.com/w/cpp/language/string_literal) prefix.
But in practice, most JSON should come from file or network streams, not directly stored in the C++ source code. In such cases, you only need to make sure the file is stored in UTF-8 or other UTF encodings.
