### ISSUE TITLE
Dealing with possible errors when using streams

### ISSUE THREAD

**Issue by lelit** [Tencent/rapidjson#1149]
I wrote [wrappers](https://github.com/lelit/python-rapidjson/blob/issue80/rapidjson.cpp#L205) around a Python _file-like_ object implementing the `Stream` concept, but I failed to understand if/how I should deal with possible errors coming from underlying `io` objects.

In `filewritestream.h` there is a comment saying _"failure deliberately ignored at this time"_, and I wonder if that is an interim measure or what.

Thank you for any hint!

**Comment by miloyip** [comment]
Sorry for late reply. But it seem have been solved.
