### ISSUE TITLE
Question: Pass Value(node) as parameter

### ISSUE THREAD

**Issue by gyrodrill** [Tencent/rapidjson#1150]
Can i pass a node of document to a function?

```
#include "rapidjson/document.h"
using namespace rapidjson;
int DoSomething(Value& v) {
    auto variab= v["abc"];
    // do something and return value
}
```

It can't be compiled for following reason:
"rapidjson::GenericValue<Encoding, Allocator>::GenericValue(const rapidjson::GenericValue<Encoding, Allocator> &rhs) [with Encoding=rapidjson::UTF8<char>, Allocator=rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>]" (declared at line 584 of "rapidjson\document.h") is inaccessible

The declaration at line 584:
```
private:
    //! Copy constructor is not permitted.
    GenericValue(const GenericValue& rhs);
```

**Comment by h46incon** [comment]
Pass a `rapidjson::Value` by reference is OK, but pass by value is prohibit unless use `std::move( )` because the copy constructor is prohibit. The compile error is cause by the expression `auto variab= v["abc"]` because it will call the copy constructor. Try `auto & var = v["abc"]`.

**Comment by gyrodrill** [comment]
Thanks for replying.
 `auto & var = v["abc"];` does works. I thought `auto` could be contains `&`.
