### ISSUE TITLE
CMake policy CMP0048 warning

### ISSUE THREAD

**Issue by yachoor** [Tencent/rapidjson#1154]
When building as subproject of project using CMake 3.9.6 I get a warning:

> CMake Warning (dev) at build/rapidjson-src/CMakeLists.txt:12 (PROJECT):
> Policy CMP0048 is not set: project() command manages VERSION variables.
> Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
> command to set the policy and suppress this warning.
>
> The following variable(s) would be set to empty:
>
>    PROJECT_VERSION
>    PROJECT_VERSION_MAJOR
>    PROJECT_VERSION_MINOR
>    PROJECT_VERSION_PATCH
>
> This warning is for project developers.  Use -Wno-dev to suppress it.

This project does not seem to use these variables, so explicitly setting policy CMP0048 (before `project()`) 
 either way would silence this warning:
```CMake
if (POLICY CMP0048)
  cmake_policy(SET CMP0048 NEW)
endif (POLICY CMP0048)
```

**Comment by miloyip** [comment]
Should we set those variables?

**Comment by yachoor** [comment]
This project uses it's own version variables:
```CMake
PROJECT(RapidJSON CXX)

set(LIB_MAJOR_VERSION "1")
set(LIB_MINOR_VERSION "1")
set(LIB_PATCH_VERSION "0")
set(LIB_VERSION_STRING "${LIB_MAJOR_VERSION}.${LIB_MINOR_VERSION}.${LIB_PATCH_VERSION}")
```
So setting the policy to `OLD` will silence the warning and not create any new empty variables:
```CMake
if (POLICY CMP0048)
  cmake_policy(SET CMP0048 OLD)
endif (POLICY CMP0048)

PROJECT(RapidJSON CXX)
...
```
For CMake 3.0 and higher you could take advantage of `project` command:
```CMake
PROJECT(RapidJSON VERSION 1.1.0 LANGUAGES CXX)
```
This would set `PROJECT_VERSION*` and `RapidJSON_VERSION*` variables instead of `LIB_*_VERSION`
and would require changing `CMAKE_MINIMUM_REQUIRED` version to at least 3.0, which is probably undesirable.

You could support both old and new CMake and use `PROJECT_VERSION*` everywhere instead of `LIB_*_VERSION` with something like:
```CMake
set(LIB_MAJOR_VERSION "1")
set(LIB_MINOR_VERSION "1")
set(LIB_PATCH_VERSION "0")
set(LIB_VERSION_STRING "${LIB_MAJOR_VERSION}.${LIB_MINOR_VERSION}.${LIB_PATCH_VERSION}")

if (CMAKE_VERSION VERSION_LESS 3.0)
  PROJECT(RapidJSON CXX)
  set(PROJECT_VERSION_MAJOR "${LIB_MAJOR_VERSION}")
  set(PROJECT_VERSION_MINOR "${LIB_MINOR_VERSION}")
  set(PROJECT_VERSION_PATCH"${LIB_PATCH_VERSION}")
  set(PROJECT_VERSION "${LIB_VERSION_STRING}")
else()
  cmake_policy(SET CMP0048 NEW)
  PROJECT(RapidJSON VERSION "${LIB_VERSION_STRING}" LANGUAGES CXX)
endif()
```
But I'm not sure if it's worth it.

You could also keep using `LIB_*_VERSION`, but also set `PROJECT_VERSION*` for CMake >= 3.0:
```CMake
set(LIB_MAJOR_VERSION "1")
set(LIB_MINOR_VERSION "1")
set(LIB_PATCH_VERSION "0")
set(LIB_VERSION_STRING "${LIB_MAJOR_VERSION}.${LIB_MINOR_VERSION}.${LIB_PATCH_VERSION}")

if (CMAKE_VERSION VERSION_LESS 3.0)
  PROJECT(RapidJSON CXX)
else()
  cmake_policy(SET CMP0048 NEW)
  PROJECT(RapidJSON VERSION "${LIB_VERSION_STRING}" LANGUAGES CXX)
endif()
```
