### ISSUE TITLE
VS2008: warning C4003 - min/max problem

### ISSUE THREAD

**Issue by escherstair** [Tencent/rapidjson#1156]
The issue is exactly what is described [here](https://stackoverflow.com/questions/27442885/syntax-error-with-stdnumeric-limitsmax/27443191#27443191) and [here](https://github.com/nlohmann/json/issues/506).
It seems that if I compile with VS2008 and <Windows.h> is included before <document.h>, a conflict between min and max macros arises.
The issue happens at lines 1008, 1014, 1015, 1032 and 1033 of <document.h> and can be fixed adding parentheses around the calls to `std::numeric_limits<float>::max` and `std::numeric_limits<float>::min`
I mean that line 1008 should be changed from
`&& (d < static_cast<double>(std::numeric_limits<uint64_t>::max()))`
to
`&& (d < static_cast<double>((std::numeric_limits<uint64_t>::max)()))`
and so on....

Could you implement this fix, please?

**Comment by chwarr** [comment]
I'm pretty sure this has been fixed already in https://github.com/Tencent/rapidjson/commit/6e38649ec61e5f4f382c257a6b27698bb55eff61 (and for the tests in https://github.com/Tencent/rapidjson/commit/e4c0ecf86b7db94014cde331cd43b6443f993be7).

**Comment by escherstair** [comment]
I see that you're right.
I've been using latest stable release v1.1.0 and so the fix hasn't been included yet.
Do you know if a new stable release will be released soon?
Otherwise I'll download the head of master branch

**Comment by chwarr** [comment]
I can't give a definitive answer about when the next release will come out: I just contributed the min/max patches. There are some issues open about tagging a release:

* https://github.com/Tencent/rapidjson/issues/1006
* https://github.com/Tencent/rapidjson/issues/1130

**Comment by sonal71** [comment]
Found the same issue in reader.h line 1704
if (d > std::numeric_limits<double>::max())

The solution in this thread fixed the issue.

Thank you!

**Comment by chwarr** [comment]
It looks like a recent commit, 2ea43433e274ec284f7b7e556faa58a99497ca89, added some more uses of `std::numeric_limits::max()`.  I've created PR #1302 to address these uses as well.
