### ISSUE TITLE
Redefinition error when switching to std::regex

### ISSUE THREAD

**Issue by xiaoPierre** [Tencent/rapidjson#1158]
Hello, 

I got a problem when trying to switch from rapidjson internal regex to c++11 regex. In the documentation, I found : 
> For C++11 compiler, it is also possible to use the std::regex by defining RAPIDJSON_SCHEMA_USE_INTERNALREGEX=0 and RAPIDJSON_SCHEMA_USE_STDREGEX=1. 

Then I defined these two macros but I got redefinition error : 
> rapidjson/schema.h:31:0: error: "RAPIDJSON_SCHEMA_USE_STDREGEX" redefined [-Werror]

I investigated in *schema.h* then I found this part of code which is the cause : 

```c++
#if !RAPIDJSON_SCHEMA_USE_INTERNALREGEX && !defined(RAPIDJSON_SCHEMA_USE_STDREGEX) && (__cplusplus >=201103L || (defined(_MSC_VER) && _MSC_VER >= 1800))
#define RAPIDJSON_SCHEMA_USE_STDREGEX 1
#else
#define RAPIDJSON_SCHEMA_USE_STDREGEX 0
#endif
```

When defining RAPIDJSON_SCHEMA_USE_STDREGEX, it will cause redefinition error in the else clause. 

I think this code and / or the documentation should be changed. 

Regards, 
Pierre

**Comment by xiaoPierre** [comment]
Still cannot use std regex 
possible fix : https://github.com/Tencent/rapidjson/pull/1161

**Comment by ivysotskyi** [comment]
having the same issue. No way to switch to std regexp.

the regex I need to check:

```
"patternProperties": {
    "^(?!sys\\.).*$"
```

the values:

` "some_variable_name" `- match
` "sys.heart_side"` - no match
