### ISSUE TITLE
Compile error because of -Werror=effc++ is on. 

### ISSUE THREAD

**Issue by blackball** [Tencent/rapidjson#1170]
Some of the errors log are pasted below 

`/home/hui/rvbust/source/rapidjson/example/archiver/archivertest.cpp:8:8: error: ‘Student::name’ should be initialized in the member initialization list [-Werror=effc++]
 struct Student {
        ^
/home/hui/rvbust/source/rapidjson/example/archiver/archivertest.cpp:8:8: error: ‘Student::age’ should be initialized in the member initialization list [-Werror=effc++]
/home/hui/rvbust/source/rapidjson/example/archiver/archivertest.cpp:8:8: error: ‘Student::height’ should be initialized in the member initialization list [-Werror=effc++]
`
I am on Ubuntu 16.04, gcc version is 5.4.0. Turn off effc++ option will fix the issue. But wonder why this is happening.

**Comment by miloyip** [comment]
`Student` does not have constructor. I think it should have no problem.
Cannot reproduce it [here](https://godbolt.org/g/aYo8dN).

**Comment by justinjereza** [comment]
I'm getting the same error here on Debian 9 with gcc 6.3.0-18. The error occurs when a variable of type Student is declared without initialization. I was able to reproduce [here](https://godbolt.org/g/MvN9t6).

**Comment by blackball** [comment]
@miloyip But if you use it like 
`Student s; 
`
It will give you error then. Like @justinjereza demonstrated.
