### ISSUE TITLE
请教一个使用上的问题？

### ISSUE THREAD

**Issue by shenzhigang** [Tencent/rapidjson#1175]
如下图，有个字段我使用的是rapidjson::Value类型（目的是反序列化时这个字段接受任何数据），但是，序列化的时候，在StringBuffer getstring的时候，就会出现异常。麻烦看一下下面的截图，帮我看看哪里使用有问题？

![image](https://user-images.githubusercontent.com/8005935/35964857-f4d2d19a-0cf3-11e8-8ef8-d597903896b0.png)

本意是这样的，希望bb这个对象类型的，不继续往里面反序列化，用一个类型接收，最后能被序列化即可
因为我反序列化出来后，不会动bb，只会修改一下aa，然后重新序列化

**Comment by miloyip** [comment]
你要存储 `Document doc`，因为 `Value bb` 使用了 `doc` 的分配器来分配，现在 `doc` 离开函数就被释放了。

**Comment by shenzhigang** [comment]
解决了我的问题，非常感谢

**Comment by shenzhigang** [comment]
@miloyip  不好意思，如何把value类型转换成document呢（在不清楚value内部结构，甚至不知道value是对象还是数组的情况下）

**Comment by shenzhigang** [comment]
补充上面的描述：我把bb改成document类型，然后24行改成simple.bb.CopyFrom(doc["bb"],allocator)。但是这样反序列化出来的bb里面还是空的。（不好意思，春节期间老家无网络手机敲的回复没有排版，请谅解😰）

**Comment by shenzhigang** [comment]
解决了，使用bb自己的allocator就可以了😁
