### ISSUE TITLE
I can not get the name of GenericObject.

### ISSUE THREAD

**Issue by damianpuci** [Tencent/rapidjson#1194]
```
"aaa": {
        "xxx": "ttt",
        "yyy": {
            "name": "asdf",
            "url": "www.github.com"
        },
        "zzz": {
            "name": "fghj",
            "id": "yuio",
        }
    }

```
Hello,
I get all of DOM tree nodes(recursive) and check if each node is an object, an array or a Value. My question is: if Value is an Object how can I get for examle "aaa" and "yyy" names?
Thank you

**Comment by miloyip** [comment]
http://rapidjson.org/md_doc_tutorial.html#QueryObject

**Comment by damianpuci** [comment]
Ok, it can be closed. I did not recognized that "aaa" is a first member in another object and it can be get by iterator.
Thank you.
