### ISSUE TITLE
Test failure: SchemaValidator.TestSuite with additionalItems.json

### ISSUE THREAD

**Issue by kachanovskiy** [Tencent/rapidjson#1198]
Win10, VS2010 x64, rapidjson master.

unit tests fail at SchemaValidator.TestSuite with additionalItems.json, at

Ch* CopyFromRaw(const GenericPointer& rhs, size_t extraToken = 0, size_t extraNameBufferSize = 0)

around lines

size_t nameBufferSize = rhs.tokenCount_; // null terminators for tokens
        for (Token *t = rhs.tokens_; t != rhs.tokens_ + rhs.tokenCount_; ++t)
            nameBufferSize += t->length;

local variables:
![image](https://user-images.githubusercontent.com/12648768/37208174-a25a9164-23a0-11e8-97b3-788b0195f8f4.png)

rhs.tokens_ seems to be uninitialized, hence subsequent Malloc call fails causing SEH exception.

**Comment by kachanovskiy** [comment]
just had a bit deeper look. no idea if behavior I observe is correct, but here what happens in GenericSchemaValidator::AddErrorLocation once it comes to the failing test case:
1) dives into GetInvalidDocumentPointer

2) documentStack is not empty, so it constructs PointerType(documentStack_.template Bottom<Ch>(), documentStack_.GetSize() / sizeof(Ch)) by first by calling constructor with source="/3" and length=2),
at this point we have temp object at 0x00000000004aa660 with:
tokens 0x0000000000856268
name 0x0000000000856278
length 1
index 3

3) then it calls copy constructor which calls copy assignment operator, which copies tokens at
```c++
            if (rhs.nameBuffer_)
                CopyFromRaw(rhs); // Normally parsed tokens.
```
after copy ctor at 0x00000000004aa768 (called from 0x00000000004aa660):
tokens 0x0000000000856280
length 1
index 3

4) then it calls destructor for temp object:
dtor of 0x00000000004aa660

5) and then after return from GetInvalidDocumentPointer instancePointer is 0x0000000000856280 with:
name = 0xfeeefeeefeeefeee
length 4277075694
index 4277075694


a quick fix that have worked for me is to replace
```c++
return documentStack_.Empty() ? PointerType() : PointerType(documentStack_.template Bottom<Ch>(), documentStack_.GetSize() / sizeof(Ch));
```

with 

```c++
if (documentStack_.Empty())
{
    return PointerType();
}
else
{
    return PointerType(documentStack_.template Bottom<Ch>(), documentStack_.GetSize() / sizeof(Ch));
}
```

in GenericSchemaValidator::GetInvalidDocumentPointer() (in incluide/rapidjson/schema.h around line 1862)

**Comment by kachanovskiy** [comment]
checked once again - yes, the fix works for me, all tests run. Want a pull request?

**Comment by miloyip** [comment]
Yes, please.

**Comment by kachanovskiy** [comment]
Here you go: #1199. I also tend to think that Appveyor Windows builds will be repaired with this PR...
