### ISSUE TITLE
How to build a GenericValue in a template class

### ISSUE THREAD

**Issue by escherstair** [Tencent/rapidjson#1214]
I have a template class defined as
```
template <class T> class MyTemplateClass {
   T	value;
   ...
};
```
In one of the member functions I need to create a rapidjson `GenericValue` from member `value` (which is of type `T`).
If `T` is one of the primitive types (`bool`, `int`, `double`, ...) one of the available constructors for `GenericValue` can be called directly:
`rapidjson::Value v(value);`
If `T` is a custom class, the costructor which takes an `Object` (created based on member `value`) as an input should be used.

Is there a way to get this behavior in `MyTemplateClass` ?

**Comment by miloyip** [comment]
This seems not an issue of RapidJSON. But I think you may add template specialization to `MyTemplateClass` for handling special cases depending on `T`. E.g.

~~~cpp
template <class T> class MyTemplateClass {
    T value;
    rapidjson::Value CreateValue() const {
        rapidjson::Value v(value);
        return v;
    }
}

template<> class MyTemplateClass<Object> {
    rapidjson::Value CreateValue() const {
        rapidjson::Value v(kObjectType);
        v.AddMember(...);
        return v;
    }
}
~~~

**Comment by escherstair** [comment]
This could be a good approach.
Thanks.
