### ISSUE TITLE
(question) DOM: Compute size

### ISSUE THREAD

**Issue by ppanhoto78** [Tencent/rapidjson#1221]
Is it possible to precompute the size of a (not yet) encoded message with DOM?

**Comment by miloyip** [comment]
Why do you mean by "size"? Memory occupied for the DOM, or the length of JSON?

**Comment by ppanhoto78** [comment]
Length of the JSON.

**Comment by miloyip** [comment]
Then you need to use `Writer` anyway. But you can write a custom output stream class which ignores all output operations.

**Comment by ppanhoto78** [comment]
thank you.
