### ISSUE TITLE
Is it possible add preformatted JSON string without escaping?

### ISSUE THREAD

**Issue by ppanhoto78** [Tencent/rapidjson#1230]
I'm creating a document with DOM and, to compose this document, I need to add some data that's  already been formatted as JSON. I was wondering if I could add those as nodes of the first without needing to parse them and reencode later.

Example (the actual portion will come from network, pseudocode below creates one string facilitate explanation):

```
auto properties = R"json({ "speed_limit": 60, "has_radars": false  })json";
rapidjson::Document root;
root["name"] = "Conversation St.";
root["properties"] = properties; // would escape the properties variable to store it as a single string.
```

**Comment by miloyip** [comment]
This is not support via DOM but `Writer::RawValue()` can do so.

**Comment by ppanhoto78** [comment]
Oh, I see that now ... Thank you.
