### ISSUE TITLE
How to access a SchemaDocument content (as a regular JSON file)

### ISSUE THREAD

**Issue by bbouzan** [Tencent/rapidjson#1233]
I'm trying to use rapidjson for the support it provides to schema. In my case, I want to use the SchemaDocument parser to load a schema file with several remote references ($ref).

Besides using the the SchemaDocument to build a SchemaValidator and validate files, I need to access the content of the SchemaDocument just like any other JSON file (just like a Document instance) in order to extract information from it.

Is there a way to do it?

Thanks in advance!

**Comment by miloyip** [comment]
An `SchemaDocument` is constructed from `Document`. So you can still extract information from the original `Document`. I can't see what is the problem.

**Comment by bbouzan** [comment]
The issue is that the original Document will only have the data parsed from the loaded JSON, not from the remote schema references. This references are only solved when the SchemaDocument is built, correct?

What I'm trying to do is to interpret SchemaDocument as a Documet, which gives me errors. For example, I cannot do:

`SchemaDocument jsonSchema(jsonDoc);`
`rapidjson::Value& value = jsonSchema["field_from_a remote_referenced_schema"];`

I guess a work-around to achieve this behavior would be to store all Document instances created inside the calls to `MyRemoteSchemaDocumentProvider::GetRemoteDocument`, and then use such a list of Document to get the information I need.

Thanks!

**Comment by bbouzan** [comment]
This work-around mentioned on my previous reply worked.
