### ISSUE TITLE
How to correctly handle parse error

### ISSUE THREAD

**Issue by sburnwal** [Tencent/rapidjson#1248]
I want to know how to correctly handle parse error. In my example, once it encounters parse error, it is not continuing further after that. 

```
const char* json = "{\"project\":\"rapidjson\",\"stars\":10 ";   //invalid json
rapidjson::Document d;
d.Parse(json);
if (d.HasParseError()) {
  std::cout << "parse error \n";
}
std::cout << "Should continue here\n";

```
Code above is not printing the line 'Should continue here' and the program just exits saying 'parse error'. I want to continue with the next instructions even if there are parse errors.

```
parse error 
Assertion failed: (IsObject()), function FindMember, file ../../rapidjson/include/rapidjson/document.h, line 1251.
Abort trap: 6
```

**Comment by miloyip** [comment]
Parsing errors **DON'T** generate assertion failure.
There must be some APIs called afterwards that makes that assertion failure.
You may use a debugger to run your code step by step, or see the stack trace when assertion fails.

**Comment by sburnwal** [comment]
Sorry my bad, that indeed was the case, was trying to get String instead of Int. Thanks!
