### ISSUE TITLE
Parsing "0e100" in full precision mode causes UB

### ISSUE THREAD

**Issue by StilesCrisis** [Tencent/rapidjson#1249]
Attempting to parse a document containing "0e100" in full precision mode will call DiyFp::Normalize() where f == 0. 

This will cause an infinite loop/soft-lock on platforms that take the plain C implementation, and generate a random value on platforms that use a builtin; __builtin_clzll and _BitScanReverse64 are both implemented with the BSR opcode, which is documented as producing an undefined value.

**Comment by miloyip** [comment]
Sorry I was too busy these few days. Will take a look.
Will u also be possible to suggest fixes on these?

**Comment by StilesCrisis** [comment]
Diyfp is a black box to me. I don't have any suggestions.

**Comment by miloyip** [comment]
Fixed in #1290 and verified in #1250.
