### ISSUE TITLE
Adding multiple Json into another json 

### ISSUE THREAD

**Issue by Bishalsahoo** [Tencent/rapidjson#1286]
Hello , I was trying to add multiple json in an array of another json
target json:
[ ]
source json1:
{
      "id": "abc",
      "name": "john",
    }
source json 2:
{
      "id": "abc",
      "name": "john",
    }
output json:
{
	"list": [{
			"id": "abc",
			"name": "john"
		},
		{
			"id": "abc",
			"name": "john"
		}
	]
}

tried to follow https://github.com/Tencent/rapidjson/issues/490
but output is:
{
	"list": [
               {
			"id": "abc",
			"name": "john",
			"id": "abc",
			"name": "john"
		}
	]
}
My code:

        Document itemList;
        itemList.SetArray();
        
        for (SizeType i = 0; i < item.Size(); i++) {

            for (SizeType j = 0; j < item[i]["lines"].Size(); j++) {

                //Obtain Item by Id

                Value &itemByID= getItemById(item[i]["lines"][j], List);

                itemList.PushBack(itemByID, itemList.GetAllocator());

                StringBuffer string;
                Writer<StringBuffer> writer(string);
                itemList.Accept(writer);
                cout<<"Lists:"<<string.GetString()<<endl;
               }
        }

I tried this but I am getting error after one insertion:

[{
      "id": "abc",
      "name": "john",
    }]

 include/rapidjson/document.h:1253: rapidjson::GenericValue<Encoding, Allocator>::MemberIterator rapidjson::GenericValue<Encoding, Allocator>::FindMember(const rapidjson::GenericValue<Encoding, SourceAllocator>&) [with SourceAllocator = rapidjson::MemoryPoolAllocator<>; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; rapidjson::GenericValue<Encoding, Allocator>::MemberIterator = rapidjson::GenericMemberIterator<false, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >]: Assertion `IsObject()' failed.

Any help to resolve this will be greatly appreciated.

**Comment by Bishalsahoo** [comment]
@miloyip please can you give me a hint to solve this issue?

**Comment by miloyip** [comment]
The code is incomplete. I can just imagine the possibility that, you "moved" the source value into the destination, but then the source value is deallocated. A simple approach is to make a copy:

~~~cpp
Value clone(itemByID, itemList.GetAllocator());
itemList.PushBack(clone);
~~~

**Comment by Bishalsahoo** [comment]
Thank you so much .

**Comment by Bishalsahoo** [comment]
Document itemList;
        itemList.SetArray();

        for (SizeType i = 0; i < item.Size(); i++) {

            for (SizeType j = 0; j < item[i]["lines"].Size(); j++) {

                //Obtain Item by Id

                Value &itemByID= getItemById(item[i]["lines"][j], priceList);
                Value clones(itemByID,itemList.GetAllocator());
                itemList.PushBack(clones,itemList.GetAllocator());
This code worked.
