### ISSUE TITLE
Do I need to write my own StackAllocator?

### ISSUE THREAD

**Issue by derekxgl** [Tencent/rapidjson#1288]
Hi,

I need to parse lots of small json strings which are received over some messaging middleware. Each message is only about 2KB, so I think it makes sense to have StackAllocator to make the parsing and access faster, but the default CrtAllocator does not seem to use memory on stack. Does it mean Rapidjson has no "real" stack allocator? 

When will the Allocator (MemoryPoolAllocator by default) get used? When StackAllocator (if configured) fails to allocate memory? I am sorry if my questions are bit silly. I haven't got time to read rapidjson source code. 

Given I need to parse json string every time a message str is received over middleware, for the parsing thread, can I reuse same rapidjson::Document? Presume it's bit faster than constructing a Document for each message? Do I need to call 'clear' or something like that before call Document::Parse over and over again?

Thanks,
Derek

**Comment by miloyip** [comment]
Check user buffer in http://rapidjson.org/md_doc_dom.html#Techniques

**Comment by derekxgl** [comment]
thanks Milo.

**Comment by miloyip** [comment]
Have u verified the size by `MemoryPoolAllocator::Size()`?
By the way, this only reduces number of `malloc()` call, and it may not be a bottleneck in every cases, and thus may not improve performance. But generally this reduces the possibility of memory fragmentation.

**Comment by derekxgl** [comment]
Yes, I did check MemoryPoolAllocator::Size(). I'm using jemalloc, so probably the bottleneck is not on memory allocation.
