### ISSUE TITLE
no release since v1.1.0 on Aug 25, 2016 ?

### ISSUE THREAD

**Issue by derekxgl** [Tencent/rapidjson#1289]
no release since v1.1.0 on Aug 25, 2016 ?

**Comment by jgornowich** [comment]
+1

**Comment by prsolucoes** [comment]
+1

**Comment by miloyip** [comment]
I created a [v1.2 Beta](milestone) and put some issues/PR into that.
I hope we could make this happen.

**Comment by derekxgl** [comment]
thanks.

**Comment by Livius90** [comment]
Use nlohmann C++ json lib, it is much better in releasing and documentation. I gave up waiting for new rapidjson release, i am using this other from now.
https://github.com/nlohmann/json
