### ISSUE TITLE
Add AppVeyor Visual Studio 2017 support

### ISSUE THREAD

**Issue by miloyip** [Tencent/rapidjson#1294]
Recruit volunteer for contribution on this issue.

**Comment by gongminmin** [comment]
Current gtest in rapidjson couldn't be compiled by VS2017. We need to upgrade the gtest the a more recent one. It's mentioned in #1309 .

However, the commit in that PR doesn't fix the compiling warnings/errors. I have a fix for that. So I'll finish that one first.
