### ISSUE TITLE
comment identifier (/* ... */ or //) inside a string is treated as comment?

### ISSUE THREAD

**Issue by guwangfeng** [Tencent/rapidjson#1300]
I wrote a json file like below:

{       
 "FileList" : [
            "C:/files/*.zip.xml"
        ],
}

seems rapidjson treats /* inside "C:/files/*.zip.xml" as comment if kParseCommentsFlag is used (the result is the same if I changed /* to //). I think comment identifier inside a string shouldn't be treated as a comment. Does I understand it correctly?

**Comment by miloyip** [comment]
I cannot reproduce your problem. `/*` and `//` inside JSON string were not treated as comments:

~~~cpp
#include "rapidjson/document.h"
#include <iostream>

int main() {
    using namespace rapidjson;
    Document d;
    d.Parse<kParseCommentsFlag>("\"test/*.zip//comment\"");
    std::cout << d.GetString() << std::endl;
}
~~~

Output:
~~~
$ g++ -I ~/github/rapidjson/include a.cpp && ./a.out
test/*.zip//comment
~~~

**Comment by guwangfeng** [comment]
Thank you! The above code snippet is a simplified one, I'll check my original json file.

**Comment by guwangfeng** [comment]
Oh~~ finally I found that it's caused by some preprocessing code by myself, not rapidjson's issue. Sorry for bothering you.
