### ISSUE TITLE
SetFloat precision

### ISSUE THREAD

**Issue by noXur** [Tencent/rapidjson#1319]
Hey, there!

Today I noticed that my converted doubles are all off. I use `SetDouble()` to set proper `double` values and a common `Writer` for saving my JSON to file.

When I want to serialize `0.02` this way, I end up with `0,01999999999...` in my JSON file. After investigating the problem, I came across the `kParseFullPrecisionFlag` flag. Then, I defined `#define RAPIDJSON_PARSE_DEFAULT_FLAGS kParseFullPrecisionFlag` in `reader.h`, but I still get the same odd results.

Do I miss something? Any help would be much appreciated. Besides that, I love your library. Great work.

**Comment by miloyip** [comment]
`kParseFullPrecisionFlag` is only for parsing JSON.

I cannot reproduce the problem:

~~~cpp
#include <iostream>
#include "rapidjson/writer.h"
#include "rapidjson/document.h"

using namespace rapidjson;

int main() {
    Document d;
    d.SetDouble(0.2);
    StringBuffer sb;
    Writer<StringBuffer> writer(sb);
    d.Accept(writer);
    std::cout << sb.GetString() << std::endl;
}
~~~

~~~
$ g++ -I ~/github/rapidjson/include a.cpp && ./a.out
0.2
~~~

**Comment by noXur** [comment]
Thank you for the fast response. I figured out that the problem lies within the parsing of boost::program_options which I used together with RapidJSON.

Great work.

**Comment by noXur** [comment]
Okay, I figured out that the problem is definitely caused by RapidJSON when using single precision floats:

**Comment by noXur** [comment]
The same problem arises if I try to work around this with `SetDouble(static_cast<double>(0.02f))`.

Unfortunately, I'm forced to store my program values as `float` values for my companies' project.

**Comment by abolz** [comment]
The output from rapidjson is actually correct and there is no loss of precision.

The compiler first needs to convert the _decimal_ floating-point number `0.02` into a _binary_ floating-point number. There are only finitely many binary single precision floating-point numbers (`float`) and `0.02` is not one of them. The one closest to `0.02` is actually `0.0199999995529651641845703125 = 5368709 * 2^-28`.

(You can use the great [Decimal to Floating-Point Converter](https://www.exploringbinary.com/floating-point-converter/) by Rick Regan to convert decimal floating-point numbers to single- or double-precision binary floating-point numbers.)

The information that you typed `0.02f` is lost now.

Now rapidjson internally stores floating-point numbers as `double`s. All `float`s are exactly representable as `double`s, so there is no loss of precision here.

The information that the original number was a single-precision `float` is lost now.

When converting the binary `double` into a decimal floating-point number for output, rapidjson uses an algorithm which tries to produce the shortest decimal number, which is closest to the original number, and which rounds to the original number when read back in (using `strtod`). In this case, the algorithm produces `0.019999999552965165`. And the answer is _correct_: This decimal number converts back to the original `double` when using `strtod`.

If you use `SetFloat` to set a number, you can use `GetFloat` to get the original number back, i.e. you can safely store `float`s in a rapidjson document.

**Comment by noXur** [comment]
Thank you @abolz for your detailed explanation.

In my scenario, I send out the generated JSON via UDP to another application written in JavaScript using Node.js. So, I think we have to work around this over there, treating the received floats as 32bit numbers and not as 64bit.

Another option would be to send the numbers as string, I guess.

However, thank you for your time.
