### ISSUE TITLE
CursorStreamWrapper不能给出错误的正确位置

### ISSUE THREAD

**Issue by PinkGabriel** [Tencent/rapidjson#1330]
参考
https://github.com/Tencent/rapidjson/pull/1070
使用如下，从文件输入。
...
  FILE* fp = fopen(argv[2], "r");
  char readBuffer[65536];
  FileReadStream is(fp, readBuffer, sizeof(readBuffer));
  CursorStreamWrapper<FileReadStream> csw(is);
  Document rapid_json;
  if (rapid_json.ParseStream(is).HasParseError()) {
    fprintf(stderr, "\nError(offset %u, line %u, col %u): %s\n",
      (unsigned)rapid_json.GetErrorOffset(),
      csw.GetLine(), // get line number
      csw.GetColumn(), // get line column
      GetParseError_En(rapid_json.GetParseError()));
    return 0;
  }
给出的错误位置总是1行0列，文件内容导入StringStream然后作为输入也试过了不行，报的错误位置都是1行0列。
谢谢！

**Comment by PinkGabriel** [comment]
发现这个测试的json文件也会报错：
{
  "enable" : 1,
  "start" : 0,
  "skip" : 0,
  "total" : -1,
  "enable_params" : [
    "id" : 0,
    "num" : 0
  ]
}
Error(offset 100, line 1, col 0): Missing a comma or ']' after an array element.
是我的使用方法不对吗？请指教，谢谢~

**Comment by miloyip** [comment]
这个 JSON 的确是不合法的，数组里不会有冒号。
不过我试重现一下 cursor 的问题。

**Comment by miloyip** [comment]
Oh... 你应该用 `ParseStream(csw)` 吧？

**Comment by PinkGabriel** [comment]
啊我的错，对json不太熟悉，然后还用错变量了。。不好意思！现在ok了，感谢回复！
