### ISSUE TITLE
PrettyWriter<FileWriterStream> on simple scalar value does not work

### ISSUE THREAD

**Issue by lelit** [Tencent/rapidjson#1336]
Hi, I received a [bug report](https://github.com/python-rapidjson/python-rapidjson/issues/107) on python-rapidjson that I was able to easily replicate on RapidJSON itself. 

Apparently when using a `PrettyWriter<FileWriterStream>` with a single scalar value as input, nothing is emitted on output.

Consider:
```shell
$ cd example/pretty
$ make pretty
g++     pretty.cpp   -o pretty
$ echo '[10]' | ./pretty
[
    10
]
$ echo '10' | ./pretty
$
```

Thanks&bye, lele.

**Comment by miloyip** [comment]
Successfully reproduced. Thank you for your report.
