### ISSUE TITLE
rapidjson pointer core dump

### ISSUE THREAD

**Issue by emmettwu** [Tencent/rapidjson#1347]
rapidjson::Document json;
rapidjson::Pointer("/data/api~").Set(json, "3.9.0.0");
// rapidjson::Pointer("/data/api").Set(json, "3.9.0.0");
rapidjson::StringBuffer buffer;
rapidjson::Writer <rapidjson::StringBuffer> writer(buffer);
json.Accept(writer);

看到IsValid()如果pointer结尾是~会判断为ParseError，求教为啥这个pointer不合法。

**Comment by miloyip** [comment]
https://tools.ietf.org/html/rfc6901

~~~
Because the characters '~' (%x7E) and '/' (%x2F) have special
   meanings in JSON Pointer, '~' needs to be encoded as '~0' and '/'
   needs to be encoded as '~1' when these characters appear in a
   reference token.
~~~
