### ISSUE TITLE
How to insert a document node into another document not compiling

### ISSUE THREAD

**Issue by jcourtat** [Tencent/rapidjson#1363]
Hello, i wanted to insert a document into another, and get it in the FAQ.
But it's not compiling

g++ -std=c++11 -o test conftest.c++ 

conftest.c++: In function ‘void create_document()’:
conftest.c++:191:39: error: no matching function for call to ‘rapidjson::GenericDocument<rapidjson::UTF8<> >::GenericDocument(rapidjson::MemoryPoolAllocator<>&)’
 Document address(person.GetAllocator());
                                       ^
conftest.c++:191:39: note: candidates are:
In file included from conftest.c++:17:0:
/usr/include/rapidjson/document.h:2377:5: note: rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::GenericDocument(const rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>&) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = rapidjson::CrtAllocator]
     GenericDocument(const GenericDocument&);
     ^
/usr/include/rapidjson/document.h:2377:5: note:   no known conversion for argument 1 from ‘rapidjson::MemoryPoolAllocator<>’ to ‘const rapidjson::GenericDocument<rapidjson::UTF8<> >&’
/usr/include/rapidjson/document.h:2059:5: note: rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::GenericDocument(rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>&&) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = rapidjson::CrtAllocator]
     GenericDocument(GenericDocument&& rhs) RAPIDJSON_NOEXCEPT
     ^
/usr/include/rapidjson/document.h:2059:5: note:   no known conversion for argument 1 from ‘rapidjson::MemoryPoolAllocator<>’ to ‘rapidjson::GenericDocument<rapidjson::UTF8<> >&&’
/usr/include/rapidjson/document.h:2050:5: note: rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::GenericDocument(Allocator*, std::size_t, StackAllocator*) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = rapidjson::CrtAllocator; std::size_t = long unsigned int]
     GenericDocument(Allocator* allocator = 0, size_t stackCapacity = kDefaultStackCapacity, StackAllocator* stackAllocator = 0) : 
     ^
/usr/include/rapidjson/document.h:2050:5: note:   no known conversion for argument 1 from ‘rapidjson::MemoryPoolAllocator<>’ to ‘rapidjson::MemoryPoolAllocator<>*’
/usr/include/rapidjson/document.h:2037:14: note: rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::GenericDocument(rapidjson::Type, Allocator*, std::size_t, StackAllocator*) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = rapidjson::CrtAllocator; std::size_t = long unsigned int]
     explicit GenericDocument(Type type, Allocator* allocator = 0, size_t stackCapacity = kDefaultStackCapacity, StackAllocator* stackAllocator = 0) :
              ^
/usr/include/rapidjson/document.h:2037:14: note:   no known conversion for argument 1 from ‘rapidjson::MemoryPoolAllocator<>’ to ‘rapidjson::Type’

GetAllocator() returns a reference but the Document constructor awaits for a pointer !

regards

**Comment by miloyip** [comment]
Can you show your code?

**Comment by jcourtat** [comment]
```
int main ()
{
    Document person;
    Document address(person.GetAllocator());

    return 0;
}
```

**Comment by miloyip** [comment]
To clone a document, you may use constructor or `CopyFrom()`

**Comment by jcourtat** [comment]
As i mentionned in the title, i only tryed to follow the faq. The example code in the faq doesn't compile as is. What is the purpose of that code is out of scope.
