### ISSUE TITLE
document 可以 parse 非json字符串？

### ISSUE THREAD

**Issue by zhanMan** [Tencent/rapidjson#1374]
**document如何判断parse的是否为json字符串？**
如果字符串是一个纯数字，document可以parse成功？我查看document结构的时候看到parse的字符串变成document的length，但是data是null。
![image](https://user-images.githubusercontent.com/31401782/46645080-b0c4b280-cbb5-11e8-8e71-3a09434000e3.png)
如果字符串是一个非纯数字，document parse是失败的？**那么document如何判断parse的是否为json字符串？**
![image](https://user-images.githubusercontent.com/31401782/46645149-20d33880-cbb6-11e8-8246-658480bebcf4.png)

**Comment by miloyip** [comment]
https://tools.ietf.org/html/rfc8259#section-3

> A JSON value MUST be an object, array, number, or string, or one of
   the following three literal names:
>      false
>      null
>      true

**Comment by zhanMan** [comment]
thanks!
