### ISSUE TITLE
how to Document.Parse() error handlling?

### ISSUE THREAD

**Issue by csi013** [Tencent/rapidjson#1381]
Hello, i have a question about the Parse function.

I'am currently using this code.

if ( document.Parse<2>( str ).HasParseError() ) {
       /* error handling */
}

but, when value of 'str' is assigned to "1", the Parse function can't capture the ParseError

is it correct?

**Comment by miloyip** [comment]
It is correct because JSON text `1` means that the root of it is a number. If you expect it to be an object or array, use `document.IsObject()` or `document.IsArray()` respectively.

**Comment by csi013** [comment]
Thank you for comment! : )
