### ISSUE TITLE
Transform GenericArray and GenericObject to GenericValue

### ISSUE THREAD

**Issue by slsyy** [Tencent/rapidjson#1404]
I would like to resolve JSON Pointer on GenericObject or GenericArray. Unfortunately it seems like i can't get GenericValue for mentioned types, because ValueType is private and there is no getter. Did I omit something or maybe It's not possible?

**Comment by miloyip** [comment]
Yes, currently it does not provide API for this purpose.

**Comment by slsyy** [comment]
I can post PR.  Would an implicit conversion operator be ok?
```cpp
operator ValueType&() const  { return value_;}
```

**Comment by miloyip** [comment]
I cannot imagine any issue at the moment.
Can you try to add this and a unit test (for resolving JSON pointer) in a PR?
