### ISSUE TITLE
Rapidjson Crash when HasMember

### ISSUE THREAD

**Issue by maytrue** [Tencent/rapidjson#1435]
I first use Document::Parse std::string 

then call optGetInt to get value from key
```
int optGetInt(const std::string& key, int optValue)
    {
        if (!mParsed || !mDocument.HasMember(key.c_str())) {
            return optValue;
        }
        RAPIDJSON_NAMESPACE_PREFIX::Value& value = mDocument[key.c_str()];
        if (value.IsInt()) {
            return value.GetInt();
        } else if (value.IsString()) {
            std::string string = value.GetString();
            int value = momo::stoi(string);
            return value;
        } else {
            return optValue;
        }
    }
```

And got [crashed]
![screen shot 2018-12-28 at 4 28 08 pm](https://user-images.githubusercontent.com/1849557/50508870-a3d1a400-0abe-11e9-83aa-a4afd5a0a9a0.png)

**Comment by miloyip** [comment]
I can't notice any problem with the code.
Can you provide a simple example that can reproduce the issue?

**Comment by Bu11etmagnet** [comment]
Maybe document wasn't an object (perhaps an array?)

**Comment by maytrue** [comment]
I can not provide example, as the crash was collected from Fabric.

I first call parse a string  if it is valid json string or not.

![screen shot 2019-01-18 at 4 17 51 pm](https://user-images.githubusercontent.com/1849557/51374067-c9415300-1b3c-11e9-9b48-6395fdbf4ddf.png)

then i call optGetInt to get value from key

![screen shot 2019-01-18 at 4 20 04 pm](https://user-images.githubusercontent.com/1849557/51374120-fd1c7880-1b3c-11e9-8e04-5544bdda99b6.png)

**Comment by ManfredBartz** [comment]
I seem to have the same problem.
Once **HasMember()** has returned false, calling HasMember() or the destructor causes a core dump.
This reproduces the problem 100% of the time:
```bash
~/c$ cat jsonBug.cpp
```
```c++
//  jsonBug.cpp                                   -*- c++ -*-
//
//  g++ -Wall -o jsonBug jsonBug.cpp && ./jsonBug

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdbool.h>
#include <assert.h>

#include <rapidjson/document.h>
#include <rapidjson/stringbuffer.h>
#include <rapidjson/writer.h>

using namespace rapidjson;
using namespace std;

int main()
{
    StringBuffer sb;
    Writer<StringBuffer> writer(sb);

    writer.StartObject();
    writer.Key("Key1");
    writer.String("Val1");
    writer.EndObject();
    printf("JSON=\"%s\"\n\n", sb.GetString());

    Document jsonDoc;
    jsonDoc.Parse(sb.GetString());
    assert(jsonDoc.IsObject());
    assert(jsonDoc.HasMember("Key1"));
    printf("Key1: %s\n", jsonDoc["Key1"].GetString());

    bool hasK2 = jsonDoc.HasMember("Key2");
    assert(hasK2);

    bool hasK3 = jsonDoc.HasMember("Key3");
    assert(hasK3);

        return 0;
}
```

```bash
~/c$ g++ -Wall --std=c++14 -o jsonBug jsonBug.cpp && ./jsonBug
```
```ascii
Key1: Val1
jsonBug: jsonBug.cpp:36: int main(): Assertion `hasK2' failed.
Aborted (core dumped)
```

```bash
~/c$ g++ --version
```
```ascii
g++ (Ubuntu 5.3.1-14ubuntu2) 5.3.1 20160413
```
```bash
~/c$
```

**Comment by miloyip** [comment]
@ManfredBartz Your `assert(false)` generate abortions. Change to `assert(!hasK2);` should be fine.

**Comment by ManfredBartz** [comment]
embarrassing 8-|

**Comment by garfieldhahu** [comment]
@maytrue Have you found how to solve it?
