### ISSUE TITLE
rapidjson在Stack 析构的时候crash

### ISSUE THREAD

**Issue by beita1** [Tencent/rapidjson#1443]
# 问题
hi,我遇到一个偶发的rapidjson相关的crash，我没办法确定是我的代码问题还是rapidjson的问题，能否提供一些帮助。在调用堆栈中我发现是在rapidjson析构时crash了
![qq 20190130235145](https://user-images.githubusercontent.com/13329945/51993550-0832b980-24ea-11e9-916a-4bca838664a5.png)

# 一些信息
## 运行环境
- win7虚拟机

## 栈中局部变量
![i e c tgtl usm54e2ug m](https://user-images.githubusercontent.com/13329945/51993459-dfaabf80-24e9-11e9-885d-517322d8b537.png)
（file_name_ && file_path_ 读取字符串出错应该是中文的原因）

## ProcessInfoItem类中成员变量的类型
- process_id_ && parent_id_ 是unsigned long
- file_name_ && file_path_ 是 wstring
- timestamp_ 是ulong

## 做过的一些尝试
- 我不确定是不是我Addmember赋值问题导致的，有模拟过传入参数的值，一切正常并没有crash

**Comment by beita1** [comment]
发现stack_是null
![2](https://user-images.githubusercontent.com/13329945/51994008-e2f27b00-24ea-11e9-848f-e5541fd94b70.png)

**Comment by beita1** [comment]
我有个同事遇到过传入参数类型不一致导致的crash，他怀疑是不是我传入参数的问题。但是我觉得从堆栈信息里明确是record_document析构时发生的问题。我自己也模拟过中文的赋值没有crash，我能排除这个问题嘛

**Comment by miloyip** [comment]
感觉有可能是内存被其他越界覆写。比较可疑的是 `WStringToString()`。
最好你把代码分离出来测试，或者去掉一些部分测试。

**Comment by beita1** [comment]
有一个信息是那段时间在做磁盘整理，想请问一下磁盘整理对项目内存会有影响吗。

**Comment by miloyip** [comment]
不会

**Comment by beita1** [comment]
问题解决了。是我们自己代码的问题。。是复制一个文件的同时我们收到系统事件读取该文件时导致的，临时对其延迟5S就解决了。就是不清楚为什么会crash在这里。
