### ISSUE TITLE
The Demo Not Working On Linux

### ISSUE THREAD

**Issue by lzfgnu** [Tencent/rapidjson#1467]
![Screenshot from 2019-03-14 20-52-34](https://user-images.githubusercontent.com/25069103/54358413-4dc2d480-469b-11e9-9fc8-777066f641aa.png)
![Screenshot from 2019-03-14 20-53-50](https://user-images.githubusercontent.com/25069103/54358429-5c10f080-469b-11e9-81f6-a61eb31057fe.png)

**Comment by Bu11etmagnet** [comment]
I tried to reproduce your problem, but my C++ compiler can't process PNG files. Please post C++ source code and compiler output as text, not pictures.

**Comment by lzfgnu** [comment]
> I tried to reproduce your problem, but my C++ compiler can't process PNG files. Please post C++ source code and compiler output as text, not pictures.

// rapidjson/example/simpledom/simpledom.cpp`
#include "rapidjson/document.h"
#include "rapidjson/writer.h"
#include "rapidjson/stringbuffer.h"
#include <iostream>

using namespace rapidjson;

int main() {
    // 1. Parse a JSON string into DOM.
    const char* json = "{\"project\":\"rapidjson\",\"stars\":10}";
    Document d;
    d.Parse(json);

    // 2. Modify it by DOM.
    Value& s = d["stars"];
    s.SetInt(s.GetInt() + 1);

    // 3. Stringify the DOM
    StringBuffer buffer;
    Writer<StringBuffer> writer(buffer);
    d.Accept(writer);

    // Output {"project":"rapidjson","stars":11}
    std::cout << buffer.GetString() << std::endl;
    return 0;
}
