### ISSUE TITLE
Assertion failed while calling Clear() function after parsing a JSON file

### ISSUE THREAD

**Issue by motein** [Tencent/rapidjson#1489]
**Reproduce Steps:**
1. Parse content from a JSON file.
![image](https://user-images.githubusercontent.com/6309457/56114984-f8792c00-5f94-11e9-8664-be25cbec6893.png)
2. Use **Clear()** method to clear the content in the current doc object. Then **Assertion failed!!!**
![image](https://user-images.githubusercontent.com/6309457/56115113-3d04c780-5f95-11e9-8383-1a08a350fce0.png)

![image](https://user-images.githubusercontent.com/6309457/56115100-32e2c900-5f95-11e9-832e-99f12b8f7179.png)

**More info:**
1. The content of this JSON file is valid.
2. I can parse the JSON file correctly.

**Comment by miloyip** [comment]
`Clear()` is only applied to array type.
The similar API for object type is `RemoveAllMembers()`.
Or you can `d.SetNull().SetObject()`

**Comment by motein** [comment]
Thanks for you kindly answer. 
Personally, Clear may not be a good name for clearing an array.

**Comment by miloyip** [comment]
The array type API resembles `std::vector`.
