### ISSUE TITLE
Parsing large json file

### ISSUE THREAD

**Issue by akki401** [Tencent/rapidjson#1511]
Hello,
I started analyzing this parser and i love it.
I have a query.
can RapidJson parse,edit and write more than 1GB size of json file?
what is the max size input data limitation of RapidJson can handle ?

**Comment by miloyip** [comment]
It depends on memory avaliable.

> Each JSON value occupies exactly 16 bytes for most 32/64-bit machines (excluding text string). By default it uses a fast memory allocator, and the parser allocates memory compactly during parsing.

**Comment by akki401** [comment]
Thanks for your quick reply.
Actually we are using QJsonParser (QtJson) to parse bigger json file(minimum 1GB) and we got the error message “QJson: Document too large to store in data structure”.
We analyzed the problem and root cause of the issue is Qt  supports only 127 MB data.
So does RapidJson can help us to solve the above issue?
Please suggest

**Comment by miloyip** [comment]
RapidJSON does not have such limit. You can try it with your data easily.

But in the default settings, each array/object can only contain 2^32 entries. This can be customized to support 2^64 if needed.

**Comment by akki401** [comment]
Thank you miloyip. Quick response.
One more Quick question.
Which is efficient and best parsing/writing? SAX or DOM?

**Comment by miloyip** [comment]
DOM uses SAX underneath. So if SAX is sufficient for the application (single pass traversal), uses SAX.

**Comment by akki401** [comment]
Thank you very much miloyip.
Very quick response.
