### ISSUE TITLE
Please do not set ccache as RULE_LAUNCH_COMPILE/LINK in CMakeLists.txt

### ISSUE THREAD

**Issue by juhanima** [Tencent/rapidjson#1527]
Rapidjson is a library which is often included in a bigger project as a dependency. The host project might have its own idea of how to best optimize compilation times. So it's not very nice to set compiler and linker launchers as global properties in the CMake-file, please do not do that.

For the very least, if you want to enforce unconditional ccache, use the variable ${CMAKE_EXECUTABLE} set by the find_program macro in stead if just plain "ccache", which may or may not be in the PATH.

**Comment by ClausKlein** [comment]
see https://github.com/Tencent/rapidjson/pull/1810

**Comment by ClausKlein** [comment]
```cmake
set(CMAKE_CXX_COMPILER_LAUNCHER "${CCACHE_EXECUTABLE}" CACHE PATH "path to ccache" FORCE)
```
I use `CCACHE_EXECUTABLE`?

**Comment by juhanima** [comment]
So you do. Thanks, closing!
