### ISSUE TITLE
cross-platform compilation on 

### ISSUE THREAD

**Issue by EvergreenHZ** [Tencent/rapidjson#1532]
Hello, I want to use the library on an embedded system (arm-himix200v002-linux-g++). but I do not know how to compile the source code.

My compiling machine: Linux ........ 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
and I do not have root privilege.

**Comment by MuratUrsavas** [comment]
You don't need to have root privileges. Follow these steps, 

1) Clone this project under your project via "git clone https://github.com/Tencent/rapidjson.git"
2) Add the sub folder "rapidjson/include" into your search include subfolders (depends on your toolchain/IDE)
3) Add "#include "rapidjson/document"" into your source file

That's it. For further information, follow the steps in the basic tutorial (http://rapidjson.org/md_doc_tutorial.html)

**Comment by EvergreenHZ** [comment]
Thank you for your time. I know what you mean, include the header file and export the search path. However, I have to compile the source code before I use it(say .a or .so), so I do not think your solution works.  Thanks again.
P.S. I think I can just use it on my Manjora and it's enough for me.
