### ISSUE TITLE
Issue escaping non-ASCII characters

### ISSUE THREAD

**Issue by timwoj** [Tencent/rapidjson#1534]
According to the documentation, I should be able to pass `ASCII<>` as the output decoding for a Writer and it'll automatically escape characters outside of the range of ASCII. Does this include for example `\x80`? The following simple example doesn't work as expected.

```
  string b = "\x80";

  Document doc;
  doc.SetObject();

  Value v;
  v.SetString(b.c_str(), b.size());
  doc.AddMember("a", v, doc.GetAllocator());

  StringBuffer buffer;
  Writer<StringBuffer, UTF8<>, ASCII<> > writer(buffer);
  doc.Accept(writer);

  cout << buffer.GetString() << endl;
```

This outputs `{"a":"`. A hexdump of the output is `0000000 7b 22 61 22 3a 22 0a`. You can see that the `\x80` character is missing entirely. I would have expected it to convert to `\u0080` as described in the FAQ. Am I doing something wrong here?

**Comment by fredgan** [comment]
Special characters:  0x80 ~ 0xbf
If these characters appears in input string and parse as ASCII<>, kParseErrorStringInvalidEncoding occurs.

So, these characters cannot write to StringBuffer as ASCII<> .
Also, when some error happens, the ```doc.Accept(writer)``` returns 0

So I think the description in the FAQ is not precise.
