### ISSUE TITLE
v1.1.0版本使用document生成json时 ，coredump

### ISSUE THREAD

**Issue by Qinsam** [Tencent/rapidjson#1535]
v1.1.0版本使用document生成json时 ，coredump

**Comment by fredgan** [comment]
把你的代码贴出来吧，以及运行环境是什么呢？

**Comment by yelu** [comment]
Document在析构时存在问题，不光是to json时，其它时候也会。

**Comment by yelu** [comment]
最近遇到了同样的问题，tojson会导致最终document析构的时候coredump。还没有来得及查出来原因。

**Comment by Qinsam** [comment]
> 
> 
> 把你的代码贴出来吧，以及运行环境是什么呢？

     rapidjson::Document resDoc;
     resDoc.SetObject();
     rapidjson::Document::AllocatorType& allocator = resDoc.GetAllocator();
     rapidjson::Value array_objects(rapidjson::kArrayType);
     for (int32_t i = start; i < end; ++i) {
         Lucene::DocumentPtr doc = searcher->doc(hits[i]->doc);
         int64_t vid = StringUtils::toLong(doc->get(L"vid"));
         string title = StringUtils::toUTF8(doc->get(L"title"));
         
         rapidjson::Value video_obj(kObjectType);
         video_obj.AddMember(StringRef("vid"),vid,allocator);
         video_obj.AddMember(StringRef("title"),StringRef(title.c_str()),allocator);
         array_objects.PushBack(video_obj,allocator);
     }
     resDoc.AddMember(StringRef("videos"),array_objects,allocator);
     StringBuffer buffer;
     Writer<StringBuffer> writer(buffer);
     resDoc.Accept(writer);

centos 7.2

**Comment by fredgan** [comment]
关于RapidJSON部分的使用，看上去是正常的。建议你把coredump文件分析一下。看看出错代码在哪行

**Comment by Qinsam** [comment]
> 
> 
> 关于RapidJSON部分的使用，看上去是正常的。建议你把coredump文件分析一下。看看出错代码在哪行



> 
> 
> 关于RapidJSON部分的使用，看上去是正常的。建议你把coredump文件分析一下。看看出错代码在哪行

**Comment by Qinsam** [comment]
> 
> 
> 关于RapidJSON部分的使用，看上去是正常的。建议你把coredump文件分析一下。看看出错代码在哪行

Thank you! You are beautiful!
