### ISSUE TITLE
是否支持流式解析以及多个json分离解析

### ISSUE THREAD

**Issue by adugeek** [Tencent/rapidjson#1537]
你好，最近在处理网络数据的时候经常会遇到如下情况
1： json字符串只读取了一半内容，剩下的内容需要再次从 socket读取.
2:   两个或多个json字符串合并在一起返回了，最后一个 json　在某些情况下也只有一半内容.

尝试使用　rapidjson解析的时候，１，２和情况都会导致失败.

**Comment by miloyip** [comment]
1. 自行定义 stream 是可以的。
2. 多个连续 JSON 可使用 `kParseStopWhenDoneFlag`。

**Comment by adugeek** [comment]
你好.目前我的处理方式确实是使用了流,当流里面有多个完整的 Json时是可以工作的.
但是当流里面的 Json 不是完整时, 则无法工作. 如果是代码上的问题,请帮忙指正下 ,感谢.  ~_~



#include <memory>
#include <iostream>
#include <sstream>
#include <rapidjson/rapidjson.h>
#include <rapidjson/document.h>
#include <rapidjson/reader.h>
#include <rapidjson/istreamwrapper.h>

int main() {

    std::string context1 = "{\"type\":\"ADDED\",\"object\":{\"kind\":\"Service\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"kubernetes\",\"namespace\":\"default\",\"selfLink\":\"/api/v1/namespaces/default/services/kubernetes\",\"uid\":\"d5c0ca00-83e1-44da-a64e-abd205962926\",\"resourceVersion\":\"149\",\"creationTimestamp\":\"2019-06-27T03:16:22Z\",\"labels\":{\"component\":\"apiserver\",\"provider\":\"kubernetes\"}},\"spec\":{\"ports\":[{\"name\":\"https\",\"protocol\":\"TCP\",\"port\":443,\"targetPort\":6443}],\"clusterIP\":\"10.96.0.1\",\"type\":\"ClusterIP\",\"sessionAffinity\":\"None\"},\"status\":{\"loadBalancer\":{}}}}\n"
                           "{\"type\":\"ADDED\",\"object\":{\"kind\":\"Service\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"new-nginx\",\"namespace\":\"default\",\"selfLink\":\"/api/v1/namespaces/default/services/new-nginx\",\"uid\":\"3bd8f79f-5d85-41b0-9d37-707ac5be0226\",\"resourceVersion\":\"1406147\",\"creationTimestamp\":\"2019-07-09T08:58:17Z\",\"labels\":{\"k8s-app\":\"new-nginx\"}},\"spec\":{\"ports\":[{\"name\":\"tcp-4124-4412-l5l5v\",\"protocol\":\"TCP\",\"port\":4124,\"targetPort\":4412}],\"selector\":{\"k8s-app\":\"new-nginx\"},\"clusterIP\":\"10.102.43.117\",\"type\":\"ClusterIP\",\"sessionAffinity\":\"None\"},\"status\":{\"loadBalancer\":{}}}}\n"
                           "{\"type\":\"ADDED\",\"object\":{\"kind\":\"Service\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"nginx-service\",\"namespace\":\"default\",\"selfLink\":\"/api/v1/namespaces/default/services/nginx-service\",\"uid\":\"7eb8ecff-e0f8-462f-8ee6-5d604aa319a1\",\"resourceVersion\":\"684460\",\"creationTimestamp\":\"2019-07-03T02:15:01Z\"},\"spec\":{\"ports\":[{\"name\":\"nginxobj\",\"protocol\":\"TCP\",\"port\":80,\"targetPort\":80}],\"selector\":{\"app\":\"nginx_test\"},\"clusterIP\":\"None\",\"type\":\"ClusterIP\",\"sessionAffinity\":\"None\"},\"status\":{\"loadBalancer\":{}}}}\n"
                           "{\"type\":\"ADDED\",\"object\":{\"kind\":\"Service\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"only-nginx\",\"namespace\":\"default\",\"selfLink\":\"/api/v1/namespaces/default/services/only-nginx\",\"uid\":\"93c4f1b6-2924-4b39-a895-d4a30e255bae\",\"resourceVersion\":\"1407143\",\"creationTimestamp\":\"2019-07-09T09:04:18Z\",\"labels\":{\"k8s-app\":\"only-nginx\"}},\"spec\":{\"ports\":[{\"name\":\"tcp-1234-12441-47r5g\",\"protocol\":\"TCP\",\"port\":1234,\"targetPort\":12441},{\"name\":\"tcp-1342-21414-9p6hb\",\"pr";


    std::string context2 = "otocol\":\"TCP\",\"port\":1342,\"targetPort\":21414},{\"name\":\"tcp-13145-13124-dntbg\",\"protocol\":\"TCP\",\"port\":13145,\"targetPort\":13124},{\"name\":\"tcp-12324-4325-pgtpk\",\"protocol\":\"TCP\",\"port\":12324,\"targetPort\":4325},{\"name\":\"tcp-2351-2345-q2g89\",\"protocol\":\"TCP\",\"port\":2351,\"targetPort\":2345}],\"selector\":{\"k8s-app\":\"only-nginx\"},\"clusterIP\":\"10.109.16.196\",\"type\":\"ClusterIP\",\"sessionAffinity\":\"None\"},\"status\":{\"loadBalancer\":{}}}}";


    std::cout << context1.size() << " " << context2.size() << std::endl;



    std::stringstream ostringstream;

    ostringstream << context1;


    rapidjson::IStreamWrapper wrapper(ostringstream);
    while (true) {
        auto p1 = std::make_shared<rapidjson::Document>();
        p1->ParseStream<rapidjson::kParseStopWhenDoneFlag>(wrapper);
        std::cout << wrapper.Tell() << std::endl;

        if (p1->HasParseError()) {
            break;
        }
    }

    ostringstream << context2;
    ostringstream.flush();
    wrapper.Flush();

    std::cout << wrapper.Tell() << std::endl;
//    wrapper.Flush();
    auto p1 = std::make_shared<rapidjson::Document>();
    p1->ParseStream<rapidjson::kParseStopWhenDoneFlag>(wrapper);
    std::cout << wrapper.Tell() << std::endl;
}

**Comment by miloyip** [comment]
要自行定义 stream 类型，读到未收到的数据要阻塞。

**Comment by adugeek** [comment]
明白了,非常感谢.
目前我用如下的代码解决了问题, 核心逻辑是发现有 Json不完成整时,把数据拷贝的新的地方,然后重新构造一个 StringStream 来解析.

 代码如下:

```c++

#include <memory>
#include <iostream>
#include <sstream>
#include <rapidjson/rapidjson.h>
#include <rapidjson/document.h>
#include <rapidjson/reader.h>
#include <rapidjson/istreamwrapper.h>
#include <rapidjson/stream.h>
#include <asio/streambuf.hpp>

asio::streambuf buffer_{};
asio::streambuf body_buffer_{};

void parser() {
    if (body_buffer_.size() == 0) {
        const char *data = asio::buffer_cast<const char *>(buffer_.data());
        rapidjson::StringStream stream(data);

        size_t lastTell = 0;

        while (lastTell < buffer_.size()) {
            auto p1 = std::make_shared<rapidjson::Document>();
            p1->ParseStream<rapidjson::kParseStopWhenDoneFlag>(stream);
            if (p1->HasParseError()) {
                break;
            }
            stream.Take();
            lastTell = stream.Tell();
        }
        assert(lastTell <= buffer_.size());
        if (lastTell < buffer_.size()) {
            body_buffer_.sputn(data + lastTell, buffer_.size() - lastTell);
        }
    } else {
        const char *buffer_data = asio::buffer_cast<const char *>(buffer_.data());
        body_buffer_.sputn(buffer_data, buffer_.size());

        const char *body_buffer_data = asio::buffer_cast<const char *>(body_buffer_.data());

        rapidjson::StringStream stream(body_buffer_data);
        size_t lastTell = 0;
        while (lastTell < body_buffer_.size()) {
            auto p1 = std::make_shared<rapidjson::Document>();
            p1->ParseStream<rapidjson::kParseStopWhenDoneFlag>(stream);
            if (p1->HasParseError()) {
                break;
            }
            stream.Take();
            lastTell = stream.Tell();
        }
        body_buffer_.consume(lastTell);
    }
}

int main() {

    std::string context1 = "{\"type\":\"ADDED\",\"object\":{\"kind\":\"Service\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"kubernetes\",\"namespace\":\"default\",\"selfLink\":\"/api/v1/namespaces/default/services/kubernetes\",\"uid\":\"d5c0ca00-83e1-44da-a64e-abd205962926\",\"resourceVersion\":\"149\",\"creationTimestamp\":\"2019-06-27T03:16:22Z\",\"labels\":{\"component\":\"apiserver\",\"provider\":\"kubernetes\"}},\"spec\":{\"ports\":[{\"name\":\"https\",\"protocol\":\"TCP\",\"port\":443,\"targetPort\":6443}],\"clusterIP\":\"10.96.0.1\",\"type\":\"ClusterIP\",\"sessionAffinity\":\"None\"},\"status\":{\"loadBalancer\":{}}}}\n"
                           "{\"type\":\"ADDED\",\"object\":{\"kind\":\"Service\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"new-nginx\",\"namespace\":\"default\",\"selfLink\":\"/api/v1/namespaces/default/services/new-nginx\",\"uid\":\"3bd8f79f-5d85-41b0-9d37-707ac5be0226\",\"resourceVersion\":\"1406147\",\"creationTimestamp\":\"2019-07-09T08:58:17Z\",\"labels\":{\"k8s-app\":\"new-nginx\"}},\"spec\":{\"ports\":[{\"name\":\"tcp-4124-4412-l5l5v\",\"protocol\":\"TCP\",\"port\":4124,\"targetPort\":4412}],\"selector\":{\"k8s-app\":\"new-nginx\"},\"clusterIP\":\"10.102.43.117\",\"type\":\"ClusterIP\",\"sessionAffinity\":\"None\"},\"status\":{\"loadBalancer\":{}}}}\n"
                           "{\"type\":\"ADDED\",\"object\":{\"kind\":\"Service\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"nginx-service\",\"namespace\":\"default\",\"selfLink\":\"/api/v1/namespaces/default/services/nginx-service\",\"uid\":\"7eb8ecff-e0f8-462f-8ee6-5d604aa319a1\",\"resourceVersion\":\"684460\",\"creationTimestamp\":\"2019-07-03T02:15:01Z\"},\"spec\":{\"ports\":[{\"name\":\"nginxobj\",\"protocol\":\"TCP\",\"port\":80,\"targetPort\":80}],\"selector\":{\"app\":\"nginx_test\"},\"clusterIP\":\"None\",\"type\":\"ClusterIP\",\"sessionAffinity\":\"None\"},\"status\":{\"loadBalancer\":{}}}}\n"
                           "{\"type\":\"ADDED\",\"object\":{\"kind\":\"Service\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"only-nginx\",\"namespace\":\"default\",\"selfLink\":\"/api/v1/namespaces/default/services/only-nginx\",\"uid\":\"93c4f1b6-2924-4b39-a895-d4a30e255bae\",\"resourceVersion\":\"1407143\",\"creationTimestamp\":\"2019-07-09T09:04:18Z\",\"labels\":{\"k8s-app\":\"only-nginx\"}},\"spec\":{\"ports\":[{\"name\":\"tcp-1234-12441-47r5g\",\"protocol\":\"TCP\",\"port\":1234,\"targetPort\":12441},{\"name\":\"tcp-1342-21414-9p6hb\",\"pr";


    std::string context2 = "otocol\":\"TCP\",\"port\":1342,\"targetPort\":21414},{\"name\":\"tcp-13145-13124-dntbg\",\"protocol\":\"TCP\",\"port\":13145,\"targetPort\":13124},{\"name\":\"tcp-12324-4325-pgtpk\",\"protocol\":\"TCP\",\"port\":12324,\"targetPort\":4325},{\"name\":\"tcp-2351-2345-q2g89\",\"protocol\":\"TCP\",\"port\":2351,\"targetPort\":2345}],\"selector\":{\"k8s-app\":\"only-nginx\"},\"clusterIP\":\"10.109.16.196\",\"type\":\"ClusterIP\",\"sessionAffinity\":\"None\"},\"status\":{\"loadBalancer\":{}}}}";

    buffer_.sputn(context1.c_str(), context1.size());

    parser();
    buffer_.consume(buffer_.size());

    buffer_.sputn(context2.c_str(), context2.size());

    parser();

    std::cout << body_buffer_.size() << std::endl;
}
```
