### ISSUE TITLE
想要的反斜杠 \. 无法表示，否则JSON解析出错

### ISSUE THREAD

**Issue by ouliuquan** [Tencent/rapidjson#1547]
以rapidjson/example/simpledom/simpledom.cpp为例，如下：

`const char* json = R"({"project":"\\.rapidjson","stars":10})";`

我要表达真正的意思是：`{"project":"\.rapidjson","stars":10}`，按照转义的规则，上面写`\\.`应该可以转成`\. `但是C++解析出来的实际上是`\\.`
如果只写1个或者3个反斜杠，编译过了，但是运行时会出错， `Assertion `IsObject()' failed.`
如果写4个反斜杠，出来C++解析出来就是4个反斜杠了，那应该怎么转义成1个反斜杠？

**Comment by miloyip** [comment]
看不懂你的问题⋯⋯
JSON `{"project":"\.rapidjson","stars":10}` 是不合法的

**Comment by ouliuquan** [comment]
我需要传递一个正则表达式，这个只是其中一个片段，必须是`\.`的搭配，我问了很多人，他们说这个是JSON解决不了的，所以我考虑用`\\.`来表示，在系统内部再把`\\`替换成`\`

**Comment by fredgan** [comment]
```
// JSON simple example
// This example does not handle errors.

#include "rapidjson/document.h"
#include "rapidjson/writer.h"
#include "rapidjson/stringbuffer.h"
#include <iostream>
#include <string>

using namespace rapidjson;

int main() {
    // 1. Parse a JSON string into DOM.
    const char* json = "{\"project\":\"\\\\.rapidjson\",\"stars\":10}";
    Document d;
    d.Parse(json);

    // 2. Modify it by DOM.
    Value& s = d["stars"];
    s.SetInt(s.GetInt() + 1);

    std::cout << "project=" << d["project"].GetString() << std::endl;

    // 3. Stringify the DOM
    StringBuffer buffer;
    Writer<StringBuffer> writer(buffer);
    d.Accept(writer);

    // Output {"project":"rapidjson","stars":11}
    std::cout << buffer.GetString() << std::endl;
    return 0;
}
```

@ouliuquan 
The output is as follow: 
```
project=\.rapidjson
{"project":"\\.rapidjson","stars":11}
```

**Comment by aline117** [comment]
用一个正则方法，先要 要 parse 的原数据做一个 替换
将 \\ 替换为 \\\\   
如原始json数据中有转义字符（这些字符包括单引号，双引号，正斜杠，反斜杠，以及换行符，制表符） 等等  都需要先  替换一下，不然parse出错
