### ISSUE TITLE
Document::Accept is broken

### ISSUE THREAD

**Issue by yda86** [Tencent/rapidjson#1553]
When I try get json as text from Value object, compilation has failed with next errors 

> Error	C2039	Null: has not member of "rapidjson::GenericStringBuffer<rapidjson::UTF8<char>,rapidjson::CrtAllocator>"	project1	c:\users\user\documents\visual studio 2017\projects\project1\project1\rapidjson\document.h	1770	
Error	C2039	Bool: has not member of "rapidjson::GenericStringBuffer<rapidjson::UTF8<char>,rapidjson::CrtAllocator>"	project1	c:\users\user\documents\visual studio 2017\projects\project1\project1\rapidjson\document.h	1771	
Error	C2039	Bool: has not member of "rapidjson::GenericStringBuffer<rapidjson::UTF8<char>,rapidjson::CrtAllocator>"	project1	c:\users\user\documents\visual studio 2017\projects\project1\project1\rapidjson\document.h	1772	
Error	C2039	StartObject: has not member of "rapidjson::GenericStringBuffer<rapidjson::UTF8<char>,rapidjson::CrtAllocator>"	project1	c:\users\user\documents\visual studio 2017\projects\project1\project1\rapidjson\document.h	1775	
Error	C2039	Key: has not member of "rapidjson::GenericStringBuffer<rapidjson::UTF8<char>,rapidjson::CrtAllocator>"	project1	c:\users\user\documents\visual studio 2017\projects\project1\project1\rapidjson\document.h	1779	
Error	C2039	EndObject: has not member of "rapidjson::GenericStringBuffer<rapidjson::UTF8<char>,rapidjson::CrtAllocator>"	project1	c:\users\user\documents\visual studio 2017\projects\project1\project1\rapidjson\document.h	1784	
Error	C2039	StartArray: has not member of "rapidjson::GenericStringBuffer<rapidjson::UTF8<char>,rapidjson::CrtAllocator>"	project1	c:\users\user\documents\visual studio 2017\projects\project1\project1\rapidjson\document.h	1787	
Error	C2039	EndArray: has not member of "rapidjson::GenericStringBuffer<rapidjson::UTF8<char>,rapidjson::CrtAllocator>"	project1	c:\users\user\documents\visual studio 2017\projects\project1\project1\rapidjson\document.h	1792	
Error	C2039	String: has not member of "rapidjson::GenericStringBuffer<rapidjson::UTF8<char>,rapidjson::CrtAllocator>"	project1	c:\users\user\documents\visual studio 2017\projects\project1\project1\rapidjson\document.h	1795	
Error	C2039	Double: has not member of "rapidjson::GenericStringBuffer<rapidjson::UTF8<char>,rapidjson::CrtAllocator>"	project1	c:\users\user\documents\visual studio 2017\projects\project1\project1\rapidjson\document.h	1799	
Error	C2039	Int: has not member of "rapidjson::GenericStringBuffer<rapidjson::UTF8<char>,rapidjson::CrtAllocator>"	project1	c:\users\user\documents\visual studio 2017\projects\project1\project1\rapidjson\document.h	1800	
Error	C2039	Uint: has not member of "rapidjson::GenericStringBuffer<rapidjson::UTF8<char>,rapidjson::CrtAllocator>"	project1	c:\users\user\documents\visual studio 2017\projects\project1\project1\rapidjson\document.h	1801	
Error	C2039	Int64: has not member of "rapidjson::GenericStringBuffer<rapidjson::UTF8<char>,rapidjson::CrtAllocator>"	project1	c:\users\user\documents\visual studio 2017\projects\project1\project1\rapidjson\document.h	1802	
Error	C2039	Uint64: has not member of "rapidjson::GenericStringBuffer<rapidjson::UTF8<char>,rapidjson::CrtAllocator>"	project1	c:\users\user\documents\visual studio 2017\projects\project1\project1\rapidjson\document.h	1803

**Comment by miloyip** [comment]
I cannot help without reproducible example.

**Comment by pah** [comment]
From the compiler error, it looks like you are passing a `StringBuffer` directly to `Accept`.  You need to use a `(Pretty)Writer` instead, see e.g. "Usage at a glance" at http://rapidjson.org:
```cpp
    // 3. Stringify the DOM
    StringBuffer buffer;
    Writer<StringBuffer> writer(buffer);
    d.Accept(writer);
```
