### ISSUE TITLE
Hasher's offset basis high and low values swapped

### ISSUE THREAD

**Issue by qdin** [Tencent/rapidjson#1558]
FNV-1a algorithm specifies the 64-bit offset basis as 0xcbf29ce484222325
https://en.wikipedia.org/wiki/Fowler–Noll–Vo_hash_function

In the code it's written as RAPIDJSON_UINT64_C2(0x84222325, 0xcbf29ce4). 
https://github.com/Tencent/rapidjson/blob/2648a732dbb8c7fa211e41616071202bfbd09c77/include/rapidjson/schema.h#L294

Shouldn't these high and low values be swapped?

**Comment by miloyip** [comment]
Thank you for noting this. Wanna give a PR?
