### ISSUE TITLE
suspicous memory leak

### ISSUE THREAD

**Issue by TrLiulu** [Tencent/rapidjson#1559]
Here is a simplified code snippet for our use case. We found if the input str's size is larger than 14, the memory will keep grow all the time. 

 #include "rapidjson/document.h"
 #include "rapidjson/error/en.h"
 #include "stdio.h"
 #include <iostream>
 using namespace rapidjson;
 int main()
 {
  std::cout << "input a string:" << std::endl;
  std::string str = "";
  std::cin >> str;
  Document d;
  d.Parse("{\"a\":[[\"joir\"]]}");
  for(int i=0;i<100000000000000;i++)
  {
     rapidjson::Value& inner_table = d["a"];
     inner_table[0][0].SetString(str.c_str(), str.length(), d.GetAllocator());
  }
  return 0;
 }

We found rapidjson handles the short string and longer ones with different ways (in document.h:2063). For the latter, it allocates memory but seems do not free them until the whole document is destructred:

    void SetStringRaw(StringRefType s, Allocator& allocator) {
        Ch* str = 0;
        if (ShortString::Usable(s.length)) {
            data_.f.flags = kShortStringFlag;
            data_.ss.SetLength(s.length);
            str = data_.ss.str;
        } else {
            data_.f.flags = kCopyStringFlag;
            data_.s.length = s.length;
            //When will release these memory?
            str = static_cast<Ch *>(allocator.Malloc((s.length + 1) * sizeof(Ch)));
            SetStringPointer(str);
        }
        std::memcpy(str, s, s.length * sizeof(Ch));
        str[s.length] = '\0';
    }

Is this a memory leak or we should use clear() or something like that at proper places?

**Comment by miloyip** [comment]
By design, the default allocator is mainly for fast parsing, and it allocates but not releases until the allocator iteself destructs.
Use `CrtAllocator` if you need to continously modifying the document.

**Comment by TrLiulu** [comment]
Do I have to modify the source code to use CrtAllocator?

**Comment by miloyip** [comment]
~~~
GenericDocument<UTF8<>, CrtAllocator> d;
~~~

**Comment by TrLiulu** [comment]
非常感谢！
