### ISSUE TITLE
travis on windows

### ISSUE THREAD

**Issue by ANaumann85** [Tencent/rapidjson#1560]
On windows, there is no shell, hence the script travis-doxygen.sh does not run.

The custom command (and target) in the lines 139-141 should be enclosed by
 if(UNIX OR CYGWIN) ... endif()

**Comment by miloyip** [comment]
I think Windows has shell now?
travis-doxygen.sh is only for building documents in travis CI automatically and upload to github pages.

**Comment by ANaumann85** [comment]
Windows has a shell, but only within a special-subshell. The classical "x64 Native Command Prompt" does not provide one.
Nevertheless, the custom target should not build automatically and a cannot reproduce the problem any more.
Sorry for the noise, I think we can close the ticket.
