### ISSUE TITLE
Single quotes handling in JSON

### ISSUE THREAD

**Issue by DjPasco** [Tencent/rapidjson#1564]
I'm creating a JSON object with following data:
`{"name":"Jo'hn", "age":"30'", "city":"New York"}`

The problem is a single quote in word John. I must to output JSON object to the file as JavaScript member to use it later in a webpage. My file contains the following text after JSON object is converted to a string and outputted to the file:
`var txt = '{"name":"Jo'hn", "age":"30'", "city":"New York"}'`

JavaScript can't understand such data and fails to parse provided JSON. To export JSON to string, I'm using following rapidjson functionality:

```
static inline void obj2str(const rapidjson::Document *doc, std::string &sJson) {
   rapidjson::StringBuffer buffer;
   rapidjson::Writer<rapidjson::StringBuffer> writer(buffer);
   doc->Accept(writer);
   sJson = buffer.GetString();
}
```
To fix such issue I must insert symbol "\\" before every single quote to produce correct output for the JavaScript. The insertion of "\\" must be done after obj2str function call. Clearly, the obj2str function breaks proper formatting of the JSON. Final result, acceptable by JavaScript, is following:
`var txt = '{"name":"Jo\'hn", "age":"30\'", "city":"New York"}'`

If I'm adding a character "\\" insertion before obj2str  - the result is still the same and JavaScript can't handle it.

So, where is the problem? Does rapidjson mishandle single quote when the string is formatted? Alternatively, maybe JSON parser used by JavaScript is implemented incorrectly?

**Comment by pah** [comment]
There is no need to generate the Javascript variable as text and parse it manually. You can directly write out the object in Javascript
```js
var obj = {"name":"Jo\'hn", "age":"30\'", "city":"New York"};

```

**Comment by DjPasco** [comment]
> 
> 
> There is no need to generate the Javascript variable as text and parse it manually. You can directly write out the object in Javascript
> 
> ```js
> var obj = {"name":"Jo\'hn", "age":"30\'", "city":"New York"};
> ```

Thank You, it helped to fix my problem.

**Comment by DjPasco** [comment]
Issue fixed with the @pah solution.
