### ISSUE TITLE
cmake -DRAPIDJSON_HAS_STDSTRING=ON doesn't work

### ISSUE THREAD

**Issue by HunterLarco** [Tencent/rapidjson#1572]
Actions taken

```
cmake . -DCMAKE_BUILD_TYPE=Release -DRAPIDJSON_HAS_STDSTRING=ON
```

Expectation

```
#define RAPIDJSON_HAS_STDSTRING=1
```

Observed behavior

Line 125 of rapidjson.h
```
#ifndef RAPIDJSON_HAS_STDSTRING
#ifdef RAPIDJSON_DOXYGEN_RUNNING
#define RAPIDJSON_HAS_STDSTRING 1 // force generation of documentation
#else
#define RAPIDJSON_HAS_STDSTRING 0 // no std::string support by default
#endif
```

Why would std::string support be disabled when explicitly enabled due to doxygen missing? This effectively overrides the option set by `cmake -DRAPIDJSON_HAS_STDSTRING`

**Comment by pah** [comment]
The section above quoted from the header is **not** overriding anything from the command-line due to the `#ifndef RAPIDJSON_HAS_STDSTRING`.  However, the Cmake implementation looks wrong, as it does not assign a **value** to the `RAPIDJSON_HAS_STDSTRING` define.

You can change `CMakeLists.txt` to:

```
option(RAPIDJSON_HAS_STDSTRING "" OFF)
if(RAPIDJSON_HAS_STDSTRING)
    add_definitions(-DRAPIDJSON_HAS_STDSTRING=1) # <-- explicitly set to 1
endif()
```
