### ISSUE TITLE
How to add a JSON object as a "value" for an existing key in a different JSON document?

### ISSUE THREAD

**Issue by suryakalpo** [Tencent/rapidjson#1576]
I've read through the basic Writer and Document tutorials, and I've also checked the tutorial here: https://github.com/Tencent/rapidjson/blob/master/example/tutorial/tutorial.cpp

This is what I have so far:

       `
        std::array<char, 65536> buffer;
        std::FILE* fp = std::fopen("template.json", "r");
        rapidjson::FileReadStream is(fp, buffer.data(), sizeof(buffer));
        std::fclose(fp);

        rapidjson::Document d;
        rapidjson::StringBuffer oBuf;
        rapidjson::Writer<rapidjson::StringBuffer> writer(oBuf);

        d.ParseStream(is);
        d.Accept(writer);

        auto str = "{\"dashboard\" : null, "key_1" : "val_1", ....}";
        rapidjson::Document d1;
        d1.Parse(str);
        if (d1.HasParseError())
        {
                int eparse =  d.GetParseError();
                int eparseoff =  d.GetErrorOffset();
                std::cerr << "JSON parsing error encountered while parsing server response" << "; Error: " << eparse << ", Offset:  " << eparseoff << std::endl;
                throw std::runtime_error("d1 parsing error!");
        }
`

At this point, I want to add the JSON doc d as a value for the "dashboard" key in JSON doc d1. However, I've no idea how to proceed further.

**Comment by suryakalpo** [comment]
Just for some context: template.json does not contain a trivial JSON string. The file contains an object that has multiple, and multilevel child nodes of types (String, Int, Array, Object), thus manually iterating d1 and adding objects to d doesn't seem like a very efficient approach.

**Comment by suryakalpo** [comment]
I think I may have figured it out. However, I'm still not sure if this is the recommended way of achieving this task. I would be very appreciative if someone could validate this method:

`std::array<char, 65536> buffer;                                                                                                                                                                                    std::FILE* fp = std::fopen("template.json", "r");                                                                                                                                                  rapidjson::FileReadStream is(fp, buffer.data(), sizeof(buffer));                                                                                                                                                   std::fclose(fp);                                                                                                                                                                                           
        rapidjson::Document d;                                                                                                                                                                                                                                                                                                                                                                                                                d.ParseStream(is);                                                                                                                                                                                                 if (d.HasParseError())                                                                                                                                                                                             {                                                                                                                                                                                                                          int eparse =  d.GetParseError();                                                                                                                                                                                   int eparseoff =  d.GetErrorOffset();                                                                                                                                                                               std::cerr << "JSON parsing error encountered while parsing server response" << "; Error: " << eparse << ", Offset:  " << eparseoff << std::endl;                                                           throw std::runtime_error("d1 parsing error!");                                                                                                                                                             }                                                                                                                                                                                                                                                                                                                                                                                                                                     rapidjson::Document d1;                                                                                                                                                                                            d1.SetObject();                                                                                                                                                                                                                                                                                                                                                                                                                       rapidjson::Document::AllocatorType& d_alloc = d1.GetAllocator();                                                                                                                                                   size_t sz = d_alloc.Size();                                                                                                                                                                                                                                                                                                                                                                                                           d1.AddMember("dashboard", d, d_alloc);                                                     `

**Comment by miloyip** [comment]
~~~cpp
d1.AddMember("dashboard", d, d_alloc);
~~~

This can **move** `d` into `d1`. Note that the values are still using memory from allocator of d. If you just want to write the combined document and then destroy both documents then it is OK. Otherwise, you may consider cloning 'd' by using 'd1.GetAllocator()`:

~~~cpp
Value v1(d, d1.GetAllocator()); // copy d1 to v1
d1.AddMember("dashboard", v1, d1.GetAllocator());
~~~

**Comment by suryakalpo** [comment]
@miloyip Thank you. I'll close this issue.
