### ISSUE TITLE
作者你好，我 想请教一下，这个框架是否能够将变量中文stirng 转成wchar_t? 在文档只看到定量

### ISSUE THREAD

**Issue by dippac** [Tencent/rapidjson#1581]
作者你好，我 想请教一下，这个框架是否能够将变量中文stirng 转成wchar_t? 在文档只看到定量。感谢！

**Comment by miloyip** [comment]
「中文string」用什么编码？如果是 UTF-8 的话是可以转换成 UTF-16 用 wchar_t 存储。

**Comment by dippac** [comment]
std:string ，目前出现了一个问题是,使用postman 通过这个框架转出来的string转wchar_t时，会出现乱码

**Comment by miloyip** [comment]
编码（encoding）是什么

**Comment by dippac** [comment]
utf-8我试试看转成utf16在转成wchar_t试试

**Comment by miloyip** [comment]
RapidJSON 支持 UTF-8, UTF-16, UTF-32 和 ASCII 编码。其他编码需要使用者自行转换。
