### ISSUE TITLE
how to GetDouble() ?

### ISSUE THREAD

**Issue by dotkt** [Tencent/rapidjson#1587]
how to deal with such json:
**{"precision_double":0.00000000000000000000000000987654321}**
GetDouble() will lost precision. but i can't get it as string.it will just return nullptr;

**Comment by dotkt** [comment]
it's ok.
what if the double value is bigger than DBL_MAX ? how to GetDouble()?

**Comment by miloyip** [comment]
Have you tried `Document::Parse<kParseFullPrecisionFlag>(...)` or `kParseNumbersAsStringsFlag`?

You can find these flags in [the user guide](http://rapidjson.org/md_doc_dom.html#Parsing).

**Comment by dotkt** [comment]
thanks a lot. it's a nice and faster json lib.
