### ISSUE TITLE
rapidjson::Value可以浅拷贝吗

### ISSUE THREAD

**Issue by ggggle** [Tencent/rapidjson#1593]
需要构造多个json串，这些json串中的部分结构是完全相同的，因此可以先将这些共同的部分单独构造出来复用。
默认使用移动语义，因此需要进行深拷贝。
似乎没有找到浅拷贝的方法，请问有更好的解决方案吗

**Comment by miloyip** [comment]
现在的 DOM 做不到，因为 Value 之间是 ownership 的关系。
但如果目的是生成 JSON，那么 `Writer::WriteRawValue()` 可以直接写入 JSON 串。

**Comment by ggggle** [comment]
了解了，谢谢
