### ISSUE TITLE
error C2061: syntax error: identifier 'stack_'

### ISSUE THREAD

**Issue by rsanthisre** [Tencent/rapidjson#1595]
Hi All,
  I am using below code in my program

#include "stdafx.h"
#include "RapidJson\rapidjson.h"
#include "RapidJson\document.h"
#include "RapidJson\stringbuffer.h"
using namespace std;
using namespace rapidjson;
....
,......

Document doc;
doc.Parse(s.c_str());

When I compile I see error

rapidjson\document.h(2425): error C2061: syntax error: identifier 'stack_'
1>  rapidjson\document.h(2425): note: while compiling class template member function 'bool rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>::StartArray(void)'
1>  rapidjson\reader.h(2004): note: see reference to function template instantiation 'bool rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>::StartArray(void)' being compiled
1>

Can someone please help me to fix the issue.

Thanks
Santhi

**Comment by miloyip** [comment]
Which compiler are you using?

**Comment by rsanthisre** [comment]
Hi Milo, Thank you for your reply. I am using Visual Studio 2015(VC++)

**Comment by rsanthisre** [comment]
The issue is solved by shuffling the RapidJson header files to StdAfx.h.
And the RapidJason header files are specified almost on top of the StdAfx.h. This solved the issue

#include "targetver.h"

#include <stdio.h>
#include <new>
#include <tchar.h>

#include <rapidjson.h>
#include <document.h>
#include <stringbuffer.h>
#include <writer.h>
#include <prettywriter.h>

#include<string>
#include <Windows.h>
#include <vector>

**Comment by rsanthisre** [comment]
Hence the issue is solved, Closed.
