### ISSUE TITLE
how to use the same document's  parsing multiple times

### ISSUE THREAD

**Issue by suspy** [Tencent/rapidjson#1605]
I want use the same doc to parse multiple times, but the allocator keep allocate memory.
Is there any way to reuse the memory?

`const char* json = "{\"project\":\"rapidjson\",\"stars\":10}";`
`Document d;`
`int i = 0;`
`while (i++ < 10000000) {`
 `    d.Parse(json);`
`     std::cout << d.GetAllocator().Capacity() << std::endl;`
`}`

**Comment by miloyip** [comment]
You may clear the allocator manually:

~~~cpp
d.SetNull();
d.GetAllocator().Clear();
~~~

But this should be simpler:

~~~cpp
Document d2;
d.Swap(d2);
~~~

To prevent memory allocation, try [user buffer](http://rapidjson.org/md_doc_dom.html#UserBuffer).

**Comment by suspy** [comment]
Thanks.
