### ISSUE TITLE
HasMember and std::string

### ISSUE THREAD

**Issue by lgilson** [Tencent/rapidjson#1620]
Hi,

lets assume i have a std::string and want to know if the DOM contains that string. Why do i have to call string.c_str() for HasMember and the []-operator?

rapidjson::GenericValue<rapidjson::UTF8<>>* input = .....
std::vector<std::string> namesToCheck;
namesToCheck.push_back("Key1");
....

for (auto key : namesToCheck)
{
	if (input->HasMember(key)) { } //<= Does not compile
	if (input->HasMember(key.c_str())) { } //<= compiles
}

And is (*input)[name.c_str()] the correct expression to access that member?

Thanks,

**Comment by suryakalpo** [comment]
@lgilson You can use std::string type directly with rapidjson if you define ```RAPIDJSON_HAS_STDSTRING``` in your code or compiler options.

**Comment by lgilson** [comment]
Thanks a lot
