### ISSUE TITLE
what's the meaning of error code =2?

### ISSUE THREAD

**Issue by CooperBruce** [Tencent/rapidjson#1657]
I use RapidJson to parse a very simple json file with a empty line ending,RapidJson reports that parse failed with error code = 2.
When delete the last empty line,everything is ok.
Does the JSON Standard not allow the file end with a empty line?

Here is the config file i using:
`{
	"test_server_list":["test_vs01"]	
}

`

**Comment by miloyip** [comment]
Empty line (and all whitespaces) are fine. It may be some other issue in your code during reading the file, for example, not null-terminate the string.

**Comment by CooperBruce** [comment]
Got it! 
I will have a try later.
ths！
