### ISSUE TITLE
Header only?

### ISSUE THREAD

**Issue by cailuming** [Tencent/rapidjson#1661]
Almost nothing but some comments in the rapidJson.h, I need to extrally include other files. what I need is just a header file only , or I'm a fool

**Comment by miloyip** [comment]
header only ≠ single header only

**Comment by cailuming** [comment]
Okay



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Milo Yip"<notifications@github.com&gt;; 
发送时间: 2020年3月11日(星期三) 下午3:09
收件人: "Tencent/rapidjson"<rapidjson@noreply.github.com&gt;; 
抄送: "冰封极"<1550378369@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Tencent/rapidjson] Header only? (#1661)




header only ≠ single header only
