### ISSUE TITLE
Feeding a nested JSON to document resulting in kParseErrorDocumentRootNotSingular

### ISSUE THREAD

**Issue by meiravRath** [Tencent/rapidjson#1664]
I'm preparing a function that will return the value of a key in a nested JSON. The problem is that I'm getting the nested JSON's content as a string from other modules in the code and that is not something I can change.

For example: {"remote": {"ip": "127.0.0.1", "port": 58811}}

The content of "remote" is a nested JSON and my code needs to return the value of "ip". Upstream, this nested JSON is turned into a string and passed on to my function.

My code is:

`string sampleInputVal = "\"remote\": {\"ip\": \"127.0.0.1\", \"port\": 58811}";
map<string, string> inputMap;

inputMap.emplace("key","remote");
inputMap.emplace("nestedKey","IP");

string getValNestedJSON(string inputVal, map<string, string> inputParameters)
{
    Document inputJSON;
    inputJSON.Parse(inputVal.c_str());

    return inputJSON[inputParameters["nestedKey"].c_str()].GetString();
}`

As you can guess, `sampleInputVal `is just something I'm using to test the function, but I think the escape characters are messing up rapidjson because I'm getting kParseErrorDocumentRootNotSingular.

What should I do?

**Comment by itai889** [comment]
1. I think that the string for the `sampleInputVal` isn't correct
2. In order to get to the nested value u need to first access the `key` property

The following has worked for me:
```
string getValNestedJSON(const string& inputVal, map<string, string>& inputParameters)
{
    Document inputJSON;
    inputJSON.Parse(inputVal.c_str());
    return inputJSON[inputParameters["key"].c_str()][inputParameters["nestedKey"].c_str()].GetString();
}

int main()
{
    string sampleInputVal  = "{\"remote\":{\"IP\":\"127.0.0.1\", \"port\":58811}}";
    map<string, string> inputMap;
    inputMap.emplace("key","remote");
    inputMap.emplace("nestedKey","IP");
    cout << "getValNestedJSON : "<<getValNestedJSON(sampleInputVal, inputMap) << endl;
}
```
With output:
`getValNestedJSON : 127.0.0.1`

**Comment by meiravRath** [comment]
Hi Itai,

The sampleInputVal is not what I wrote or what you wrote, it's "{\"IP\":\"127.0.0.1\", \"port\":58811}".
I tried your solution, which worked on your sampleInputVal, but not on the real one as I got it from another member in my team. 

I tried:
```
string getValNestedJSON(string inputVal, map<string, string> inputParameters)
{
	Document inputJSON;
	inputJSON.Parse(inputVal.c_str());
	const auto nestedKeyVal = inputParameters["nestedKey"].c_str();
	return inputJSON[nestedKeyVal].GetString();
}
```
But I put a breakpoint at `const auto nestedKeyVal = inputParameters["nestedKey"].c_str();`
and got kParseErrorNone in inputJSON parseResult_.

**Comment by meiravRath** [comment]
The issue I had was with adding an extra } at the end of sampleInputVal. Human mistake. 
The code I ended up working for me is:

`string getValNestedJSON(string inputVal, map<string, string> inputParameters)
{
	string output;
	Document inputJSON;
	inputJSON.Parse(inputVal.c_str());
	const auto nestedKeyVal = inputParameters["nestedKey"].c_str();
	if (inputJSON[nestedKeyVal].IsString())
		output = inputJSON[nestedKeyVal].GetString();
	else if (inputJSON[nestedKeyVal].IsInt())
		output = to_string(inputJSON[nestedKeyVal].GetInt());
	else if (inputJSON[nestedKeyVal].IsDouble())
		output = to_string(inputJSON[nestedKeyVal].GetDouble());
	else if (inputJSON[nestedKeyVal].IsBool())
		output = to_string(inputJSON[nestedKeyVal].GetBool());
	else if (inputJSON[nestedKeyVal].IsUint())
		output = to_string(inputJSON[nestedKeyVal].GetUint());
	else if (inputJSON[nestedKeyVal].IsInt64())
		output = to_string(inputJSON[nestedKeyVal].GetInt64());
	else if (inputJSON[nestedKeyVal].IsUint64())
		output = to_string(inputJSON[nestedKeyVal].GetUint64());
	else if (inputJSON[nestedKeyVal].IsUint64())
		output = to_string(inputJSON[nestedKeyVal].GetUint64());
	else
		output = "Value in nested key cannot be obtained";
	
	return output;
}`
