### ISSUE TITLE
你们腾讯弄了个港独大佬，“中国人的劣根性才是病毒之源，如此态度，十多年后，SARS 3.0必定出现”

### ISSUE THREAD

**Issue by kcauchy** [Tencent/rapidjson#1666]
![101584594077_ pic](https://user-images.githubusercontent.com/1373951/77033389-1095ce80-69e2-11ea-8014-32eeae56c5ae.jpg)
![121584594114_ pic_hd](https://user-images.githubusercontent.com/1373951/77033403-21464480-69e2-11ea-9d4e-377203540629.jpg)
![111584594106_ pic_hd](https://user-images.githubusercontent.com/1373951/77033416-299e7f80-69e2-11ea-9972-2ef1396f55d7.jpg)

![91584594076_ pic](https://user-images.githubusercontent.com/1373951/77033432-34f1ab00-69e2-11ea-83b0-eb1e71c86f37.jpg)
![81584594075_ pic](https://user-images.githubusercontent.com/1373951/77033426-30c58d80-69e2-11ea-8052-7725a08fde23.jpg)
![71584594074_ pic](https://user-images.githubusercontent.com/1373951/77033421-2dca9d00-69e2-11ea-8cfd-9321aac32d47.jpg)

**Comment by kcauchy** [comment]
加油哦，腾讯，我看好你们支持港独。

**Comment by hyqhyq3** [comment]
![image](https://user-images.githubusercontent.com/1583343/77037316-08429100-69ec-11ea-884c-06a6a3b69c62.png)
希望大家理性看待，不要随意被人带了节奏，是真是假自己先判断一下再发言

**Comment by kcauchy** [comment]
![161584598891_ pic_hd](https://user-images.githubusercontent.com/1373951/77037760-03321180-69ed-11ea-8499-a94e2a3a1ffb.jpg)

![181584598893_ pic_hd](https://user-images.githubusercontent.com/1373951/77037768-07f6c580-69ed-11ea-8202-2250ff0182a1.jpg)

![171584598892_ pic_hd](https://user-images.githubusercontent.com/1373951/77037773-0b8a4c80-69ed-11ea-8130-e1c10c61c15c.jpg)

**Comment by kcauchy** [comment]
@hyqhyq3 

教你一个简单判断是不是港独的办法：他如果说“中国人有劣根性，XXXX”，那他潜意识里就认为，自己是不是中国人。否则开头应该是“内地人/大陆人XXXX”。

还有，你问问他，割席不割席？大概他会回答：不割席。和伊斯兰极端分子一样，被发现了，永远说自己是温和的穆斯林。

希望你不要被港独蒙蔽了双眼。

**Comment by pagict** [comment]
discussion on political standpoint is not suggested at a tech forum

**Comment by supplicationXi** [comment]
加油猎巫!冲冲冲!
打倒他我就能坐上他的位置了!

**Comment by kcauchy** [comment]
@supplicationXi 我是P民不假，GFW也不会为我开放，可是你见过香港人拿锤子打大陆人么？

在香港人眼里，你连P民都没有资格，甚至连人都不算，你只是支那人。

你问问他：### 和暴徒割席不割席？不割席就不要假装温和派。假装温和是你们香港人的一惯逻辑

![191584599836_ pic_hd](https://user-images.githubusercontent.com/1373951/77038625-35dd0980-69ef-11ea-8b5e-00bdc79c3c6b.jpg)

![201584599853_ pic_hd](https://user-images.githubusercontent.com/1373951/77038635-3a092700-69ef-11ea-9714-769936e3940d.jpg)

**Comment by supplicationXi** [comment]
一切的起因是你主子死要面子抓桂敏海
到底是谁把香港人逼成这样的?
是你主子

**Comment by supplicationXi** [comment]
天天留岛不留人不是你们最喜欢做的事吗?
然后给外国人看到了不也是拿温和派中国人出来洗地吗?
"我是温和中国人,我和那些天天叫嚣着屠杀黑人穆斯林台湾人白人的中国人不一样"
和暴徒割席不割席？不割席就不要假装温和派。假装温和是你们的一惯逻辑

**Comment by kcauchy** [comment]
@supplicationXi 那我深刻理解了。就算杀光大陆人，香港人也在所不惜。

![image](https://user-images.githubusercontent.com/1373951/77038922-d29fa700-69ef-11ea-816e-df191921a588.png)

你们永远不会割席。

**Comment by supplicationXi** [comment]
@kcauchy 那我深刻理解了。就算杀光黑人穆斯林台湾人白人，你也在所不惜

**Comment by kcauchy** [comment]
@supplicationXi 拿着锤子的人，在这里说“留岛不留人”。

你倒是举个大陆人打香港人的例子？说不出来就别在这里喷。

**Comment by kcauchy** [comment]
@supplicationXi 大陆人抢劫了中国移动？大陆人放火烧了小米？

连登没有说过杀光大陆人？

你倒是举个例子，说大陆人留岛不留人啊。举啊

**Comment by kcauchy** [comment]
@supplicationXi 我们天天要“留岛不留人”，然后给你们把商铺烧了？然后你们还在这里说我们有暴力？

真是中外驰名双标。

![20191024042331650](https://user-images.githubusercontent.com/1373951/77039358-b819fd80-69f0-11ea-961b-54837b7aaca9.jpg)

**Comment by supplicationXi** [comment]
还是那句话,这一切的起因是你主子死要面子把桂敏海抓了
然后你主子指使了831
![image](https://user-images.githubusercontent.com/52769029/77039322-a5072d80-69f0-11ea-9159-f10e2109b4aa.png)
最后才发展成这样的
弄清楚前因后果

**Comment by supplicationXi** [comment]
你知道桂敏海是谁吗?哈哈

**Comment by supplicationXi** [comment]
小废物永远看不清楚前因后果,只觉得所有人都在欺负他, 所有人都是一瞬间变得暴力的

**Comment by supplicationXi** [comment]
你也不知道6月份之前的和平游行, 也不知道831是事情激化的起点

**Comment by supplicationXi** [comment]
想泼粪或者集体猎巫请到墙内去,别在技术社区脱粪

**Comment by kcauchy** [comment]
@supplicationXi 原来是一个看轮子新闻的人哦。

我先不讨论轮子新闻的真假先：

1. 图片里的人，跟大陆人有毛关系？
2. 图片里的人，跟小米有毛关系？
3. 怎么样才能解释，你们要打大陆人，要烧小米？

难道是因为你们的警察打人了，所以你就要烧大陆的商铺？因为共产党没批准831，所以要拿锤子打大陆人？所以要去烧小米？你们烧小米，打大陆人，为什么还要叫嚣大陆人“留岛不留人”？

不要逃避，正面解释为什么！

**我一句脏话没有，泼粪的可是你！真是中外驰名双标！**

**Comment by supplicationXi** [comment]
你说哪一条是轮子新闻?
这事的起点就是中联办的送中条例, 不怪你主子怪谁?

**Comment by supplicationXi** [comment]
至于为什么不骂党要把仇恨加到大陆人身上嘛..
是谁宣传党国不分来着?

**Comment by supplicationXi** [comment]
> 
> 
> @supplicationXi 原来是一个看轮子新闻的人哦。
> 
> 我先不讨论轮子新闻的真假先：
> 
>     1. 图片里的人，跟大陆人有毛关系？
> 
>     2. 图片里的人，跟小米有毛关系？
> 
>     3. 怎么样才能解释，你们要打大陆人，要烧小米？
> 
> 
> 难道是因为你们的警察打人了，所以你就要烧大陆的商铺？因为共产党没批准831，所以要拿锤子打大陆人？所以要去烧小米？你们烧小米，打大陆人，为什么还要叫嚣大陆人“留岛不留人”？
> 
> 不要逃避，正面解释为什么！
> 
> **我一句脏话没有，泼粪的可是你！真是中外驰名双标！**

 kcauchy opened this issue 2 hours ago · 22 comments

**Comment by kcauchy** [comment]
@supplicationXi 连大纪元都不知道是轮子的。可笑可笑。

正面回答啊：送中条例为什么导致你们烧小米？送中条例为什么导致你们拿锤子打大陆人？为什么你是们放火杀人，反而诬陷大陆人“留岛不留人”？

笑话，图片可是香港媒体拍的。

**Comment by supplicationXi** [comment]
831视频一搜一大堆,引用谁的不一样?

 这事的起点就是中联办的送中条例, 不怪你主子怪谁?

**Comment by supplicationXi** [comment]
你可能不会用搜索引擎?
我教你:打开youtube
搜索831事件
单击回车

**Comment by kcauchy** [comment]
@supplicationXi 请你正面回答：为什么共产党的送中条例有问题，你们就一定要放火烧小米？为什么共产党的送中条例有问题，你们就一定要拿锤子打大陆人？为什么共产党的送中条例有问题，你们就一定要放火烧小米，拿锤子打大陆人还要诬陷大陆人“留岛不留人”？

**Comment by kcauchy** [comment]
@supplicationXi 算了，可能你听不懂中文，我也懒得问了。

**Comment by supplicationXi** [comment]
> 
> 
> @supplicationXi 请你正面回答：为什么共产党的送中条例有问题，你们就一定要放火烧小米？为什么共产党的送中条例有问题，你们就一定要拿锤子打大陆人？为什么共产党的送中条例有问题，你们就一定要放火烧小米，拿锤子打大陆人还要诬陷大陆人“留岛不留人”？



至于为什么不骂党要把仇恨加到大陆人身上嘛..
是谁宣传党和人民不分来着?

**Comment by kcauchy** [comment]
@supplicationXi 哈哈哈哈哈哈哈哈。哈哈哈哈哈哈。哈哈哈哈哈哈。

> 至于为什么不骂党要把仇恨加到大陆人身上嘛..
> 是谁宣传党和人民不分来着?

好。各位。看清楚，看清楚。这句话，可不是我说的

**Comment by supplicationXi** [comment]
你主子天天在那人民=党=中国,当然就要接受这个宣传的后果

**Comment by supplicationXi** [comment]
> 
> 
> @supplicationXi 算了，可能你听不懂中文，我也懒得问了。

那我希望你删掉这个issue

**Comment by kcauchy** [comment]
@supplicationXi 

> 你主子天天在那人民=党=中国,当然就要接受这个宣传的后果

因为：人民=党=中国
所以：反对共产党 = 反对中国人
再可以推论下： 因为要支持自由 = 反对共产党

==> 因为要支持自由 = 所以反对中国人。

恭喜你，给Milo Yip做实了。

**Comment by supplicationXi** [comment]
> 
> 
> @supplicationXi
> 
> > 你主子天天在那人民=党=中国,当然就要接受这个宣传的后果
> 
> 因为：人民=党=中国
> 所以：反对共产党 = 反对中国人
> 再可以推论下： 因为要支持自由 = 反对共产党
> 
> ==> 因为要支持自由 = 所以反对中国人。
> 
> 恭喜你，给Milo Yip做实了。

自由在核心价值观里面
你不是中国人?不知道核心价值观?

**Comment by supplicationXi** [comment]
所以你为什么要到github来脱粪?
能请你把issue删掉吗?

**Comment by kcauchy** [comment]
@supplicationXi 恭喜你，你成功证明了，Milo Yip是港独。至于港独独不对，和我无关。而且按照你的逻辑，因为党=人民，那么香港人自动的站到了所有中国人的对立面。

谢谢哦。我左右不了腾讯，也扒不了他的全家信息。而且，嘴巴也不如你臭。

**Comment by supplicationXi** [comment]
哈哈, 香港只要不支持你主子的都是独立分子
你知道泛民是什么吗?

**Comment by kcauchy** [comment]
@supplicationXi 知道，写“蓝丝于狗不得入内”的那两个，还有一个智商只有70，考试考0分的。

**Comment by supplicationXi** [comment]
你主子初中没毕业,半斤八两

**Comment by supplicationXi** [comment]
你到现在也不想把这个issue删掉,到底是为了和我争个输赢呢, 还是想恶心其他人呢?

**Comment by kcauchy** [comment]
@supplicationXi 顺便一提，这是bbc报道的。bbc的口味挺符合你们的。

**Comment by pagict** [comment]
discussion on political standpoint is not suggested at a tech forum. i will close this issue for now.

技术社区不建议讨论政治立场，我先把该issue关闭了。

**Comment by microcai** [comment]
马化腾就是港独份子, 没毛病.

**Comment by microcai** [comment]
> ![image](https://user-images.githubusercontent.com/1583343/77037316-08429100-69ec-11ea-884c-06a6a3b69c62.png)
> 希望大家理性看待，不要随意被人带了节奏，是真是假自己先判断一下再发言

他只是墙内墙外使用不同的语言发了截然不同的言论而已啊.... 类似台湾某人被中国撤侨说自己是中国人 回到台湾说自己是被逼的.

**Comment by microcai** [comment]
而且 Miloy 说的是他参加的是受香港政府批准的反中游行.... 香港政府批准的反中, 能叫反中吗?

**Comment by NinjaMoon** [comment]
小朋友你还是把这个贴子删除，经风记委员会员建议给你打码了，因为发现你竟然是个女生所以而且在武汉，这不是你玩的地方，删贴吧


李吉婷 #已经实名验证
微博:https://www.weibo.com/u/390××××056
手机:15172441××2
地区:湖北省武汉市黄陂区××阳街
https://github.com/kcauchy
https://twitter.com/karlcauchy
karl@cauchies.org
kar×××××hy@gmail.com

**Comment by karlcauchyy** [comment]
小朋友你还是把这个贴子删除，经风记委员会员建议给你打码了，因为发现你竟然是个女生所以而且在武汉，这不是你玩的地方，删贴吧


李吉婷 #已经实名验证
微博:https://www.weibo.com/u/390××××056
手机:15172441××2
地区:湖北省武汉市黄陂区××阳街
https://github.com/kcauchy
https://twitter.com/karlcauchy
karl@cauchies.org
kar×××××hy@gmail.com

**Comment by kcauchy** [comment]
@karlcauchyy 开小号过来炫耀要扒光我么？抱歉，这个名字不是我的。而且我不住在武汉。

**Comment by karlcauchyy** [comment]
> @karlcauchyy 开小号过来炫耀要扒光我么？抱歉，这个名字不是我的。而且我不住在武汉。

给你脸不要脸，是不是那就让大家都看看

**Comment by kcauchy** [comment]
@karlcauchyy 我明白了。这就是腾讯的一贯作风对么？我的确势单力薄。厉害厉害。

**Comment by kcauchy** [comment]
@karlcauchyy 而且，你是第一天玩Github么？不知道Github非项目管理员无法删issue么？

**Comment by karlcauchyy** [comment]
周同学你明白什么，你用你女朋友的信息顶包？

**Comment by kcauchy** [comment]
@karlcauchyy 我知道你们已经获取了全部的我的个人信息。但是我删不了issue。请你明白。

**Comment by kcauchy** [comment]
@karlcauchyy 你应该找管理员。我没有这个权限。

**Comment by karlcauchyy** [comment]
小朋友你还是把这个贴子删除，经风记委员会员建议给再次你打码。

周×乔
深圳市宇称科技有限责任公司
电话：18682281××0
邮箱：yu.xiaoqiu@foxmail.com
地址：深圳市前海深港合作区前湾一路1号×栋×01室
https://github.com/kcauchy
https://twitter.com/karlcauchy
karl@cauchies.org
karlcauchy@gmail.com
关联域名
cauchies.cn
ivyc.work
xisca.trade
xisca.work

周希乔的gmail用的下面的女生信息应该是他的相关联系人
李吉婷
微博:https://www.weibo.com/u/3902155056
手机:15172441772
地区:湖北省武汉市黄陂区石阳街

**Comment by kcauchy** [comment]
@karlcauchyy 我真的不会删除这个帖子，我没找到在哪里删。

**Comment by kcauchy** [comment]
@karlcauchyy 不如您帮帮我？我看了很多教程也没找到删除的地方。。。。

**Comment by microcai** [comment]
除非你不使用wechat 否则你必然会很容易被腾讯人肉出来的啦!

**Comment by gnaggnoyil** [comment]
@ghost 被出道了就车软了?我恶意地提醒你一句在github上讨论政治问题是几乎不会有一个具有明显偏好的第三方对言论按照其偏好进行控制的,所以你最好在此前提下重新审视你发言的有效性和煽动性,否则你不会给我们这些翻墙上github的夜蝶们带来任何笋丝.

**Comment by garypang13** [comment]
大快人心,哈哈,粉蛆真是无孔不入,被曝了就知道求饶了,

**Comment by chen3feng** [comment]
> @hyqhyq3
> 
> 教你一个简单判断是不是港独的办法：他如果说“中国人有劣根性，XXXX”，那他潜意识里就认为，自己是不是中国人。否则开头应该是“内地人/大陆人XXXX”。
> 
> 还有，你问问他，割席不割席？大概他会回答：不割席。和伊斯兰极端分子一样，被发现了，永远说自己是温和的穆斯林。
> 
> 希望你不要被港独蒙蔽了双眼。

说“中国人”要看语境，原作者是中国院士，没有证据证明他不认可自己是中国人。要是说大陆人劣根性，那才是妥妥的歧视呢

**Comment by huopd** [comment]
这是港独？独尼玛了个逼，弱智东西

**Comment by fnrandom** [comment]
@chen3feng 我感觉这里有个问题。如果中国人需要为中国政府的行为负责的话，这个想法是不是有点太极端了。如果是这样的话，那ISIS烧死美国人也是对的咯。

另外，Milo大在知乎上真的有那么一点那啥，有一些帖子对于自己的国家认可是非常模糊的。

**Comment by fnrandom** [comment]
@chen3feng 大部分大陆人其实都不反感8月份之前的游行。之后就变成了对大陆人的整体攻击了。尤其是我看有一次游行，全程高喊Free Tibet，Free Urgurs，我心里很不是滋味。你们要五大诉求，一定要肢解大陆么？举着美国国旗到美国大使馆要求美国制裁中国。

**Comment by garypang13** [comment]
> @chen3feng 大部分大陆人其实都不反感8月份之前的游行。之后就变成了对大陆人的整体攻击了。尤其是我看有一次游行，全程高喊Free Tibet，Free Urgurs，我心里很不是滋味。你们要五大诉求，一定要肢解大陆么？举着美国国旗到美国大使馆要求美国制裁中国。

Free Tibet，Free Urgurs 怎么了,台湾和你大陆有半毛钱关系吗?你天天跟人说林志玲是你老婆,林志玲就是你老婆了吗?你敢碰一下吗? 支共对新疆穆斯林关进集中营,丧心病狂的打压人权,难道不值得free吗?

**Comment by fnrandom** [comment]
@garypang13 Tibet不是西藏么？

**Comment by garypang13** [comment]
> @garypang13 Tibet不是西藏么？

认错单词了...
我想说的是,中国人并不无辜,国内封闭的信息环境是个反智思潮的天然炼蛊皿,大部分中国人都成了粉蛆,民族主义,法西斯主义极端分子,反智怪物, 人肉,举报,戴高帽,批斗,喊打喊杀,无所不用其极,每次看国内的东西我都感到深深的恐惧与寒意,只想早日远离这片被诅咒的土地.

**Comment by fnrandom** [comment]
@garypang13 那你大概没看过连登。。。连登上基本上没有低于杀人的。。。全部都要求杀光大陆人。。。

**Comment by chen3feng** [comment]
> @chen3feng 我感觉这里有个问题。如果中国人需要为中国政府的行为负责的话，这个想法是不是有点太极端了。如果是这样的话，那ISIS烧死美国人也是对的咯。
> 
> 另外，Milo大在知乎上真的有那么一点那啥，有一些帖子对于自己的国家认可是非常模糊的。

确实有些，但是同样的话，内地人说就是自省反省，香港人说就被理解成攻击。是不是说明很多内地人还没把香港人当成中国人，而过于玻璃心了呢？

至于 milo，我看了一些他的文字，感觉他对国家民族认同没什么问题，不过显然对内地以至于占中后的香港政府不认同。

香港显然有一些极端分子，不但仇恨内地政府，还扩大到了仇恨内地人民。但是没有证据证明 milo 是这样的人。

**Comment by chen3feng** [comment]
> @chen3feng 大部分大陆人其实都不反感8月份之前的游行。之后就变成了对大陆人的整体攻击了。尤其是我看有一次游行，全程高喊Free Tibet，Free Urgurs，我心里很不是滋味。你们要五大诉求，一定要肢解大陆么？举着美国国旗到美国大使馆要求美国制裁中国。

有证据证明 milo 参加过以“港独”为核心诉求的游行吗？我知道后期游行里诉求港独的人逐渐增多，即使他参加了，就能证明 milo 个人是港独，暴徒，而加以指责吗？

**Comment by fnrandom** [comment]
@chen3feng 就是因为经常翻墙关心香港的事情，所以才会有如此感慨啊。

例如，我上面举例的例子，游行人数高达数十万众。但反过来，支持一国两制的人出来游行，只有寥寥数百人。早期还有反对暴力的游行，后期则完全没有了。

区议会选举，几乎所有的选区，都是泛民获胜，甚至完全不考虑服务社区，只考虑政治立场选出了个别连BBC都颇为震惊的候选人。

我们天天喊“香港同胞”，“台湾同胞”，国台办，港澳办持续不断的惠台、惠港，就算不寄希望他们投桃报李，但也不希望他们这么敌视我们吧。

如果你今天去到香港，绝大部分港人的态度，都是支持年轻人的政治诉求，对于极端行为，则大部分以”不懂事“带过。可想而知，整个香港的人民态度，已经是”我虽然讨厌暴力，但我更讨厌你们“。

我们并没有努力想让香港同胞认为我们是敌人，但是最后的结果就是这样。支持23条立法的何君尧，在整个香港几乎给所有港人唾骂；推动逃犯条例的民建联主席，最后也得反过来支持停止立法，前后态度完全不一，可见香港的社会舆论压力对她来说有多大。

结合到近期疫情，有多少香港人还在叫”武汉肺炎“，”中国肺炎“，哪怕几乎全部的新闻媒体都已经改口叫”新冠肺炎“，批评政府瞒报、谎报，封城没有民主、自由，部分新闻媒体天天报道武汉的惨状，大量医护人员罢工要求全面封关。恐怕大部分港人都认为全面封关是对的吧。我们承认武汉我们初期做的不好，尤其是居家隔离这一政策造成了大量悲剧；但是如今国内外疫情形势反转，却完全听不到香港媒体对意大利惨状的报道，对美国lock down的批评，也没有医护再次上街要求全面对外封关。

今天的香港，我认为并不如您所说的分裂。具体的政治诉求各有区别不假，但”五大诉求，缺一不可“，”反共反中“这个核心诉求，几乎得到了全体港人的一致认可。在这个前提下，几乎全体港人，都不会去做”割席“之事，而从各个方面去支持小部分勇武派。例如，理大围城之时，大量香港人，是真的在外围默默支持里面被围的学生，自发地想要帮助他们。

王洪光将军说：“如果有70%-80%的人都反对你，那就是我们的敌人，不要搞错了“。将军的话有些激进，但可以确定的是，不是我们要当香港人的敌人，是香港人想要当我们的敌人，至少，不愿意做我们的朋友；不止是政府，还包括大陆的人民。

**Comment by fnrandom** [comment]
@chen3feng Milo大技术水平确实高超，我也很尊敬他。我相信大陆大部分人也不反对他们和平示威。

这么多人攻击楼主，说“因为党宣传人民和党一体”，所以可以打大陆人；我看了真的不寒而栗。这是身份的问题，大陆人出生在大陆，所以就该被打，我认为这个逻辑是不通的。大陆人并没有表明自己的政治立场，就遭受到暴力攻击，这是“身份犯罪“，往重了说，这是法西斯行为。

相反，我们大陆人之所以生气，也是因为，大部分港人“不割席”，自己选择了站在暴力犯罪的一边，而绝不是他仅仅是香港人。我认为，如果游行最后发展到暴力示威的阶段，那么和平示威者必须要出来说，我们和他们是不一样的。否则我认为和平示威者是有责任的。即便不是主动参与这么重，但也是在默许、纵容。而在“国家”这个问题上，显然讨论余地就不那么大了。

同样，如果叶大的言论是反对逃犯条例，但是支持一个中国，反对暴力示威，我相信大部分大陆人都没有任何意见。但显然，这是我们一厢情愿。香港人普遍，还是对大陆人有些”优越感“，不然也不会说”中国人的劣根性“导致了新冠肺炎，也不会仍然使用”武汉肺炎“这一WHO所反对的带有歧视性的称呼了。

**Comment by swanf** [comment]
> > @chen3feng 大部分大陆人其实都不反感8月份之前的游行。之后就变成了对大陆人的整体攻击了。尤其是我看有一次游行，全程高喊Free Tibet，Free Urgurs，我心里很不是滋味。你们要五大诉求，一定要肢解大陆么？举着美国国旗到美国大使馆要求美国制裁中国。
> 
> Free Tibet，Free Urgurs 怎么了,台湾和你大陆有半毛钱关系吗?你天天跟人说林志玲是你老婆,林志玲就是你老婆了吗?你敢碰一下吗? 支共对新疆穆斯林关进集中营,丧心病狂的打压人权,难道不值得free吗?
> 天天抱着支共给你们灌输的大一统毒瘤思想危害人类

台湾和大陆为啥没关系？说白了台湾就是明码标价的一块地和上面的肉，国际市场上的一件商品而已。台湾的军事价值是要远远大于经济价值，打下来就是你的。

当然，商业媒体荒腔走板，自由民拳打倒一切，品葱少年一身热血不得志啊。劝你少看点大纪元、新唐人、毒苹果、文昭、石涛、王剑 、江峰、天亮时分、年代向钱看、张林、郭文贵系列节目、stone、sydney dad、Free Asia,、China Uncensored、老外看中国、BBC中文版、VOA美国之音中文版、CNN中文版，出国了我看了这些玩意就想觉得中国不容易，本来反共的我都直接被整成自干五了。

**Comment by microcai** [comment]
西方媒体就伟大公正客观了? 以前这么认为还算是情有可原.....

**Comment by microcai** [comment]
明镜周刊: 只有自由和民主才能抵抗新冠肺炎.

**Comment by huopd** [comment]
楼上这么喜欢独裁去朝鲜吧

**Comment by li9080** [comment]
@garypang13 麻烦你再说一遍？

> Free Tibet，Free Urgurs 怎么了,台湾和你大陆有半毛钱关系吗?你天天跟人说林志玲是你老婆,林志玲就是你老婆了吗?你敢碰一下吗? 支共对新疆穆斯林关进集中营,丧心病狂的打压人权,难道不值得free吗?
天天抱着支共给你们灌输的大一统毒瘤思想危害人类

不要退缩，再说一次。

> 第二十条　任何人组织、策划、实施或者参与实施以下旨在分裂国家、破坏国家统一行为之一的，不论是否使用武力或者以武力相威胁，即属犯罪：
> （一）将香港特别行政区或者中华人民共和国其他任何部分从中华人民共和国分离出去；
> （二）非法改变香港特别行政区或者中华人民共和国其他任何部分的法律地位；
> （三）将香港特别行政区或者中华人民共和国其他任何部分转归外国统治。
> 犯前款罪，对首要分子或者罪行重大的，处无期徒刑或者十年以上有期徒刑；对积极参加的，处三年以上十年以下有期徒刑；对其他参加的，处三年以下有期徒刑、拘役或者管制。


> 第三十六条　任何人在香港特别行政区内实施本法规定的犯罪的，适用本法。犯罪的行为或者结果有一项发生在香港特别行政区内的，就认为是在香港特别行政区内犯罪。
在香港特别行政区注册的船舶或者航空器内实施本法规定的犯罪的，也适用本法。
第三十七条　香港特别行政区永久性居民或者在香港特别行政区成立的公司、团体等法人或者非法人组织在香港特别行政区以外实施本法规定的犯罪的，适用本法。
第三十八条　不具有香港特别行政区永久性居民身份的人在香港特别行政区以外针对香港特别行政区实施本法规定的犯罪的，适用本法。

**Comment by li9080** [comment]
@chen3feng 和李铭柱一样，自己做了事不愿意去承担后果。发一个声明说自己是“一国两制的坚定支持者”。要证据是司法机关的事情，上面列了那么多图片，对于我们吃瓜群众来说，哪一条不是违反国安法的铁证？你敢说@miloyip 回到香港和朋友面前，还是“一国两制的坚定支持者”吗？

法律是不朔及既往了，中国人可是记着的。

**Comment by tianly123** [comment]
真的牛皮

**Comment by lsp0086** [comment]
6666

**Comment by FanJingDou** [comment]
> 加油猎巫！冲冲冲！ 可惜你猎了多少人GFW也不会为你开放，你还是P民

急急急，咋地你也是咯，你是港毒台毒还是藏毒，又或者是？

**Comment by FanJingDou** [comment]
> [@chen3feng](https://github.com/chen3feng)大部分大陆人其实都没有反感8月份的游行。之后就变成了对大陆人的攻击了。尤其是我看有一次游行，全程高喊自由西藏，自由乌尔古尔，我心里很不是滋味。你们要五大诉求，一定要肢解大陆么？举着美国国旗到美国游行要求美国制裁中国。

经典你看到 我看到的是你这种毒不敢走在街上因为让人知道了会被直接打死
