### ISSUE TITLE
修改复杂结构的json报文时，报错Type错误？

### ISSUE THREAD

**Issue by panyfx** [Tencent/rapidjson#1671]
有类似如下的复杂嵌套json报文，需动态修改json doc对象。
{
    "root":{
        "query":{
            "bool":{
                "items":[
                    "obj1":{

                    },
                    "obj2":{

                    }
                    ,
                    "obj3":{

                    },
                    "obj4":{
                        "subObj":{

                        }
                    }
                ]               

            }
        }
    }
}
比如这里修改items这个array里，obj4这个对象。会出现编译问题。
auto* items = rapidjson::GetValueByPointer(doc, "/root/query/bool/items");

auto obj4 = items->GetArray()[items->Size() - 1]["obj4"]
 rapidjson::Value temp(rapidjson::kObjectType);
 temp.CopyFrom(other, doc.GetAllocator());
obj4.AddMember(itemString.c_str(), temp.Move(), doc.GetAllocator());

rapidjson/document.h:1420:5: error: no type named ‘Type’ in ‘struct rapidjson::internal::DisableIf<rapidjson::internal::OrExpr<rapidjson::internal::IsPointer<rapidjson::GenericValue<rapidjson::UTF8<> > >, rapidjson::internal::IsGenericValue<rapidjson::GenericValue<rapidjson::UTF8<> > > >, rapidjson::GenericValue<rapidjson::UTF8<> >&>’

看错误可能是obj4的类型没有确定出来。请问这样场景支持吗，我看示例里没有找到这样 的示例。

**Comment by miloyip** [comment]
能不能给一个简单、完整、独立能重现的代码？

**Comment by panyfx** [comment]
// Hello World example
// This example shows basic usage of DOM-style API.

#include "rapidjson/document.h"     // rapidjson's DOM-style API
#include "rapidjson/prettywriter.h" // for stringify JSON
#include "rapidjson/pointer.h"
#include <rapidjson/istreamwrapper.h>
#include <rapidjson/stringbuffer.h>
#include <rapidjson/writer.h>
#include <rapidjson/rapidjson.h>
#include <rapidjson/allocators.h>
#include <cstdio>

#include<iostream>
#include<string>

// g++ --std=c++11 test.cpp  -o mytest -I./include

using namespace rapidjson;
using namespace std;

int main(int, char*[]) {
    ////////////////////////////////////////////////////////////////////////////
    // 1. Parse a JSON text string to a document.

    const char json[] = " { \"hello\" : \"world\", \"t\" : true , \"f\" : false, \"n\": null, \"i\":123, \"pi\": 3.1416, \"a\":[1, 2, 3, 4] } ";
    const char docJson[] = "{\"root\": {\"query\": {\"bool\": {\"items\": [{\"obj1\": {}},{\"obj2\": {}},{\"obj3\": {}},{\"obj4\": {\"subObj\": {}}}]}}}}";
	Document doc;
	doc.Parse(docJson);
    if (doc.HasParseError()) {
        
		printf("parse docJson error\n");
		std::cout << doc.GetParseError();
        return false;
    }
	Document other;
	other.Parse(json);
    if (other.HasParseError()) {
        printf("parse json error\n");
		std::cout << other.GetParseError();
        return false;
    }
   auto* items = rapidjson::GetValueByPointer(doc, "/root/query/bool/items");
   auto& obj4 = items->GetArray()[items->Size() - 1]["obj4"]["subObj"];
   rapidjson::Value temp(rapidjson::kObjectType);
   temp.CopyFrom(other, doc.GetAllocator());
   std::string otherKey = "other";
   obj4.AddMember(otherKey.c_str(), temp.Move(), doc.GetAllocator());
   
   rapidjson::StringBuffer bufferjson2;
     rapidjson::Writer<rapidjson::StringBuffer> writerjson(bufferjson2);
     doc.Accept(writerjson);
   printf( bufferjson2.GetString());
   
    return 0;
}

**Comment by panyfx** [comment]
otherKey.c_str() 这个不能这么用。问题原因应该是在这里。
