### ISSUE TITLE
Parsing an array of objects with RapidJSON

### ISSUE THREAD

**Issue by Davidowu** [Tencent/rapidjson#1674]
I'm facing a problem with parsing a JSON file via RapidJSON and loading its contents into attributes of objects which I created in my program (a card game). The JSON file contains two types of Cards - Creature and Spellcards - each of which have attributes assigned to them.

```
bool loadConfig(std::string config_file){

    std::ifstream ifs(config_file);
    rapidjson::IStreamWrapper isw(ifs);
    rapidjson::Document file;
    file.ParseStream(isw);

    assert(file.IsObject());
    assert(file.HasMember("Creatures"));
    assert(file["Creatures"].IsString());
    printf("Name: %s\n", file["Creatures"].GetString());

    return true;
}
```

The function I am working with gets its string from a command line argument. I have tried using IStreamwrapper to get rapidJSON to start parsing, but i am getting the Error Message "Assertion `file["Creatures"].IsString()' failed"`. 

This is the config file I am working with.

```
{
  "Creatures" : [
    {
      "name": "Big Wall",
      "mana_cost": 7,
      "damage_points": 2,
      "life_points": 9,
      "shield": true,
      "mana_drain": false
    },
    {
      "name": "Werwolf",
      "mana_cost": 13,
      "damage_points": 9,
      "life_points": 6,
      "shield": false,
      "mana_drain": false
    }
  ],
  "Spells" : [
    {
      "name": "Healer"
    },
    {
      "name": "Relief"
    },
    {
      "name": "Rebirth"
    },
    {
      "name": "Dracula"
    }
  ]
}
```

I used "file.HasParesError" and it returned true and "file.GetType" also returned Null. Could the problem be that I am dealing with two arrays in one json file? If so, what would be the best way to go about to solve this problem?

**Comment by miloyip** [comment]
"Creatures" is an array...
