### ISSUE TITLE
Has WriteString in writer.h deal with the length correctly for the last branch? 

### ISSUE THREAD

**Issue by raymondnuaa** [Tencent/rapidjson#1681]
For the following function in writer.h , there are two lines to reserve the stack size.

But for the last branch, save we have same input and output encoding, the stack size to be reserved should be **2 + length*1**

Please check if there is issue. Thanks!

bool WriteString(const Ch* str, SizeType length)  {
        ..........
        if (TargetEncoding::supportUnicode)
            PutReserve(*os_, 2 + length * 6); // "\uxxxx..."
        else
            PutReserve(*os_, 2 + length * 12);  // "\uxxxx\uyyyy..."
       ............
       else if (RAPIDJSON_UNLIKELY(!(writeFlags & kWriteValidateEncodingFlag ? 
                Transcoder<SourceEncoding, TargetEncoding>::Validate(is, *os_) :
                Transcoder<SourceEncoding, TargetEncoding>::TranscodeUnsafe(is, *os_))))
                return false;
        .............
}

**Comment by miloyip** [comment]
I cannot really understand your question. Can you explain further?

**Comment by raymondnuaa** [comment]
Thanks for your quick reply :-) 

There are lines to reserve the stack size: 
PutReserve(*os_, 2 + length * 6); // "\uxxxx..."
PutReserve(*os_, 2 + length * 12); // "\uxxxx\uyyyy..."

But for the last code branch, say the output and input have same encoding.
Then the line :
Transcoder<SourceEncoding, TargetEncoding>::TranscodeUnsafe(is, *os_))))
is just doing the following work:
 os.Put(is.Take());  (I've read your article at zhihu which mentioned this also)

So for this case, the stack size reservation which should be not correct.
It should be 
PutReserve(*os_, 2 + length * 1); //same length but plus two for the quote mark

Please help to confirm if it is a issue. Thanks!
(In my test, I need to change the code to make it work)

**Comment by miloyip** [comment]
Even if the encoding are the same, some characters needed to be escaped as `\uxxxx`.

**Comment by raymondnuaa** [comment]
Thank you for your explanation! 
I think I misunderstood the PutReserve, it is just to expand the stack and it does not need to be exact same with the count that to be used during the write operation.
