### ISSUE TITLE
#DEN

### ISSUE THREAD

**Issue by sdtacrc** [Tencent/rapidjson#1682]
Document document;
double dValue = 1.744e-039#DEN;
document.AddMember("Value", dValue , document.GetAllocator());
StringBuffer strBuffer;  
Writer<StringBuffer> writer(strBuffer);  
document.Accept(writer);  
string str =  strBuffer.GetString();
---------------------
The result "str " has substring "#DEN", How to avoid it???

**Comment by miloyip** [comment]
What compiler are you using?
Since `#DEN` seems not a standard C++ syntax and I cannot reproduce the problem.

**Comment by sdtacrc** [comment]
It may not be "#DEN", or something else.
for example:
Document document;
double a = 0.0;
double dVlaue = 1.0/a;
document.AddMember("Value", dValue , document.GetAllocator());
StringBuffer strBuffer;
Writer writer(strBuffer);
document.Accept(writer);
string str = strBuffer.GetString();


then something went wrong when I try to parse "str".










At 2020-04-02 10:00:23, "Milo Yip" <notifications@github.com> wrote:

What compiler are you using?
Since #DEN seems not a standard C++ syntax and I cannot reproduce the problem.

**Comment by miloyip** [comment]
For +/-inf, `document.Accpet(writer)` should return `false`, indicating an error during stringifying the JSON.

**Comment by miloyip** [comment]
There is `kWriteNanAndInfFlag` for `Writer` to use relaxed JSON syntax.
And similiarly `kParseNanAndInfFlag` for parsing.
