### ISSUE TITLE
Failed to parse a valid json string, which has right escaped character, and error code is 11.

### ISSUE THREAD

**Issue by panyfx** [Tencent/rapidjson#1690]
#include <rapidjson/document.h>
#include <rapidjson/istreamwrapper.h>
#include "rapidjson/stringbuffer.h"
#include "rapidjson/writer.h"
#include<rapidjson/pointer.h>
#include<iostream>

int main(){
    
    
    std::string badStr = "{\"test\":{\"sub\":\"\\\"}}";
    rapidjson::Document djsonbad;
    djsonbad.Parse(badStr.c_str(),badStr.length());
    if (djsonbad.HasParseError()) {
        std::cout << "Failed to parse json string, pidjson::ParseErrorCode code =" << djsonbad.GetParseError() << ", jsonStr is :" << badStr << std::endl;
        
    }
    else{
        std::cout << "Good" << std::endl;
    }
    
}

**Comment by miloyip** [comment]
`{"test":{"sub":"\"}}` is not a valid JSON.

**Comment by panyfx** [comment]
{"test":{"sub":"\"}} is invalid, but badStr  is valid, '\'  is escaped .

**Comment by miloyip** [comment]
You try `std::cout << badStr;`.

**Comment by panyfx** [comment]
I had tried with jsoncpp,  Failed.
thank you.
