### ISSUE TITLE
Can't Parse Valid JSON (IsObject() / IsArray() assertion failed)

### ISSUE THREAD

**Issue by LeviHarrison** [Tencent/rapidjson#1695]
Hi there, I'm having a little trouble parsing some JSON returned by a CURL API call. 
```
#include "import.h"
#include <iostream>
#include "rapidjson/document.h"
#include "rapidjson/reader.h"
#include <curl/curl.h>
using namespace import;
using namespace std;
using namespace rapidjson;

const char* import::makerequest() {
    CURL *curl;
    curl = curl_easy_init();
    string rawoutput;
    const char* json;
    if(curl) {
    curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, "POST");
    curl_easy_setopt(curl, CURLOPT_URL, "CENSORED");
    curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);
    curl_easy_setopt(curl, CURLOPT_DEFAULT_PROTOCOL, "https");
    struct curl_slist *headers = NULL;
    headers = curl_slist_append(headers, "Content-Type: application/json");
    curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
    const char *data = "{CENSORED}";
    curl_easy_setopt(curl, CURLOPT_POSTFIELDS, data);
    rawoutput = curl_easy_perform(curl);
    json = rawoutput.c_str();
    curl_easy_cleanup(curl);
    return json;
    }
}

void import::parseresponse() {
    const char* json = makerequest();
    Document document;
    document.Parse(json);
    cout << document["Token"].GetString() << endl;
}
```
The JSON returned by the API call looks something like this: `{"Token":"878sdad-1938ndns-82ahh82-jsf8sa","TokenId":0,"UserId":391732}`, which is then converted into a const char* and returned to the parseresponse() function. When this is run it returns this error: `Assertion failed: IsArray(), file C:\CENSORED_PATH\include\rapidjson\document.h, line 1253`. When I try to assert IsObject() in the code like this:
```
void import::parseresponse() {
    const char* json = makerequest();
    Document document;
    document.Parse(json);
    assert(document.IsObject());
    cout << document["Token"].GetString() << endl;
}
```
Same thing happens. Any suggestions?

**Comment by fredgan** [comment]
If the returned JSON is what you described, rapidjson should not report this error.

You'd better print the json string first before you parse it so that you can confirm what happened.

**Comment by LeviHarrison** [comment]
Even though it isn’t showed here, rawoutput is printed in the console, which reveals that JSON..

**Comment by fredgan** [comment]
Hi Levi,
From your console output, It doesn't meet the latest release version or latest master version. Which version are you using?

**Comment by LeviHarrison** [comment]
Just pulled from master, same error

**Comment by PunitSalian** [comment]
@LeviHarrison  is this fixed ?

**Comment by LeviHarrison** [comment]
At this point I’ve moved on from rapidjson, so I’m not sure. After looking more closely though, I think the problem lies with C++ itself, in which “ and : are considered special characters when in strings. To combat the you need to either format the string in a special way. The string CURL gives me isn’t in one of those formats, and the parser won’t accept it. I can’t find anyway to programmatically format it, so that is that.

**Comment by miloyip** [comment]
I think your code shown above is errornous that, `json` in `makerequest()` points to a buffer which may have been destructed after `rawoutput` is destructed. You can return `rawoutput` instead and do `c_str()` outside.

Also, since the json return may not be always in the format you think, you may need to check whether the parse is success, the root is object, the token member exists, the token value is a string, etc.

**Comment by ThomasP1988** [comment]
i think rawoutput = curl_easy_perform(curl); doesnt return json, you might have to write a CURLOPT_WRITEFUNCTION.
 (https://stackoverflow.com/questions/9786150/save-curl-content-result-into-a-string-in-c)
(https://curl.haxx.se/libcurl/c/curl_easy_perform.html)
