### ISSUE TITLE
Passing an rapidjson array or object as a parameter

### ISSUE THREAD

**Issue by UdayKrishnan** [Tencent/rapidjson#1697]
Is it possible to pass a rapidjson array or object as a parameter type, to allow for method overloading based on rapidjson types ?.

**Comment by miloyip** [comment]
I cannot really understand your question. Please show some code example.

**Comment by UdayKrishnan** [comment]
Normally signatures look like some_method_1(rapidjson::Value& value), on value obj there are IsXXX and GetXXX methods that API provides, I was wondering if below was possible, so dynamic polymorphism can take place based on value types, so if the value were an array, a method that takes an array would be invoked, for e.g

over_loaded_method(val.FindMember("key")->value) , would invoke over_loaded_method with an array type as parameter, if val.FindMember("key")->value was an array, or would invoke the same over_loaded_method with object type as parameter  if val.FindMember("key")->value was an object.

**Comment by miloyip** [comment]
How about using `Value::Array`, `Value::Object`, etc.? But this is done by static binding:

~~~cpp
void someMethod(Value::Array& a);
void someMethod(Value::Object& o);

someMethod(doc["items"].GetArray());
someMethod(doc["address"].GetObject());
~~~

For dynamic polymorphism, you will need to do dispatch. `Value::Accept` use visitor pattern to do dispatching, and the visitor class can be polymorphic if needed.
