### ISSUE TITLE
建议能通过[]运算符动态添加属性，以及通过重载<<运算符动态添加数组元素

### ISSUE THREAD

**Issue by ALittleDruid** [Tencent/rapidjson#1708]
`    Document d(kObjectType);

    d.AddMember("key", "value", d.GetAllocator());

    d["str1"] = "123";
    d["real1"] = 45.6;
    d["int1"] = 789;
    d["str2"] = "中文测试";

    Value obj(kObjectType);
    obj["str1"] = "o123";
    obj["real"] = 45.7;
    obj["str2"] = "测试";
    d["obj"] = obj;

    Value arr(kArrayType);
    arr << "1" << "2" << 3 /*<< anotherobj << anotherArr*/;
    d["arr"] = arr;

    StringBuffer buffer;
    Writer<StringBuffer> writer(buffer);
    d.Accept(writer);

    std::cout << buffer.GetString() << std::endl;`

第二行是正确用法，期待下面的写法也能够得到支持
是否考虑内部去维护allocator_，不要暴露给使用者比较好

**Comment by miloyip** [comment]
内部维护要增加内存，在 1.x 的 API 设计里不会作修改。
可考虑使用 `Pointer` 的 API。
