### ISSUE TITLE
SchemaDocument Crashes in High Load and Multi Threaded Mode

### ISSUE THREAD

**Issue by mohsenomidi** [Tencent/rapidjson#1709]
Dears, 

I am currently using RapidJson Schema validator, all incomming messages gets from network with http server and after that it passes to the validator. in normal load everything works fine but in high load my app just crashes with error below :
`
/usr/local/include/rapidjson/internal/stack.h:152: const T* rapidjson::internal::Stack<Allocator>::Top() const [with T = rapidjson::internal::SchemaValidationContext<rapidjson::GenericSchemaDocument<rapidjson::GenericValue<rapidjson::UTF8<> > > >; Allocator = rapidjson::CrtAllocator]: Assertion `GetSize() >= sizeof(T)' failed.

`
the usage is in multi thread mode with high load. 

any advise ?

**Comment by miloyip** [comment]
I am unsure about your situation but the validator cannot be executed by different threads at the asme time. Try to have a separated schema validator per thread.

**Comment by mohsenomidi** [comment]
Dear @miloyip 

Thanks for your response, we are completely on same page, I currently use an internal http server (we developed internally) and for our client side connections we should use schema validator to ensure our receiving json is valid before parsing, therefore the only way is this
In this example the threads created by our http server and rapidjson dose not know about threads, the management for validator in multi thread situation is difficult but possible, and if there is no way for it we will do it.
But it is very nice if the SchemaObject and Validator will be thread safe.
Would you please think about it and feedback

Best Regards,
