### ISSUE TITLE
api change?

### ISSUE THREAD

**Issue by lianghongzhuo** [Tencent/rapidjson#1712]
Hi, I encounter a usage problem in different rapidjson versions.
One code can compile at the current master rapidjson version but cannot compile on the version installed using `apt-get` which is version `1.1.0`

But when changed the code to a different direction, I can build through it using v1.1.0 rapidjson.
The code I changed can be found here: https://github.com/lianghongzhuo/openrave/commit/d1cb154d2c75bd27164405b5486795e8297d95b1
Before I change the code, only can work on the master rapidjson, after the change, can work on v1.1.0.
Any explanation will be appreciated. Thank you!

**Comment by miloyip** [comment]
I remember there is a relaxation of `Swap` for `Value` and `Document` after v1.1.0.

**Comment by lianghongzhuo** [comment]
Thank you for your reply, I think I can close this issues now.
