### ISSUE TITLE
Getting the wrong size for large arrays

### ISSUE THREAD

**Issue by fwsGonzo** [Tencent/rapidjson#1716]
Hey,
I have some large JSON documents with arrays of 25600 items, and when I parse the document using simply ParseStream from a FileReadStream. RapidJSON reports that the parsing succeeded, and then when I get to the array the size is 4096. Also, the document contains at least 10 layers, however RapidJSON reports a size of 1. It looks like RapidJSON is not parsing the whole thing.

Is there any kind of memory limit applied here? Is there something I can try to access the whole document?

[towntest.json.zip](https://github.com/Tencent/rapidjson/files/4626833/towntest.json.zip)

```
	const auto& root = doc.GetObject();
...
	const auto& jlayers = root["layers"].GetArray();
...
	for (const auto& jlayer : jlayers)
	{
...
		const auto& data = jlayer["data"].GetArray();
		for (const auto& it : data) {
			unsigned value = it.GetInt();
...
```

I have opened this file in firefox and I can browse all 25600 array integers in all the layers.
What am I doing wrong?

**Comment by miloyip** [comment]
~~~cpp
#include "rapidjson/document.h"
#include "rapidjson/filereadstream.h"

using namespace rapidjson;

int main() {
    Document d;
    char buffer[4096];
    FILE* fp = fopen("towntest.json", "r");
    FileReadStream frs(fp, buffer, sizeof(buffer));
    printf("%d\n", d.ParseStream(frs).GetParseError());
    fclose(fp);

    printf("%u\n", d["layers"].Size());
    for (auto& layer : d["layers"].GetArray())
        printf("%s\n", layer["name"].GetString());
}
~~~

~~~
% g++ -std=c++11 -I ~/github/rapidjson/include a.cpp && ./a.out
0
27
Ground FLOOR 0
Walls
Walls B1 D1
Walls B1 D2
Ground FLOOR 1
Street
Street D1
Street D2
Walls
Walls D1
Walls D2
Object Layer 1
Objects
Objects 2
Objects 3
Above 1 FLOOR 2
Above 2
Above 3
Ground FLOOR 3
Walls
Walls D1
Walls D2
Objects
Above 1
Above 2
Above 3
Above 4
~~~

I found there are 27 layers as shown above.

**Comment by miloyip** [comment]
In default configuration, `SizeType == unsigned`, and it should support 2^32-2 elements in an array.

**Comment by miloyip** [comment]
I think the problem in your code is that, `jlayers`should not be a reference.

**Comment by fwsGonzo** [comment]
Many thanks, it just means I have a bug and I don't see it. Sorry for wasting your time!
