### ISSUE TITLE
C++20 Warning: operator '|': deprecated between enumerations of different types

### ISSUE THREAD

**Issue by lukedan** [Tencent/rapidjson#1721]
Hello,

I've been using the latest version (from vcpkg) of RapidJSON with a project of mine that uses C++20. When compiled under MSVC using `/W4`, the compiler generates multiple warnings that says:
```
rapidjson\document.h(1924): warning C5054: operator '|': deprecated between enumerations of different types
rapidjson\document.h(1925): warning C5054: operator '|': deprecated between enumerations of different types
...
```
For me, this is the only place where the compiler gives this warning. It seems that simply `static_cast`ing to `int` solves the issue, but I'm not sure about the compatibility of this solution.

**Comment by lukedan** [comment]
Also, I believe that the line number corresponds to lines 2003-2016 on `master`.

**Comment by miloyip** [comment]
I am not sure if this is a false alarm. We may change it into `static const uint16_t`. Can you have a try and make a PR?

**Comment by lukedan** [comment]
Yes. However, since rapidjson is a header-only library, won't this introduce multiple definitions of these variables?

**Comment by lukedan** [comment]
I'm getting a lot of `unknown file: error: SEH exception with code 0xc0000005 thrown in SetUpTestCase().` in `unittest` and `perftest`. The tests seem unaffected though.

**Comment by lukedan** [comment]
Another problem is that it was possible to reference these flags using both `rapidjson::kNullType` and `rapidjson::Type::kNullType`. Simply changing `Type` to `uint16_t` may break code. The identifier `uint16_t` itself is also introduced in C++11 which causes compatibility issues.

**Comment by miloyip** [comment]
Yes, I found that those are two anonymous enum, so changing one to `uint16_t` cannot solve the problem. 
Besides, `std::uint16_t` is C++03.
So may be a workaround is to add more casts. However, gcc may generate other warning about unused cast...

**Comment by jovibor** [comment]
Getting the same warnings on the latest MSVS under `/std:c++latest`.
This is due to non-conforming `C++20` behavior.
[See here for details](https://docs.microsoft.com/en-us/cpp/overview/cpp-conformance-improvements?view=vs-2019#binary-expressions-with-different-enum-types).

In a light of C++20 spreading wider and wider, it would be very nice to resolve this.
Thanks.

**Comment by lukedan** [comment]
I've finally found some time to look at this issue. While trying to compile the tests I ran into a issue where the constructor and assignment operator of `SchemaDocumentProvider` at the end of `schematest.cpp` is undefined and causes compilation errors.

**Comment by lukedan** [comment]
Another minor issue I ran into when building the tests: The option `gtest_force_shared_crt` is not properly detected by gtest until CMake is ran a second time. Maybe this deserves its own issue?
