### ISSUE TITLE
enforce the hex string to be encoded with \u00.. format

### ISSUE THREAD

**Issue by atari83** [Tencent/rapidjson#1734]
Heya,
I'm trying to serialize a string with hexadecimal values (0x7e 0x01) to json value. Currently, when i use SetString() the output would be: "~\u0001".

Is there anyway that I could enforce rapidjson to write the all hex values with \u00.. format ? (as you see the first hex value is considered as normal character ).

My second question is that i tried to serialize 0x81 0x01 hexa string, and this time the output is "?\u0001" . Can anybody tell me how 0x81 is equal to "?" char ?

Thanks.

**Comment by miloyip** [comment]
Can you show a runnable code example?

**Comment by atari83** [comment]
Hello Milo,

The code is as follow:

```
        rapidjson::Value j_3gpp_ms_timezone;
        j_3gpp_ms_timezone.SetString( _3gpp_ms_timezone->c_str(), _3gpp_ms_timezone->length(), d.GetAllocator() );
        obj.AddMember( "3gpp_ms_timezone", j_3gpp_ms_timezone, d.GetAllocator() );

```

Regarding to second part of my question, I think the problem with 0x81 (and conversion to '?' character) is the fact that 0x81 = 129 and basically cannot fit into 'char' datatype.

So, changed my definition for _3gpp_ms_timezone from using std::string to unsigned char*, but then I receive an error on using SetString():

DataJSONMessage.cpp:256:28: error: no matching member function for call to 'SetString'
        j_3gpp_ms_timezone.SetString( _3gpp_ms_timezone->c_str(), _3gpp_ms_timezone->length(), d.GetAllocator() );
        ~~~~~~~~~~~~~~~~~~~^~~~~~~~~
rapidjson/document.h:1884:19: note: candidate function not viable: no known conversion from 'const std::__1::basic_string<unsigned char, std::__1::char_traits<unsigned char>, std::__1::allocator<unsigned char> >::value_type *' (aka 'const unsigned char *') to 'const rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::Ch *' (aka 'const char *') for 1st argument
    GenericValue& SetString(const Ch* s, SizeType length, Allocator& allocator) { return SetString(StringRef(s, length), allocator); }


So, can please guide me how to solve this issue ?

Thanks

**Comment by atari83** [comment]
Ok, about second part of my problem and I dont know if this is good solution or not, but i came up with defining some Generic types:

```
typedef rapidjson::GenericValue<rapidjson::UTF8<unsigned char> > UValue;
typedef rapidjson::GenericDocument<rapidjson::UTF8<unsigned char> > UDocument;
typedef rapidjson::GenericStringBuffer<rapidjson::UTF8<unsigned char>> UStringBuffer;

```

And now output contains the 0x81 (in form of a character) :
`3ggp_gprs_nego_qos_prof:"\u0001"`

So, back to main question .. For this specific json value, i'd like to render it with \u00.. format. I expected to get something like: "\u0081\u0001"

**Comment by miloyip** [comment]
Using `ASCII` as encoding can enforce all character not in ASCII range to be written as unicode escaped.
See https://rapidjson.org/md_doc_encoding.html

**Comment by atari83** [comment]
Hello Milo,
Sorry for long delay. Actually you were right :)
Using Ascii encoder was the solution indeed.

Thanks again.
