### ISSUE TITLE
Accept 报错，编译通不过，当使用UTF16的时候

### ISSUE THREAD

**Issue by 826655197** [Tencent/rapidjson#1747]
代码的作用是把v， 转换成 一个UTF16的字符串， 但是编译不通过VS2015

        rapidjson::GenericValue<rapidjson::UTF16<> > v;	
	v.SetString(L"你好");
	rapidjson::GenericStringBuffer< rapidjson::UTF16<> > wbuffer;
	rapidjson::Writer< rapidjson::GenericStringBuffer< rapidjson::UTF16<> > > writer(wbuffer);
	v.Accept(writer);  // 编译出错
	wstring s = wbuffer.GetString();

**Comment by miloyip** [comment]
~~~cpp
#include "rapidjson/document.h"
#include "rapidjson/writer.h"
#include "rapidjson/stringbuffer.h"
#include <string>

using namespace std;
using namespace rapidjson;

int main() {
   GenericValue<rapidjson::UTF16<> > v; 
    v.SetString(L"你好");
    GenericStringBuffer<UTF16<> > wbuffer;
    Writer<GenericStringBuffer<UTF16<> >, UTF16<>, UTF16<> > writer(wbuffer);
    v.Accept(writer);
    wstring s = wbuffer.GetString();
}
~~~
