### ISSUE TITLE
JSON document comparison always returns true if it contains only a string value

### ISSUE THREAD

**Issue by mmustaquim** [Tencent/rapidjson#1748]
If I have two JSON documents that only contain string values then RapidJSON parses them and considers their type to be kNullType... which then results in any two string-only JSON documents to be reported as being equal even when they are not.

The following code demonstrates this issue:

```c++
#include <iostream>
#include <rapidjson/document.h>

int main() {
    rapidjson::Document d1;
    d1.Parse("hello");

    rapidjson::Document d2;
    d2.Parse("world");

    std::cout << "JSON documents are equal: " << (d1 == d2 ? "Yes" : "No");

    std::cout << "JSON type: " << d1.GetType() << std::endl;

    return 0;
}
```

This gives the output:

```
JSON are equal: Yes
JSON type: 0
```

**Comment by miloyip** [comment]
These are not a valid JSON and `parse()` returns error.
A valid JSON of a single string is, e.g., `d1.Parse("\"hello\"");`

**Comment by mmustaquim** [comment]
You're right. Thank you for the quick response.
