### ISSUE TITLE
Crash when parsing a JSON combining emoji and Cyrillic characters

### ISSUE THREAD

**Issue by vadim-berman** [Tencent/rapidjson#1749]
Hello RapidJSON team / Milo,

I am getting a crash when invoking `rapidjson::Document::Parse`. The error code is `kParseErrorStringUnicodeSurrogateInvalid`.

The crash is coming from the `if` block between lines 1023 and 1032 in `reader.h`. If I comment the block out, the crash does not happen. 

I don't see the version anywhere in the source code, but my files are dated by May 2018. Thanks in advance, and thanks for your work. 

[rapidjsoncrash.txt](https://github.com/Tencent/rapidjson/files/4929214/rapidjsoncrash.txt)

**Comment by miloyip** [comment]
We added `kParseErrorStringUnicodeSurrogateInvalid` in #1744
And I found that "\ud83dе\udeac" in your JSON is invalid, causing the parse complain about this.
But it should not "crash".

**Comment by vadim-berman** [comment]
I see, thanks for the prompt response!

By crashing I meant having errors, sorry. My code throws an exception when there are errors. So you're saying it's safe to just treat the error as a warning and continue, or just keep the block commented out? 

Not sure why you deem it invalid. The .NET built-in parser is able to parse it without errors.

**Comment by miloyip** [comment]
See #1738

**Comment by vadim-berman** [comment]
I see, thanks. 

So deducing that your answer is "yes, Vadim, you can ignore it" :) . Thanks!

FYI though, my version is from 2018, so it does not include your recent changes.
