### ISSUE TITLE
SchemaValidator handler methods called twice during Accept()

### ISSUE THREAD

**Issue by smhdfdl** [Tencent/rapidjson#1798]
I have created a unit test to validate a document against a schema...

```
TEST(SchemaValidator, Patient) {
    CrtAllocator allocator;
    char* json = ReadFile("patient.schema.json", allocator);
    Document d;
    d.Parse(json);
    ASSERT_FALSE(d.HasParseError());

    char* jsonp = ReadFile("patient-example.json", allocator);
    Document dp;
    dp.Parse(jsonp);
    ASSERT_FALSE(dp.HasParseError());

    SchemaDocument sd(d);
    SchemaValidator validator(sd);
    if (!dp.Accept(validator)) {
        ...
        ADD_FAILURE();
    }
    CrtAllocator::Free(json);
    CrtAllocator::Free(jsonp);
}
```
I am seeing a behaviour I don't understand. If I add `std::cout` statements to each of the main validator handler methods (eg, StartObject, Key, etc), I see that each method is called *twice* for each event emitted by Accept().  
```
validator constructor
validator created
Accept object
validator StartObject 
validator StartObject 
validator Key: 'resourceType'
validator Key: 'resourceType'
Accept string: 'Patient'
validator Value
validator Value
validator Key: 'id'
validator Key: 'id'
Accept string: 'example'
validator Value
validator Value
...
validator EndObject 
validator EndObject 
```
In each handler method, macro RAPIDJSON_SCHEMA_HANDLE_PARALLEL_ is used. It loops over all contexts. Adding further `std::cout` statements, I can see that for each context it loops over all validators in the context. For each validator in the context it calls the same handler method again. It is this handler call that is the second call I am seeing.  
```
validator constructor
validator created
Accept object
validator StartObject  
  schema StartObject
  validator handle parallel - context #1 = 0x27a13a0 
  validator handle parallel - validator count 1  
    validator StartObject  
      schema StartObject
  validator handle parallel context #2 = 0x297fb20 
  validator handle parallel - validator count 0  
...
```
Why is this happening?  It feels like it is a bug.

**Comment by smhdfdl** [comment]
@miloyip  My organisation is considering RapidJSON as the schema validator for a project, we need to understand this behaviour please.

**Comment by miloyip** [comment]
Can you create a reproducible example?
Due to the event nature of the validator, some rules need to check values in parallel.

**Comment by smhdfdl** [comment]
@miloyip Certainly, I can create a PR that adds a unit test, if you authorize my id

**Comment by smhdfdl** [comment]
@miloyip In unit test `ValidateMetaSchema` I can observe some values being checked in parallel, as you say. But that only happens for value events. What I am seeing is two calls for every event.

**Comment by smhdfdl** [comment]
@miloyip The construct that causes the behaviour is the `oneOf` at the root of the schema. In the schema there is just one item in its array. If I replace the `oneOf` with the `#definition` it points at, the validator handler methods are only called once.
