### ISSUE TITLE
clzll.h not found.

### ISSUE THREAD

**Issue by dan-ryan** [Tencent/rapidjson#1825]
I've just updated to the latest Master to fix the errors I was getting when using C++20. Everything works on my Mac, but running on CircleCI with GCC I get this error: 

```
In file included from source/lib/rapidjson/document.h:20,
                 from source/CESerializable.hpp:11,
                 from source/CEEvent.hpp:11,
                 from source/stress/RandomEventFactory.hpp:10,
                 from source/stress/RandomEventFactory.cpp:6:
source/lib/rapidjson/reader.h:23:10: fatal error: internal/clzll.h: No such file or directory
   23 | #include "internal/clzll.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

Does anyone know why this is happening?

**Comment by miloyip** [comment]
The file is https://github.com/Tencent/rapidjson/blob/master/include/rapidjson/internal/clzll.h
Are some files was not copied to the folder?

**Comment by dan-ryan** [comment]
Nothing has changed, other than the updating to the latest. But I'll double-check to make sure nothing is missing.

**Comment by dan-ryan** [comment]
Yeah my fault :)
The file was new and I missed it and it never got uploaded to git.
