### ISSUE TITLE
Find absolute path to a node in json using rapidjson

### ISSUE THREAD

**Issue by prantarn** [Tencent/rapidjson#1829]
I am working on a problem that requires me to find the absolute path to a node in a DOM given its name using rapidjson. I am badly stuck and have no working solutions in my mind.

**Comment by miloyip** [comment]
Show an example?

**Comment by prantarn** [comment]
"internal-parameters": {
                        "background-scan-index-repair-enabled": true,
                        "extraneous-keys-realtime-repair-enabled": true
                    },
                    "ldap-proxy": {
                        "application-type-mappings": [
                            {
                                "exp-user-profile-name": "hlrUserProfile",
                                "application-type": "external",
                                "default-group-id": 50,
                                "hide-not-active-keys-when-internal": true
                            }
                           {
                                "exp-user-profile-name": "epsUserProfile",
                                "application-type": "internal",
                                "default-group-id": 52,
                                "hide-not-active-keys-when-internal": true
                            }
                         ]
                     }
                     "tuning": {
                             "rtdb": {
                                    "load-management": {
                                           "limits": [
                                                  {
                                                        "operation-subset": "incomingOperations",
                                                        "rate": 11550
                                                   }
                                            ]
                                       }
                                 }
                         }

This is an example from the complete DOM, I need to find the absolute path of for example "application-type-mappings" or "limits" without explicitly mentioning any parent node name.

**Comment by prantarn** [comment]
Hi, @miloyip can you help?

**Comment by prantarn** [comment]
rapidjson::Document qryDoc;
 qryDoc.Parse(qryJson.c_str());
 std::string absolutPath = "";
 findAllPaths(qryDoc, absolutPath);

 std::unordered_map<std::string, std::string> objPathMap;
 void findAllPaths(const rapidjson::Value& v, std::string& path)
{
  if(v.IsObject())
  {
    for(rapidjson::Value::ConstMemberIterator itr = v.MemberBegin(); itr != v.MemberEnd(); ++itr)
    {
      if(rtdbObjectKeyTypes.find(itr->name.GetString()) == rtdbObjectKeyTypes.end())
      {
        findAllPaths(itr->value, path.append("/").append(itr->name.GetString()));
        //path.erase(path.find(itr->name.GetString()));
      }
      else
      {
        objPathMap[itr->name.GetString()] = path;
        //path = "";
        //return;
      }
    }
  }
  else if(v.IsArray())
  {
    for(rapidjson::SizeType i = 0; i < v.Size(); ++i)
    {
      if(rtdbObjectKeyTypes.find(v[i].GetString()) == rtdbObjectKeyTypes.end())
      {
        findAllPaths(v[i], path.append(v[i].GetString()));
        //path.erase(path.find(v[i].GetString()));
      }
      else
      {
        objPathMap[v[i].GetString()] = path;
        //path = "";
        //return;
      }
    }
  }
  else
  {
     path = "";
  }

}

**Comment by miloyip** [comment]
I wrote an example, which travsese a document and print out the "path" as JSON pointer.

~~~cpp
#include "rapidjson/document.h"
#include "rapidjson/filereadstream.h"
#include "rapidjson/pointer.h"
#include "rapidjson/stringbuffer.h"
#include <iostream>

using namespace rapidjson;

void traverse(const Value& v, const Pointer& p) {
    StringBuffer sb;
    p.Stringify(sb);
    std::cout << sb.GetString() << std::endl;

    switch (v.GetType()) {
    case kArrayType:
        for (SizeType i = 0; i != v.Size(); ++i)
            traverse(v[i], p.Append(i));
        break;
    case kObjectType:
        for (Value::ConstMemberIterator m = v.MemberBegin(); m != v.MemberEnd(); ++m) 
            traverse(m->value, p.Append(m->name.GetString(), m->name.GetStringLength()));
        break;
    default:
        break;
    }
}

int main(int, char*[]) {
    char readBuffer[65536];
    FileReadStream is(stdin, readBuffer, sizeof(readBuffer));

    Document d;
    d.ParseStream(is);

    Pointer root;
    traverse(d, root);

    return 0;
}
~~~

Running it with https://github.com/Tencent/rapidjson/blob/master/bin/data/glossary.json

~~~
g++ -I include traverseaspointer.cpp && ./a.out < bin/data/glossary.json

/glossary
/glossary/title
/glossary/GlossDiv
/glossary/GlossDiv/title
/glossary/GlossDiv/GlossList
/glossary/GlossDiv/GlossList/GlossEntry
/glossary/GlossDiv/GlossList/GlossEntry/ID
/glossary/GlossDiv/GlossList/GlossEntry/SortAs
/glossary/GlossDiv/GlossList/GlossEntry/GlossTerm
/glossary/GlossDiv/GlossList/GlossEntry/Acronym
/glossary/GlossDiv/GlossList/GlossEntry/Abbrev
/glossary/GlossDiv/GlossList/GlossEntry/GlossDef
/glossary/GlossDiv/GlossList/GlossEntry/GlossDef/para
/glossary/GlossDiv/GlossList/GlossEntry/GlossDef/GlossSeeAlso
/glossary/GlossDiv/GlossList/GlossEntry/GlossDef/GlossSeeAlso/0
/glossary/GlossDiv/GlossList/GlossEntry/GlossDef/GlossSeeAlso/1
/glossary/GlossDiv/GlossList/GlossEntry/GlossSee
~~~

The advantage of using `Pointer` is that you can resolve a value from document with a pointer later.

Note: The root pointer outputs an empty string, which is correct in the JSON pointer RFC.

**Comment by vsdownloader** [comment]
谢谢作者，功能上大体是这样的，不过跟我期望的还是稍微有些差距，因为我是期望利用错误节点输出当前节点的路径，还是很感谢作者。
因为我写的代码都是解析完操作命令字段，根据操作命令再把参数传给命令处理函数

void demo(const std::string& s)
{
Document op;
op.Parse(s.c_str());

ParseMqttParam(GOBJ(mqtt)); //解析mqtt参数
ParseMqttParam(GOBJ(other));
...
}

void ParseMqttParam(Value& op){
...
ParseTopic(GOBJ(topics); //解析主题参数
...  
}

void ParseTopics(Value& op)
{
   错误可能出现在这里。。。
}

**Comment by miloyip** [comment]
你可以把 `Pointer` 伴随 `Value` 传到每个函数。
