### ISSUE TITLE
GetValueByPointer - Pass path as a parameter

### ISSUE THREAD

**Issue by jtaylorme** [Tencent/rapidjson#1830]
After several hours of fruitless attempts I thought I would ask...How can I pass a variable as the second parameter?   This seems like it should be simple, and probably is, but I cannot find any examples and cannot make anything work.   The following works fine but how do I pass "/results/0/recordIdentifier" using a variable?   I see that the second parameter is a const char, which of course, is the problem.  Hardcoding paths into an application makes no sense so I am obviously missing something.  Thanks.

if (tV = GetValueByPointer(docjson, "/results/0/recordIdentifier"))
	rstring = tV->GetString();

**Comment by jtaylorme** [comment]
I just figured it out.  Thanks anyway.

**Comment by jtaylorme** [comment]
Guess I should post my solution in case anyone else is wondering..

const Pointer& mypath = (Pointer)my_path_value_variable;

**Comment by int2e** [comment]
if (tV = GetValueByPointer(docjson, Pointer(path)))
rstring = tV->GetString();

**Comment by jtaylorme** [comment]
Thanks.
