### ISSUE TITLE
Example from documentation using EncodedOutputStream is not working

### ISSUE THREAD

**Issue by CyberDani** [Tencent/rapidjson#1851]
Hi dev team,

I am trying out the examples as I read through the documentation trying to understand the library as good as I can. I have found an example using the latest commit(b1a4d91a53e0884ff7f60eafd9e9efa98781c97b) at the time of writing from the master branch  which does not seems to work.

**The slightly modified code:**
```C++
// Document is GenericDocument<UTF8<> > 
Document d;
const char json[] = "[1, 2, 3, 4]";
d.Parse(json);    

FILE* filepoint;
errno_t err;
if ((err = fopen_s(&filepoint, "testFiles\\output_utf32le.json", "wb")) != 0) {
      // File could not be opened. filepoint was set to NULL
      WARN("Cannot open file \"testFiles\\output_utf32le.json\", error:" << err);
      FAIL();
}

char writeBuffer[256];
FileWriteStream bos(filepoint, writeBuffer, sizeof(writeBuffer));

typedef EncodedOutputStream<UTF32LE<>, FileWriteStream> OutputStream;
OutputStream eos(bos, true);   // Write BOM

Writer<OutputStream, UTF32LE<>, UTF8<>> writer(eos);
d.Accept(writer);   // This generates UTF32-LE file from UTF-8 in memory

fclose(filepoint);
``` 

**Errors:**
\rapidjson\include\rapidjson\document.h(1962,1): error C2664: 'bool rapidjson::Writer<OutputStream,rapidjson::UTF32BE<unsigned int>,rapidjson::UTF8<const unsigned int *>,rapidjson::CrtAllocator,0>::Key(const unsigned int *,rapidjson::SizeType,bool)': cannot convert argument 1 from 'const char *' to 'const unsigned int *'

rapidjson\include\rapidjson\document.h(1978,1): error C2664: 'bool rapidjson::Writer<OutputStream,rapidjson::UTF32BE<unsigned int>,rapidjson::UTF8<const unsigned int *>,rapidjson::CrtAllocator,0>::String(const unsigned int *,rapidjson::SizeType,bool)': cannot convert argument 1 from 'const char *' to 'const unsigned int *'

**My dev environment:**
OS: Windows 10 version 2004 (build 19041.804)
C++ version: C++20 experimental
Compiler: MSVC 16.8.5

Hope this will be fixed and the above code will work fine 😇

**Comment by CyberDani** [comment]
It might be related to the AutoUTFOutputStream example which is also not working for me.

**Comment by miloyip** [comment]
You just mistakenly swapped the source and target encoding in the template paramaters:

~~~cpp
Writer<OutputStream, UTF8<>, UTF32LE<>> writer(eos);
~~~

**Comment by CyberDani** [comment]
Thank you so much for the quick answer!

You are right. I have swapped source and target encoding and now it works.

As a suggestion, you might update this on your website so others will not just copy-paste it as I did then asking why it is not working: https://rapidjson.org/md_doc_stream.html

**Comment by miloyip** [comment]
@CyberDani Thank you for your feedback. I didn't realize that the mistake in the document. It is now fixed.
