### ISSUE TITLE
rapidjson crash SIGBUS(BUS_ADRALN): Placement-new address alignment problem

### ISSUE THREAD

**Issue by zhlila** [Tencent/rapidjson#1852]
in rapidjson/document.h:
![微信截图_20210302143458](https://user-images.githubusercontent.com/6738727/109608221-8009bd00-7b64-11eb-927b-dbf268907bc0.png)

the address of **buffer** may not aligned:
![微信截图_20210302144329](https://user-images.githubusercontent.com/6738727/109608999-af6cf980-7b65-11eb-9972-192c1ba1e73f.png)

when use the **buffer** to construct **GenericValue**, it cause SIGBUS(BUS_ADRALN):
![微信截图_20210302143945](https://user-images.githubusercontent.com/6738727/109608698-38376580-7b65-11eb-8987-19bcb6a8b417.png)

target platform :armeabi-v7a
toolchain :ndk-r17c

reference : http://5.9.10.113/42521605/placement-new-address-alignment

**Comment by miloyip** [comment]
This path generate assertion failure and should not be entered.

**Comment by zhlila** [comment]
> This path generates assertion failure and should not be entered.

well, in my case, release builds have NDEBUG defined, which will cause <assert.h> to translate assert() as a no-op

**Comment by miloyip** [comment]
This API is undefined behavior for accessing non-existing member.
So going into this path is a kind of bug in the user application.
You may use schema to validate the JSON first, or use `FindMember()` to check if the member exists before access.
