### ISSUE TITLE
Possible bug in #include <rapidjson/fwd.h>

### ISSUE THREAD

**Issue by daravi** [Tencent/rapidjson#1853]
Hi I am getting this compile error:
```
../path_to_header:325:30: error: too few template arguments for class template 'Writer'
                std::unique_ptr<rapidjson::Writer<rapidjson::StringBuffer>> createRjWriter();
```

Here is the function I am trying to declare in my header:
```
std::unique_ptr<rapidjson::Writer<rapidjson::StringBuffer>> createRjWriter();
```
Am I doing something wrong or is this a bug in the fwd header? My code compiles if I include the headers.

Edit: It seems that the default template arguments are not in the forward declaration. Is there a limitation that prevents you from adding it?

In fwd.h:
```
template<typename OutputStream, typename SourceEncoding, typename TargetEncoding, typename StackAllocator, unsigned writeFlags>
class Writer;
```

In writer.h:
```
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags>
class Writer
```

**Comment by daravi** [comment]
For anyone else having the same issue, my temporary solution is to add the default arguments until this is fixed:
```
using default_writer_t = rapidjson::Writer<rapidjson::StringBuffer, rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator, 0>;
```

**Comment by miloyip** [comment]
Currently you need to specify all template parameters, as in `fwdtest.cpp`.

**Comment by daravi** [comment]
Ok closing then.
