### ISSUE TITLE
How to properly return Document/Value from pplx task?

### ISSUE THREAD

**Issue by acceleratxr** [Tencent/rapidjson#1856]
I have code that needs to pass around a Document and/or Value object by reference. I'm finding a lot of difficulty with this because the standard copy constructors are explicitly private.

For example I want to be able to do the following.

```
#include "rapidjson/document.h"

using namespace rapidjson;

Document& SomeOperation()
{
	Document result(kObjectType);
	return result;
}

int main()
{
	Document val = SomeOperation();
	return 0;
}
```

Using the above example will result in the error:
```
error C2248: 'rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>::GenericDocument': cannot access private member declared in class 'rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>'
```

So what is the correct way to pass around these objects by reference?

**Comment by miloyip** [comment]
First, returning a reference of local variable is always wrong in C++.
Second, due to early design decision related to performance, RapidJSON does not permit copy construction. You can pass a reference as parameter in this case, or for C++11 or above, you can just return the `Document` which will have move semantic:

~~~cpp
#include "rapidjson/document.h"

using namespace rapidjson;

Document SomeOperation()
{
    Document result(kObjectType);
    return result;
}

int main()
{
    Document val = SomeOperation();
}
~~~

**Comment by acceleratxr** [comment]
> First, returning a reference of local variable is always wrong in C++.
> Second, due to early design decision related to performance, RapidJSON does not permit copy construction. You can pass a reference as parameter in this case, or for C++11 or above, you can just return the `Document` which will have move semantic:
> 
> ```c++
> #include "rapidjson/document.h"
> 
> using namespace rapidjson;
> 
> Document SomeOperation()
> {
>     Document result(kObjectType);
>     return result;
> }
> 
> int main()
> {
>     Document val = SomeOperation();
> }
> ```

You're correct. My example was possibly too simplistic and didn't fully capture the problem. I am doing as you describe, but in this case the `SomeOperation` is actually an async function that returns a PPL task. So more accurately the problem looks like this...

```
#include "pplx/pplxtasks.h"
#include "rapidjson/document.h"

using namespace rapidjson;

pplx::task<Document> SomeOperation()
{
	pplx::create_task([=]()
	{
		Document result(kObjectType);
		return result;
	});
}

int main()
{
	Document val = SomeOperation().get();
	return 0;
}
```

Again in this context the code fails to compile because, presumably, pplx is relying on the use of the copy constructor when passing back the task's result. Do you have a recommendation for how to work around this?

**Comment by miloyip** [comment]
If `task` supports move constructor than it should also work.
If no, you may try to wrap it in `unique_ptr<Document>`.

**Comment by acceleratxr** [comment]
For those that encounter a similar problem... I tried the shared_ptr approach but ran into some other issues with that. Ultimately I decided to convert the document into a variant, specifically using a std::any. This makes the data much more portable when passing around (even when using move operations).
