### ISSUE TITLE
Inconsistent result when iterating on members

### ISSUE THREAD

**Issue by SILIZ4** [Tencent/rapidjson#1860]
Hi! I'm looking for a way to check whether a specific sequence of tags `document[tag1][tag2]...[tagN]` exists or not while I don't know if each individual level exists. If think I found a solution with recursion in the code I present below.

However, even though `rapidjson::Value` is const, it seems like something inside the object is changing because I don't get the same results for the exact same function call. The output of the program is
```
v1 exists: 1
v2 exists: (empty members) 0
```
I see that the second time I call the function, it seems like `document.GetObject()` has no members. The only solution I found was to parse the document again before calling the function, but it is impractical.

```cpp
#include <iostream>
#include <vector>
#include "rapidjson/document.h"

using namespace std;

bool exprExists(const rapidjson::Value& value, vector<string>::iterator tag, const vector<string>::iterator end) {
    bool exists;

    if (value.IsObject() && tag!=end) {

        if (value.MemberBegin() == value.MemberEnd() )
            cout << "(empty members) ";

        for (auto itr=value.MemberBegin(); itr!=value.MemberEnd(); itr++) {
            if (itr->name.GetString() == *tag) {
                exists = exprExists(itr->value, ++tag, end);
                break;
            }
        }
    }
    else if (tag == end)
        exists = true;
    else
        exists = false;

    return exists;
}


int main() {
    rapidjson::Document document;
    document.Parse("{\"sampling\": true}");

    std::vector<string> v1 = {"sampling"};
    std::vector<string> v2 = {"sampling"};

    cout << "v1 exists: " << exprExists(document.GetObject(), v1.begin(), v1.end()) << endl;
    cout << "v2 exists: " << exprExists(document.GetObject(), v2.begin(), v2.end()) << endl;

    return 0;
}
```

**Comment by miloyip** [comment]
Although I cannot reproduce the problem on my machine, but I think

~~~cpp
    cout << "v1 exists: " << exprExists(document.GetObject(), v1.begin(), v1.end()) << endl;
    cout << "v2 exists: " << exprExists(document.GetObject(), v2.begin(), v2.end()) << endl;
~~~

Should be replaced by:

~~~cpp
    cout << "v1 exists: " << exprExists(document, v1.begin(), v1.end()) << endl;
    cout << "v2 exists: " << exprExists(document, v2.begin(), v2.end()) << endl;
~~~

`GetObject()` returns a `Value::ObjectType`. Your code seems converting it back to `Value` as a reference. And some compiler may not handle it properly. `Document` is inherited from `Value` so you can safely pass it as `Value&`.

Besides, you may take a look at the `Pointer` feature of RapidJSON which can fulfill the need of the above code.

**Comment by SILIZ4** [comment]
Thank you for your help, it works if I remove `.GetObject()`. I didn't look at the `Pointer` feature, I'll take a look
