### ISSUE TITLE
Incorrect parsing of small JSONs containing only values

### ISSUE THREAD

**Issue by andykras** [Tencent/rapidjson#1864]
Consider JSON like "123", which is a valid [RFC 7159](https://tools.ietf.org/html/rfc7159#section-13). 

Actual behavior: 
```cpp
document.Parse("123");
document.IsInt(); // false
document.IsString(); // true
```
Expected behavior: 
```cpp
document.Parse("123");
document.IsInt(); // true
document.IsString(); // false
int value = document.GetInt(); // 123
```

**Comment by miloyip** [comment]
~~~cpp
#include "rapidjson/document.h"
#include <iostream>

using namespace rapidjson;
using namespace std;

int main() {
    Document d;
    d.Parse("123");
    cout << d.IsInt() << endl;
    cout << d.GetInt() << endl;
    cout << d.IsString() << endl;
}
~~~

~~~bash
$ g++ -I ~/github/rapidjson/include a.cpp && ./a.out
1
123
0
~~~

**Comment by andykras** [comment]
Sorry, can please you try a bigger number like "2761013065264", actually I faced it's not working with this value. I didn't expect it's working for small one.

**Comment by andykras** [comment]
I found out that problem was in my code, I parsing like this
```cpp
d.Parse("\"123\"");
```
which is I guess is incorrect.

**Comment by miloyip** [comment]
This value is bigger than the range of 32-bit (signed) integer, so `d.IsInt() == false`. However, `d.IsInt64() == true` and `d.IsNumber() == true`.

`d.IsString()` will always be false for numbers.

**Comment by andykras** [comment]
Yes, thank you. Close the issue as irrelevant.
