### ISSUE TITLE
Memory leak due to GetRemoteDocument using a raw pointer

### ISSUE THREAD

**Issue by rbeuvot** [Tencent/rapidjson#1886]
Hello,

I am using a remote document provider (in RapidJson version 1.1.0) and I am facing a memory leak at the creation of the remote document
Here is my code:

```
const rapidjson::SchemaDocument* RemoteSchemaDocumentProvider::GetRemoteDocument(const char* iRef,
                                                                                 rapidjson::SizeType iLength) {
    // Definition of aDoc
    rapidjson::SchemaDocument * aSchemaDocument = new rapidjson::SchemaDocument(*aDoc,this);
    return  aSchemaDocument;
}
```
It is then called here:
https://github.com/Tencent/rapidjson/blob/2fb78f9cee01996f020d5af7592b37c5a0693b31/include/rapidjson/schema.h#L1476

The memory of **remoteDocument** is then never freed.
Do you know who has the ownership of the pointer ?
Did I forgot something on my implementation ?

Thank you in advance,
Regards
Richard.

**Comment by miloyip** [comment]
The ownership of the schema documents is at user's side.  You may refer to:

https://github.com/Tencent/rapidjson/blob/2fb78f9cee01996f020d5af7592b37c5a0693b31/test/unittest/schematest.cpp#L1090-L1093

You may use a `map`/`unordered_map` to hold the loaded documents, so everytime a remote document is referred, you don't need to load it again.

**Comment by rbeuvot** [comment]
Ok, I might use an `unordered_map`.
Thank you very much for the fast reply
