### ISSUE TITLE
Using Subscript / array index operator on rapidjson ( Array ) Value crashes on SUSE Linux!

### ISSUE THREAD

**Issue by joshyas** [Tencent/rapidjson#1890]
Hello, please follow the 2 code snippets below. Please let me know in case you know what am I doing wrong

here's the code which crashes at runtime on SUSE Linux leaving no trace!

~~~cpp
    rapidjson::Document jsonDoc;
    jsonDoc.Parse( theJsonString.c_str() );
    if( jsonDoc.HasParseError() )
    {
        //  error out
    }
    else
    {
        rapidjson::Value::MemberIterator itrPRs = jsonDoc.FindMember( "PropertyRecords" );
        if( itrPRs != jsonDoc.MemberEnd() && ( itrPRs->value ).IsArray() )
        {
            rapidjson::Value& jsonPRArray = ( itrPRs->value );
            //  jsonPRArray.Size() returns valid size
            for( size_t inx = 0; inx < jsonPRArray.Size(); ++inx )
            {
                rapidjson::Value& jsonPropRec = jsonPRArray[inx];   //  crashes leaving no trace!
                //  work with jsonPropRec
            }
        }
    }
~~~

here's the alternative which works

~~~cpp
    rapidjson::Document jsonDoc;
    jsonDoc.Parse( theJsonString.c_str() );
    if( jsonDoc.HasParseError() )
    {
        //  error out
    }
    else
    {
        rapidjson::Value::MemberIterator itrPRs = jsonDoc.FindMember( "PropertyRecords" );
        if( itrPRs != jsonDoc.MemberEnd() && ( itrPRs->value ).IsArray() )
        {
            rapidjson::Value& jsonPRArray = ( itrPRs->value );
            //  jsonPRArray.Size() returns valid size
            for( rapidjson::Value::ValueIterator itrPRDoc = jsonPRArray.Begin(); itrPRDoc != jsonPRArray.End(); ++itrPRDoc )
            {
                rapidjson::Value& jsonPropRec = *itrPRDoc;  //  works as expected!
                //  work with jsonPropRec
            }
        }
    }
~~~

**Comment by miloyip** [comment]
I can only figure out that `SizeType` should be used instead of `size_t`. But it should not generate crash.
I don't know if you can compile and run it with assertion fail. Or you may try to `gdb` on that line and see what exactly generates the crash.

**Comment by joshyas** [comment]
> 
> 
> I can only figure out that `SizeType` should be used instead of `size_t`. But it should not generate crash.
> I don't know if you can compile and run it with assertion fail. Or you may try to `gdb` on that line and see what exactly generates the crash.


Thanks Milo for taking a look. Yes, I also have tried using the `rapidjson::SizeType` instead of `size_t` - but even that didn't help. Yes, even I find this weird. I am experiencing this with _release_ built libraries which usually is the case in a production environment. I faintly remember that having used _debug_ built libraries the crash wasn't reproducible.
I will check around with my colleagues on how `gdb` can be put to use here.

**Comment by tallalnparis4ev** [comment]
If it helps in anyway, the following runs fine on CentOS Linux release 8.3.2011 and Catalina 10.15.6
```
#include "rapidjson/document.h"
#include <iostream>
#include <string>

int main() {
    rapidjson::Document jsonDoc;
    std::string theJsonString = "{\"PropertyRecords\":[1,2,3,4]}";
    jsonDoc.Parse( theJsonString.c_str() );
    rapidjson::Value::MemberIterator itrPRs = jsonDoc.FindMember( "PropertyRecords" );
    if( itrPRs != jsonDoc.MemberEnd() && ( itrPRs->value ).IsArray() )
    {
        rapidjson::Value& jsonPRArray = ( itrPRs->value );
        for( rapidjson::SizeType inx = 0; inx < jsonPRArray.Size(); ++inx )
        {
            rapidjson::Value& jsonPropRec = jsonPRArray[inx];
            std::cout << jsonPropRec.GetInt() << std::endl;
        }
    }
}
```
It would be helpful if you could paste ``theJsonString`` so we can determine if your problem is only reproducible on SUSE Linux

**Comment by joshyas** [comment]
@tallalnparis4ev - thank u for taking a look. I've pasted actual JSON stream coming into play at run time. Having parsed it to create a rapidjson::Document, I retrieve the value of its property, "PropertyRecords" which happens to be a JSON Array. Note that it's a JSON Array of 10 JSON Objects and I iterate over each of these JSON Objects.

`{"SchemaVersion":"1.1.0","Locale":"en_US","PropertyRecords":[{"ID":"PCOE_0","Locale":"en_US","NodeId":"CSTPCOE#ADT-DEVICE-MA1#001","UnitSystem":1,"Properties":[{"ID":"CSTPCOE#02-xLv+/w#001","Value":1.1},{"ID":"CSTPCOE#02-xq7+/w#001","Value":2},{"ID":"CSTPCOE#02-QK7+/w#001","Value":3},{"ID":"CSTPCOE#02-P67+/w#001","Value":4},{"ID":"CSTPCOE#02-Ga7+/w#001","Value":5.5},{"ID":"CSTPCOE#02-GK7+/w#001","Value":6.6},{"ID":"CSTPCOE#02-F67+/w#001","Value":"seven"},{"ID":"CSTPCOE#02-0q7+/w#001","Value":8.8},{"ID":"CSTPCOE#02-bK7+/w#001","Value":9.9},{"ID":"CSTPCOE#02-a67+/w#001","Value":10.1},{"ID":"CSTPCOE#02-Ua7+/w#001","Value":11.11},{"ID":"CSTPCOE#02-aq7+/w#001","Value":12.12},{"ID":"CSTPCOE#02-LK7+/w#001","Value":13.13},{"ID":"CSTPCOE#02-K67+/w#001","Value":14.14}]},{"ID":"PCOE_1","Locale":"en_US","NodeId":"CSTPCOE#ADT-DEVICE-MA1#001","UnitSystem":1,"Properties":[{"ID":"CSTPCOE#02-xLv+/w#001","Value":1.1},{"ID":"CSTPCOE#02-xq7+/w#001","Value":2},{"ID":"CSTPCOE#02-QK7+/w#001","Value":3},{"ID":"CSTPCOE#02-P67+/w#001","Value":4},{"ID":"CSTPCOE#02-Ga7+/w#001","Value":5.5},{"ID":"CSTPCOE#02-GK7+/w#001","Value":6.6},{"ID":"CSTPCOE#02-F67+/w#001","Value":"seven"},{"ID":"CSTPCOE#02-0q7+/w#001","Value":8.8},{"ID":"CSTPCOE#02-bK7+/w#001","Value":9.9},{"ID":"CSTPCOE#02-a67+/w#001","Value":10.1},{"ID":"CSTPCOE#02-Ua7+/w#001","Value":11.11},{"ID":"CSTPCOE#02-aq7+/w#001","Value":12.12},{"ID":"CSTPCOE#02-LK7+/w#001","Value":13.13},{"ID":"CSTPCOE#02-K67+/w#001","Value":14.14}]},{"ID":"PCOE_2","Locale":"en_US","NodeId":"CSTPCOE#ADT-DEVICE-MA1#001","UnitSystem":1,"Properties":[{"ID":"CSTPCOE#02-xLv+/w#001","Value":1.1},{"ID":"CSTPCOE#02-xq7+/w#001","Value":2},{"ID":"CSTPCOE#02-QK7+/w#001","Value":3},{"ID":"CSTPCOE#02-P67+/w#001","Value":4},{"ID":"CSTPCOE#02-Ga7+/w#001","Value":5.5},{"ID":"CSTPCOE#02-GK7+/w#001","Value":6.6},{"ID":"CSTPCOE#02-F67+/w#001","Value":"seven"},{"ID":"CSTPCOE#02-0q7+/w#001","Value":8.8},{"ID":"CSTPCOE#02-bK7+/w#001","Value":9.9},{"ID":"CSTPCOE#02-a67+/w#001","Value":10.1},{"ID":"CSTPCOE#02-Ua7+/w#001","Value":11.11},{"ID":"CSTPCOE#02-aq7+/w#001","Value":12.12},{"ID":"CSTPCOE#02-LK7+/w#001","Value":13.13},{"ID":"CSTPCOE#02-K67+/w#001","Value":14.14}]},{"ID":"PCOE_3","Locale":"en_US","NodeId":"CSTPCOE#ADT-DEVICE-MA1#001","UnitSystem":1,"Properties":[{"ID":"CSTPCOE#02-xLv+/w#001","Value":1.1},{"ID":"CSTPCOE#02-xq7+/w#001","Value":2},{"ID":"CSTPCOE#02-QK7+/w#001","Value":3},{"ID":"CSTPCOE#02-P67+/w#001","Value":4},{"ID":"CSTPCOE#02-Ga7+/w#001","Value":5.5},{"ID":"CSTPCOE#02-GK7+/w#001","Value":6.6},{"ID":"CSTPCOE#02-F67+/w#001","Value":"seven"},{"ID":"CSTPCOE#02-0q7+/w#001","Value":8.8},{"ID":"CSTPCOE#02-bK7+/w#001","Value":9.9},{"ID":"CSTPCOE#02-a67+/w#001","Value":10.1},{"ID":"CSTPCOE#02-Ua7+/w#001","Value":11.11},{"ID":"CSTPCOE#02-aq7+/w#001","Value":12.12},{"ID":"CSTPCOE#02-LK7+/w#001","Value":13.13},{"ID":"CSTPCOE#02-K67+/w#001","Value":14.14}]},{"ID":"PCOE_4","Locale":"en_US","NodeId":"CSTPCOE#ADT-DEVICE-MA1#001","UnitSystem":1,"Properties":[{"ID":"CSTPCOE#02-xLv+/w#001","Value":1.1},{"ID":"CSTPCOE#02-xq7+/w#001","Value":2},{"ID":"CSTPCOE#02-QK7+/w#001","Value":3},{"ID":"CSTPCOE#02-P67+/w#001","Value":4},{"ID":"CSTPCOE#02-Ga7+/w#001","Value":5.5},{"ID":"CSTPCOE#02-GK7+/w#001","Value":6.6},{"ID":"CSTPCOE#02-F67+/w#001","Value":"seven"},{"ID":"CSTPCOE#02-0q7+/w#001","Value":8.8},{"ID":"CSTPCOE#02-bK7+/w#001","Value":9.9},{"ID":"CSTPCOE#02-a67+/w#001","Value":10.1},{"ID":"CSTPCOE#02-Ua7+/w#001","Value":11.11},{"ID":"CSTPCOE#02-aq7+/w#001","Value":12.12},{"ID":"CSTPCOE#02-LK7+/w#001","Value":13.13},{"ID":"CSTPCOE#02-K67+/w#001","Value":14.14}]},{"ID":"PCOE_5","Locale":"en_US","NodeId":"CSTPCOE#ADT-DEVICE-MA1#001","UnitSystem":1,"Properties":[{"ID":"CSTPCOE#02-xLv+/w#001","Value":1.1},{"ID":"CSTPCOE#02-xq7+/w#001","Value":2},{"ID":"CSTPCOE#02-QK7+/w#001","Value":3},{"ID":"CSTPCOE#02-P67+/w#001","Value":4},{"ID":"CSTPCOE#02-Ga7+/w#001","Value":5.5},{"ID":"CSTPCOE#02-GK7+/w#001","Value":6.6},{"ID":"CSTPCOE#02-F67+/w#001","Value":"seven"},{"ID":"CSTPCOE#02-0q7+/w#001","Value":8.8},{"ID":"CSTPCOE#02-bK7+/w#001","Value":9.9},{"ID":"CSTPCOE#02-a67+/w#001","Value":10.1},{"ID":"CSTPCOE#02-Ua7+/w#001","Value":11.11},{"ID":"CSTPCOE#02-aq7+/w#001","Value":12.12},{"ID":"CSTPCOE#02-LK7+/w#001","Value":13.13},{"ID":"CSTPCOE#02-K67+/w#001","Value":14.14}]},{"ID":"PCOE_6","Locale":"en_US","NodeId":"CSTPCOE#ADT-DEVICE-MA1#001","UnitSystem":1,"Properties":[{"ID":"CSTPCOE#02-xLv+/w#001","Value":1.1},{"ID":"CSTPCOE#02-xq7+/w#001","Value":2},{"ID":"CSTPCOE#02-QK7+/w#001","Value":3},{"ID":"CSTPCOE#02-P67+/w#001","Value":4},{"ID":"CSTPCOE#02-Ga7+/w#001","Value":5.5},{"ID":"CSTPCOE#02-GK7+/w#001","Value":6.6},{"ID":"CSTPCOE#02-F67+/w#001","Value":"seven"},{"ID":"CSTPCOE#02-0q7+/w#001","Value":8.8},{"ID":"CSTPCOE#02-bK7+/w#001","Value":9.9},{"ID":"CSTPCOE#02-a67+/w#001","Value":10.1},{"ID":"CSTPCOE#02-Ua7+/w#001","Value":11.11},{"ID":"CSTPCOE#02-aq7+/w#001","Value":12.12},{"ID":"CSTPCOE#02-LK7+/w#001","Value":13.13},{"ID":"CSTPCOE#02-K67+/w#001","Value":14.14}]},{"ID":"PCOE_7","Locale":"en_US","NodeId":"CSTPCOE#ADT-DEVICE-MA1#001","UnitSystem":1,"Properties":[{"ID":"CSTPCOE#02-xLv+/w#001","Value":1.1},{"ID":"CSTPCOE#02-xq7+/w#001","Value":2},{"ID":"CSTPCOE#02-QK7+/w#001","Value":3},{"ID":"CSTPCOE#02-P67+/w#001","Value":4},{"ID":"CSTPCOE#02-Ga7+/w#001","Value":5.5},{"ID":"CSTPCOE#02-GK7+/w#001","Value":6.6},{"ID":"CSTPCOE#02-F67+/w#001","Value":"seven"},{"ID":"CSTPCOE#02-0q7+/w#001","Value":8.8},{"ID":"CSTPCOE#02-bK7+/w#001","Value":9.9},{"ID":"CSTPCOE#02-a67+/w#001","Value":10.1},{"ID":"CSTPCOE#02-Ua7+/w#001","Value":11.11},{"ID":"CSTPCOE#02-aq7+/w#001","Value":12.12},{"ID":"CSTPCOE#02-LK7+/w#001","Value":13.13},{"ID":"CSTPCOE#02-K67+/w#001","Value":14.14}]},{"ID":"PCOE_8","Locale":"en_US","NodeId":"CSTPCOE#ADT-DEVICE-MA1#001","UnitSystem":1,"Properties":[{"ID":"CSTPCOE#02-xLv+/w#001","Value":1.1},{"ID":"CSTPCOE#02-xq7+/w#001","Value":2},{"ID":"CSTPCOE#02-QK7+/w#001","Value":3},{"ID":"CSTPCOE#02-P67+/w#001","Value":4},{"ID":"CSTPCOE#02-Ga7+/w#001","Value":5.5},{"ID":"CSTPCOE#02-GK7+/w#001","Value":6.6},{"ID":"CSTPCOE#02-F67+/w#001","Value":"seven"},{"ID":"CSTPCOE#02-0q7+/w#001","Value":8.8},{"ID":"CSTPCOE#02-bK7+/w#001","Value":9.9},{"ID":"CSTPCOE#02-a67+/w#001","Value":10.1},{"ID":"CSTPCOE#02-Ua7+/w#001","Value":11.11},{"ID":"CSTPCOE#02-aq7+/w#001","Value":12.12},{"ID":"CSTPCOE#02-LK7+/w#001","Value":13.13},{"ID":"CSTPCOE#02-K67+/w#001","Value":14.14}]},{"ID":"PCOE_9","Locale":"en_US","NodeId":"CSTPCOE#ADT-DEVICE-MA1#001","UnitSystem":1,"Properties":[{"ID":"CSTPCOE#02-xLv+/w#001","Value":1.1},{"ID":"CSTPCOE#02-xq7+/w#001","Value":2},{"ID":"CSTPCOE#02-QK7+/w#001","Value":3},{"ID":"CSTPCOE#02-P67+/w#001","Value":4},{"ID":"CSTPCOE#02-Ga7+/w#001","Value":5.5},{"ID":"CSTPCOE#02-GK7+/w#001","Value":6.6},{"ID":"CSTPCOE#02-F67+/w#001","Value":"seven"},{"ID":"CSTPCOE#02-0q7+/w#001","Value":8.8},{"ID":"CSTPCOE#02-bK7+/w#001","Value":9.9},{"ID":"CSTPCOE#02-a67+/w#001","Value":10.1},{"ID":"CSTPCOE#02-Ua7+/w#001","Value":11.11},{"ID":"CSTPCOE#02-aq7+/w#001","Value":12.12},{"ID":"CSTPCOE#02-LK7+/w#001","Value":13.13},{"ID":"CSTPCOE#02-K67+/w#001","Value":14.14}]}]}`

**Comment by tallalnparis4ev** [comment]
Hey @joshyas thanks for posting! I think it's best someone else picks this up, because it's a pain for me to run SUSE on my system.

**Comment by joshyas** [comment]
Finally, we analyzed the Core dump file using `gdb`. The SUSE environment in this case was patched with `libc.so` which was corrupt and it made the rapidjson APIs to not work as expected.
Having patched with the corrected `libc.so` ( or by removing the corrupt patch ) - things worked as expected!

Thank you for pointing to do the `gdb` analysis. Although time consuming it's an experience to pick up!
Please close / reject this thread accordingly.
