### ISSUE TITLE
[Question] what is the right way to handle field writing failure

### ISSUE THREAD

**Issue by shawncao** [Tencent/rapidjson#1910]
Hi, below is a simple code example to do error handling Double method, when it sees value of infinity, it will produce empty field value which result a invalid JSON.

So I was thinking to use a simple check and write a default value (0) instead, it failed with error:

> Assertion failed: (type == kStringType), function Prefix, file > /Users/shawncao/nebula/build/rapidjson/src/rapidjson/include/rapidjson/writer.h, line 484.
Abort trap: 6

I assume it doesn't expect me to call Double method twice even the first call failed, any solution for this? such as remove current key and rewrite the whole pair, or method to reset the internal state since last Double() call failed?

Thanks! 

Repro code:
```
    rapidjson::StringBuffer buffer;
    rapidjson::Writer<rapidjson::StringBuffer> json(buffer);
    json.StartObject();
    json.Key("v");
    auto dr = json.Double(std::numeric_limits<float>::infinity());
    // if not success, write a default value
    if (!dr) {
      json.Double(0);
    }
    json.EndObject();
    auto result = buffer.GetString();
```

**Comment by miloyip** [comment]
`Double()` returns `false` when it is failed to write the value. When it is failed, it cannot be rolled back.
If you need to write another value when the data is invalid for JSON, I think you need to use `std::isfinite()` to make the test.

**Comment by shawncao** [comment]
Thanks Milo!

**Comment by shawncao** [comment]
I prefer a feature like "reset" current key is because I don't want to bet the "failure" pure on single case of "infinite" value, it may fail on other cases as well - so I can generically fallback to default when it happens as error handling, so would love to have that feature if reasonable to have in the future.

**Comment by miloyip** [comment]
IMHO, falling back to default is not always a good option. If the data cannot be represented in some format, the application shall consider different ways to handle this.
Similar to `PrettyWriter`, it is trivial to write a wrapper to handle different cases from application side.

**Comment by shawncao** [comment]
Agreed - not always good, but sometimes fit what application needs - handle similar problem in scale and be able to tolerate wrong value, if I'm sure there are ONLY two cases that Double will return false (NaN, Infinite), I think handling these cases in application is completely fine. 

I actually see that we have flag on both writer and parser side, so that's pretty good option for me for now: 

(write) https://github.com/varchar-io/nebula/blob/d5ba9dc43de79da87122e8f5edb2efab837c1033/src/surface/eval/Histogram.h#L40

(read) https://github.com/varchar-io/nebula/blob/d5ba9dc43de79da87122e8f5edb2efab837c1033/src/surface/eval/Histogram.cpp#L30

Thanks again for your input, appreciate it!
