### ISSUE TITLE
A writer problem 

### ISSUE THREAD

**Issue by Jasonzyt** [Tencent/rapidjson#1914]
Compile with Visual Studio 2019(C++17)
When I write(output) StringBuffer to a file or the console,some value in the array will be `null`.
Like this(the original file has 200+KiB data)
```json lines
{
    "KEY": [
        {
           "value":"...(A normal value)"
        },
        {
             "value":"...(A normal value)"
        },
        {
             "value":"...(A normal value)"
        },
        null, 
        null,
        null,
        null,
        null,
        {
             "value":"...(A normal value)"
        },
        null,
        null,
        null,
        null,
        {
             "value":"...(A normal value)"
        },
    ]
}
```
I try many times,the wrong array members are fixed.
And I try many way to output(StringBuffer&PrettyWriter&Writer&OStreamWrapper),the outputs have the same problem.
BUT if I use `json_doc["KEY"][3]["value"].GetInt()`,I can get the correct value.
How can I solve this problem?
~~I will use JsonCPP instead of rapidJson(XD)~~
PS: I am not a native English speaker and My English may be not very good.Please forgive me.

**Comment by miloyip** [comment]
Any simple code that can reproduce your problem?

**Comment by Jasonzyt** [comment]
I have fixed this problem, but I don't know the reason.
I removed a `printf` function(4 in all) in the loop control,and it became normal.
I think this problem is related to that.
![image](https://user-images.githubusercontent.com/66063199/125099493-a6d79180-e10a-11eb-8acb-4d6e0bc1dfc7.png)

**Comment by Jasonzyt** [comment]
I found a pattern.
If (string)owners is null and (Value(kArrayType))shared_player does not have any member,it will have this problem.
I removed (string)owners,and it got normal.

**Comment by Jasonzyt** [comment]
I do not know if this problem is related to rapidjson.
It is weird.
Because the return value of `doc["KEY"][123]` is normal,I think it is related to `doc.Accept(writer)` funtion.

**Comment by Jasonzyt** [comment]
I found the source of the problem.
I replaced `str.pop_back()` with `if (!str.empty()) str.pop_back();`, it became OK

**Comment by Jasonzyt** [comment]
I found the source of the problem.
I replaced `str.pop_back()` with `if (!str.empty()) str.pop_back();`, it became OK
