### ISSUE TITLE
error: writing 1 byte into a region of size 0

### ISSUE THREAD

**Issue by PurpleAzurite** [Tencent/rapidjson#1924]
Compiling with gcc with Debug configuration works fine but Release throws the following:

```
/home/david/dev/heartcore/vendor/rapidjson/include/rapidjson/uri.h:330: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
In file included from /home/david/dev/heartcore/vendor/rapidjson/include/rapidjson/pointer.h:19,
                 from /home/david/dev/heartcore/vendor/rapidjson/include/rapidjson/schema.h:19,
                 from /home/david/dev/heartcore/vendor/rapidjson/example/schemavalidator/schemavalidator.cpp:9:
/home/david/dev/heartcore/vendor/rapidjson/include/rapidjson/uri.h: In member function ‘void rapidjson::GenericUri<ValueType, Allocator>::Parse(const Ch*, std::size_t) [with ValueType = rapidjson::GenericValue<rapidjson::UTF8<> >; Allocator = rapidjson::CrtAllocator]’:
/home/david/dev/heartcore/vendor/rapidjson/include/rapidjson/uri.h:330:17: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
  330 |         *query_ = '\0';
      |         ~~~~~~~~^~~~~~
```

**Comment by PurpleAzurite** [comment]
No compiler configuration (clang, mingw, etc.), other than GCC debug, can currently compile rapidjson on our end due to this issue. As such we have switched to an alternative parser. This compilation failure is not limited to just one development machine. None of our systems can compile the code outside of the mentioned configuration.

**Comment by smhdfdl** [comment]
@miloyip Any idea about how to fix this one?

**Comment by miloyip** [comment]
@smhdfdl Can we add `#pragma` to disable this warning? If we ensure it is not a problem. New versions of compilers always add more and more warnings...

**Comment by smhdfdl** [comment]
@miloyip @PurpleAzurite A small refactor of the code appears to remove the warnings. The compiler seems to have been confused by the `+ 1` on the previous line.

**Comment by todd-richmond** [comment]
fails with gcc 11.2 on centos so probably just newer compilers

**Comment by smhdfdl** [comment]
@miloyip Are you ok closing this issue, as should be fixed by PR #1940

**Comment by shawnxbc** [comment]
> @miloyip @PurpleAzurite A small refactor of the code appears to remove the warnings. The compiler seems to have been confused by the `+ 1` on the previous line. Eg:
> 
> ```
>         auth_ = scheme_;
>         auth_++;
>         *auth_ = '\0';
> ```

@smhdfdl I'm on another project and the same error poped out. I don't know how to fix it. Could you please tell me why this refactorization passed the compiler? There seems no difference between it and the original.

**Comment by smhdfdl** [comment]
@shawnxbc Sorry but I have no idea why the fix works.

**Comment by Xeverous** [comment]
I know it's late but FYI I got the same weird warning on my own project which uses high-level C++ (no memcpy / byte stuff), it points to random types and totally sane operations like ctor member init list (which can not cause undefined behavior).

[Searching GCC bugzilla](https://gcc.gnu.org/bugzilla/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=SUSPENDED&bug_status=WAITING&bug_status=REOPENED&cf_known_to_fail_type=allwords&cf_known_to_work_type=allwords&f0=OP&f1=OP&f10=OP&f11=OP&f12=product&f13=component&f14=alias&f15=short_desc&f17=content&f18=CP&f19=CP&f2=product&f20=OP&f21=OP&f22=alias&f23=short_desc&f25=content&f26=CP&f27=CP&f28=OP&f29=OP&f3=component&f30=product&f31=component&f32=alias&f33=short_desc&f35=content&f36=CP&f37=CP&f38=OP&f39=OP&f4=alias&f40=alias&f41=short_desc&f43=content&f44=CP&f45=CP&f46=OP&f47=OP&f48=product&f49=component&f5=short_desc&f50=alias&f51=short_desc&f53=content&f54=CP&f55=CP&f56=OP&f57=OP&f58=alias&f59=short_desc&f61=content&f62=CP&f63=CP&f7=content&f8=CP&f9=CP&j1=OR&j11=OR&j21=OR&j29=OR&j39=OR&j47=OR&j57=OR&o12=substring&o13=substring&o14=substring&o15=substring&o16=substring&o17=matches&o2=substring&o22=substring&o23=substring&o24=substring&o25=matches&o3=substring&o30=substring&o31=substring&o32=substring&o33=substring&o34=substring&o35=matches&o4=substring&o40=substring&o41=substring&o42=substring&o43=matches&o48=substring&o49=substring&o5=substring&o50=substring&o51=substring&o52=substring&o53=matches&o58=substring&o59=substring&o6=substring&o60=substring&o61=matches&o7=matches&product=gcc&query_format=advanced&short_desc=byte%20into%20a%20region%20of%20size%200&short_desc_type=allwordssubstr&v12=into&v13=into&v14=into&v15=into&v16=into&v17="into"&v2=byte&v22=a&v23=a&v24=a&v25="a"&v3=byte&v30=region&v31=region&v32=region&v33=region&v34=region&v35="region"&v4=byte&v40=of&v41=of&v42=of&v43="of"&v48=size&v49=size&v5=byte&v50=size&v51=size&v52=size&v53="size"&v58=0&v59=0&v6=byte&v60=0&v61="0"&v7="byte") with this warning gives me 8 results, many on totally bug-free code. Fixes generally include tweaking optimization options.

**Comment by SparklesReal** [comment]
Same problem

[build] In function ‘void u32toa_naive(uint32_t, char*)’,
[build]     inlined from ‘void i32toa_naive(int32_t, char*)’ at /home/sparkles/Coding/Game/extern/RapidJSON/test/unittest/itoatest.cpp:115:17,
[build]     inlined from ‘void VerifyValue(T, void (*)(T, char*), char* (*)(T, char*)) [with T = int]’ at /home/sparkles/Coding/Game/extern/RapidJSON/test/unittest/itoatest.cpp:62:6:
[build] /home/sparkles/Coding/Game/extern/RapidJSON/test/unittest/itoatest.cpp:103:19: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
[build]   103 |         *buffer++ = *--p;
[build]       |         ~~~~~~~~~~^~~~~~
[build] /home/sparkles/Coding/Game/extern/RapidJSON/test/unittest/itoatest.cpp:103:19: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
[build] /home/sparkles/Coding/Game/extern/RapidJSON/test/unittest/itoatest.cpp:103:19: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
