### ISSUE TITLE
PrettyWriter 输出被截短了

### ISSUE THREAD

**Issue by kerry999** [Tencent/rapidjson#1939]
你好，

我在android上用ndk开发C++程序

string RehabTraining::GetResultJson()
{
    StringBuffer sb;
    PrettyWriter<StringBuffer> writer(sb);
    pImpl->doc.Accept(writer);    // Accept() traverses the DOM and generates Handler events.
    clogger->info("json changed: {0}",sb.GetString());
    return sb.GetString();
}

调用方式：
    clogger->info("initRehabPlan input string = {0}",plan);
    if (pImpl->doc.Parse(plan.c_str()).HasParseError()) { return; }
    clogger->info("initRehabPlan parsed json={0}",GetResultJson());

第一个打印输入Parse的字符串是对的，含有三个完整的：动作01，动作02，动作03

I/MC: 18:22:33.340 mc info initRehabPlan input string = {"ver": 1,"days": [20210501,-20210503,-20210505,-20210507], "works":[    {        "name":"动作01",	"id":1,        "video":"https://",        "motions":        [            [                {"bone1":["mid_shoulder", "mid_hip"], "bone2":["right_shoulder","right_elbow"],"startAngle":0,"endAngle":30}            ]        ],        "groups":                [                    {                        "rest":[],                        "scores":[-1],                        "time":[-1],                        "restAfterGroup": 300                    },                    {                        "rest":[10,5],                        "scores":[-1,-1,-1],                        "time":[-1,-1,-1],                        "restAfterGroup": 100                    },                    {                        "rest":[-10,-5,-10,-5],                        "scores":[-1,-1,-1,-1,-1],                        "time":[-1,-1,-1,-1,-1],                        "restAfterGroup": 0                    }                ]    },    {	"name":"动作02",	"id":2,	"video":"https://1",        "motions":        [            [                {"bone1":["left_shoulder","left_hip"], "bone2":["left_shoulder","left_elbow"], "startAngle":0,"endAngle":30}            ]        ],        "groups":        [            {                "rest":[],                "scores":[-1],                "time":[-1],                "restAfterGroup": 300            },            {                "rest":[-10,-5],                "scores":[-1,-1,-1],                "time":[-1,-1,-1],                "restAfterGroup": 100            },            {                "rest":[-10,-5,-10,-5],                "scores":[-1,-1,-1,-1,-1],                "time":[-1,-1,-1,-1,-1],                "restAfterGroup": 0            }        ]    },    {	"name":"动作03",	"id":3,	"video":"https://1",        "motions":        [            [                {"bone1":["left_hip", "left_knee"], "bone2":["left_knee","left_ankle"], "startAngle":0,"endAngle":30}            ]        ],        "groups":        [            {                "rest":[],                "scores":[-1],                "time":[-1],                "restAfterGroup": 300            },            {                "rest":[-10,-5],                "scores":[-1,-1,-1],                "time":[-1,-1,-1],                "restAfterGroup": 100            },            {                "rest":[-10,-5,-10,-5],                "scores":[-1,-1,-1,-1,-1],                "time":[-1,-1,-1,-1,-1],                "restAfterGroup": 0            }        ]    }]}

但是经过 PrettyWriter后就被揭短了，只打印了动作01，动作02的一部分，后面都没有了：
 I/MC: 18:22:33.340 mc info initRehabPlan parsed json={
        "ver": 1,
        "days": [
            20210501,
            -20210503,
            -20210505,
            -20210507
        ],
        "works": [
            {
                "name": "动作01",
                "id": 1,
                "video": "https://",
                "motions": [
                    [
                        {
                            "bone1": [
                                "mid_shoulder",
                                "mid_hip"
                            ],
                            "bone2": [
                                "right_shoulder",
                                "right_elbow"
                            ],
                            "startAngle": 0,
                            "endAngle": 30
                        }
                    ]
                ],
                "groups": [
                    {
                        "rest": [],
                        "scores": [
                            -1
                        ],
                        "time": [
                            -1
                        ],
                        "restAfterGroup": 300
                    },
                    {
                        "rest": [
                            10,
                            5
                        ],
                        "scores": [
                            -1,
                            -1,
                            -1
                        ],
                        "time": [
                            -1,
                            -1,
                            -1
                        ],
                        "restAfterGroup": 100
                    },
                    {
                        "rest": [
                            -10,
                            -5,
                            -10,
                            -5
                        ],
                        "scores": [
                            -1,
                            -1,
                            -1,
                            -1,
                            -1
                        ],
                        "time": [
                            -1,
                            -1,
                            -1,
                            -1,
                            -1
                        ],
                        "restAfterGroup": 0
                    }
                ]
            },
            {
                "name": "动作02",
                "id": 2,
                "video": "https://1",
                "motions": [
                    [
                        {
                            "bone1": [
                                "left_shoulder",
                                "left_hip"
                            ],
                            "bone2": [
                                "left_shoulder",
                                "left_elbow"
                            ],
                            "startAngle": 0,
                            "endAngle": 30
                        }
                    ]
                ],
                "groups": [
                    {
                        "rest": [],
                        "scores": [
                            -1
                        ],
                        "time": [
                            -1
                        ],
                        "restAfterGroup": 300
                    },
                    {
                        "rest": [
                            -10,
                            -5
                        ],
                        "scores": [
                            -1,
                            -1,
                            -1
                        ],
                        "time": [
                            -1,
                            -1,
                            -1
                        ],
                        "restAfterGroup": 100
                    },
                    {
                        "rest": [
                            -10,
                            -5,
                            -10,
                            -5
                        ],
                        "scores": [
                            -1,
                            -1,
                            -1,
                            -1,
                            -1
                        ],
                        "time": [
                            -1,
                            -1,
                            -1,
                            -1,

**Comment by dinomight** [comment]
I tried to reproduce this by copying your input string into a test and running it against master. I don't see the truncation. I'm wondering if it could be related to the UTF-8 characters. Have you tried removing those to see if that helps? Could this be an issue of the logger making a decision to truncate? Have you tried using `std::cout` or an output file and see if there is a difference?

**Comment by kerry999** [comment]
sorry that it does is the issue that our own logger's buffer size is not big enough. thank your advice and sorry for bothering you.
