### ISSUE TITLE
Parse() is only parsing members with a  short name and ConstMemberIterator->name.GetString() returns nullptr on first Member

### ISSUE THREAD

**Issue by Balmm4** [Tencent/rapidjson#1959]
Hello 

I’m quite new to C++ and rapidjson, so maybe I'm doing something wrong.

I’m having two problems. 
The first problem is about parsing. Somehow only members with a name, shorter than 14 signs are getting parsed. 
I’m not able to parse the first JSON, while I’m able to parse the second one without any problems. 

This JSON I cannot parse:

    {
        "WaveGeneration.inner_barker": 0,
        "WaveGeneration.outer_barker": 7,
        "WaveGeneration.waveout_mode": 1,
        "WaveGeneration.code": 0,
        "Measure_Control.delay_up_down": 500,
        "Measure_Control.delay_code_down": 500,
        "Measure_Control.delay_adc_pre": 3380,
        "Measure_Control.delay_adc_past": 3380,
        "Measure_Control.delay_down_sim": 500,
        "Measure_Control.path_length": 10,
        "Measure_Control.water_temperature": 10,
        "Measure_Control.path_angle": 7.8
    }

This JSON is parsed correctly:

    {
        "outer_barker": 7,
        "outer_barker": 7,
        "inner_barker": 0,
        "waveout_mode": 1,
        "code": 0,
        "delay_up_down": 500,
        "d_code_down": 500,
        "delay_adc_pre": 3380,
        "d_adc_past": 3380,
        "delay_down_si": 500,
        "mode": 0,
        "target": 0,
        "forced": 0,
        "skipCalc": 0,
        "nMeasurements": 1,
        "path_angle": 7.8,
        "path_length": 10,
        "water_tempera": 10
    }

This is how I parse:

    bool SystemControl::parse(std::string str){
    
        rapidjson::Document JDoc;

        // Parsing JSON if expected
        if(JSONExpected_){
            JDoc.Parse(str.c_str());
            if (JDoc.IsObject() && !JDoc.HasParseError()){
                
                for (rapidjson::Value::ConstMemberIterator itr = JDoc.MemberBegin(); itr != JDoc.MemberEnd(); itr++){
                        if(nullptr != itr->name.GetString()){
                            std::cout << "Name: " << itr->name.GetString() << "Value: " << itr->value.GetInt() << std::endl;
                        } else {
                            // I'm landing always here on first iteration
                            std::cout << "String is nullptr!" << std::endl;
                            std::cout << "Value: " << itr->value.GetInt() << std::endl;
                        }
                }

                hwConfig_->setConfig(&JDoc);
                std::cout << "Parsed JSON successfully!" << std::endl;
            } else {
                std::cerr << "Failed parsing JSON" << std::endl;
            }
            JSONExpected_ = false;
        }
    }

The code snippet above is slightly adapted. It shows the file SystemControl.cpp. The rapidjson::Document is defined in the corresponding header and not within this function as shown in the snippet above. 

The other problem is about the  ConstMemberIterator. When I try to access the Name of the first member, I always get a nullptr returned. The odd thing is, that I can access the value of the first member without any problems. I tried to swap the members, with the same result. Additionally, the first Member gets found with the HasMemeber() method. 

My target is Xilinx Zynq ZC702, which has a ARM Cortex A9 processor. Consequently I’m cross-compiling (arm-none-eabi-g++), with a toolchain provided by Xilinx. 

Since this is the first time I’m creating an Issue on GitHub, I apologize in advance if this post violates any rules. Please let me know if you want me to change anything or if more information is needed. 

thanks in advance for any advice!

**Comment by Balmm4** [comment]
Hello Dinomight

Thank you very much for your effort. 
Meanwhile I've decided to use a JSON-Library which is more suitable for embedded context.

**Comment by dinomight** [comment]
Do you mind letting me know what that library is? I'm just generally curious what made that other library more suitable.

**Comment by Balmm4** [comment]
No I don't mind at all. It is [ArduinoJSON](https://arduinojson.org/). 

The library convinces me because it is specifically designed for systems with little RAM, is thread-safe and is also very well documented. 
I still think rapidjson is a great library, but not necessarily the best choice for my use case. 

Thank you again for your efforts and development work!
