### ISSUE TITLE
Parser class with a SchemaDocument member

### ISSUE THREAD

**Issue by KimBP** [Tencent/rapidjson#1972]
Hi

I'm trying to make a 'parser' object containing a schema, but it seems like it can be done only with a heap allocated schema.
What I would like to do is to do something like this:

```
class Parser {
public:   
   Parser() 
   {
      1 Create rapidjson::Document from my schema source
      2 Check for Parse errors
      3 Convert /assign to schemaDoc
    }
    ~Parser() {}

private:
  rapidjson::SchemaDocument schemaDoc;
}
```

Apparently SchemaDocument only has a move-constructor and a constructor taking a Document.

I could provide the Document as an option to my parser like this:
```
: 
public:
    Parser(rapidjson::Document doc) : schemaDoc(doc) {}
:
```

But that require code outside my class to have rapidjson knowledge - which isn't preferable.
Alternatively I could make a 'ParserCreate function' - but then again I think that will require the complete Parser to be heap allocated 

Am I right in these observations or am I missing something in respect to the SchemaDocument class?

**Comment by dinomight** [comment]
One trick to get around the only public constructor taking a document is to invoke a method that returns a document. Something like this:
```cpp
class Parser
{
public:
    Parser() :
        schemaDoc_(LoadDocument())
    {
    }

private:
    rapidjson::Document LoadDocument()
    {
        // Create document
        // Check for errors
        // return document
    }

    rapidjson::SchemaDocument schemaDoc_;
};
```

I would say the trickiest bit is what you do when there is a load error. Your only option would be to throw an exception. If that's not acceptable, you may have to stick with heap allocation and check if you were able to successfully create the schema document. With options like `std::unique_ptr`, heap allocation isn't a huge issue unless you are on a constrained platform.

**Comment by KimBP** [comment]
Thanks
That's a fine solution. Don't know why I didn't see that myself. 😊 

I'm not so worried about 'load error'. I'm on an embedded platform and the schema comes from a static const array, so I'll simply add an assert to ensure any problems are located before releasing the SW.

Having the schema itself as static const in flash would be even better, but I doubt that is possible.

I'll immediately remove my current std::unique_ptr solution
