### ISSUE TITLE
Seeing Duplicate Objects in PrettyWriter Ouput After EraseMember

### ISSUE THREAD

**Issue by tysenmoore-xse** [Tencent/rapidjson#2012]
I am seeing a problem where I do an erase and the stringified output after the erase has two of the same object. The basic code operation is:

- Add a "version"
- Move an object "bdd" to a new member "netBldr"
- Erase the original "bdd"--which is obviously null at this point
- Verify there are no duplicates in the object
- Stringify/dump the object--at this point there is a duplicate "netBldr" object

I have narrowed the issue down to two possible lines within the example below.

1. If I remove the AddMember("version") (at "PROBLEM AREA 1?") the final stringified output is as expected (i.e. only a single "netBldr" object).
2. If I remove the EraseMember("bdd") (at "PROBLEM AREA 2?") the final stringified output is as expected (i.e. only a single "netBldr" object).

So leaving either of the two lines I've identified in the code I get a duplicate "netBldr" object in the stringified output. 

I also learned that if I add the version Member to an object outside of the root object I get no duplicates and the EraseMember is fine. For example,
Change `rootExtObj->AddMember( "version", 0, alloc );` to `extObj->AddMember( "version", 0, alloc );`

It is unclear when stepping through the code why either of these operations is causing a problem in the stringified output. I have a couple questions:

1. Is there something obvious to you that I should not be doing that is causing the problem?
2. Could the problem just be in the PrettyWriter and not in the two operations I've identified, but what could be causing this issue there?
 
Any suggestions would be MUCH appreciated. 

```cpp

#include "rapidjson/pointer.h"

TEST(PrettyWriter, eraseDouble)
{
    Value*                       extObj;
    Value*                       rootExtObj;
    Document                     doc;
    Document::AllocatorType&     alloc  = doc.GetAllocator();
    const char testData[] = R"~#~(
{
  "ext": [
    {
      "name": "Name Here",
      "vendor": "Vendor Here",
      "data": {
        "bdd": {
          "networks": {},
          "nodes": {},
          "streams": {},
          "peripheralCfg": {},
          "tdm": {}
        },
        "nodeSim": {
          "overrides": {}
        },
        "other": {
          "tdm": []
        }
      }
    } ]
}
)~#~";
    
    auto dumpJson = [&doc]()
    {
        StringBuffer buffer;
        PrettyWriter<StringBuffer> writer(buffer);

        if (doc.Accept(writer))
        {
            std::cout << buffer.GetString() << "\n";
        }
        else
        {
            std::cout << ">>>ERROR>>>" << buffer.GetString() << "<<<ERROR<<<\n";
        }
    };

    doc.Parse( testData );

    rootExtObj = Pointer( "/ext/0" ).Get(doc);
    extObj     = &(*rootExtObj)["data"];

    extObj->AddMember( "netBldr", Value(kObjectType).Move(), alloc );

    // PROBLEM AREA 1?
    rootExtObj->AddMember( "version", 0, alloc );
    // Also tried:
    //rootExtObj->AddMember( "version", Value(kNumberType).Move(), alloc );
    //(*rootExtObj)["version"].SetInt(0);

    dumpJson();

    // Move the old object as is to the new location
    (*extObj)["netBldr"].AddMember( "hmiData", (*extObj)["bdd"], alloc );

    dumpJson();
    //-------------------------------------------------------------
    // RESULT: 
    // - "bdd" is null (as expected)
    // - "netBldr" is populated (as expected)
    //-------------------------------------------------------------

    // PROBLEM AREA 2?
    extObj->EraseMember( "bdd" );

    for (Value::ConstMemberIterator itr = extObj->MemberBegin(); itr != extObj->MemberEnd(); ++itr)
    {
        std::cout << itr->name.GetString() << "\n";
    }
    //-------------------------------------------------------------
    // OUTPUT: (no duplicate detected)
    // nodeSim
    // other
    // netBldr
    //-------------------------------------------------------------

    dumpJson();
    //-------------------------------------------------------------
    // RESULT: If you look at the output "netBldr" is repeated!
    //-------------------------------------------------------------

} // PrettyWriter.eraseDouble
```

For somewhere to test I placed the test in `test/unittest/prettywriter.cpp`.

Ran the test for `build` using:
`./bin/unittest --gtest_filter="PrettyWriter.eraseDouble"`

OS: Ubuntu 18.04
Compiler: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Tested using rapidjson: 8261c1ddf43f10de00fd8c9a67811d1486b2c784

**Comment by miloyip** [comment]
After `rootExtObj->AddMember( "version", 0, alloc );`, `extObj` as a pointer is no-longer valid.
This is similar to modifying a C++ container, then the previously created iterators will become invalid.

**Comment by tysenmoore-xse** [comment]
Once you point it out it id perfectly clear. Thanks so much for your time and help!
