### ISSUE TITLE
Json data is incomplete when add a double value with “inf”

### ISSUE THREAD

**Issue by hagen666** [Tencent/rapidjson#2029]
Rapidjson version：1.1.0

when AddMember has a double with value 'inf', the json is incomplete:
running the following code will output an incomplete json：
```
    rapidjson::Document doc(rapidjson::kObjectType);
    double f = 0.0;
    double d = 1.0/f;
    doc.AddMember(rapidjson::Value("result", doc.GetAllocator()).Move(),
                   rapidjson::Value(d).Move(), doc.GetAllocator());
    rapidjson::StringBuffer buffer;
    rapidjson::Writer<rapidjson::StringBuffer> writer(buffer);
    doc.Accept(writer);
    std::cout << buffer.GetString() << std::endl;
``` 

the output is : {"result":
The json is incomplete when the variable d is assigned or computed by user.

中文：
使用rapidJson的AddMember方法添加一个double值，当这个double值为inf时（即除以double 0时），会导致输出的json被截断，不是完整的json值。一个inf的double值可以由这样的代码得到：
```
    double f = 0.0;
    double d = 1.0/f;
```
如果这个值由用户输入或者前置计算中没有进行规避，此时不会输出完整的json。

**Comment by miloyip** [comment]
`doc.Accept()` returns false when it failed.
inf/nan is not supported in JSON standard.

**Comment by miloyip** [comment]
Use `kWriteNanAndInfFlag` to permit non-standard output of nan/inf.

**Comment by hagen666** [comment]
OK, I'll try it later.
