### ISSUE TITLE
Crash if a nested array doesn't exist

### ISSUE THREAD

**Issue by RCECoder** [Tencent/rapidjson#2060]
I use this code to access a complex array nested inside objects and arrays
`const Value& items = d["Object"]["Object"]["Array"][3]["Object"]["Object"]["Object"]["Array"][0]["Object"]["Array"][0]["Object"]["Array"].GetArray();
`

If the above doesn't exist, app will crash. Otherwise it works fine. All functions crash `GetStringLength()`, `GetString()` etc.

How to check the existence of this array before touching it?

**Comment by miloyip** [comment]
Seems [Pointer](https://rapidjson.org/md_doc_pointer.html) is a good fit for this.

**Comment by RCECoder** [comment]
Thanks for this. How do you iterate the array? 
`items[i]["title/title/text"].GetStringLength()`
No longer works and returns 0 when using the Pointer method. Was working with the reference.

**Comment by miloyip** [comment]
You need to check the document about how to use `Pointer`.
`Pointer` can be resolved on `Value` (not only `Document` root). For example, after iteration, you get an `v` of `Value&`, you can get a descendent  by resolving a `Pointer` on `v`.

**Comment by RCECoder** [comment]
This is fixed by using the `Pointer` as suggested. Thank you.
