### ISSUE TITLE
Sort question about nested array

### ISSUE THREAD

**Issue by CharlesMengCA** [Tencent/rapidjson#2064]
Hi 

If I want to sort not only the object, but also the nested array, how can I do?

{
    "delta": 123,
    "alpha": ["Fiat", "BMW", "Ford"],
    "gama": "test string",
    "zeta": false
}

The expected result:

{
    "alpha": [
        "BMW",
        "Fiat",
        "Ford"
    ],
    "delta": 123,
    "gama": "test string",
    "zeta": false
}

**Comment by sharmadhiraj86** [comment]
I want to contribute to solve this issue. So please if you can assign this issue to be, it would be very helpful.

**Comment by sharmadhiraj86** [comment]
@CharlesMengCA

**Comment by sharmadhiraj86** [comment]
@miloyip @pagict @esrrhs @yunchenglu

**Comment by sharmadhiraj86** [comment]
I would like to contribute to solve this issue. So if possible, can you please assign this issue to me and help me with some resources for the issue? @CharlesMengCA @miloyip @pagict @esrrhs @piratf @Alex-duzhichao @yunchenglu @jnicholls @leolchat @steveire @thedrow @kkaefer @spl @gadomski @yhager @mloskot @jollyroger @danvk @pah @ChrisLundquist @martinlindhe @kolya7k @rkoshy @rkoshy @fmalita @yurikhan @ludocode @thorade @patcheng @patcheng @drewnoakes @lelit

**Comment by yurikhan** [comment]
Firstly, why are you tagging everybody here? I, for one, have no decision making powers here.

Secondly, object property keys are always strings and in well-formed JSON objects they are unique, so sorting properties by key is well-defined and semantic-preserving. On the other hand, arrays can contain elements of different types, including sub-arrays and sub-objects, and their order is significant. It is neither possible to define an universal ordering for sorting, nor generally desirable to sort array elements in the library.

@CharlesMengCA: If in your particular application, for some particular array, the element order is insignificant and you know exactly the type of elements, you can sort them yourself. I believe `GenericValue::Begin()` and `GenericValue::End()` methods will give you a pair of iterators that you can stick into the `std::sort` algorithm along with a comparison predicate applicable to your values.

I suggest that no changes to the library are necessary in this relation, and that this issue should be closed.

**Comment by jnicholls** [comment]
Couldn’t have said it better myself @yurikhan.

**Comment by CharlesMengCA** [comment]
yurikhan, thank you for your offer!

I finally figured it out by reading those examples. As a C++ newbie, here is my code.  Maybe have lots of problems or errors, but it works like I expected

https://github.com/CharlesMengCA/DisplayJSONFiles/blob/master/WinMergeScript.cpp

**Comment by yurikhan** [comment]
> but it works like I expected

Yeah, that’s because your expectations are low.

Your plugin will crash trying to sort these arrays:

```
[42, "hello", {"name": "joe"}]
["hello", {"name": "joe"}, 42]
[{"name": "joe"}, "hello", 42]
```

all for different reasons.
