### ISSUE TITLE
If an array is too long, the json string will be incomplete.

### ISSUE THREAD

**Issue by Ircon** [Tencent/rapidjson#2106]
# environment
Ubuntu 18.04.6 LTS
CMake version 3.10.2
rapidjson v1.1.0
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 

# codes and questions
I am uploading the data to server by mqtt and I need to upload a lot of data in josn.
```c++
string laserScanMsger(const sensor_msgs::LaserScan::ConstPtr &ptr)
{
    auto pt = ptr.get();
    Document d;
    d.Parse(json_laserScan);
    Document::AllocatorType& allocator = d.GetAllocator();

    d["id"].SetInt64(9876);

    d["data"]["angle_min"].SetDouble(pt->angle_min);
    d["data"]["angle_max"].SetDouble(pt->angle_max);
    d["data"]["angle_increment"].SetDouble(pt->angle_increment);
    d["data"]["time_increment"].SetDouble(pt->time_increment);
    d["data"]["scan_time"].SetDouble(pt->scan_time);
    d["data"]["range_min"].SetDouble(pt->range_min);
    d["data"]["range_max"].SetDouble(pt->range_max);

    {
        int k = 0;
        auto data = pt->ranges;
        ROS_INFO("size is : %d", data.size());
        for(auto i = data.begin(); i != data.end(); i++) {
            d["data"]["ranges"].GetArray()
                .PushBack(Value().SetDouble(*i), allocator);
            ++k;
        }
        ROS_INFO("k is %d.", k);
    }
    {
        auto data = pt->intensities;
        for(auto i = data.begin(); i != data.end(); i++)
        {
            d["data"]["intensities"].GetArray()
                .PushBack(Value().SetDouble(*i), allocator);
        }
    }
    StringBuffer buffer;
    Writer<StringBuffer> writer(buffer);
    d.Accept(writer);
    ROS_INFO("String len: %d", buffer.GetSize());
    buffer.Flush();
    return buffer.GetString();
}
```
`ROS_INFO` is same as `printf`. 
the string `json_laserScan` is 
```c++
const char json_laserScan[] = R"json(
{
	"id":123,
	"data":{
		"angle_min":1.0,
		"angle_max":1.0,
		"angle_increment":1.0,
		"time_increment":1.0,
		"scan_time":1.0,
		"range_min":1.0,
		"range_max":1.0,
		"ranges":[],
		"intensities":[]
	}
}
)json";
```

the length of the array named `ranges`  is 360. this length is fixed.

I print the context of the return of `laserScanMsger`.
```
{"id":9876,"data":{"angle_min":0.0,"angle_max":6.2657318115234375,"angle_increment":0.01745329238474369,"time_increment":2.0483409457483504e-7,"scan_time":0.00016366243653465062,"range_min":0.15000000596046448,"range_max":8.0,"ranges":[1.9229999780654907,1.9190000295639038,1.9157500267028809,1.906000018119812,1.902999997138977,1.8990000486373901,1.8902499675750732,1.8892500400543213,1.8892500400543213,1.8862500190734863,1.8852499723434448,1.8852499723434448,1.8845000267028809,1.8852499723434448,1.8872499465942383,1.8872499465942383,1.8902499675750732,1.8892500400543213,1.8990000486373901,1.9019999504089355,1.8902499675750732,1.312999963760376,1.3380000591278076,1.9210000038146973,1.9320000410079956,1.934999942779541,1.941249966621399,1.9672499895095825,
```
the end of json string is uncomplete.
I tried to print information about the size of range array.
![image](https://user-images.githubusercontent.com/11171522/208129855-e11fac05-0157-48e6-9b11-deb4f893951e.png)

the length of ranges is correct and the `intensities` array also is not outputed.
the length of json string is same as the outputed size, `ROS_INFO` can output all context of josn string.

# wants
Is there a limit in the length of the json string?
How to set the limit for the length of the json string?

# Others
I am Chinese. I am poor at English. If you can speak Chinese, please response to me by Chinese.

**Comment by Ircon** [comment]
I find sonething about the data. there are many nulls.
![image](https://user-images.githubusercontent.com/11171522/208228385-43483f18-f13c-4ba8-bde8-6f51aae65d0a.png)

**Comment by Ircon** [comment]
The `null` is inf in data. last programment will output the inf as null.

**Comment by Ircon** [comment]
I am sure that the `inf` make rapidjson output a incomplete josn string.

**Comment by miloyip** [comment]
`inf` is not support by JSON standard.
`Writter::Accept()` return `false` to indicate error during output.
Use `kWriteNanAndInfFlag` to relax the syntax https://rapidjson.org/md_doc_sax.html#Writer

**Comment by Ircon** [comment]
thanks
