### ISSUE TITLE
rapidjson::Value::GetDouble returns not correctly

### ISSUE THREAD

**Issue by Hotege** [Tencent/rapidjson#2146]
rapidjson::Value::GetDouble() may return a result with deviation.
Example is following:
`
        double x1 = 2083.0322947900847;
        double y1 = 560.2283269191088;
        double z1 = 338.782685363364;

        const char* SOURCE = "{\
            \"X\": 2083.0322947900847,\
            \"Y\": 560.2283269191088,\
            \"Z\": 338.782685363364\
        }\0";
        rapidjson::Document doc;
        doc.Parse(SOURCE);
        double x2 = doc["X"].GetDouble();
        double y2 = doc["Y"].GetDouble();
        double z2 = doc["Z"].GetDouble();

        printf("%.16lf, %.16lf\n", x1, x2);
        printf("%.16lf, %.16lf\n", y1, y2);
        printf("%.16lf, %.16lf\n", z2, z2);
        printf("%g\n", abs(x1 - x2));
        printf("%g\n", abs(y1 - y2));
        printf("%g\n", abs(z1 - z2));

        rapidjson::Document out;
        out.Parse("{}");
        rapidjson::Document::AllocatorType& allocator = out.GetAllocator();
        rapidjson::Value wx(rapidjson::Type::kNumberType);
        wx.SetDouble(x1);
        out.AddMember("X", wx, allocator);
        rapidjson::Value wy(rapidjson::Type::kNumberType);
        wy.SetDouble(y1);
        out.AddMember("Y", wy, allocator);
        rapidjson::Value wz(rapidjson::Type::kNumberType);
        wz.SetDouble(z1);
        out.AddMember("Z", wz, allocator);
        rapidjson::StringBuffer sb;
        rapidjson::Writer<rapidjson::StringBuffer> writer(sb);
        out.Accept(writer);
        std::string cache = sb.GetString();
        printf(">>>> %s\n", cache.c_str());

        rapidjson::Document doc2;
        doc2.Parse(cache.c_str());
        double x3 = doc2["X"].GetDouble();
        double y3 = doc2["Y"].GetDouble();
        double z3 = doc2["Z"].GetDouble();
        printf("%.16lf, %.16lf\n", x1, x3);
        printf("%.16lf, %.16lf\n", y1, y3);
        printf("%.16lf, %.16lf\n", z2, z3);
        printf("%g\n", abs(x1 - x3));
        printf("%g\n", abs(y1 - y3));
        printf("%g\n", abs(z1 - z3));`

**Comment by miloyip** [comment]
Can you try `Parse<kParseFullPrecisionFlag>()`?
https://rapidjson.org/md_doc_dom.html#Parsing

**Comment by Hotege** [comment]
> Can you try `Parse<kParseFullPrecisionFlag>()`? https://rapidjson.org/md_doc_dom.html#Parsing

Yeah, it works for my high precision situation. Thanks.
