### ISSUE TITLE
Inconsistent behaviour of IsInt64 / IsUint64 / IsDouble

### ISSUE THREAD

**Issue by sesky4** [Tencent/rapidjson#2170]
Hi ! Thanks for the great work.

I'm writing code to check if a number is in range. I did a test and found something interesting.

| number               | note         | IsInt64 | IsUint64 | IsDouble | IsLosslessDouble | IsFloat | IsLosslessFloat |
|----------------------|--------------|---------|----------|----------|------------------|---------|-----------------|
| 9223372036854775807  | int64_max    | yes     | yes      | no       | no               | no      | yes             |
| 9223372036854775808  | int64_max+1  | no      | yes      | no       | yes              | no      | yes             |
| -9223372036854775808 | int64_min    | yes     | no       | no       | yes              | no      | yes             |
| -9223372036854775809 | int64_min-1  | no      | no       | yes      | yes              | yes     | yes             |
| 18446744073709551615 | uint64_max   | no      | yes      | no       | no               | no      | yes             |
| 18446744073709551616 | uint64_max+1 | no      | no       | yes      | yes              | yes     | yes             |
| 179769313486...368   | double_max   | no      | no       | yes      | yes              | no      | no              |
| -179769313486...368  | double_min   | no      | no       | yes      | yes              | no      | no              |
| 179769313486...369   | double_max+1 | no      | no       | yes      | yes              | no      | no              |
| -179769313486...369  | double_min-1 | no      | no       | yes      | yes              | no      | no              |

1. `IsDouble / IsFloat returns true for 18446744073709551616 / -9223372036854775809`
2.  `IsInt64 / IsUint64 returns false when out-of-range, but IsDouble gives true` 

My questions are:
1. Is this a bug? 
2. Is it possible to use rapidjson to detect out-of-range error ? If not, is there a way to obtain the string representation of a rapidjson::Value ? ( so i can do the validation myself )

Code to replicate:
```
int Haha() {
    std::cout << std::fixed;
    std::cout.precision(1024);
    std::cout << std::numeric_limits<int64_t>::max() << std::endl;
    std::cout << std::numeric_limits<int64_t>::lowest() << std::endl;
    std::cout << std::numeric_limits<uint64_t>::max() << std::endl;
    std::cout << std::numeric_limits<uint64_t>::lowest() << std::endl;
    std::cout << std::numeric_limits<double>::max() << std::endl;
    std::cout << std::numeric_limits<double>::lowest() << std::endl;

    std::vector<std::string> nums{
        "9223372036854775807",
        "9223372036854775808",
        "-9223372036854775808",
        "-9223372036854775809",
        "18446744073709551615",
        "18446744073709551616",
        "17976931348623157081452742373170435679807056752584499659891747680315726078002853876058955863276687817154045895"
        "35143824642343213268894641827684675467035375169860499105765512820762454900903893289440758685084551339423045832"
        "36903222948165808559332123348274797826204144723168738177180919299881250404026184124858368",
        "-1797693134862315708145274237317043567980705675258449965989174768031572607800285387605895586327668781715404589"
        "53514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583"
        "236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368",
        "17976931348623157081452742373170435679807056752584499659891747680315726078002853876058955863276687817154045895"
        "35143824642343213268894641827684675467035375169860499105765512820762454900903893289440758685084551339423045832"
        "36903222948165808559332123348274797826204144723168738177180919299881250404026184124858369",
        "-1797693134862315708145274237317043567980705675258449965989174768031572607800285387605895586327668781715404589"
        "53514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583"
        "236903222948165808559332123348274797826204144723168738177180919299881250404026184124858369",
    };
    for (const auto &num : nums) {
        std::cout << "\n\n\n";
        std::cout << num << std::endl;

        std::string num_json = "{\"hello\":" + num + "}";

        rapidjson::Document rep_json;
        rapidjson::ParseResult pr = rep_json.Parse(num_json.c_str());
        if (!pr) {
            std::cout << "parse fail" << std::endl;
            continue;
        }
        auto &val = rep_json["hello"];

        std::cout << "IsNumber: " << val.IsNumber() << std::endl;
        std::cout << "IsInt64: " << val.IsInt64() << std::endl;
        std::cout << "IsUint64: " << val.IsUint64() << std::endl;
        std::cout << "IsDouble: " << val.IsDouble() << std::endl;
        std::cout << "IsLosslessDouble: " << val.IsLosslessDouble() << std::endl;
        std::cout << "IsFloat: " << val.IsFloat() << std::endl;
        std::cout << "IsLosslessFloat: " << val.IsLosslessFloat() << std::endl;
    }
    return 0;
}
```

**Comment by miloyip** [comment]
> * Is this a bug?
> * Is it possible to use rapidjson to detect out-of-range error ? If not, is there a way to obtain the string representation of a rapidjson::Value ? ( so i can do the validation myself )

For numbers that cannot be represented in `int64_t`, `uint64_t`, they are stored as `double`, so `IsDouble()` returns `true` for those case.

There is a `kParseNumbersAsStringsFlag` but you cannot determine whether a value was originally represented as JSON number or JSON string.

**Comment by sesky4** [comment]
okay, thanks !
