### ISSUE TITLE
Veracode CWE-190 Integer Overflow or Wraparound in reader.h

### ISSUE THREAD

**Issue by spanikul** [Tencent/rapidjson#2177]
Veracode flagged CWE-190 (integer overflow or wraparound) on lines 1507 and 1519 in reader.h 

https://github.com/Tencent/rapidjson/blob/master/include/rapidjson/reader.h#L1507
https://github.com/Tencent/rapidjson/blob/master/include/rapidjson/reader.h#L1519

https://cwe.mitre.org/data/definitions/190.html

**Comment by spanikul** [comment]
changes noted below where verified with Veracode:

 include/rapidjson/reader.h | 16 ++++++++++++++--
 1 file changed, 14 insertions(+), 2 deletions(-)

diff --git a/include/rapidjson/reader.h b/include/rapidjson/reader.h
index 55546601..9ece7f5c 100644
--- a/include/rapidjson/reader.h
+++ b/include/rapidjson/reader.h
@@ -1504,7 +1504,13 @@ private:
                             break;
                         }
                     }
-                    i = i * 10 + static_cast<unsigned>(s.TakePush() - '0');
+					i64 = i * 10LL + static_cast<unsigned>(s.TakePush() - '0');
+					if (RAPIDJSON_UNLIKELY(i64 >= 214748364)) {
+						use64bit = true;
+						break;
+					}
+					else
+						i = (unsigned)i64;
                     significandDigit++;
                 }
             else
@@ -1516,7 +1522,13 @@ private:
                             break;
                         }
                     }
-                    i = i * 10 + static_cast<unsigned>(s.TakePush() - '0');
+					i64 = i * 10LL + static_cast<unsigned>(s.TakePush() - '0');
+					if (RAPIDJSON_UNLIKELY(i64 >= 214748364)) {
+						use64bit = true;
+						break;
+					}
+					else
+						i = (unsigned)i64;					
                     significandDigit++;
                 }
         }

**Comment by miloyip** [comment]
I think the current code will not overflow but the checking above:

```cpp
                    if (RAPIDJSON_UNLIKELY(i >= 214748364)) { // 2^31 = 2147483648
                        if (RAPIDJSON_LIKELY(i != 214748364 || s.Peek() > '8')) {
```

You should prove the problem with a fail unit test case.
I believe this is a false alarm.

**Comment by spanikul** [comment]
Totally agree that it will not overflow with the checks in place but I think tools like Veracode are simply not  smart enough and flag these lines of code without properly analyzing the code.  So the code that I've added is to suppress a vulnerability that gets marked Very High.

**Comment by spanikul** [comment]
OKay, thanks for the review.
