### ISSUE TITLE
How to realize eventbased / non-blocking parsing

### ISSUE THREAD

**Issue by sdettmer** [Tencent/rapidjson#2201]
Hi,

I have an application where many sources from network arrive and a stored in buffers. One has JSON messages. The application already appends received bytes on the buffer. When one message is complete, I'd like to remove it from the FIFO and send it as message event to a handler.
The application cannot parse JSON itself, so it does not know where the boundary of the message is (it does not even know when a message is complete).
According to the documentation I could use a memory stream. This possibly is straightforward when having one thread for each buffer, but I need to implement it non-blocking. 

How do I handle the situations:
1) the message in the memory region is not yet complete
2) there is more data than just one message in the memory (for example, multiple messages were received).

Does Parse considers "not yet completely received message" as error? Does it lose its parse state between each unsuccessful attempt?

How do I parse input without knowing when a message is complete?

**Comment by aikawayataro** [comment]
There's no such feature, but you can write the custom parser using code from `GenericReader` and `GenericDocument`.
Maybe you can do something with custom `Reader` or Generator with `GenericDocument::Populate` and c++20 coroutines tho.
`GenericDocument::Parse` method expects complete and valid json string.

**Comment by sdettmer** [comment]
OK, thank you. We discussed this in the team and found no proper way and don't have C++20. Using setjmp for us is not option either. We could only use a thread that fills the buffer while the reader is waiting.
