### ISSUE TITLE
JSON schema incorrect validation with array with uniqueItems

### ISSUE THREAD

**Issue by arghness** [Tencent/rapidjson#2205]
Tested against the release 1.1.0 and the latest master at the time of writing.

With the schema:

```json
{
  "$schema": "http://json-schema.org/schema#",
  "id": "http://test.com/schemas/test.schema.json",
  "type": "object",
  "properties": {
    "myArray": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object"
      }
    }
  }
}
```

And the JSON document:

```json
{
  "myArray": [
    {
      "a": "a"
    },
    {
      "b": "b"
    },
    {
      "c": "c"
    }
  ] 
} 
```

I get the following error from the schemavalidator example:

```text
Input JSON is invalid.
Invalid schema: #/properties/myArray
Invalid keyword: uniqueItems
Invalid code: 11
Invalid message: Array has duplicate items at indices '%duplicates' but 'uniqueItems' is true.
Invalid document: #/myArray/1
Error report:
{
    "uniqueItems": {
        "duplicates": [
            0,
            1
        ],
        "errorCode": 11,
        "instanceRef": "#/myArray",
        "schemaRef": "#/properties/myArray"
    }
}
Error Name: uniqueItems
Message: Array has duplicate items at indices '0,1' but 'uniqueItems' is true.
Instance: #/myArray
Schema: #/properties/myArray
```

But these objects are unique. If I change the first object in the array that it's saying is a duplicate:

```json
{
  "myArray": [
    {
      "a": "a1"
    },
    {
      "b": "b"
    },
    {
      "c": "c"
    }
  ]
}
```

I get an error with the next 2 elements instead:

```text
Input JSON is invalid.
Invalid schema: #/properties/myArray
Invalid keyword: uniqueItems
Invalid code: 11
Invalid message: Array has duplicate items at indices '%duplicates' but 'uniqueItems' is true.
Invalid document: #/myArray/2
Error report:
{
    "uniqueItems": {
        "duplicates": [
            1,
            2
        ],
        "errorCode": 11,
        "instanceRef": "#/myArray",
        "schemaRef": "#/properties/myArray"
    }
}
Error Name: uniqueItems
Message: Array has duplicate items at indices '1,2' but 'uniqueItems' is true.
Instance: #/myArray
Schema: #/properties/myArray
```

This same situation occurs with longer keys/values as well, which is where I came across the issue.

**Comment by aikawayataro** [comment]
Looks like the problem caused by buggy `Hasher` implementation, can you provide the testing code? I'll try to investigate.

**Comment by arghness** [comment]
> can you provide the testing code? I'll try to investigate.

I used the schemavalidator example https://github.com/Tencent/rapidjson/blob/master/example/schemavalidator/schemavalidator.cpp with the first schema and document in this issue post.

**Comment by aikawayataro** [comment]
Confirmed, the problem is the object hashing, the algorithm used for keys and string values is the same, the `Hasher::Hash` produce zero hash value by performing xor between them. I will land the fix to my fork soon.

**Comment by chengm204** [comment]
happy to see your question got some reply which means the project is not dead. No one tried to help 2204 yet. Anyway it's a good symptom.
