### ISSUE TITLE
DiyFp operator*() not correct

### ISSUE THREAD

**Issue by chengm204** [Tencent/rapidjson#2206]
```
    DiyFp d1{-6484.96572};
    DiyFp d2{16.30619};
    char buf[128];
    auto d_multiplies = d1*d2;
    memset(buf, 0x0, sizeof(char)*128);
    auto p = dtoa(d_multiplies, buf, 5);
    *p = '\0';
    std::cout << buf << std::endl;
```
result is 268541201.08317

by right it should be -105745.08317 if I just want precision of 5.

**Comment by chengm204** [comment]
Really wish to have some support and confidence in this project.

**Comment by aikawayataro** [comment]
I don't think your use of `DiyFp` is correct. Why do you want to use it directly? It's not a user-friendly class at all, but you can look for actual usage in RapidJSON internals.

**Comment by chengm204** [comment]
whether I used it correctly is another issue. Since there is such a public interface operator*(), should it work? I quickly checked RapidJSON internals, seems there is no DiyFp1*DiyFp2, convert to double first?
If I call std::cout << d1.ToDouble() << std::endl;
I got 6484.9657200000001. I must have missed some design concept here.

**Comment by michalmiotk** [comment]
changing in diyfp.h line 89 from return DiyFp(h, e + rhs.e + 64); to return DiyFp(h, e + rhs.e + 52); should move your result to 65561.8 so a lot closer than before.
(based on version  - commit f9d53419e912910fd8fa57d5705fa41425428c35)

**Comment by chengm204** [comment]
Should we expect a negative value since input is minus something?

**Comment by michalmiotk** [comment]
I don't see in struct DiyFp field to store sign bit.

**Comment by chengm204** [comment]
So DiyFp is not supposed to support negative value by design?

**Comment by michalmiotk** [comment]
I think so

**Comment by chengm204** [comment]
design purpose is clear now.
