### ISSUE TITLE
Question: any guidelines for using rapidjson for parsing in web assembly (emsdk)?

### ISSUE THREAD

**Issue by manuel2a** [Tencent/rapidjson#2210]
Greetings! I'm a fan. Using `rapidjson` for a while. Awesome!

On the current project:
- we're parsing json in web assembly (empscripten/emsdk/64-bit experimental)
- c++20 requirement from another component
- we're hitting some weirdness on vanilla parsing
   - unusually high memory usage (payload 10MiB; memory usage 2GiB)
   - reversing keys in the payload makes it work/crash...

```
Document d;
string input; // read it somehow
d.parse( input );
```  

Anyone with wisdom/guidelines/gotchas/tutorials for `rapidjson + wasm`? Google is not helping :frowning_face:

**Comment by aikawayataro** [comment]
Perhaps with a minimal reproducible example I can help you.
If you succeeded in solving the problem, can you share the info for future readers?

**Comment by manuel2a** [comment]
Couldn't get `rapidjson` + `emsdk` 64 -bit working
* it's an experimental build mode -- seems like a 64-bit wrapper around a 32-bit target
   * we needed 64-bit because of another component (analytics)
* weird non-deterministic runtime errors on parsing, payload dependent

I can report that `rapidjson` + `emsdk` (32-bit) -> `wasm` totally works :heavy_check_mark:
* rolled our own analytics using `c++` standard libraries
* example: https://anyw.ai/dashboard/ai-chat-bots
