### ISSUE TITLE
dtoa can't support high precision double

### ISSUE THREAD

**Issue by chengm204** [Tencent/rapidjson#2220]
Sample double value: 59980528.1478392933

char buf[128];
memset(buf, 0x0, 128);
dtoa(value, buf, 19);

std::cout << buf << std::endl;
buf value is 59980528.14783929.

but the function signature is
inline char* dtoa(double value, char* buffer, int maxDecimalPlaces = 324)
maybe I mis-understood maxDecimalPlaces ?

**Comment by chengm204** [comment]
It seems a double's integer part + fraction part digits can't exceed certain number?

**Comment by aikawayataro** [comment]
That's a binary64 limitation (64-bit format used to represent IEEE 754).
```cpp
static_assert(59980528.1478392933 == 59980528.14783929);
```

**Comment by chengm204** [comment]
How to link these 2 facts together:
static_assert(59980528.1478392933 == 59980528.14783929);
and
-2.22507e-308 to 1.79769e+308 (which is double data range)

**Comment by aikawayataro** [comment]
> Is it possible to improve this limitation?

Not within the scope of this project. RapidJSON uses 64 bits for integers and IEEE 754 binary64 for numbers with precision (as do the vast majority of json software).



> How to link these 2 facts together:
> static_assert(59980528.1478392933 == 59980528.14783929);
> and
> -2.22507e-308 to 1.79769e+308 (which is double data range)

I don't understand why you're assume to link this, need more info for that one.

**Comment by chengm204** [comment]
What I meant is that your statc_assert is correct. And a double number can
be very large. But dtoa can only handle not very long double.

Btw, do you know other project which could print longer ( not necessary
bigger) double?

**Comment by chengm204** [comment]
What I really want to say is double value can be very big; but at the same
time, compiler wants to say sorry we can only handle this kind of value
meaningfully by static_assert.

**Comment by aikawayataro** [comment]
I couldn't find any C/C++ libraries that meet your requirements, but consider using GNU MPFR and encoding numbers as strings.

**Comment by chengm204** [comment]
explained.
