### ISSUE TITLE
IStreamWrapper does not recognize special characters like € or korean chars

### ISSUE THREAD

**Issue by AlexKayX** [Tencent/rapidjson#2226]
I try to read a utf8 encoded json file with a special character € and various korean characters.
file content:
{"test":"this is german ä ü ö and € and this is korean 가 나 다"}

Code:
std::ifstream ifs{"utf8.txt"};
rapidjson::IStreamWrapper isw{ ifs };
rapidjson::Document doc;
doc.ParseStream( isw );
const char* cc = doc["test"].GetString();
const rapidjson::Value& test = doc["test"];
std::string s = test.GetString();

neither in cc nor in test nor in s the characters are not displayed correctly.
What am i doing wrong?
Compiler is Visual Studio 2019, iso c++ 14 standard,

**Comment by pluvivanto** [comment]
I attempted to replicate the issue using the attached files  but encountered no errors. 
result: 
![image](https://github.com/Tencent/rapidjson/assets/140719273/94726d9a-6a4e-40c9-b63b-34970e14e7fc)
It seems both `cc` and `s` prints correctly as expected.
Possible reasons for the problem could be:
1. The `utf8.txt` file might have been saved with an incorrect encoding.
1. Your terminal (or the output destination) font may not support the characters used in the file.

[testcode.zip](https://github.com/Tencent/rapidjson/files/14141322/testcode.zip)

**Comment by AlexKayX** [comment]
@pluvivanto Thanks for your test. The file has the correct encoding ( your test-utf8.json file does not work either) and the output destination works well. It seems to be a compiler or a visualstudio project problem.
