### ISSUE TITLE
Build fails on macOS due to Include/rapidjson/msinttypes/stdint.h

### ISSUE THREAD

**Issue by joey-chance** [Tencent/rapidjson#2249]
I am working on a project that was initially built on Windows but I am on Mac. I am trying to build it using CLion and CMake however I got an error saying:
```
Include/rapidjson/msinttypes/stdint.h:38:2: error: "Use this header only with Microsoft Visual C++ compilers!"
#error "Use this header only with Microsoft Visual C++ compilers!"
```

I checked Include/rapidjson/msinttypes/stdint.h and found:
```
#ifndef _MSC_VER // [
#error "Use this header only with Microsoft Visual C++ compilers!"
#endif // _MSC_VER ]
```

Is there a solution to this since rapidjson is supposed to be cross-platform compatible?

**Comment by TheOtherDave** [comment]
I found this in rapidjson.h
#if defined(_MSC_VER) && (_MSC_VER < 1800)	// Visual Studio 2013
#include "msinttypes/stdint.h"
#include "msinttypes/inttypes.h"
#else
// Other compilers should have this.
#include <stdint.h>
#include <inttypes.h>
#endif
Looks to me like you probably shouldn't be including anything from the `msinttypes` directory directly, but I'm not sure.

**Comment by joey-chance** [comment]
Agreed, I excluded it from the build and it worked. Thanks!
