### ISSUE TITLE
中文key可以解析吗？

### ISSUE THREAD

**Issue by gdragone1** [Tencent/rapidjson#2291]
如题

**Comment by WangZixi2001** [comment]
可以(默认的话是utf8的)

**Comment by gdragone1** [comment]
string json_key = "对话"
json.HasMember(json_key.c_str())) 为啥会报错哇？
json.HasMember("对话") 这样就没事

**Comment by gdragone1** [comment]
求个中文使用说明哇

**Comment by WangZixi2001** [comment]
> string json_key = “对话” json。HasMember（json_key.c_str（））） 为啥会报错哇？ json。HasMember（“对话”） 这样就没事

你这个问题太多了,1.需要分配器(你得手动分配内存)2.如果你是window很可能是GBK编码,可能会乱码3.HasMember()不是添加键值对的吗,你这个参数也不对啊
看这个 https://rapidjson.org/zh-cn/

**Comment by gdragone1** [comment]
不是哦，我是解析parse操作哦，不是add操作



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月23日(星期二) 下午2:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tencent/rapidjson] 中文key可以解析吗？ (Issue #2291)














  
string json_key = “对话” json。HasMember（json_key.c_str（））） 为啥会报错哇？ json。HasMember（“对话”） 这样就没事
  
你这个问题太多了,1.需要分配器(你得手动分配内存)2.如果你是window很可能是GBK编码,可能会乱码3.HasMember()不是添加键值对的吗,你这个参数也不对啊
 看这个 https://rapidjson.org/zh-cn/

**Comment by WangZixi2001** [comment]
> 不是哦，我是解析parse操作哦，不是add操作
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年7月23日(星期二) 下午2:03 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Tencent/rapidjson] 中文key可以解析吗？ (Issue #2291) string json_key = “对话” json。HasMember（json_key.c_str（））） 为啥会报错哇？ json。HasMember（“对话”） 这样就没事 你这个问题太多了,1.需要分配器(你得手动分配内存)2.如果你是window很可能是GBK编码,可能会乱码3.HasMember()不是添加键值对的吗,你这个参数也不对啊 看这个 https://rapidjson.org/zh-cn/ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

奥上面那个看成AddMember了
那我感觉有可能是编码问题,你这问题描述的不清楚,只能简单判断
