### ISSUE TITLE
Feature request or how to implement: GetDecimal()

### ISSUE THREAD

**Issue by catdsnny** [Tencent/rapidjson#2317]
I'm parsing bitcoin JSON responses.  The fields in the JSON are of the form {"value" : 1.234}  (just example).   I want to parse this field with no loss (e.g. GetDouble() will round it).  I may be able to self-parse this with the SAX model, but it would be nice to be able to use the Document object and create a new function to perfectly parse the value with no rounding. It could be to an int64 with appropriate multiplier (such as x 10^8 or whatever). Thoughts on the best way to do this?  Thanks!

**Comment by miloyip** [comment]
You may use `kParseNumbersAsStringsFlag` to parse the numbers as string in 'Document'.
For more advanced requirement, as you said, using fixed point to represent number, you may use 'kParseNumbersAsStringsFlag' and handle the number with `RawNumber()` in `Reader` callback.
See https://rapidjson.org/md_doc_sax.html#Handler and https://github.com/Tencent/rapidjson/blob/master/example/filterkeydom/filterkeydom.cpp .

**Comment by catdsnny** [comment]
unfortunately that flag still translates the numeric to a double first

this field (in raw form)
"difficulty":0.0000152587890625

becomes this (using the string parse)
"difficulty":"1.52587890625e-05"

it looks like the only way to precisely handle large precision numbers is with SAX

thanks!

**Comment by catdsnny** [comment]
kParseNumbersAsStringsFlag works as intended - string is exactly copied with no parsing or conversion - thanks!

**Comment by catdsnny** [comment]
Works perfectly, thanks!
