### ISSUE TITLE
Example of dropping a field while parsing

### ISSUE THREAD

**Issue by danvk** [Tencent/rapidjson#613]
See [this StackOverflow question](http://stackoverflow.com/questions/36774625/skip-certain-fields-while-parsing-a-document-with-rapidjson). I'm parsing large GeoJSON files and would like to produce `Document` objects without the `coordinates` arrays, which can easily take up 75+% of the space.

I implemented a [`GenericValue` subclass](https://gist.github.com/danvk/90beec9f0387788eca9c1ba8402dbee1) which uses the SAX parser callbacks and its own stack to pull this off. It winds up roughly doubling parsing performance, so this is a very worthwhile optimization. It leaves much to be desired, however: it duplicates large amounts of code from `GenericDocument` and it's unable to build up objects in exactly the same manner, since methods like `GenericValue::SetObjectRaw` are private.

@miloyip suggested on StackOverflow that a better way to do this would be with the [`GenericDocument::Populate` method](http://rapidjson.org/md_doc_schema.html), and that I should file an issue asking for an example. So here I am :)

**Comment by miloyip** [comment]
Hi,

I have created two examples in #615 , which filters a user-specified key, and then output directly or populates a DOM.

Its usage is like this:

widget.json
~~~js
{"widget": {
    "debug": "on",
    "window": {
        "title": "Sample Konfabulator Widget",
        "name": "main_window",
        "width": 500,
        "height": 500
    },
    "image": { 
        "src": "Images/Sun.png",
        "name": "sun1",
        "hOffset": 250,
        "vOffset": 250,
        "alignment": "center"
    },
    "text": {
        "data": "Click Here",
        "size": 36,
        "style": "bold",
        "name": "text1",
        "hOffset": 250,
        "vOffset": 100,
        "alignment": "center",
        "onMouseUp": "sun1.opacity = (sun1.opacity / 100) * 90;"
    }
}}
~~~

~~~
$ filterkey image < widget.json | pretty
~~~
~~~js
{
    "widget": {
        "debug": "on",
        "window": {
            "title": "Sample Konfabulator Widget",
            "name": "main_window",
            "width": 500,
            "height": 500
        },
        "text": {
            "data": "Click Here",
            "size": 36,
            "style": "bold",
            "name": "text1",
            "hOffset": 250,
            "vOffset": 100,
            "alignment": "center",
            "onMouseUp": "sun1.opacity = (sun1.opacity / 100) * 90;"
        }
    }
}
~~~

The core thing is the `FilterKeyHandler`, which receives SAX events, filters them, and forward to the output handler. Both examples uses the same `FilterKeyHandler`. I think you may implement your own filter for your requirements.
