### ISSUE TITLE
Question about Number struct

### ISSUE THREAD

**Issue by bpeikes-tl** [Tencent/rapidjson#696]
I'm working on some code to add functionality to store the raw "string" with doubles, so they can be parsed by a fixed precision class we use.
In the changes I'm making, I would like to replace the "d" member in the Number struct, with another struct. Namely

```
struct DoubleString
{
     double d;
     char     str[32];    
}
```

I then changed some of the code to store the raw string data when parsing a double into the "str" member, so I can parse it later if needed.

My question is related to a comment at the bottom of the Number struct, which states that it the structure is 8 bytes. Are there any assumptions in the code that Number is 8 bytes? This is what the number struct would look like after the change:

```
    // By using proper binary layout, retrieval of different integer types do not need conversions.
    union Number {
#if RAPIDJSON_ENDIAN == RAPIDJSON_LITTLEENDIAN
        struct I {
            int i;
            char padding[4];
        }i;
        struct U {
            unsigned u;
            char padding2[4];
        }u;
#else
        struct I {
            char padding[4];
            int i;
        }i;
        struct U {
            char padding2[4];
            unsigned u;
        }u;
#endif
        int64_t i64;
        uint64_t u64;
        DoubleString d;
    };  // 8 bytes
```

Thoughts? We love this library, but the handling of doubles doesn't work for some of our numeric types where we can't have rounding.

**Comment by miloyip** [comment]
If it is not 8 bytes, then there will be issues for big endian. You need to add paddings to make it work.
By the way, I think an alternative is to refer to the string type, instead of storing a fixed size string. This will reduce memory usage for the whole `GenericValue` type.
