### ISSUE TITLE
Compile error on Mac OS X in document.h

### ISSUE THREAD

**Issue by jwwalker** [Tencent/rapidjson#708]
I'm trying to build the Assimp project which uses RapidJSON, using Xcode 4.6.3.  When I run `clang --version`, I get "Apple LLVM version 4.2 (clang-425.0.28) (based on LLVM 3.2svn)".  The error message is shown below.  Sorry, I can't figure out how to keep the issue editor from eating the spaces that are supposed to position carets under error locations.

contrib/rapidjson/include/rapidjson/document.h:1259:22: error: call to constructor of 'rapidjson::GenericValuerapidjson::UTF8<char, rapidjson::MemoryPoolAllocatorrapidjson::CrtAllocator >' is ambiguous
        GenericValue v(value);
                     ^ ~~~~~
contrib/rapidjson/include/rapidjson/document.h:1330:16: note: in instantiation of function template specialization 'rapidjson::GenericValuerapidjson::UTF8<char, rapidjson::MemoryPoolAllocatorrapidjson::CrtAllocator >::AddMember<unsigned long>' requested here
        return AddMember(n, value, allocator);
               ^
code/glTFAssetWriter.inl:108:13: note: in instantiation of function template specialization 'rapidjson::GenericValuerapidjson::UTF8<char, rapidjson::MemoryPoolAllocatorrapidjson::CrtAllocator >::AddMember<unsigned long>' requested here
        obj.AddMember("byteLength", b.byteLength, w.mAl);
            ^
contrib/rapidjson/include/rapidjson/document.h:634:14: note: candidate constructor
    explicit GenericValue(int i) RAPIDJSON_NOEXCEPT : data_() {
             ^
contrib/rapidjson/include/rapidjson/document.h:640:14: note: candidate constructor
    explicit GenericValue(unsigned u) RAPIDJSON_NOEXCEPT : data_() {
             ^
contrib/rapidjson/include/rapidjson/document.h:646:14: note: candidate constructor
    explicit GenericValue(int64_t i64) RAPIDJSON_NOEXCEPT : data_() {
             ^
contrib/rapidjson/include/rapidjson/document.h:661:14: note: candidate constructor
    explicit GenericValue(uint64_t u64) RAPIDJSON_NOEXCEPT : data_() {
             ^
contrib/rapidjson/include/rapidjson/document.h:673:14: note: candidate constructor
    explicit GenericValue(double d) RAPIDJSON_NOEXCEPT : data_() { data_.n.d = d; data_.f.flags = kNumberDoubleFlag; }
             ^
1 error generated.

**Comment by miloyip** [comment]
https://github.com/assimp/assimp/issues/980
