### ISSUE TITLE
GenericValue::AddMember does not accept const std::string references

### ISSUE THREAD

**Issue by yachoor** [Tencent/rapidjson#717]
[`GenericValue::AddMember`](https://github.com/miloyip/rapidjson/blob/f54b0e47a08782a6131cc3d60f94d038fa6e0a51/include/rapidjson/document.h#L1233) overload for `std::basic_string` takes non-const reference, but the comment says it should be a constant string reference. It calls `GenericValue` constructor taking a const reference, so I don't see a reason for it being non-const - probably just an omission of const keyword.

**Comment by yachoor** [comment]
The code works fine when calling:
```C++
Value o(kObjectType);
const std::string& ref = ...
o.AddMember("sth", ref, allocator);
```
but fails for:
```C++
Value o(kObjectType);
Value other = ...
const std::string& ref = ...
o.AddMember(other, ref, allocator);
```

**Comment by yachoor** [comment]
I don't know if it's a bug or I'm just using it wrong, I've ended wrapping the string in `Value` myself before calling `AddMember`.

**Comment by limdor** [comment]
In general I would say, why AddMember doesn't support const &?
We have this signature:
GenericValue& AddMember(GenericValue& name, GenericValue& value, Allocator& allocator)
but not this one:
GenericValue& AddMember(const GenericValue& name, const GenericValue& value, Allocator& allocator)

This would prevent a call like this:
dict.AddMember("table", rapidjson::Value(rapidjson::kArrayType), allocator);

Because rvalues must be const.

**Comment by miloyip** [comment]
Because of move semantics, the value is moved into the object.

**Comment by limdor** [comment]
This is true if C++11 is available, not in pre C++11

**Comment by miloyip** [comment]
RapidJSON is designed to use move semantics before C++11.
http://rapidjson.org/md_doc_tutorial.html#MoveSemantics

**Comment by limdor** [comment]
Thanks @miloyip 
Then,  should this call be done like this?
```
rapidjson::Value value_to_add(rapidjson::kArrayType)
dict.AddMember("table", value_to_add, allocator);
```

**Comment by pah** [comment]
Your example is one option in C++03.  The other option is to explicitly `Move()`  the temporary:
```cpp
dict.AddMember("table", rapidjson::Value(rapidjson::kArrayType).Move(), allocator);
```
In C++11, an rvalue reference should work out of the box.
