### ISSUE TITLE
Is SchemaDocument thread safe?

### ISSUE THREAD

**Issue by niukuo** [Tencent/rapidjson#728]
I have a class like this:

```
class MyApiHandler {

rapidjson::SchemaDocument schema_;
void Handle(rapidjson::Document json)
{
    SchemaValidator validator(schema_);
    if (!json.Accept(validator)) {
        //xxxx...
    }
}


}
```

I found that if there is some keywords in schema, it will cause heap corruption in multi-thread enviroment.
some of the known keywords: ["allOf", "pattern"]

So I wonder if SchemaDocument is thread safe?

**Comment by miloyip** [comment]
All classes in RapidJSON are designed to be reentrant.
They can be read by multiple threads but can only be written by single thread.
I think `Document` requires to be `Document &` in above code.
Please try to submit a minimal reproductible example if possible.

**Comment by niukuo** [comment]
run this will cause segfault

```
#include <rapidjson/schema.h>
#include <rapidjson/document.h>
#include <rapidjson/filereadstream.h>
#include <rapidjson/stringbuffer.h>

namespace rapidjson {

const int N = 100000;

class MyApiHandler {
    static void ParseDocument(const char *name, Document *doc)
    {
        FILE *fp = fopen(name, "r");
        char readBuffer[65536];
        FileReadStream is(fp, readBuffer, sizeof(readBuffer));
        ParseResult ok = doc->ParseStream(is);
        fclose(fp);
        assert(ok);
    }
    const SchemaDocument *schema_;
public:
    MyApiHandler() {
        Document d;
        ParseDocument("schema.json", &d);
        schema_ = new SchemaDocument(d);
    }
    ~MyApiHandler()
    {
        delete schema_;
    }
    int Validate(const Document &d)
    {
        SchemaValidator validator(*schema_);
        int ret = 0;
        for (int i = 0; i < N; ++i) {
            if (!d.Accept(validator)) {
                ret = -1;
            }
        }
        return ret;
    }
    static int Worker(MyApiHandler *hdr)
    {
        Document d;
        ParseDocument("doc.json", &d);
        return hdr->Validate(d);
    }
    static void* StartThread(void *arg)
    {
        return (void *)Worker((MyApiHandler *)arg);
    }
};

}
int main()
{
    using namespace rapidjson;
    MyApiHandler handler;
    const int n = 24;
    pthread_t th[n];
    for (int i = 0; i < n; ++i) {
        int ret = pthread_create(&th[i], NULL, MyApiHandler::StartThread, &handler);
    }
    for (int i = 0; i < n; ++i) {
        pthread_join(th[i], NULL);
    }
    printf("exit\n");
}
```

schema.json
```
{
    "type": "object",
    "properties": {
        "key1": {
            "pattern": "(abc|def)"
        }
    }
}
```
```
{
    "key1": "abc",
    "key2": "def"
}
```

**Comment by miloyip** [comment]
It is found that the internal regex is not reentrant, and cannot be safely executed by multiple threads.
I will try to fix this.

**Comment by miloyip** [comment]
The current workaround is to use the C++11 std::regex, e.g.

~~~
$g++ -std=c++11 -DRAPIDJSON_SCHEMA_USE_INTERNALREGEX=0 -I ~/github/rapidjson/include a.cpp
~~~

**Comment by niukuo** [comment]
thx. but I think there is same problem in somewhere else. I'll try to find it.

**Comment by miloyip** [comment]
Thank you for the report. I think it may be possible to run the json schema test suite in multithread ways to expose similar situation.

**Comment by niukuo** [comment]
I found that GenericSchemaValidator::GetNullHandler() will always return the same object.
so is SchemaValidatingReader not reentrant?

**Comment by miloyip** [comment]
`GetNullHandler()` should not be a problem as the object has no internal state.

**Comment by niukuo** [comment]
I found that if I use a thread-safe Stack, everything is ok.
because there are more than one thread calling RAPIDJSON_SCHEMA_HANDLE_PARALLEL_, and using a same rapidjson::Document

**Comment by miloyip** [comment]
I refactored regex and it should be thread safe. Can you help verifying it in your tests?

**Comment by niukuo** [comment]
schema.json

```
{
    "allOf": [{
        "$ref": "#/abc"
    }],
    "properties": {
        "key1": {
        }
    }
}
{
    "allOf": [{
        "$ref": "#/abc"
    }],
    "properties": {
        "key1": {
        }
    }
}
```

doc.json

```
{
    "key1": "abc",
    "key2": "def"
}
```

and i run
```
g++ a.cpp -lrt -g && ./a.out
```

and segmentfault

**Comment by miloyip** [comment]
I tried removing the duplicated schema.json and found that it will still segment fault with `schemavalidator`. I think it is due to incorrect handling of missing `$ref`.

**Comment by niukuo** [comment]
$diff rapidjson/schema.h fixed_rapidjson/schema.h
1580d1579
<         nullHandler_(true),
1609d1607
<         nullHandler_(false),
1625,1627d1622
<         if (nullHandler_) {
<             RAPIDJSON_DELETE(&outputHandler_);
<         }
1801d1795
<         nullHandler_(true),
1920c1914,1915
<         return *RAPIDJSON_NEW(OutputHandler);
---
>         static OutputHandler nullHandler;
>         return nullHandler;
1928d1922
<     bool nullHandler_;

and everything is ok.
I think there is concurrent conflicts in rapidjson::GenericDocument::stack_

**Comment by miloyip** [comment]
#770

**Comment by niukuo** [comment]
I think there is still something wrong.
```
$diff rapidjson_ok/schema.h rapidjson_bug/schema.h
1636c1636,1637
<             delete nullHandler_;
---
>             nullHandler_->~OutputHandler();
>             StateAllocator::Free(nullHandler_);
1930c1931
<         return *(nullHandler_ = new OutputHandler);
---
>         return *(nullHandler_ = static_cast<OutputHandler*>(stateAllocator_->Malloc(sizeof(OutputHandler))));
```
or segfault while using SchemaValidatingReader.
maybe stateAllocator_->Malloc is not thread-safe

**Comment by niukuo** [comment]
but i dont think the problem is solved.
