### ISSUE TITLE
How to deal with nested array by Json Pointer?

### ISSUE THREAD

**Issue by HyNet** [Tencent/rapidjson#733]
Hi, I have a problem on getting value of nested array by Json Pointer.

`{"data":[
             ["1", "2", "3"],
             ["4", "5", "6"],
             ["7","8", "9"]
           ]
 }`

Can I get value "3" in array by using `rapidjson::Pointer("/data/0/2")`?
Or, Is there a better way to deal with the nested array above?

**Comment by miloyip** [comment]
Yes, you can use `"/data/0/2"` to resolve the value "3".
But if you want to iterate all elements, you should just use `"/data"` and then iterate them by array iterator.
