### ISSUE TITLE
Error: type/value mismatch at argument 1 in template parameter list for ‘template<class Writer> class CoamBaseInfo’

### ISSUE THREAD

**Issue by zyfmix** [Tencent/rapidjson#734]
When i change template<typename Writer> from Serialize fun to class like below:

``` c
template <typename Writer>
class CoamBaseInfo : public BaseReaderHandler<UTF8<>, CoamBaseInfo<Writer>> {
public:
    CoamBaseInfo(const string& upWay, const string& opWay, const string& upInfo);
    CoamBaseInfo(const CoamBaseInfo& rhs);
    virtual ~CoamBaseInfo();

//    template <typename Writer>
    void Serialize(Writer& writer) const {

    }
    redis_command* GetAreaInfoHiRedisCmd();

protected:
    string upWay_; // [CoamBaseInfo]
    string opWay_; // [Insert|Update|Delete]
    string upInfo_;
    string upKey_; // 更新的键
};
```

and i call it in main fun like below:

``` c
int main()
{
    CoamBaseInfo<Writer> areaInfo;
    return 0;
}
```

When i compile it with g++,it crashed error like below:

``` c
type/value mismatch at argument 1 in template parameter list for ‘template<class Writer> class CoamBaseInfo’
```

Who can help me to fixed it out?

**Comment by miloyip** [comment]
The `Writer` template needs `OutputStream` template parameter:

~~~cpp
template<
    typename OutputStream,
    typename SourceEncoding = UTF8<>,
    typename TargetEncoding = UTF8<>,
    typename StackAllocator = CrtAllocator,
    unsigned writeFlags = kWriteDefaultFlags>
class Writer {
// ...
};
~~~

For example:
~~~cpp
    StringBuffer s;
    CoamBaseInfo<Writer<StringBuffer> > areaInfo("", "", "");
~~~

**Comment by zyfmix** [comment]
@miloyip Thank you for your answer. When i change it like below:
``` c
int main() {

    CoamBaseInfo<Writer<StringBuffer> > areaInfo("", "", "");
//    CoamBaseInfo coamBaseInfo;
    
}
```
and make,it crashed error:
``` bash
g++    -std=c++11   CMakeFiles/te_testor.dir/src/coam_base_info.cpp.o CMakeFiles/te_testor.dir/src/te_testor.cpp.o  -o te_testor
CMakeFiles/te_testor.dir/src/te_testor.cpp.o: In function `main':
te_testor.cpp:(.text+0xb9): undefined reference to `CoamBaseInfo<rapidjson::Writer<rapidjson::GenericStringBuffer<rapidjson::UTF8<char>, rapidjson::CrtAllocator>, rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator, 0u> >::CoamBaseInfo(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
te_testor.cpp:(.text+0x122): undefined reference to `CoamBaseInfo<rapidjson::Writer<rapidjson::GenericStringBuffer<rapidjson::UTF8<char>, rapidjson::CrtAllocator>, rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator, 0u> >::~CoamBaseInfo()'
collect2: error: ld returned 1 exit status
```
what missing?

**Comment by miloyip** [comment]
You have not implemented the constructor and destructor in your class...

**Comment by zyfmix** [comment]
i have CoamBaseInfo construct in my coam_base_info.cpp like below:
``` c
template <typename Writer>
CoamBaseInfo<Writer>::CoamBaseInfo(const string& upWay, const string& opWay, const string& upInfo) : upWay_(upWay), opWay_(opWay), upInfo_(upInfo){}

template <typename Writer>
CoamBaseInfo<Writer>::CoamBaseInfo(const CoamBaseInfo& rhs) : upWay_(rhs.upWay_), opWay_(rhs.opWay_), upInfo_(rhs.upInfo_) {}

//template<typename Writer>
//CoamBaseInfo::CoamBaseInfo() {}

template <typename Writer>
CoamBaseInfo<Writer>::~CoamBaseInfo() {}
```
could you tell me how to change it. Thank you very much.

**Comment by miloyip** [comment]
Since `CoamBaseInfo` is a template class, you need to put all its implementations in header. Otherwise the caller cannot see them and let compiler generate the specialized code.

**Comment by zyfmix** [comment]
I was confuse for this Writer template,can you give me a example for how to implementations in my [coam_base_info.hpp](http://asr.iirii.com/Documents/Open/my.zip)? I'm a new programmer in c++ . thank you very much.

**Comment by miloyip** [comment]
I think you may use `Document` for deserialization/serialization, that will be more easier than using the SAX-style API.

**Comment by zyfmix** [comment]
@miloyip , I like SAX-style API design,and used in other code.i don't know how to fixed for this problem.can you help me?

**Comment by miloyip** [comment]
But if you used SAX in other code, you should know how to use it here, I think.
I cannot help you to write your code. I do not know what the requirements are as well.
Please tell us what problem do you encounter.

**Comment by zyfmix** [comment]
I has AreaSerialInfo class inheritance from CoamBaseInfo.and want overload Serialize which has template <typename Writer> and can't set it virtual in CoamBaseInfo. wanna move template <typename Writer> to it's class.

**Comment by miloyip** [comment]
As my understanding,
1. You want to make the class possible to serialize to any writer via template (static binding). 
2. You want to make `Serialize()` polymorphic (dynamic binding).

This is not possible to fulfil these two requirements at the same time.

One possible solution is to change the first requirement, making it polymorphic. When I design RapidJSON, I have thought of this. You need to make an interface fulfil the `Handler` concept:

~~~cpp
class IWriter {
public:
    virtual ~IWriter() {}
    virtual bool Null() = 0;
    virtual bool Bool(bool b) = 0;
    virtual bool Int(int i) = 0;
    virtual bool Uint(unsigned i) = 0;
    virtual bool Int64(int64_t i) = 0;
    virtual bool Uint64(uint64_t i) = 0;
    virtual bool Double(double d) = 0;
    virtual bool RawNumber(const Ch* str, SizeType length, bool copy) = 0;
    virtual bool String(const Ch* str, SizeType length, bool copy) = 0;
    virtual bool StartObject() = 0;
    virtual bool Key(const Ch* str, SizeType length, bool copy) = 0;
    virtual bool EndObject(SizeType memberCount) = 0;
    virtual bool StartArray() = 0;
    virtual bool EndArray(SizeType elementCount) = 0;
};

class CoamBaseInfo {
    virtual Serialize(IWriter& writer);
};
~~~

And then you can implement some writers that implements this `IWriter`, for passing to `Serialize()`.

**Comment by zyfmix** [comment]
But how to defined `typedef typename SourceEncoding::Ch Ch;` with IWriter?I make it get error:
``` bash 
error: ‘Ch’ does not name a type
     virtual bool RawNumber(const Ch* str, SizeType length, bool copy = false) = 0;
```

**Comment by miloyip** [comment]
Do you need to support different character types in runtime?
If not, you can simply declare `typedef char Ch` in the class.
