### ISSUE TITLE
Build breaks with clang when examples are enabled

### ISSUE THREAD

**Issue by yurivict** [Tencent/rapidjson#761]
Errors:

```
/usr/ports/devel/rapidjson/work/rapidjson-1.1.0/include/rapidjson/pointer.h:803:36: error: 'nullptr' is incompatible with C++98 [-Werror,-Wc++98-compat]
        RAPIDJSON_ASSERT(source != NULL);
```

Adding this optiojn `-Wno-c++98-compat` helps.

**Comment by miloyip** [comment]
It looks strange as `nullptr` is not used in in `pointer.h` and other headers.
How do you build the examples?

**Comment by yurivict** [comment]
Adding ```-DRAPIDJSON_BUILD_EXAMPLES:BOOL=ON``` argument to cmake, and then running ```make```.

**Comment by jbeich** [comment]
https://github.com/freebsd/freebsd/commit/c8ed04c26b6758354853a6bed4629f71d0d01a7d behavior affects FreeBSD since 10.0. It seems Clang's `-Weverything` adds `-Wc++98-compat` even in `-std=c++11` mode. I wonder what type of spaghetti code Clang expects.

**Comment by piratf** [comment]
This issue was temporarily closed due to no response for a long time.

Please try checking it out according to the reply above.
