### ISSUE TITLE
关于GetValueByPointer的问题。

### ISSUE THREAD

**Issue by mymixing** [Tencent/rapidjson#768]
哈，找到地方提问了。

const rapidjson::Value\* pValue = NULL;
char xpath[64];
char\* pAdForm[2] = {"banner","video"};
for(int i=0; i<2; i++){
    int xlen = snprintf(xpath, sizeof(xpath)-1, "/imp/%d/%s", m_impIndex, pAdForm[i]);
    if(pValue = GetValueByPointer(rpJDoc, xpath, xlen)){
        if(i == 1){     //for video
            m_minduration = (_pValue)["minduration"].GetInt();
            m_maxduration = (_pValue)["maxduration"].GetInt();
        }
        m_Letv_w = (_pValue)["w"].GetInt();
        m_Letv_h = (_pValue)["h"].GetInt();
        break;
    }
}

这段代码，如果在98\0x下编译，由于编译器不会初始化数组，内存都是垃圾值，
这种情况就会造成偶发性断言失败的现象。

所以，如果能添这样一个模版，感觉易用性会好一点。
template <typename T, typename CharType>
typename T::ValueType\* GetValueByPointer(T& root, const CharType(&source), size_t length) {
    return GenericPointer<typename T::ValueType>(source, length).Get(root);
}

这样的话，也允许接收指针类型数据了

**Comment by esrrhs** [comment]
@mymixing 没懂什么意思，你看看最新的接口，估计可以满足你的需求了吧
