### ISSUE TITLE
Why to write three define here?

### ISSUE THREAD

**Issue by shuaitq** [Tencent/rapidjson#801]
Hello!
I see your code. And I'm very confused why you should write like following.

rapidjson.h
#define RAPIDJSON_JOIN(X, Y) RAPIDJSON_DO_JOIN(X, Y)
#define RAPIDJSON_DO_JOIN(X, Y) RAPIDJSON_DO_JOIN2(X, Y)
#define RAPIDJSON_DO_JOIN2(X, Y) X##Y

Could you tell me why?
Thanks!

**Comment by pah** [comment]
The first indirection is needed in order to expand eventual macros in `X` or `Y`:
```cpp
#define FOO foo
#define BAR bar
// without indirection - concatenates unexpanded arguments
RAPIDJSON_DO_JOIN2(FOO, BAR) // --> FOOBAR
// with indirection    - concatenates expanded arguments
RAPIDJSON_JOIN(FOO,BAR)      // --> foobar
```
The second indirection is probably no longer needed on today's preprocessors.
