### ISSUE TITLE
Rapidjson why i can query array with index only with ConstValueIterator in c++

### ISSUE THREAD

**Issue by meiry** [Tencent/rapidjson#802]
Hello all , just started to use the this great lib and i have question : 
i have this simple part of json :

    "foo" : [{
    				"Name" : "t1",
    				"things" : []
    			}, {
    				"name" : "t2",
    				"things" : []
    			}
    		],

Array that contains objects , this is part of much larger json 
rapidjson::Value& foo = jsonValue["foo"];
constructFoo(&foo);

This is the function that iterate the array of objects 

    constructFoo(rapidjson::Value* jsonValue)
    {
    for (rapidjson::SizeType i = 0; i < jsonValue->Size(); i++) 
    	{
    		rapidjson::Value& fooObj = jsonValue[i];
        }
    
    }

The jsonValue->Size() value is 2   
but the fooObj keep return the all Array foo   
and not the object per index 

This on the other hard works fine , 

    for (rapidjson::Value::ConstValueIterator itr = jsonValue->Begin(); itr != jsonValue->End(); ++itr)
    	{
    		rapidjson::Type tt = itr->GetType();  // Is type Object 
    		 
                
    	}

What is the difference ? why simple index based loop don't work ?

**Comment by miloyip** [comment]
Since `jsonValue` is a pointer in:

~~~cpp
constructFoo(rapidjson::Value* jsonValue)
~~~

So you need to dereference it to use `operator[]`, e.g.

~~~
rapidjson::Value& fooObj = (*jsonValue)[i];
~~~
