### ISSUE TITLE
After reading the source code, some question in part of allocator

### ISSUE THREAD

**Issue by okajo** [Tencent/rapidjson#805]
file :allocator.h

in the class of CrtAllocator
CrtAllocator::Realloc{
(void)originalSize; 
  if (newSize == 0) {
            std::free(originalPtr);
            return NULL;
        }
        return std::realloc(originalPtr, newSize);
}

**1. I find the parameter originalSize is not used,why need this parameter?
2. after free the originalPtr ,don not set it to NULL,this may be thread unsafe
3. the std::realloc do not consider the problem of failure of alloc** 

in the part of class MemoryPoolAllocator
MemoryPoolAllocator::Malloc{
 if (chunkHead_ == 0 || chunkHead_->size + size > chunkHead_->capacity)
            if (!AddChunk(chunk_capacity_ > size ? chunk_capacity_ : size))
                return NULL;
}

**4. about the ways of chunk allocator, after AddChunk ,the original Chunk generate the memory fragmentation. how about this problem .**

**Comment by esrrhs** [comment]
@okajo  
1. other allocator implementations can use this parameter
2. originalPtr is local value, there's no thread unsafe
3. if std::realloc fail, just return the value to the allocator's caller to handle it
4.the chunk_capacity_ make every chunk big enough to avoid memory fragmentation
It is 3 year later after your question, I think you already know your question's answer by yourself. :)
