### ISSUE TITLE
Is it safe to throw exceptions from Allocators?

### ISSUE THREAD

**Issue by glebov-andrey** [Tencent/rapidjson#812]
The `Allocator` concept doesn't appear to define any exception specifications (even for `Free()`). Should it be understood then that any `Allocator` member function may throw an exception and this will not cause any resource leaks?
Obviously, it would be very wrong to throw from `Free()` but can `Malloc()` and `Realloc()` throw?
Since the library uses raw pointers a lot, can it be specified in documentation that throwing from `Malloc()`/`Realloc()` is well defined and doesn't cause resource leaks?

**Comment by esrrhs** [comment]
if realloc return null, is means there is not enough memory. so there is nothing can do but crash.
