### ISSUE TITLE
Translate doc/internals.md into Chinese

### ISSUE THREAD

**Issue by SuperSodaSea** [Tencent/rapidjson#814]
Currently ```doc/internals.md``` only have English version. I can help to translate it into Chinese if it is necessary.

**Comment by miloyip** [comment]
I am welcome for that. I am just not sure if it is needed as well.

**Comment by SuperSodaSea** [comment]
I think it is useful for those who want to know the internals of RapidJSON. The translation is working in progress.

**Comment by SuperSodaSea** [comment]
@miloyip This issue can be closed now.
