### ISSUE TITLE
"Addmember" overwriting keys in loop

### ISSUE THREAD

**Issue by saswatbORAT** [Tencent/rapidjson#819]
I'm trying to loop a map and trying to get all the keys and its values, the data coming from the map is correct but the Document is replacing its keys with the last key of the map.    

```
    rapidjson::Document doc;
    doc.SetObject();
    for(int i = 0; i < 5; i++){
        doc.AddMember(StringUtils::format("%d", i).c_str(), i, doc.GetAllocator());
    }

```
The output should be : 
`{"0":0 "1":1, "2":2, "3":3, "4":4}`

But the output is : 
`{"4":0, "4":1, "4":2, "4":3, "4":4}`

Is there any way to fix this ?

Thanks

**Comment by keke8273** [comment]
same issue here.

**Comment by keke8273** [comment]
OK, a deep copy of the key `Value` fixed the problem for me. 

```
      for (auto& file : files)
      {
          auto filename = file.stem().string();

          rapidjson::Value key(filename.c_str(), record_json.GetAllocator());

          record_json.AddMember(key, component_json, record_json.GetAllocator());
      }

```

**Comment by rodney-b** [comment]
I'm having the same issue but deep copying didn't help. I have something similar to the following:

```
        rj::Document myArray(rj::kArrayType);

        for (unsigned int i = 0; i < result.size(); i++) {
                rj::Document doc(rj::kObjectType);
                rj::Document::AllocatorType& docAllocator = doc.GetAllocator();

                rj::Value myId(result[i].c_str(), docAllocator);

                doc.AddMember(rj::StringRef(idKey), myId, docAllocator);

                rj::Value tmpCopy(doc, docAllocator);
                myArray.PushBack(tmpCopy, docAllocator);
         }
```

At the end, myArray contains an array with all the same values, being the last value of result[i]. 

Instead of myId being 1,2,3,4,5 it's just 5,5,5,5,5.

**Comment by miloyip** [comment]
@rodney-b Use `myArray.GetAllocator()`.

**Comment by miloyip** [comment]
A document owns a default allocator, which is used for allocating memory for values. When a document is destructed, its allocator also free all memory it allocated.
So normally the values should have the same life cycle as the document.

**Comment by rodney-b** [comment]
Then does it just happen that when the doc allocator is created again in the next iteration it's put in the same memory location as the one that was previously destroyed and hence previous objects that were assigned the destroyed allocators are getting the value of the new allocator is holding?
