### ISSUE TITLE
DigitGen in dtoa.h

### ISSUE THREAD

**Issue by nicolaichuk** [Tencent/rapidjson#822]
in function DigitGen https://github.com/miloyip/rapidjson/blob/master/include/rapidjson/internal/dtoa.h line 103

`   // kappa = 0`
`    for (;;) {`
`        p2 *= 10;`
`        delta *= 10;`
`        char d = static_cast<char>(p2 >> -one.e);`
`        if (d || *len)`
`            buffer[(*len)++] = static_cast<char>('0' + d);`
`        p2 &= one.f - 1;`
`        kappa--;`
`        if (p2 < delta) {    // <===========================================   line 103`
`            *K += kappa;`
`            int index = -static_cast<int>(kappa);`
`            GrisuRound(buffer, *len, delta, p2, one.f, wp_w.f * (index < 9 ? kPow10[-static_cast<int>(kappa)] : 0));`
`            return;`
`        }`
`}`

may be need change " p2 < delta" to "p2 <= delta"

**Comment by nicolaichuk** [comment]
ping...

**Comment by miloyip** [comment]
Can you elaborate?
