### ISSUE TITLE
GetInteger()

### ISSUE THREAD

**Issue by sagaceilo** [Tencent/rapidjson#823]
Hello,

I'd propose new accesor to GenericValue:

```
    int GetInteger() const {
        RAPIDJSON_ASSERT(IsNumber());
        if ((data_.f.flags & kIntFlag) != 0)                   return data_.n.i.i; // exact type, no conversion.
        if ((data_.f.flags & kDoubleFlag) != 0)                return static_cast<int>(data_.n.d);   double -> int (may lose precision)
        if ((data_.f.flags & kUintFlag) != 0)                  return static_cast<int>(data_.n.u.u); // unsigned -> int 
        if ((data_.f.flags & kInt64Flag) != 0)                 return static_cast<int>(data_.n.i64); // int64_t -> int (may lose precision)
        RAPIDJSON_ASSERT((data_.f.flags & kUint64Flag) != 0);  return static_cast<int>(data_.n.u64); // uint64_t -> int (may lose precision)
    }
```

Why ? There is already GetDouble()/GetFloat() that does 'smart' casting based on value flags. There is no hovewer such thing for integer type. It'd be usefull to have one, so You could simply use:

```
if( value.IsNumber() )   return value.GetInteger();
```

Without worrying of exact internal type (as You would expect from GetDouble() and GetFloat() ).
Doing static_cast<int>( GetFloat() ) could solve this without touching with the API but that introduces some extra casting (may loose some bits ?)

Right now lets say I'm expecting integer but someone wrote 10.0 and vice versa. Just for sake of not trashing code all over the place checks for both integer and float or writing new wrappers.... ;)

If I'm wrong or there is another way to get Integer out of GenericValue with 'smart' way, I'd be pleased to hear ;) Thanks and looking for hearing from You.

**Comment by miloyip** [comment]
I think there are too many option combinations for implementing this function.

`static_cast` in your proposed code will generate various undefined behaviour, not just losing precision. For example, Many `double` are not in the range of `int`.

You may use `GetDouble()` instead, and then check whether it fits your desired integer type, and then do the casting.
