### ISSUE TITLE
FindMemberPtr

### ISSUE THREAD

**Issue by OlafvdSpek** [Tencent/rapidjson#826]
A variant returning a pointer instead of an iterator allows one to write simpler code. No use of MemberEnd() is necessary at the call site and -> value can be skipped too.
Could you add such a FindMemberPtr?

```
inline const rapidjson::Value* find_ptr(const rapidjson::Value& v, const char* k)
{
	if (!v.IsObject())
		return NULL;
	auto i = v.FindMember(k);
	return i == v.MemberEnd() ? NULL : &i->value;
}
```

**Comment by miloyip** [comment]
I think this is kind of a helper function, which may not be suitable to add into the API.
You may also try using the JSON Pointer API for similar usage.

**Comment by OlafvdSpek** [comment]
Right, it should be provided as a non-member function.
I'll have a look at the pointer API.

**Comment by OlafvdSpek** [comment]
Why was this closed?
