### ISSUE TITLE
How to build for iOS?

### ISSUE THREAD

**Issue by michaeleisel** [Tencent/rapidjson#828]
Hi, I tried building with instructions given, but it tells me that the project was built for OS X. How can I build for iOS?

**Comment by michaeleisel** [comment]
I guess it works by just putting the .h files in there, but then I'm losing the changes from the CMake file

**Comment by hondero2552** [comment]
Yes Michael, you don't have the build the library as is a header library. It would be better to define what you need to before including the headers and that way you will have it set like you want to. What is it that you are trying to do?
