### ISSUE TITLE
Error compilation Ubuntu 14.04

### ISSUE THREAD

**Issue by pamarinp** [Tencent/rapidjson#834]
Hi,

I have a bunch of errors while compiling the rapidjson from the steps in the tutorial: 

> `git clone https://github.com/miloyip/rapidjson

> cd rapidjson

> git submodule update --init

> mkdir build

> cd build

> cmake ..

> make

> sudo make install`

While the "make" step, these errors appear (I am not showing all of them)
> 
> `Linking CXX executable ../bin/jsonx
> [ 18%] Built target jsonx
> Scanning dependencies of target messagereader
> [ 20%] Building CXX object example/CMakeFiles/messagereader.dir/messagereader/messagereader.cpp.o
> Linking CXX executable ../bin/messagereader
> [ 20%] Built target messagereader
> Scanning dependencies of target schemavalidator
> [ 22%] Building CXX object example/CMakeFiles/schemavalidator.dir/schemavalidator/schemavalidator.cpp.o
> In file included from /home/lsi-ros/catkin_ws/src/icab_project/tmp/rapidjson/example/schemavalidator/schemavalidator.cpp:7:0:
> /home/lsi-ros/catkin_ws/src/icab_project/tmp/rapidjson/include/rapidjson/schema.h: In instantiation of ‘static const ValueType& rapidjson::internal::Schema<SchemaDocumentType>::GetTypeString() [with SchemaDocumentType = rapidjson::GenericSchemaDocument<rapidjson::GenericValue<rapidjson::UTF8<> > >; rapidjson::internal::Schema<SchemaDocumentType>::ValueType = rapidjson::GenericValue<rapidjson::UTF8<> >]’:
> /home/lsi-ros/catkin_ws/src/icab_project/tmp/rapidjson/include/rapidjson/schema.h:390:65:   required from ‘rapidjson::internal::Schema<SchemaDocumentType>::Schema(SchemaDocumentType*, const PointerType&, const ValueType&, const ValueType&, rapidjson::internal::Schema<SchemaDocumentType>::AllocatorType*) [with SchemaDocumentType = rapidjson::GenericSchemaDocument<rapidjson::GenericValue<rapidjson::UTF8<> > >; rapidjson::internal::Schema<SchemaDocumentType>::PointerType = rapidjson::GenericPointer<rapidjson::GenericValue<rapidjson::UTF8<> > >; rapidjson::internal::Schema<SchemaDocumentType>::ValueType = rapidjson::GenericValue<rapidjson::UTF8<> >; rapidjson::internal::Schema<SchemaDocumentType>::AllocatorType = rapidjson::CrtAllocator]’
> /home/lsi-ros/catkin_ws/src/icab_project/tmp/rapidjson/include/rapidjson/schema.h:1350:9:   required from ‘rapidjson::GenericSchemaDocument<ValueType, Allocator>::GenericSchemaDocument(const ValueType&, rapidjson::GenericSchemaDocument<ValueType, Allocator>::IRemoteSchemaDocumentProviderType*, Allocator*) [with ValueT = rapidjson::GenericValue<rapidjson::UTF8<> >; Allocator = rapidjson::CrtAllocator; rapidjson::GenericSchemaDocument<ValueType, Allocator>::ValueType = rapidjson::GenericValue<rapidjson::UTF8<> >; rapidjson::GenericSchemaDocument<ValueType, Allocator>::IRemoteSchemaDocumentProviderType = rapidjson::IGenericRemoteSchemaDocumentProvider<rapidjson::GenericSchemaDocument<rapidjson::GenericValue<rapidjson::UTF8<> > > >]’
> /home/lsi-ros/catkin_ws/src/icab_project/tmp/rapidjson/example/schemavalidator/schemavalidator.cpp:42:24:   required from here
> /home/lsi-ros/catkin_ws/src/icab_project/tmp/rapidjson/include/rapidjson/schema.h:883:63: error: conversion to ‘rapidjson::SizeType {aka unsigned int}’ from ‘long unsigned int’ may alter its value [-Werror=conversion]
>          static const ValueType v(s, sizeof(s) / sizeof(Ch) - 1);\
>                                                                ^
> /home/lsi-ros/catkin_ws/src/icab_project/tmp/rapidjson/include/rapidjson/schema.h:894:5: note: in expansion of macro ‘RAPIDJSON_STRING_’
>      RAPIDJSON_STRING_(Type, 't', 'y', 'p', 'e')
>      ^
> `

Most of them are the same type, any ideas?

**Comment by lichray** [comment]
Compiler version please.

**Comment by ashok012** [comment]
I am facing the similar issue on RHEL7, gcc version is 4.8.5.
