### ISSUE TITLE
rapidjson::SetValueByPointer() doesn't take const char*?

### ISSUE THREAD

**Issue by xlqian** [Tencent/rapidjson#838]
`SetValueByPointer` doesn't take `const char * ` as its second argument while rapidjson::Pointer() can actually take `const char *`, is there a reason why it's done in that way? 

(I'd like to open a PR for that, but i need to be sure that is reasonable)

Thank you

**Comment by xlqian** [comment]
Sorry my bad...

**Comment by miloyip** [comment]
I think they are `const`.

~~~cpp
template <typename T>
typename T::ValueType& SetValueByPointer(T& root, const GenericPointer<typename T::ValueType>& pointer, const typename T::ValueType& value, typename T::AllocatorType& a) {
    return pointer.Set(root, value, a);
}

template <typename T>
typename T::ValueType& SetValueByPointer(T& root, const GenericPointer<typename T::ValueType>& pointer, const typename T::Ch* value, typename T::AllocatorType& a) {
    return pointer.Set(root, value, a);
}
~~~

 If you find specific ones that are incorrect, please tell me.
