### ISSUE TITLE
Inttypes.h handling in VS when using older platform toolsets 

### ISSUE THREAD

**Issue by sully7** [Tencent/rapidjson#843]
When using a newer version of VS (2013, 2015, etc) but compiling to an older platform toolset (v100, lets say, for VS 2010), `inttypes.h` is not inlcuded in the environment either, and so we need to use `msinttypes/inttypes.h` as well

**Comment by sully7** [comment]
## **inttypes.h**
 - line 162 should read
`#if defined(_MSC_PLATFORM_TOOLSET ) && (_MSC_PLATFORM_TOOLSET < 120)	// Visual Studio 2013`

## msinttypes/inttypes.h 
- line 51 should read
`#if (_MSC_PLATFORM_TOOLSET >= 120)`

- line 314 should read
#endif // _MSC_PLATFORM_TOOLSET >= 120

**Comment by sully7** [comment]
Also effected is line 538 in `rapidjson.h`.

**Comment by miloyip** [comment]
Since I don't have the platform for testing this, can you create a pull request on this?

**Comment by miloyip** [comment]
@sully7 Would you like to provide a PR on this?
