### ISSUE TITLE
RawNumber() inconsistent about quotes

### ISSUE THREAD

**Issue by bbeuning** [Tencent/rapidjson#852]
When reading, RawNumber() does not look for quotes.
But when writing, RawNumber() outputs quotes (because it calls WriteString() internally).
We changed our code to use RawValue() so output does not have quotes.

We use RawNumber() for monetary values where round-off is completely unacceptable.

Thanks,

**Comment by BGC-nglass** [comment]
Also came across this when sending Reader events back into Writer, using kParseNumbersAsStringsFlag to preserve precision and was surprised to find numbers were being quoted.  

Can override as follows in derived writer implementation, which is basically what bbeuning says above.
```
    bool RawNumber(const Ch* str, rapidjson::SizeType length, bool copy = false) {
        (void)copy;
        Prefix(rapidjson::kNumberType);
        return EndValue(WriteRawValue(str, length));
    }
```
This is fine for Reader->Writer events, but wonder if you would want input checking to validate numeric digits if it were to be called in isolation.
