### ISSUE TITLE
rapidjson/reader.h Compiler Errors

### ISSUE THREAD

**Issue by SyrianBallaS** [Tencent/rapidjson#854]
I'm not sure if this makes a difference but in the Property Pages of my project I have RAPIDJSON_HAS_STDSTRING=1 and RAPIDJSON_ENDIAN=RAPIDJSON_LITTLEENDIAN.

I'm using RapidJSON 1.02 from the NuGet Package in Visual Studio 2015. I'm using it as an include path library but it seems to always come up with errors, the best I can do right now is comment where they happen or fix it to work v140 because I need document.h and that needs reader.h. I'm going to bold the actual errors.

Here are the errors from a diagnostic build:
This error doesn't seem to make any sense, I uninstalled and reinstalled rapidjson from nuget but it's still here.
1>                   Set Property: ErrorText=This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.
1>                   T**ask "Error" skipped, due to false condition; (!Exists('..\packages\rapidjson.1.0.2\build\native\rapidjson.targets')) was evaluated as (!Exists('..\packages\rapidjson.1.0.2\build\native\rapidjson.targets')).**
1>23:15:57.123     1>

These are from Reader.h, the minimal build is too vague, if you'd rather want that I can put it.

1>**c:\users\sam\documents\visual studio 2015\projects\ra_integration\packages\rapidjson.1.0.2\build\native\include\rapidjson\reader.h(403): error C2039: 'Peek': is not a member of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'**
1>                     c:\program files (x86)\microsoft visual studio 14.0\vc\include\xstring(2633): note: see declaration of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' (TaskId:18)
1>                     c:\users\sam\documents\visual studio 2015\projects\ra_integration\packages\rapidjson.1.0.2\build\native\include\rapidjson\document.h(1796): note: see reference to function template instantiation 'rapidjson::ParseResult rapidjson::GenericReader<rapidjson::UTF8<char>,rapidjson::UTF8<char>,rapidjson::CrtAllocator>::Parse<0,InputStream,rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>>(InputStream &,Handler &)' being compiled (TaskId:18)
1>                             with (TaskId:18)
1>                             [ (TaskId:18)
1>                                 InputStream=std::string, (TaskId:18)
1>                                 Handler=rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator> (TaskId:18)
1>                             ] (TaskId:18)
1>                     c:\users\sam\documents\visual studio 2015\projects\ra_integration\packages\rapidjson.1.0.2\build\native\include\rapidjson\document.h(1796): note: see reference to function template instantiation 'rapidjson::ParseResult 
****
**rapidjson::GenericReader<rapidjson::UTF8<char>,rapidjson::UTF8<char>,rapidjson::CrtAllocator>::Parse<0,InputStream,rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>>(InputStream** &,Handler &)' being compiled (TaskId:18)
1>                             with (TaskId:18)
1>                             [ (TaskId:18)
1>                                 InputStream=std::string, (TaskId:18)
1>                                 Handler=rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator> (TaskId:18)
1>                             ] (TaskId:18)
1>                     c:\users\sam\documents\visual studio 2015\projects\ra_integration\packages\rapidjson.1.0.2\build\native\include\rapidjson\document.h(1822): note: see reference to function template instantiation 'rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator> &rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>::ParseStream<0,Encoding,InputStream>(InputStream &)' being compiled (TaskId:18)
1>                             with (TaskId:18)
1>                             [ (TaskId:18)
1>                                 Encoding=rapidjson::UTF8<char>, (TaskId:18)
1>                                 InputStream=std::string (TaskId:18)
1>                             ] (TaskId:18)
1>                     c:\users\sam\documents\visual studio 2015\projects\ra_integration\packages\rapidjson.1.0.2\build\native\include\rapidjson\document.h(1822): note: see reference to function template instantiation 'rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator> &rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>::ParseStream<0,Encoding,InputStream>(InputStream &)' being compiled (TaskId:18)
1>                             with (TaskId:18)
1>                             [ (TaskId:18)
1>                                 Encoding=rapidjson::UTF8<char>, (TaskId:18)
1>                                 InputStream=std::string (TaskId:18)
1>                             ] (TaskId:18)
1>                     c:\users\sam\documents\visual studio 2015\projects\ra_integration\ra_integration\raweb.cpp(482): note: see reference to function template instantiation 'rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator> &rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>::ParseStream<std::string>(InputStream &)' being compiled (TaskId:18)
1>                             with (TaskId:18)
1>                             [ (TaskId:18)
1>                                 InputStream=std::string (TaskId:18)
1>                             ] (TaskId:18)
1>                     c:\users\sam\documents\visual studio 2015\projects\ra_integration\ra_integration\raweb.cpp(482): note: see reference to function template instantiation 'rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator> &rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>::ParseStream<std::string>(InputStream &)' being compiled (TaskId:18)
1>                             with (TaskId:18)
1>                             [ (TaskId:18)
1>                                 InputStream=std::string (TaskId:18)
1>                             ] (TaskId:18)
1>23:15:58.325     1>
1>c:\users\sam\documents\visual studio 2015\projects\ra_integration\packages\rapidjson.1.0.2\build\native\include\rapidjson\reader.h(404): error C2039: 'Tell': is not a member of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'
1>                     c:\program files (x86)\microsoft visual studio 14.0\vc\include\xstring(2633): note: see declaration of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' (TaskId:18)
1>23:15:58.325     1>

**1>c:\users\sam\documents\visual studio 2015\projects\ra_integration\packages\rapidjson.1.0.2\build\native\include\rapidjson\reader.h(404): error C2660: 'rapidjson::GenericReader<rapidjson::UTF8<char>,rapidjson::UTF8<char>,rapidjson::CrtAllocator>::SetParseError': function does not take 1 arguments**
1>23:15:58.325     1>
**1>c:\users\sam\documents\visual studio 2015\projects\ra_integration\packages\rapidjson.1.0.2\build\native\include\rapidjson\reader.h(414): error C2039: 'Peek': is not a member of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'**
1>                     c:\program files (x86)\microsoft visual studio 14.0\vc\include\xstring(2633): note: see declaration of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' (TaskId:18)
1>23:15:58.325     1>
1>c:\users\sam\documents\visual studio 2015\projects\ra_integration\packages\rapidjson.1.0.2\build\native\include\rapidjson\reader.h(415): error C2039: 'Tell': is not a member of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'
1>                     c:\program files (x86)\microsoft visual studio 14.0\vc\include\xstring(2633): note: see declaration of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' (TaskId:18)
1>23:15:58.325     1>

**1>c:\users\sam\documents\visual studio 2015\projects\ra_integration\packages\rapidjson.1.0.2\build\native\include\rapidjson\reader.h(415): error C2660: 'rapidjson::GenericReader<rapidjson::UTF8<char>,rapidjson::UTF8<char>,rapidjson::CrtAllocator>::SetParseError': function does not take 1 arguments**
1>                     The command exited with code 2. (TaskId:18)
1>                   Done executing task "CL" -- FAILED. (TaskId:18)

**Comment by SyrianBallaS** [comment]
To make it easier I'm gonna put the code I commented out to make it build. I'll probably make custom methods or use the standard library in the meantime. This is only the stuff in rapidjson/reader.h.

Lines 295-305 (I didn't comment out the whole function but I don't think I'm gonna use it)
```
template<typename InputStream>
void SkipWhitespace( InputStream& is )
{
    internal::StreamLocalCopy<InputStream> copy( is );
    InputStream& s( copy.s );

    //  while(s.Peek( ) == ' ' || s.Peek( ) == '\n' || s.Peek( ) == '\r' || s.Peek( ) == '\t')
  //        s.Take( );
}
```

Lines 464-484
`              ```
  if(is.Peek( ) == '\0')
        {
                        RAPIDJSON_PARSE_ERROR_NORETURN( kParseErrorDocumentEmpty, is.Tell( ) );
                        RAPIDJSON_PARSE_ERROR_EARLY_RETURN( parseResult_ );
                    }
                    else
                    {
                        ParseValue<parseFlags>( is, handler );
                        RAPIDJSON_PARSE_ERROR_EARLY_RETURN( parseResult_ );

            if(!(parseFlags & kParseStopWhenDoneFlag))
            {
                SkipWhitespace( is );

                                if(is.Peek( ) != '\0')
                {
                                        RAPIDJSON_PARSE_ERROR_NORETURN( kParseErrorDocumentRootNotSingular, is.Tell( ) );
                                        RAPIDJSON_PARSE_ERROR_EARLY_RETURN( parseResult_ );
                }
            }
        }`
```

Lines 1616-1635
```
while(is.Peek( ) != '\0')
        {
            Token t = Tokenize( is.Peek( ) );
            IterativeParsingState n = Predict( state, t );
            IterativeParsingState d = Transit<parseFlags>( state, t, n, is, handler );

            if(d == IterativeParsingErrorState)
            {
                HandleError( state, is );
                break;
            }

            state = d;

            // Do not further consume streams if a root JSON has been parsed.
            if((parseFlags & kParseStopWhenDoneFlag) && state == IterativeParsingFinishState)
                break;

            SkipWhitespace( is );
        }
```
Lines 1586-1606 (Didn't comment out the whole thing)
```
   template <typename InputStream>
    void HandleError( IterativeParsingState src, InputStream& is )
    {
        if(HasParseError( ))
        {
            // Error flag has been set.
            return;
        }

        //switch(src)
        //{
        //    case IterativeParsingStartState:            RAPIDJSON_PARSE_ERROR( kParseErrorDocumentEmpty, is.Tell( ) );
        //    case IterativeParsingFinishState:           RAPIDJSON_PARSE_ERROR( kParseErrorDocumentRootNotSingular, is.Tell( ) );
        //    case IterativeParsingObjectInitialState:
        //    case IterativeParsingMemberDelimiterState:  RAPIDJSON_PARSE_ERROR( kParseErrorObjectMissName, is.Tell( ) );
        //    case IterativeParsingMemberKeyState:        RAPIDJSON_PARSE_ERROR( kParseErrorObjectMissColon, is.Tell( ) );
        //    case IterativeParsingMemberValueState:      RAPIDJSON_PARSE_ERROR( kParseErrorObjectMissCommaOrCurlyBracket, is.Tell( ) );
        //    case IterativeParsingElementState:          RAPIDJSON_PARSE_ERROR( kParseErrorArrayMissCommaOrSquareBracket, is.Tell( ) );
        //    default:                                    RAPIDJSON_PARSE_ERROR( kParseErrorUnspecificSyntaxError, is.Tell( ) );
        //}
    }
```

**Comment by StilesCrisis** [comment]
You are almost certainly misusing the library. Please post the code you wrote. Commenting out code inside the library is not going to work.

**Comment by kadst43** [comment]
I believe that I'm seeing this problem too.  I've just started trying to get rapidjson compiled in, so maybe I'm doing something wrong...

Simplifying my code down to just show the error, here's the code:

`#include "BlueprintManager.h"
#include "document.h"
#include <sstream>

using namespace rapidjson;

void BlueprintManager::processFile(const char* filename)
{
    // Load the file into a rapidjson document
    const char* json = "{\"project\":\"rapidjson\",\"stars\":10,\"subobject\":{\"number\":13.33}}";
    std::stringstream stringStream(json);
    Document document;
    document.ParseStream(stringStream);
}`

The error is on that last line (the one calling ParseStream).  I'm using VS2013, again not doing anything particularly fancy.  

It looks to me like you're calling Peek and Tell on std::stringstream, but it doesn't have members with those names (it has peek and tellg, maybe?  I'm not all that familiar with stringstream - I still usually do c-style string handling).

Here are the errors:

1>------ Build started: Project: TESAI, Configuration: Debug Win32 ------
1>Build started 5/16/2017 7:28:35 PM.
1>InitializeBuildStatus:
1>  Touching "Debug\TESAI.tlog\unsuccessfulbuild".
1>ClCompile:
1>  BlueprintManager.cpp
1>c:\soft\behavior_prototype\third-party\rapidjson\reader.h(409): error C2039: 'Peek' : is not a member of 'std::basic_stringstream<char,std::char_traits<char>,std::allocator<char>>'
1>          c:\soft\behavior_prototype\third-party\rapidjson\document.h(1703) : see reference to function template instantiation 'rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding,Encoding,Allocator>::Parse<0,InputStream,rapidjson::GenericDocument<Encoding,Allocator,rapidjson::CrtAllocator>>(InputStream &,Handler &)' being compiled
1>          with
1>          [
1>              SourceEncoding=rapidjson::UTF8<char>
1>  ,            Encoding=rapidjson::UTF8<char>
1>  ,            Allocator=rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>
1>  ,            InputStream=std::stringstream
1>  ,            Handler=rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>
1>          ]
1>          c:\soft\behavior_prototype\third-party\rapidjson\document.h(1703) : see reference to function template instantiation 'rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding,Encoding,Allocator>::Parse<0,InputStream,rapidjson::GenericDocument<Encoding,Allocator,rapidjson::CrtAllocator>>(InputStream &,Handler &)' being compiled
1>          with
1>          [
1>              SourceEncoding=rapidjson::UTF8<char>
1>  ,            Encoding=rapidjson::UTF8<char>
1>  ,            Allocator=rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>
1>  ,            InputStream=std::stringstream
1>  ,            Handler=rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>
1>          ]
1>          c:\soft\behavior_prototype\third-party\rapidjson\document.h(1729) : see reference to function template instantiation 'rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator> &rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>::ParseStream<0,Encoding,InputStream>(InputStream &)' being compiled
1>          with
1>          [
1>              Encoding=rapidjson::UTF8<char>
1>  ,            InputStream=std::stringstream
1>          ]
1>          c:\soft\behavior_prototype\third-party\rapidjson\document.h(1729) : see reference to function template instantiation 'rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator> &rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>::ParseStream<0,Encoding,InputStream>(InputStream &)' being compiled
1>          with
1>          [
1>              Encoding=rapidjson::UTF8<char>
1>  ,            InputStream=std::stringstream
1>          ]
1>          c:\soft\behavior_prototype\tesai\tesai\src\blueprintmanager.cpp(14) : see reference to function template instantiation 'rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator> &rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>::ParseStream<std::stringstream>(InputStream &)' being compiled
1>          with
1>          [
1>              InputStream=std::stringstream
1>          ]
1>          c:\soft\behavior_prototype\tesai\tesai\src\blueprintmanager.cpp(14) : see reference to function template instantiation 'rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator> &rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>::ParseStream<std::stringstream>(InputStream &)' being compiled
1>          with
1>          [
1>              InputStream=std::stringstream
1>          ]
1>c:\soft\behavior_prototype\third-party\rapidjson\reader.h(410): error C2039: 'Tell' : is not a member of 'std::basic_stringstream<char,std::char_traits<char>,std::allocator<char>>'
1>c:\soft\behavior_prototype\third-party\rapidjson\reader.h(410): error C2660: 'rapidjson::GenericReader<SourceEncoding,Encoding,Allocator>::SetParseError' : function does not take 1 arguments
1>          with
1>          [
1>              SourceEncoding=rapidjson::UTF8<char>
1>  ,            Encoding=rapidjson::UTF8<char>
1>  ,            Allocator=rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>
1>          ]
1>c:\soft\behavior_prototype\third-party\rapidjson\reader.h(420): error C2039: 'Peek' : is not a member of 'std::basic_stringstream<char,std::char_traits<char>,std::allocator<char>>'
1>c:\soft\behavior_prototype\third-party\rapidjson\reader.h(421): error C2039: 'Tell' : is not a member of 'std::basic_stringstream<char,std::char_traits<char>,std::allocator<char>>'
1>c:\soft\behavior_prototype\third-party\rapidjson\reader.h(421): error C2660: 'rapidjson::GenericReader<SourceEncoding,Encoding,Allocator>::SetParseError' : function does not take 1 arguments
1>          with
1>          [
1>              SourceEncoding=rapidjson::UTF8<char>
1>  ,            Encoding=rapidjson::UTF8<char>
1>  ,            Allocator=rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>
1>          ]
1>
1>Build FAILED.
1>
1>Time Elapsed 00:00:00.51
2>------ Build started: Project: TESAITest, Configuration: Debug Win32 ------
2>Build started 5/16/2017 7:28:36 PM.
2>InitializeBuildStatus:
2>  Touching "Debug\TESAITest.tlog\unsuccessfulbuild".
2>ClCompile:
2>  All outputs are up-to-date.
2>LINK : fatal error LNK1104: cannot open file 'C:\soft\behavior_prototype\TESAI\Debug\TESAI.lib'
2>
2>Build FAILED.
2>
2>Time Elapsed 00:00:00.16
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

**Comment by miloyip** [comment]
@kadst43 You cannot use `std::stringstream` directly. You may:

1. Use `rapidjson::StringStream` in `rapidjson/stream.h`
2. Use `rapidjson::BasicIStreamWrapper` in `istreamwrapper.h`

**Comment by kadst43** [comment]
Ahhh, I knew it must be something simple.  Thanks for the fast response!

**Comment by Hiwen** [comment]
> Ahhh, I knew it must be something simple. Thanks for the fast response!

I think maybe you can change your code like this:
`#include "BlueprintManager.h"
#include "document.h"
#include

using namespace rapidjson;

void BlueprintManager::processFile(const char* filename)
{
// Load the file into a rapidjson document
const char* json = "{"project":"rapidjson","stars":10,"subobject":{"number":13.33}}";
//std::stringstream stringStream(json);
Document document;
document.Parse<0>(json);    // change like this
}`

**Comment by Bu11etmagnet** [comment]
```
const char* json = "{"project":"rapidjson","stars":10,"subobject":{"number":13.33}}";
```

is not even valid C++:

```
error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
const char* json = "{"project":"rapidjson","stars":10,"subobject":{"number":13.33}}";
                      ^
                       
error: expected ';' after top level declarator
const char* json = "{"project":"rapidjson","stars":10,"subobject":{"number":13.33}}";
                      ^
                      ;
error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
const char* json = "{"project":"rapidjson","stars":10,"subobject":{"number":13.33}}";
                                ^
                                 
error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
const char* json = "{"project":"rapidjson","stars":10,"subobject":{"number":13.33}}";
                                            ^
                                             
error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
const char* json = "{"project":"rapidjson","stars":10,"subobject":{"number":13.33}}";
                                                       ^
                                                        
error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
const char* json = "{"project":"rapidjson","stars":10,"subobject":{"number":13.33}}";
```
