### ISSUE TITLE
Slow parsing time on iOS

### ISSUE THREAD

**Issue by michaeleiselsc** [Tencent/rapidjson#856]
Hi, I've benchmarked the RapidJSON library taking 20 ms on a 4MB JSON payload, and in general being around 40% of the time that iOS's NSJSONSerialization library takes to create an Objective-C object. Since work in Objective-C, e.g. creating the objects during serialization, is much slower than processing in C/C++, e.g. the work that RapidJSON does. I'm concerned that I'm either not building it very well or that there's some bottleneck in RapidJSON, at least for the iOS architecture. I've tried -Os, -O3, incremental LTO and monolithic LTO, and still get about the same results. And the *weird* thing is that I built the project a while back, and I was getting results where parsing took 10% compared to Apple rather than 40%, but I lost the project and can no longer re-create those results. Are there are any adjustments I should make, or any action items for RapidJSON to consider?

Here's a screenshot of the profiler from repeatedly parsing a JSON file with RapidJSON's SAX parser and a handler that does nothing:
<img width="1174" alt="screen shot 2017-02-16 at 2 47 20 pm" src="https://cloud.githubusercontent.com/assets/7732829/23044862/efd4f210-f456-11e6-972b-eb177d008bcb.png">

Trace file:
[rapidjson.trace.zip](https://github.com/miloyip/rapidjson/files/781746/rapidjson.trace.zip)

Project, which you can build and run to see Apple's method and mine in comparison:
[RapidJSONTest.zip](https://github.com/miloyip/rapidjson/files/781748/RapidJSONTest.zip)

**Comment by michaeleiselsc** [comment]
gason is about 100x faster (it does in-situ DOM parsing)

**Comment by StilesCrisis** [comment]
Did you try running the Rapidjson parser with the Insitu parser flag? It looks like a large portion of the work here is string copying, which can often be avoided in Insitu mode (and this is how gason works by default).

**Comment by michaeleiselsc** [comment]
@StilesCrisis yes, i've tried in-situ with little effect. the slow-down appears to the push method, which i don't think changes very much for in-situ

**Comment by StilesCrisis** [comment]
You could try running https://github.com/miloyip/nativejson-benchmark on your machine and see what happens. On my machine rapidjson and Jason are neck-and-neck.

**Comment by StilesCrisis** [comment]
Gason

**Comment by pah** [comment]
If you repeatedly parse into the same `Document` (i.e. using the default [`MemoryPoolAllocator` ](http://rapidjson.org/classrapidjson_1_1_memory_pool_allocator.html)), memory consumption will accumulate over time.

If you don't need the previous values any longer, you can call `Clear()` on the allocator:
```cpp
  rapidjson::Document d;
  d.GetAllocator().Clear(); // free previously allocated memory
```

**Comment by zhuangtao97** [comment]
My test result is that NSJSONSerialization parses faster than rapidJSON
