### ISSUE TITLE
Update is made to the object collection in the memory then does it take exactly the same time to serialize to disk, or the RapidJson allows you to just update based on the delta change to the collection in memory

### ISSUE THREAD

**Issue by krishnadakka** [Tencent/rapidjson#864]
Hi, update is made to the object collection in the memory for 1 tag. The question is: Does it take exactly the same time to serialize to disk, or the RapidJson allows you to just update based on the delta change to the collection in memory.Here is the code
{
    "Tags": [
        {
            "Name": "P1_0",
            "Group1": "",
            "Group2": ""
		},
		{
            "Name": "P1_1",
            "Group1": "",
            "Group2": ""
		},
		{
            "Name": "P1_2",
            "Group1": "",
            "Group2": ""
		},
		{
            "Name": "P1_3",
            "Group1": "",
            "Group2": ""
		}
	]
}

 char readBuffer[65536];	
static rapidjson::Document doc(kObjectType);
static rapidjson::Value* array = NULL;	
FILE* fpointer = fopen("C:\\Temp\\Test1.json", "rb+");
		FileReadStream fsstream(fpointer, readBuffer, sizeof(readBuffer));
		doc.ParseStream(fsstream);
		fclose(fpointer);
		array = Pointer("/Tags").Get(doc);				
		array->Erase(array->Begin() + (1));		//delete tag

		doc2.SetObject();                                     //Add new tag
		Value json_objects(kObjectType);
		std::string TempStr = "P1_11";
		MemoryPoolAllocator<> allocator;
		Value szNam(TempStr.c_str(), static_cast<SizeType>(strlen(TempStr.c_str())), allocator);
		json_objects.AddMember("Name", szNam, doc2.GetAllocator());
		array->PushBack(json_objects, doc2.GetAllocator());
		char bufferWrite[65536];

FILE* fp = fopen("C:\\Temp\\Test1.json", "w");  // is it take exactly the same amount of time to serialize to disk ?
		FileWriteStream fileWriteStream2(fp, bufferWrite, sizeof(bufferWrite));
		PrettyWriter<FileWriteStream> writeStream2(fileWriteStream2);
		doc.Accept(writeStream2);
		fclose(fp);

**Comment by miloyip** [comment]
RapidJSON does not keep track of the original JSON after parsing.
Currently you need to serialize the whole JSON even if there is only a value changed.
