### ISSUE TITLE
Appending lots of values to an Array

### ISSUE THREAD

**Issue by ai-tor** [Tencent/rapidjson#865]
Hi!

Imagine you have an array of length 100000. According to Rapidjson tutorial, the way of adding values to a JSON Array is by pushing back the elements one by one.

Is there a way to set the JSON Array with all the values at once, similar to what is done with Strings?

Thank you! :)

**Comment by miloyip** [comment]
Currently, using `Reserve()` first and then `PushBack()` should be the fastest way.
If you have suggestions for improving this, you (or others) may propose and discuss.
