### ISSUE TITLE
StackAllocator ALWAYS allocates from the HEAP with user buffers (It is not supposed to)

### ISSUE THREAD

**Issue by hondero2552** [Tencent/rapidjson#878]
Alright, so I spend all day yesterday tracking this bug down and I found a couple of solutions and also decided on one and that's why I am summiting this bug report with it.

**The Issue**
It doesn't matter how big the stack allocator that you pass in is, this allocator always calls malloc the first time it is used. 

**What functionality does this bug affect**
This issue directly affects the usage of user buffers. This affects the validity of the following Gitbook argument (with the code as well): 

```C++
typedef GenericDocument<UTF8<>, MemoryPoolAllocator<>, MemoryPoolAllocator<>> DocumentType;
char valueBuffer[4096];
char parseBuffer[1024];
MemoryPoolAllocator<> valueAllocator(valueBuffer, sizeof(valueBuffer));
MemoryPoolAllocator<> parseAllocator(parseBuffer, sizeof(parseBuffer));
DocumentType d(&valueAllocator, sizeof(parseBuffer), &parseAllocator);
d.Parse(json);
```
>If the total size of allocation **is less than 4096+1024 bytes during parsing, this code does not invoke any heap allocation (via
new or malloc() ) at all.**

This issue does not affect the use of the library without user buffers since the StackAllocator always allocates from the HEAP anyways.

**What triggers the bug?**
The problem is that the stack template class' constructor does not use the stack capacity argument correctly. The truth is, it doesn't need it. When the stack constructor is called, the stack capacity is set to a higher number than what the buffer can hold. This triggers the realloc() function of the ``` MemorypoolAllocator<>``` to call malloc with a new size. The reason it does this is because the memory pool allocator already occupied 24 bytes with the ``` chunkHeader*``` so it doesn't have the **entire** capacity of the buffer anymore.

**How to fix it? FINALLY!**
Solution 1: Super easy, but questionable.
The easiest solution is to set the ``` initialCapacity_``` of the ``` StackAllocator``` to ```0```. This will fix everything. BUT, every function in the library that uses a StackAllocator(which I think is every single one) will be carrying around this extra parameter that does absolutely nothing.

Solution 2: Elegant but cumbersome
Bottom line up front, remove the ``` stackCapacity``` from the Stack template class. This will require a bunch of lines of code altered in the library and it will also require the pdf documentation quoted above to be changed.

**The good news**
I changed the library code already, all we need to do now is accept the merge, AND CHANGE the Gitbook section "USER BUFFER" so it reflects calling the DocumentType constructor with only two arguments. The capacity argument is not needed anymore. Which I never used so I don't know how to submit changes for it. 

**Below is how the code will look like once it is fixed. Feel free to use this code for the GitBook update.**
```C++
#include <iostream>
#include "include/rapidjson/document.h"
#include "/rapidjson/stringbuffer.h"
#include "include/rapidjson/writer.h"
#include "include/rapidjson/prettywriter.h"
using namespace rapidjson;
using namespace std;

int main(int argc, const char * argv[])
{
    typedef GenericDocument<UTF8<>, MemoryPoolAllocator<>, MemoryPoolAllocator<>> DocumentType;
    typedef GenericStringBuffer<UTF8<>, MemoryPoolAllocator<>> StringBufferLocal;
    
    const char json[] = "{\"object_name\":\"array\",\"array_types\":\"productPrice\",\"array\":\
    [\
    {\"ean\": 98875640932,\"store_id\": 19,\"dollars\": 142,\"cents\": 88},\
    {\"ean\": 98875640932,\"store_id\": 90,\"dollars\": 142,\"cents\": 88},\
    {\"ean\": 98875640932,\"store_id\": 362,\"dollars\": 142,\"cents\": 88},\
    {\"ean\": 98875640932,\"store_id\": 43,\"dollars\": 142,\"cents\": 88},\
    {\"ean\": 98875640932,\"store_id\": 55,\"dollars\": 142,\"cents\": 88},\
    {\"ean\": 98875640932,\"store_id\": 90,\"dollars\": 142,\"cents\": 88},\
    {\"ean\": 98875640932,\"store_id\": 362,\"dollars\": 142,\"cents\": 88},\
    {\"ean\": 905438740137,\"store_id\": 7,\"dollars\": 3,\"cents\": 99}]\
    }";
    //const size_t bufferSize = 300;/*UNCOMMENT THIS CODE IF YOU WANT TO TEST MALLOC BEING CALLED.*/
    const size_t bufferSize = 1024;/*UNCOMMENT THIS CODE IF YOU WANT TO TEST MALLOC NOT BEING CALLED.*/
    char valueBuffer[2048];
    char parseBuffer[bufferSize];
    memset(valueBuffer, 0, sizeof(valueBuffer));
    memset(parseBuffer, 0, sizeof(parseBuffer));
    
    MemoryPoolAllocator<> valueAllocator(valueBuffer, sizeof(valueBuffer));
    MemoryPoolAllocator<> parseAllocator(parseBuffer, sizeof(parseBuffer));
    
    char buffer[1024];
    memset(buffer, 0, sizeof(buffer));
    MemoryPoolAllocator<> allocator(buffer, sizeof(buffer));
    
    StringBufferLocal Sbuffer(&allocator);
    Writer<StringBufferLocal, UTF8<>, UTF8<>, MemoryPoolAllocator<>> writer(Sbuffer, &parseAllocator);
    
    DocumentType d(&valueAllocator, &parseAllocator);
    
    d.Parse(json);
    cout << "Bytes used by valueAllocator: " << valueAllocator.Size() << endl;
    cout << "Bytes used by parseAllocator: " << parseAllocator.Size() << endl;
    parseAllocator.Clear();
    
    d.Accept(writer);
    
    cout << "Bytes used by allocator: " << allocator.Size() << endl;
    cout << "Bytes used by parseAllocator: " << parseAllocator.Size() << endl;
    
    cout << "Pretty writer used: " << Sbuffer.GetSize() << endl;
    cout << Sbuffer.GetString() << endl;
    return 0;
}

```

**Comment by hondero2552** [comment]
anybody home?? Tencent? Milo?

**Comment by hondero2552** [comment]
@miloyip Anybody home? I've been trying since last year to fix this bug!!!!

**Comment by miloyip** [comment]
Sorry I may have missed this issue. I will investigate it.

**Comment by hondero2552** [comment]
@miloyip Better late than never I guess. I have to admit though I deleted the repo and the fix as well (although I re-forked it a couple of days ago). Many things have changed since then so I'm not sure if my initial solution would still work. I ran some tests and the bug is still there. Tonight I will find a fix again but please post any recommendations you have as to which way to go with the fix. I do not want to submit a fix that may break the library. Thanks and let's squash this bug. My company depends greatly on rapidjson.

**Comment by hondero2552** [comment]
@miloyip The problem really is with the documentation. Because DocumentType::Parse() creates another stack, if you specify the size of the stack passed into the constructor as the size of your buffer then the second stack will automatically have to allocate more memory (from the heap). Also, the stack passed into the constructor of DocumentType also allocates a new chunk of memory because the buffer size does not account for the memory occupied for the chunk_header. 
Basically there are many things wrong because how the documentation describes how to use user buffers. Honestly I am not sure I can submit a fix for this unless you tell me what you would like to see.

I think the easiest thing will be to thoroughly update the documentation to show what is going on behind the scene.

A work around that I found was to pass 0 as the initial capacity of the stack allocator and this actually fixes everything. 0 must also be passed to other constructors that take the a stack allocator along with its initial size, i.e. Writer::(), etc...

Let me know!

**Comment by N-Schaef** [comment]
I just encountered this issue myself.
The problem is still unresolved.

For the time beeing I use the fix mentioned above (passing 0 as buffer size to documents) and it seems to be working.

**Comment by hondero2552** [comment]
Yeahp it is still there. such a shame because I submitted the fix so all is needed to do is merge it and fix the documentation.
