### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by crafet** [Tencent/rapidjson#893]
cc1plus: warnings being treated as errors
In file included from /data/test/test/rapid_json/rapidjson-master/example/schemavalidator/schemavalidator.cpp:7:
/data/test/test/rapid_json/rapidjson-master/include/rapidjson/schema.h: In member function 'bool rapidjson::GenericSchemaValidator<SchemaDocumentType, OutputHandler, StateAllocator>::Key(const typename SchemaDocumentType::SchemaType::EncodingType::Ch*, rapidjson::SizeType, bool) [with SchemaDocumentType = rapidjson::GenericSchemaDocument<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >, rapidjson::CrtAllocator>, OutputHandler = rapidjson::BaseReaderHandler<rapidjson::UTF8<char>, void>, StateAllocator = rapidjson::CrtAllocator]':
/data/test/test/rapid_json/rapidjson-master/include/rapidjson/schema.h:790: error: 'index' may be used uninitialized in this function
/data/test/test/rapid_json/rapidjson-master/include/rapidjson/schema.h:790: note: 'index' was declared here
make[2]: *** [example/CMakeFiles/schemavalidator.dir/schemavalidator/schemavalidator.cpp.o] Error 1
make[1]: *** [example/CMakeFiles/schemavalidator.dir/all] Error 2
make: *** [all] Error 2

in directory rapidjson-master/
cmake ./ && make

**Comment by miloyip** [comment]
This seems false alarm. I checked the code it should not have problem.

**Comment by transdell** [comment]
I had exactly the same compiler error with my cmake build on /usr/lib/gcc/x86_64-redhat-linux/4.4.7 build.

I added -Wno-error to allow the build to continue but then it failed again attempting to compile one of the test files.

[ 37%] Building CXX object test/unittest/CMakeFiles/unittest.dir/valuetest.cpp.o
/external/rapidjson/test/unittest/valuetest.cpp: In member function ‘virtual void Value_ArrayHelperRangeFor_Test::TestBody()’:
/external/rapidjson/test/unittest/valuetest.cpp:1136: error: expected initializer before ‘:’ token
/external/rapidjson/test/unittest/valuetest.cpp:1140: error: expected primary-expression before ‘switch’
/external/rapidjson/test/unittest/valuetest.cpp:1140: error: expected ‘;’ before ‘switch’
/external/rapidjson/test/unittest/valuetest.cpp:1140: error: expected primary-expression before ‘switch’
/external/rapidjson/test/unittest/valuetest.cpp:1140: error: expected ‘)’ before ‘switch’
/external/rapidjson/test/unittest/valuetest.cpp:1144: error: expected initializer before ‘:’ token
/external/rapidjson/test/unittest/valuetest.cpp:1148: error: expected primary-expression before ‘switch’
/external/rapidjson/test/unittest/valuetest.cpp:1148: error: expected ‘;’ before ‘switch’
/external/rapidjson/test/unittest/valuetest.cpp:1148: error: expected primary-expression before ‘switch’
/external/rapidjson/test/unittest/valuetest.cpp:1148: error: expected ‘)’ before ‘switch’
/external/rapidjson/test/unittest/valuetest.cpp: In member function ‘virtual void Value_ObjectHelperRangeFor_Test::TestBody()’:
/external/rapidjson/test/unittest/valuetest.cpp:1514: error: expected initializer before ‘:’ token
/external/rapidjson/test/unittest/valuetest.cpp:1521: error: expected primary-expression before ‘switch’
/external/rapidjson/test/unittest/valuetest.cpp:1521: error: expected ‘;’ before ‘switch’
/external/rapidjson/test/unittest/valuetest.cpp:1521: error: expected primary-expression before ‘switch’
/external/rapidjson/test/unittest/valuetest.cpp:1521: error: expected ‘)’ before ‘switch’
/external/rapidjson/test/unittest/valuetest.cpp:1525: error: expected initializer before ‘:’ token
/external/rapidjson/test/unittest/valuetest.cpp:1532: error: expected primary-expression before ‘switch’
/external/rapidjson/test/unittest/valuetest.cpp:1532: error: expected ‘;’ before ‘switch’
/external/rapidjson/test/unittest/valuetest.cpp:1532: error: expected primary-expression before ‘switch’
/external/rapidjson/test/unittest/valuetest.cpp:1532: error: expected ‘)’ before ‘switch’
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/algorithm:62,
                 from /external/rapidjson/thirdparty/gtest/googletest/include/gtest/internal/gtest-port.h:274,
                 from /external/rapidjson/thirdparty/gtest/googletest/include/gtest/internal/gtest-internal.h:40,
                 from /external/rapidjson/thirdparty/gtest/googletest/include/gtest/gtest.h:58,
                 from /external/rapidjson/test/unittest/unittest.h:47,
                 from /external/rapidjson/test/unittest/valuetest.cpp:15:
/external/rapidjson/include/rapidjson/document.h: In function ‘void std::__introsort_loop(_RandomAccessIterator, _RandomAccessIterator, _Size, _Compare) [with _RandomAccessIterator = rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >*, _Size = long int, _Compare = ValueIntComparer]’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_algo.h:5258:   instantiated from ‘void std::sort(_RAIter, _RAIter, _Compare) [with _RAIter = rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >*, _Compare = ValueIntComparer]’
/external/rapidjson/test/unittest/valuetest.cpp:1722:   instantiated from here
/external/rapidjson/include/rapidjson/document.h:573: error: ‘rapidjson::GenericValue<Encoding, Allocator>::GenericValue(const rapidjson::GenericValue<Encoding, Allocator>&) [with Encoding = rapidjson::UTF8<char>, Allocator = rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>]’ is private
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_algo.h:2301: error: within this context
/external/rapidjson/include/rapidjson/document.h: In function ‘void std::__insertion_sort(_RandomAccessIterator, _RandomAccessIterator, _Compare) [with _RandomAccessIterator = rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >*, _Compare = ValueIntComparer]’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_algo.h:2193:   instantiated from ‘void std::__final_insertion_sort(_RandomAccessIterator, _RandomAccessIterator, _Compare) [with _RandomAccessIterator = rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >*, _Compare = ValueIntComparer]’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_algo.h:5260:   instantiated from ‘void std::sort(_RAIter, _RAIter, _Compare) [with _RAIter = rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >*, _Compare = ValueIntComparer]’
/external/rapidjson/test/unittest/valuetest.cpp:1722:   instantiated from here
/external/rapidjson/include/rapidjson/document.h:573: error: ‘rapidjson::GenericValue<Encoding, Allocator>::GenericValue(const rapidjson::GenericValue<Encoding, Allocator>&) [with Encoding = rapidjson::UTF8<char>, Allocator = rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>]’ is private
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_algo.h:2127: error: within this context
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_algo.h:2193:   instantiated from ‘void std::__final_insertion_sort(_RandomAccessIterator, _RandomAccessIterator, _Compare) [with _RandomAccessIterator = rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >*, _Compare = ValueIntComparer]’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_algo.h:5260:   instantiated from ‘void std::sort(_RAIter, _RAIter, _Compare) [with _RAIter = rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >*, _Compare = ValueIntComparer]’
/external/rapidjson/test/unittest/valuetest.cpp:1722:   instantiated from here
/external/rapidjson/include/rapidjson/document.h:573: error: ‘rapidjson::GenericValue<Encoding, Allocator>::GenericValue(const rapidjson::GenericValue<Encoding, Allocator>&) [with Encoding = rapidjson::UTF8<char>, Allocator = rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>]’ is private
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_algo.h:2134: error: within this context
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_algo.h:2193:   instantiated from ‘void std::__final_insertion_sort(_RandomAccessIterator, _RandomAccessIterator, _Compare) [with _RandomAccessIterator = rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >*, _Compare = ValueIntComparer]’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_algo.h:5260:   instantiated from ‘void std::sort(_RAIter, _RAIter, _Compare) [with _RAIter = rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >*, _Compare = ValueIntComparer]’
/external/rapidjson/test/unittest/valuetest.cpp:1722:   instantiated from here
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_algo.h:2134: error:   initializing argument 2 of ‘void std::__unguarded_linear_insert(_RandomAccessIterator, _Tp, _Compare) [with _RandomAccessIterator = rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >*, _Tp = rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >, _Compare = ValueIntComparer]’
/external/rapidjson/include/rapidjson/document.h: In function ‘void std::__unguarded_insertion_sort(_RandomAccessIterator, _RandomAccessIterator, _Compare) [with _RandomAccessIterator = rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >*, _Compare = ValueIntComparer]’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_algo.h:2194:   instantiated from ‘void std::__final_insertion_sort(_RandomAccessIterator, _RandomAccessIterator, _Compare) [with _RandomAccessIterator = rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >*, _Compare = ValueIntComparer]’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_algo.h:5260:   instantiated from ‘void std::sort(_RAIter, _RAIter, _Compare) [with _RAIter = rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >*, _Compare = ValueIntComparer]’
/external/rapidjson/test/unittest/valuetest.cpp:1722:   instantiated from here
/external/rapidjson/include/rapidjson/document.h:573: error: ‘rapidjson::GenericValue<Encoding, Allocator>::GenericValue(const rapidjson::GenericValue<Encoding, Allocator>&) [with Encoding = rapidjson::UTF8<char>, Allocator = rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>]’ is private
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_algo.h:2161: error: within this context
make[2]: *** [test/unittest/CMakeFiles/unittest.dir/valuetest.cpp.o] Error 1
make[1]: *** [test/unittest/CMakeFiles/unittest.dir/all] Error 2
make: *** [all] Error 2

Is there a minimum version of g++ that you now require? As it stands we cannot compile the latest version with gcc 4.4.7. Our project is targeted for long term release so it still using an older release of Redhat/GCC.

**Comment by miloyip** [comment]
@transdell I checked the line 1136:

~~~cpp
        for (auto& v : x.GetArray()) {
~~~

which is within:

~~~cpp
#if RAPIDJSON_HAS_CXX11_RANGE_FOR
...
#endif
~~~

So that it seems it incorrectly enabled this C++11 feature. But this should be identified automatically in `rapidjson.h`:

~~~cpp
#ifndef RAPIDJSON_HAS_CXX11_RANGE_FOR
#if defined(__clang__)
#define RAPIDJSON_HAS_CXX11_RANGE_FOR __has_feature(cxx_range_for)
#elif (defined(RAPIDJSON_GNUC) && (RAPIDJSON_GNUC >= RAPIDJSON_VERSION_CODE(4,6,0)) && defined(__GXX_EXPERIMENTAL_CXX0X__)) || \
      (defined(_MSC_VER) && _MSC_VER >= 1700)
#define RAPIDJSON_HAS_CXX11_RANGE_FOR 1
#else
#define RAPIDJSON_HAS_CXX11_RANGE_FOR 0
#endif
#endif // RAPIDJSON_HAS_CXX11_RANGE_FOR
~~~

For 4.4.7 this should not be defined. Can you find out why?

**Comment by transdell** [comment]
One of the problems was that on my linux vm the cmake cache variable RAPIDJSON_BUILD_CXX11 was defaulting to ON. When I toggled this to OFF the build completed with -Wno-error override.

That's the good news. 

When I ran the ./unittest not all of the test cases passed and one crashed the program.
...
[ RUN      ] Document.ParseStream_EncodedInputStream
unknown file: Failure
C++ exception with description "fp_ != 0" thrown in the test body.
[  FAILED  ] Document.ParseStream_EncodedInputStream (1 ms)
[ RUN      ] Document.ParseStream_AutoUTFInputStream
unknown file: Failure
C++ exception with description "fp_ != 0" thrown in the test body.
[  FAILED  ] Document.ParseStream_AutoUTFInputStream (0 ms)
...
and then one test causes a segfault:
...
[ RUN      ] SchemaValidator.ValidateMetaSchema
Segmentation fault

**Comment by transdell** [comment]
Just in case it is relevant...I have to use a cmake shadow build because my sources are in a read-only share.

**Comment by miloyip** [comment]
It seems that it just cannot find the test json files from the current path.

~~~
    const char *paths[] = {
        "encodings",
        "bin/encodings",
        "../bin/encodings",
        "../../bin/encodings",
        "../../../bin/encodings"
    };
 ~~~

**Comment by transdell** [comment]
Okay. That it probably why my shadow build is not working.

FYI I had the exact same issue on one of my projects where my gtest app needed access to a test media directory. I solved it by finding the location relative to the test file by using the __FILE__ compiler variable.

This worked for in-source and out-of-source shadow builds of cmake.

**Comment by Code-ReaQtor** [comment]
Similar error to @crafet found when adding rapidjson through ExternalProject_Add(). I am also using GCC 4.4.7

**Comment by suyu0521** [comment]
Similar error to @crafet found when in directory rapidjson-master/
cmake ./ && make. 
I am also using GCC 4.4.7

**Comment by AndrijKolomiets** [comment]
Works on  Windows, but on Linux g++ says:
error: ‘rapidjson::Value {aka class rapidjson::GenericValue<rapidjson::UTF8<> >}’ has no member named ‘GetArray’
for (auto& v : a.GetArray())

 I use g++ 5.4.1

**Comment by jiapengwen** [comment]
> Works on Windows, but on Linux g++ says:
> error: ‘rapidjson::Value {aka class rapidjson::GenericValue<rapidjson::UTF8<> >}’ has no member named ‘GetArray’
> for (auto& v : a.GetArray())
> 
> I use g++ 5.4.1

because your rapidjson version is 1.0, please use v1.1.0
