### ISSUE TITLE
How to construct and parse json string values containing '\\r' '\\t' etc characters?

### ISSUE THREAD

**Issue by raveendrajoshi** [Tencent/rapidjson#917]
I have a json like the following:
 "{\"project\": \"rapid\\rjson\",\"stars\":10}"

In the above json, the string value of \"rapid\\rjson\" has 2 different characters '\\' and 'r'.

But when the above json is parsed, the '\\' and 'r' characters are being treated as one '\r' character.

My question is, how to get the string as "rapid\rjson" after parsing?

Following is the code snippet and the output:

Code:
-----
    const char* json = "{\"project\": \"rapid\\rjson\",\"stars\":10}";
    Document d;
    d.Parse(json);

    Value val(kObjectType);

    cout << "json string: " << json << endl;

    val = d["project"];
    cout << "project: " << val.GetString() << endl; 
    val = d["stars"];
    cout << "stars: " << val.GetInt() << endl;

Output:
-------
json string: {"project": "rapid\rjson","stars":10}
jsonect: rapid      --> \\r being treated as carriage return and the output is overwritten
stars: 10

As a work around for this, I tried using PrettyWriter. The problem with the \\r got solved. But now, the output contains " (quotes) at the beginning and end of the string. 

Here the question is, how to get rid of these quotes?

Following is the code snippet and the output using PrettyWriter:

Code:
-----
    const char* json = "{\"project\": \"rapid\\rjson\",\"stars\":10}";
    Document d;
    d.Parse(json);

    Value val(kObjectType);

    cout << "json string: " << json << endl;

    val = d["project"];
    StringBuffer buffer;
    PrettyWriter<StringBuffer> writer(buffer);
    val.Accept(writer);
    cout << "project: " << buffer.GetString() << endl; 
	
    val = d["stars"];
    cout << "stars: " << val.GetInt() << endl;

Output:
-------
json string: {"project": "rapid\rjson","stars":10}
project: "rapid\rjson"       --> contains " (quotes)
stars: 10

Any input on this is appreciated. 

Thank you for your time.

Raveendra

**Comment by miloyip** [comment]
To represent two characters `\` and `r` in JSON, the JSON should be:

~~~js
{"project": "rapid\\rjson","stars":10}
~~~

**Comment by raveendrajoshi** [comment]
Thank you for the reply miloyip.

The JSON in the code is indeed {"project": "rapid\\rjson","stars":10}. Please see the code snippet.

I have not explicitly mentioned this information in the description section.

Thanks
Raveendra

**Comment by raveendrajoshi** [comment]
\\r

**Comment by gshejwalkar** [comment]
I am also having similar issue. Is there any way to overcome it.

**Comment by lichray** [comment]
```
const char* json = R"({"project": "rapid\\rjson","stars":10})";
```

**Comment by raveendrajoshi** [comment]
I tried the above the string as suggested by lichray but got the following compilation error:

` g++ -o json_test json_test.cpp -I ../../include/
json_test.cpp:17: error: stray ‘\’ in program
json_test.cpp:17: error: stray ‘\’ in program
json_test.cpp: In function ‘int main()’:
json_test.cpp:17: error: ‘R’ was not declared in this scope
json_test.cpp:17: error: expected ‘,’ or ‘;’ before string constant
`
Can you please explain little more on this?

**Comment by lichray** [comment]
```
g++ -Wall -std=c++11 -o json_test json_test.cpp ..
```
http://en.cppreference.com/w/cpp/language/string_literal

**Comment by kAngelProjects** [comment]
It looks as though you can solve this issue with a mixture of ravendrajoshi's original code and lichray's addition. If you avoid using PrettyWriter:

`const char* json = R"({"project": "rapid\\rjson","stars":10})";
	rapidjson::Document d;
	d.Parse(json);

	rapidjson::Value val(rapidjson::kObjectType);

	std::cout << "json string: " << json << std::endl;

	val = d["project"];
	std::cout << "project: " << val.GetString() << std::endl;
	val = d["stars"];
	std::cout << "stars: " << val.GetInt() << std::endl;


	getch();`

then you can get this output:

![918-2](https://cloud.githubusercontent.com/assets/10655265/24949116/6d8607c0-1f64-11e7-920b-d7f1821a3fd6.PNG)

Which drops the quotes and keeps the \. 

When playing around with PrettyWriter it also seems to me that the \ is not what causes the "rapid\rapidjson" to be wrapped in quotes. I tried with PrettyWriter using just "rapidrapidjson" and the quotes were still there. 

![918](https://cloud.githubusercontent.com/assets/10655265/24949206/b2a88f8a-1f64-11e7-9d2f-edd10c767f26.PNG)

So I think you can get around this issue by avoiding PrettyWriter and using lichray's formatting.
