### ISSUE TITLE
StringStream does not map to std::istringstream

### ISSUE THREAD

**Issue by michcleary** [Tencent/rapidjson#919]
I'm trying to use a std::istringstream, but rapidjson needs rapidjson:;StringStream.  There doesn't appear to be a good conversion for this.

My code looks like this:
const std::istringstream &json_is; (method param)
rapidjson::Document document;
rapidjson::StringStream(json_is); //compilation error shown below
//no instance of constructor RapidjsonGenericStringStream ... matches the arg list
rapidjson::ParseResult result = doc.ParseStream(strStream);

I find it hard to believe that I would have to convert my istringstream to a char* to use rapidjson::StringStream.  There must be a way to do it.  I don't see any documentation or examples on that.  ParseStream should take a std istringstream.

**Comment by pah** [comment]
See the [documentation](http://rapidjson.org/md_doc_stream.html#iostreamWrapper) for an example how to use standard library streams with RapidJSON:
```cpp
#include <rapidjson/istreamwrapper.h>
// ...
rapidjson::IstreamWrapper strStream(json_is);
rapidjson::ParseResult result = doc.ParseStream(strStream);
```
