### ISSUE TITLE
Compilation size

### ISSUE THREAD

**Issue by MrLonko** [Tencent/rapidjson#925]
Dear 

We are using a very old ARM GCC 3.3.4 which has to be used as the platform does not have a newer one :(
One thing we noticed is that any file/function that uses rapidjson grows insanely.

Oh the compile flag needed is -O2 otherwise memory problems :)

For example NM or Size says that we a function in objdump ExtractResponse of size 122kb which is huge compared to other really big functions without the use of rapidjson.

For example an if statement:
		if (d.HasMember("xid") && !d["xid"].IsNull()) h.xId = d["xid"].GetString(); 
       With the statement the function size is 00122148 without only d.HasMember("xid") so: 
                if (!d["xid"].IsNull()) h.xId = d["xid"].GetString(); 
       the function size reduces to: 00120476
       
       Drop by 1672. 

If i recompile the whole aplication on a modern ubuntu gcc 5.4+ the of the same function is insignificant.

So there is something in the compiler itself. 
Any idea how to make the executable smaller under our old gcc ? 
90% of size increase i see in the files with rapidjson, under gcc 3.3.4 with O2 and stripped the size is 4,9mb :) under GCC 5.4 with O2 the size is 1.6mb...

I'm losing my mind :S

**Comment by lichray** [comment]
Please provide a minimal self-contained program in source code to allow us to verify; compilers' inlining/loop unrolling strategy is not arguable without context.

**Comment by MrLonko** [comment]
Dear,

basically an example from simple tutorial. 
If i enable -O2 which is mandatory the main function becomes number one by size  (00015080 T main)

Each time i add a line of: assert(document["hello"].IsString()); the size increases by: 260bytes

If i set flag O0 the size of main drops to:  00004180 T main

Any idea what the compiler is doing wrong ?
[LinuxProject2.zip](https://github.com/miloyip/rapidjson/files/911265/LinuxProject2.zip)

**Comment by lichray** [comment]
On Mon, Apr 10, 2017 at 2:45 PM, MrLonko <notifications@github.com> wrote:

> If i enable -O2 which is mandatory the main function becomes number one by
> size (00015080 T main)
> If i set flag O0 the size of main drops to: 00004180 T main


Of course, O0 is no inlining at all.

> Each time i add a line of: assert(document["hello"].IsString()); the size
> increases by: 260bytes
>
Not too surprising?  With my gcc-6.3 I see
10 new instructions (inliner chooses to keep
operator[] and substitutes the rest), half of
which is contributed by "assert" itself.

=== cut === cut ===

The program sizes from your bug report give
me an impression that your toolchain may
static linked the programs to libstdc++,
please double check by compiling a small
program that uses iostream.  IIUC,
rapidjson needs not link to libstdc++,
@miloyip ?

-- 
Zhihao Yuan, ID lichray
The best way to predict the future is to invent it.
_______________________________________________

**Comment by MrLonko** [comment]
Dear 

the ldd reports:
arm-linux-ldd LinuxProject2
checking sub-depends for 'not found'
checking sub-depends for 'not found'
checking sub-depends for 'not found'
checking sub-depends for 'not found'
checking sub-depends for 'not found'
        libstdc++.so.5 => not found (0x00000000)
        libm.so.0 => not found (0x00000000)
        libfloat.so.1 => not found (0x00000000)
        libgcc_s.so.1 => not found (0x00000000)
        libc.so.0 => not found (0x00000000)
        /lib/ld-uClibc.so.0 => /lib/ld-uClibc.so.0 (0x00000000)

Do you think i am missing something or libstdc++ isnt linked statically?

**Comment by lichray** [comment]
```
:~/tmp$ arm-linux-gnueabihf-g++ -Wall -O2 LinuxProject2.cpp
:~/tmp$ ll -h a.out
-rwxrwxr-x 1 ubuntu 65K Apr 10 21:30 a.out
```
How large is a helloworld (in iostream) executable with your toolchain?

**Comment by MrLonko** [comment]
Smaler ?
user@sa:/tmp/VisualGDB/d/_Work/rapidjsontest/LinuxProject2$ arm-linux-g++ -Wall -O2 LinuxProject2.cpp
user@sa:/tmp/VisualGDB/d/_Work/rapidjsontest/LinuxProject2$ ls -ltr
-rwxr-xr-x 1 user user 6450 apr 11 08:16 LinuxProject2.cpp
-rwxrwxr-x 1 user user 6757 apr 11 08:18 a.out

arm-linux-nm -g --size-sort  a.out -C --radix=d
00000004 T _fini
00000004 T _init
00000004 V std::basic_streambuf<char, std::char_traits<char> >::_S_pback_size
00000008 V guard variable for rapidjson::internal::StrtodDiyFp(char const*, unsigned int, unsigned int, int, double*)::kPow10
00000080 T main
00000140 B _ZSt4cout@@GLIBCPP_3.2

**Comment by lichray** [comment]
>  90% of size increase i see in the files with rapidjson, under gcc 3.3.4 with O2 and stripped the size is 4,9mb :) under GCC 5.4 with O2 the size is 1.6mb...

Oh, you were talking about your own application, not the example file.

But I don't see anything wrong so far, expect, maybe, gcc3's inline strategy is dumb, and this is fixable, for example, patch certain rapidjson's function as `__attribute__ ((noinline))` or explicit instantiate some template in your code.

**Comment by MrLonko** [comment]
Is there a way to say to whole document.h not to inline any of the functions?

**Comment by MrLonko** [comment]
Going with -fno-inline
00002140 W rapidjson::internal::u64toa(unsigned long long, char*)
00002472 V rapidjson::internal::Pow10(int)::e
**00002960 T main**
00004552 W void rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseNumber<(unsigned int)0, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator> >(rapidjson::GenericStringStream<rapidjson::UTF8<char> >&, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator>&)

going without that flag:
00005384 W void rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseNumber<(unsigned int)0, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator> >(rapidjson::GenericStringStream<rapidjson::UTF8<char> >&, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator>&)
00005808 W bool rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::Accept<rapidjson::PrettyWriter<rapidjson::GenericStringBuffer<rapidjson::UTF8<char>, rapidjson::CrtAllocator>, rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator, (unsigned int)0> >(rapidjson::PrettyWriter<rapidjson::GenericStringBuffer<rapidjson::UTF8<char>, rapidjson::CrtAllocator>, rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator, (unsigned int)0>&) const
**00015096 T main**

So inlining is definitly a real problem of GCC 3.3. in terms of final executable size.
I tried the same flag on our Large executable and executable size after strip is without flag 4,9mb with no inlining 1,6mb :)

What will happen when if i don't use inlining? is the performance really noticable?

**Comment by MrLonko** [comment]
Still maybe disabling inlining for some files is the way to go? not having a global setting?
But don't seem to find a pragma for whole file, not really inclined to change all the source of rapidjson

**Comment by lichray** [comment]
You can try
```
#pragma GCC push_options
#pragma GCC optimize ("Os")
// ...code
#pragma GCC pop_options
```
But I'm not sure whether it works for templates as they are not instantiated at the definition site.  IMHO the best option here is to figure out some most bloated function and try to de-inline them case by case.
