### ISSUE TITLE
Compile errors on VS2017 when using new ( _NORMAL_BLOCK , __FILE__ , __LINE__ )

### ISSUE THREAD

**Issue by kundelstein** [Tencent/rapidjson#938]
Hi,
When you want to debug (memory leaks) under VS2017 (and previous) there is usually involved overloading the new.

The code looks similar to this one:

```
#define _CRTDBG_MAP_ALLOC
#include <stdlib.h>
#include <crtdbg.h> 
#ifndef DBG_NEW
#define DBG_NEW new ( _NORMAL_BLOCK , __FILE__ , __LINE__ )
#define new DBG_NEW
#endif
```

and is followed with the code in main ():
`_CrtSetDbgFlag (_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);`

Unfortunately rapidjson compilation doesn't work and gives errors even with the basic code used:
code:
```
Document d;
d.Parse (json);
```

error:
document.h(2367): error C2061: syntax error: identifier 'stack_'

**Comment by miloyip** [comment]
Is it the proper way to define that `new`?

**Comment by kundelstein** [comment]
I don't think any sane person would use it in production version. It is just dirty, but quite common way to substitute the use of the constructor so it can log the current line and file to the CRTDBG.

The quick fix is to define the new after including the rapidjson's headers.

**Comment by pah** [comment]
Another option would be to define [`RAPIDJSON_NEW`](http://rapidjson.org/rapidjson_8h.html#abdc7cd7902748ffe6626d71c59a73c3b) accordingly as well.  With this, you can track the allocations in RapidJSON, too.  Maybe something like:
```cpp
#ifdef DBG_NEW
#define RAPIDJSON_NEW(TypeName) \
  DBG_NEW TypeName
#endif
#include <rapidjson/rapidjson.h>
// ...
```

**Comment by pagict** [comment]
I think pah's comment would be a solution. I'll close this, feel free to reopen it if still troubles you

> Another option would be to define [`RAPIDJSON_NEW`](http://rapidjson.org/rapidjson_8h.html#abdc7cd7902748ffe6626d71c59a73c3b) accordingly as well. With this, you can track the allocations in RapidJSON, too. Maybe something like:
> 
> ```c++
> #ifdef DBG_NEW
> #define RAPIDJSON_NEW(TypeName) \
>   DBG_NEW TypeName
> #endif
> #include <rapidjson/rapidjson.h>
> // ...
> ```
