### ISSUE TITLE
how to use on iOS platform

### ISSUE THREAD

**Issue by lixiaofan0** [Tencent/rapidjson#942]
stdint.h  error "Use this header only with Microsoft Visual C++ compilers!" .   I defined _MSC_VER,build failed too. anyone can help

**Comment by miloyip** [comment]
You should not define `_MSC_VER`. I think you may have mistakenly added `-I rapidjson/msinttypes`.

**Comment by chaoszm** [comment]
Also encounter this problem.What do you mean " mistakenly added -I rapidjson/msinttypes"?

**Comment by workhardupc** [comment]
使用pod方式引入, 没有别的设置：
       pod 'rapidjson', '1.1.0'
报同样的问题:
       Use this header only with Microsoft Visual C++ compilers!

**Comment by Asten09** [comment]
情况类似，直接引入rapidjson也会报同样的错误
