### ISSUE TITLE
Writer to unescaped value

### ISSUE THREAD

**Issue by randodev** [Tencent/rapidjson#948]
My library received a string json , which I parse to a Document using 
`
Document jsonDoc;
jsonDoc.Parse(jsonString);
`
I then proceed to iterate over all key:value pairs, and want to parse each value as a string. Meaning that, whatever type of value it contains (number, bool, string), I want to send it out as a string. So I tried using the Writer, like so:

`Writer<StringBuffer> writer(buffer);
		iter->value.Accept(writer);
		if (buffer.GetString())
			jsonstr = buffer.GetString();`

jsonstr is the value string. The problem is, the double quotes are escaped, meaning instead of a value looking like:
"**a_random_value**"
it looks like
"**\\"a_random_value\\"**"

How can I prevent the escaping, and convert all my values to string?

**Comment by miloyip** [comment]
You may first check `value.IsString()`.
If it returns true, then just `value.getString()`, otherwise use writer to convert the value as string.

**Comment by Totolin** [comment]
@miloyip That fixed my issue. Thank you!

Another issue I have is that a path value from my json (that looks like this "\\device\\harddiskvolume2\\program files\\..."  contains double backslashes. But, after parsing, the value contains only a single, escaped backslash ( 92 '\\' ).
How can I prevent it from eliminanting the second backslash?

**Comment by miloyip** [comment]
That is a normal behaviour. If you really want to represents two slashes in a string in JSON. You should have four of them `"\\\\"`.

**Comment by Totolin** [comment]
So there's no parse flag I can set to make sure the parsing is ' as is ' ,without escaping?

**Comment by miloyip** [comment]
No. It will become ambiguous.
