### ISSUE TITLE
Addmember at beginning?

### ISSUE THREAD

**Issue by arrabal** [Tencent/rapidjson#957]
I've parsed a json like this one: 

```
{
 "item": {
       "type": "t1",
       "name": "item 1",
       "tags": ["tag1", "tag2"]
   }
}
```

I'd like to add an attribute named "id", so what I do is this: 

`val.AddMember("id", current_id++, document.GetAllocator())`

If I print the Json, the attribute "id" is at the end, after tags. I'd like to add the attribute "id" just before "type". Is there any way to accomplish this? 

When I have few elements it's easy to do it manually but let's say I forgot to add the id to a json with hundreds of items.

Thanks.

**Comment by miloyip** [comment]
There is no API for that. But you can "move" all the old entries into a new value.

~~~cpp
Document d;
d.Parse(...);

Value temp;
temp.AddMember("id", current_id++, d.GetAllocator());
for (Value::MemberIterator m = d.MemberBegin(); m != d.MemberEnd(); ++m)
    temp.AddMember(m->name, m->value, d.GetAllocator());
d.Swap(temp);
~~~

I have not tested the above code. Hope it works.

**Comment by arrabal** [comment]
Thanks for your reply @miloyip 
It looks good, but I get an error executing addMember statement: 

`temp.AddMember("id", current_id++, d.GetAllocator());`

I also tried this: 
`temp.SetObject().AddMember("id", current_id++, d.GetAllocator());`

it produces this: 

`rapidjson/document.h:1103: rapidjson::GenericValue<Encoding, Allocator>& rapidjson::GenericValue<Encoding, Allocator>::operator[](const rapidjson::GenericValue<Encoding, SourceAllocator>&) [with SourceAllocator = rapidjson::MemoryPoolAllocator<>; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>]: Assertion `false' failed.
`
Using addMember on values existing in the document does not produce that error. 

Thanks.

**Comment by arrabal** [comment]
Also, having some way to reorder members within a value would work for me too. Thanks.

**Comment by miloyip** [comment]
I amended my code by constructing `temp` as object type.
But the `operator[]` should not been called when calling `AddMember()`.
You may check the call stack to see which line generates the assertion failure.
