### ISSUE TITLE
how to parse object in first array 

### ISSUE THREAD

**Issue by bernibak** [Tencent/rapidjson#971]
`[
         {
		"A": false,
		"B": "Mike",
		"C": "1.01"
	}, {
		"A": false,
		"B": "Mice",
		"C": "2.02"
	}, {
		"A": false,
		"B": "Boss",
		"C": "3.03"
	}, {
		"A": false,
		"B": "Bright",
		"C": "4.04"
	}
]
`
how to get parsed information this??
repeatedly

**Comment by miloyip** [comment]
What problem did you encounter?

**Comment by pagict** [comment]
since no further info given, i'll close this issue. if the question stays, feel free to reopen it, better with more details
