### ISSUE TITLE
realloc error

### ISSUE THREAD

**Issue by njligames** [Tencent/rapidjson#973]
Hello,
I am including rapidjson in my project using cmake and building it for macOS with SDL.
The project runs fine in release but breaks in debug.
I am at a loss to what to do.

Here is the error:

macOS(73695,0x101c0a3c0) malloc: *** error for object 0x10280e410: pointer being realloc'd was not allocated *** set a breakpoint in malloc_error_break to debug

This is the rapidjson code I use, right at the beginning of main

```
std::string ss = R"(
    {
        "hello": "world",
        "t": true ,
        "f": false,
        "n": null,
        "i": 123,
        "pi": 3.1416,
        "a": [1, 2, 3, 4]
    }
    )";
    
    
    Document document;
    
    char *s = new char[ss.length() + 1];
    strcpy(s, ss.c_str());
    
    document.Parse(s);
```

It breaks at line 981 in reader.h. 
`success = (isKey ? handler.Key(str, length, true) : handler.String(str, length, true));`
The value of isKey is true. I am unable to step into handler.Key.  The value of str is "hello" with a length of 5.

**Comment by miloyip** [comment]
I cannot reproduce this on Mac OS 10.12.5:

~~~cpp
#include <string>
#include "rapidjson/document.h"

int main() {
    std::string ss = R"(
    {
        "hello": "world",
        "t": true ,
        "f": false,
        "n": null,
        "i": 123,
        "pi": 3.1416,
        "a": [1, 2, 3, 4]
    }
    )";
    
    rapidjson::Document document;
    
    char *s = new char[ss.length() + 1];
    strcpy(s, ss.c_str());
    
    document.Parse(s);

    delete[] s;
}
~~~

~~~
$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ g++ -I ~/github/rapidjson/include -g -std=c++11 a.cpp && ./a.out
~~~

**Comment by njligames** [comment]
```
g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

It looks like I can update llvm.

the second command you did is not how I ran into the error.
`$ g++ -I ~/github/rapidjson/include -g -std=c++11 a.cpp && ./a.out`

I compile with SDL2.

I will update llvm and see what happens.

**Comment by miloyip** [comment]
Please provide a minimal, reproducible case, in order for investigation.

**Comment by njligames** [comment]
I changed file permissions on a source files, which was the source of the error
