### ISSUE TITLE
Rapidjson as submodule broken

### ISSUE THREAD

**Issue by ibell** [Tencent/rapidjson#979]
I'm having a hell of a time getting rapidjson to work as a submodule of another project.  It was fine before, but now that I have updated the commit for rapidjson submodule to either master or v.1.1, I keep getting this error:

```
git.exe submodule update --init --recursive --force -- "thirdparty/gtest"

fatal: git fetch_pack: expected ACK/NAK, got 'ERR want 0a439623f75c029912728d80cb7f1b8b48739ca4 not valid'
fatal: The remote end hung up unexpectedly
Fetched in submodule path 'thirdparty/gtest', but it did not contain 0a439623f75c029912728d80cb7f1b8b48739ca4. Direct fetching of that commit failed.
```

FWIW, a clean checkout of rapidjson seems totally fine.  ARGH!

Anyone have any idea how to repair this error?  I'm totally stuck and can't move forward until this is fixed.

**Comment by Jamiras** [comment]
I had a similar issue. It seems to have been caused by googletest moving from `chromium.googlesource.com` to github. I was able to fix it by running `git submodule sync` in the `rapidjson` directory to update the reference, then `git submodule update` in the normal fashion.
