### ISSUE TITLE
IsObject() failed for concatenated json string

### ISSUE THREAD

**Issue by nietzschetmh** [Tencent/rapidjson#988]
I have a calculated doulbe number called **dp**, which is around 101.11

If i do 
```

std::string pp="{\"dp\":";
pp=pp+std::to_string(dp)+std::string("}");
const char* px=pp.c_str();
Document d;
d.Parse(px);
assert(d.IsObject());

```
It will fail **AssertionIsObject()' failed.`**

However, if I mannually set **dp** to any integer number, such as 10, 100, it will always pass the assert.

This troubles me a lot and i don't understand why.

**Comment by miloyip** [comment]
Check `d.GetParseError()` and also show `px`.
