### ISSUE TITLE
Q: How to inherit Document and/or Value to provide user setters?

### ISSUE THREAD

**Issue by qywx** [Tencent/rapidjson#990]
For example
```
auto setter = [](int i){ return i>13 ? 13 : i; }
Value v(12);
v =setter(14);
assert( v == 13 );
```
I want to encapsulate this setter into Value. Like this:
```
struct SetterableValue  : publc Value {
    std::function<> setter;
    
}
// Using
Value v = 12;
v.setter = [](int i){ return i>13 ? 13 : i; };
v = 14;
assert( v == 13 );
```
What functions should be overridden? Can you give some *concept*?. Please help.

**Comment by sledgeh** [comment]
When use some Java-like interface - `virtual int foo(int bar) = 0;` it is obvious what to implement. Compiler will produce readable errors. But not so with templated concepts...

**Comment by StilesCrisis** [comment]
Virtual functions have a very high performance impact which are likely to be unacceptable for Rapidjson.

I don't think Rapidjson itself needs to change here. Instead you should probably wrap the Rapidjson document object in your own class which exposes an API that is easier for you to work with. That's what we've done at my work (we've made things safer at the cost of a bit of performance)

**Comment by sledgeh** [comment]
@StilesCrisis, thank you for respond.
